#!/usr/bin/env python3
"""
Project Protogonos: Integration
Z² Framework Origin of Life Full Simulation

This script integrates the 5 phases of abiogenesis into a single pipeline,
demonstrating the complete theoretical pathway from inorganic precursors
to compartmentalized, self-replicating, homochiral networks governed by
Z² geometry.

Author: Carl Zimmerman
License: AGPL-3.0-or-later
"""

import time
import os
import json
import subprocess

def run_phase(phase_num: int, script_name: str, desc: str):
    print("\n" + "*"*80)
    print(f"Executing Phase {phase_num}: {desc}")
    print("*"*80 + "\n")
    
    start_time = time.time()
    
    # Run the script
    try:
        # Assuming the script is executable and in the same directory
        result = subprocess.run(['python3', script_name], capture_output=True, text=True, check=True)
        print(result.stdout)
    except subprocess.CalledProcessError as e:
        print(f"Error running {script_name}:")
        print(e.stdout)
        print(e.stderr)
        return False
        
    duration = time.time() - start_time
    print(f"Phase {phase_num} completed in {duration:.2f} seconds.")
    return True

def compile_final_recipe():
    print("\n" + "="*80)
    print("Z² GEOMETRIC ORIGIN OF LIFE: THE COMPLETE RECIPE")
    print("="*80)
    
    # Read the results generated by each phase
    results_dir = "results"
    
    try:
        with open(os.path.join(results_dir, "phase1_prebiotic_thermo.json")) as f:
            p1 = json.load(f)
            
        with open(os.path.join(results_dir, "phase2_chirality.json")) as f:
            p2 = json.load(f)
            
        with open(os.path.join(results_dir, "phase3_polymerization.json")) as f:
            p3 = json.load(f)
            
        with open(os.path.join(results_dir, "phase4_autocatalytic.json")) as f:
            p4 = json.load(f)
            
        with open(os.path.join(results_dir, "phase5_compartmentalization.json")) as f:
            p5 = json.load(f)
            
        print("\nThe Inevitable Emergence of Life requires the following state-space:")
        print("\n1. ENVIRONMENT (Phase 1)")
        print(f"   Catalytic Surface: {p1['optimal_conditions']['catalyst']} (Lattice Spacing ≈ 5.79 Å)")
        print(f"   Temperature:       {p1['optimal_conditions']['temperature_C']:.1f} °C")
        print(f"   Pressure:          {p1['optimal_conditions']['pressure_atm']:.1f} atm")
        
        print("\n2. CHIRALITY (Phase 2)")
        meteor_scenario = next(s for s in p2 if s['scenario'] == 'Meteoritic Excess')
        print(f"   Selection Mechanism: Z² 5D Compactification Sign Ambiguity")
        print(f"   Amplification: From {meteor_scenario['initial_ee']:.1e} to {meteor_scenario['final_ee']:.4f} L-excess")
        
        print("\n3. PEPTIDES (Phase 3)")
        print(f"   Survival Mechanism: Geometric Shielding from Hydrolysis")
        print(f"   Structure: Emergence of Alpha-Helices (Z² Backbone Angles: -57°, -47°)")
        
        print("\n4. METABOLISM (Phase 4)")
        print(f"   Interaction: Z² Aromatic Stacking (6.015 Å)")
        print(f"   Network: Emergence of {p4['num_raf_sets']} Reflexively Autocatalytic Sets")
        
        print("\n5. COMPARTMENTALIZATION (Phase 5)")
        print(f"   Membrane: Fatty acid vesicles")
        print(f"   Head-group packing: {p5['optimal_head_spacing_angstroms']:.3f} Å (Matches Z Constant)")
        
        print("\nCONCLUSION:")
        print("Life is a geometric phase transition. It is the deterministic relaxation")
        print("of matter into the minimum-energy configurations defined by the 5D")
        print("Kaluza-Klein compactification metric.")
        
    except FileNotFoundError as e:
        print(f"Warning: Could not compile final recipe. Missing results file: {e}")

if __name__ == "__main__":
    print("Initializing Project Protogonos Full Simulation Pipeline...\n")
    
    scripts = [
        ("protogonos_prebiotic_synthesis.py", "Prebiotic Synthesis & Mineral Catalysis"),
        ("protogonos_chirality_breaking.py", "Parity Violation & Chiral Amplification"),
        ("protogonos_polymerization.py", "Geometric Natural Selection of Peptides"),
        ("protogonos_autocatalytic_closure.py", "Emergence of Autocatalytic Sets"),
        ("protogonos_compartmentalization.py", "Proto-membrane Assembly")
    ]
    
    success = True
    for i, (script, desc) in enumerate(scripts, 1):
        if not run_phase(i, script, desc):
            success = False
            break
            
    if success:
        compile_final_recipe()
    else:
        print("\nPipeline failed. Check error logs above.")
