#!/usr/bin/env python3
"""Quadratic Dirac chain after adding the tensor compensator scalar projection.

The unitary-gauge scalar ADM density is the double-multiplier density plus
``k^2*tau*(zeta-chi)``.  This is the scalar projection of the trace-free
spatial multiplier constraint.  Every Hessian, secondary, Poisson matrix and
rank is generated by SymPy; finite-k and k=0 are not merged.
"""

from __future__ import annotations

import json
import sys

import sympy as sp


def pb(left, right, pairs):
    return sp.simplify(sum(sp.diff(left, q) * sp.diff(right, p)
                           - sp.diff(left, p) * sp.diff(right, q)
                           for q, p in pairs))


def sector(k_value):
    k = sp.symbols("k", real=True)
    z, alpha, beta, chi, lam, sig, tau = sp.symbols(
        "z alpha beta chi lambda sigma tau", real=True
    )
    zd = sp.symbols("zd", real=True)
    L = (-6 * zd**2 - 4 * k**2 * beta * zd + 2 * k**2 * z**2
         + 4 * k**2 * alpha * z + k**2 * lam * (z - chi)
         + k**2 * sig * (alpha - chi) + k**2 * chi**2
         + k**2 * tau * (z - chi))
    if k_value == 0:
        L = L.subs(k, 0)
    pz = sp.symbols("pz", real=True)
    zd_sol = sp.solve(sp.Eq(pz, sp.diff(L, zd)), zd, dict=True)[0][zd]
    H = sp.factor((pz * zd - L).subs(zd, zd_sol))
    qs = (z, alpha, beta, chi, lam, sig, tau)
    ps = sp.symbols("pz pa pb pc pl ps pt", real=True)
    pairs = tuple(zip(qs, ps))
    velocities = tuple(sp.symbols("v0:7", real=True))
    hessian = sp.hessian(L, (zd,) + velocities[1:])
    primaries = tuple(ps[1:])
    secondaries_all = tuple(sp.factor(pb(p, H, pairs)) for p in primaries)
    secondaries = tuple(c for c in secondaries_all if c != 0)
    constraints = primaries + secondaries
    matrix = sp.Matrix([[pb(a, b, pairs) for b in constraints] for a in constraints])
    rank = matrix.rank()
    first_class = len(constraints) - rank
    second_class = rank
    phase_dim = 2 * len(qs)
    dof = sp.Rational(phase_dim - 2 * first_class - second_class, 2)
    return {
        "lagrangian": L,
        "hessian": hessian,
        "hessian_rank": hessian.rank(),
        "primaries": primaries,
        "secondaries_all": secondaries_all,
        "secondaries": secondaries,
        "constraint_matrix": matrix,
        "constraint_rank": rank,
        "first_class": first_class,
        "second_class": second_class,
        "phase_dimension": phase_dim,
        "physical_dof": dof,
    }


def main() -> int:
    finite = sector("nonzero")
    zero = sector(0)
    checks = [
        finite["hessian"] == finite["hessian"].T,
        finite["constraint_matrix"] == -finite["constraint_matrix"].T,
        zero["constraint_matrix"] == -zero["constraint_matrix"].T,
        sp.simplify(finite["constraint_matrix"].rank()) == finite["constraint_rank"],
        finite["physical_dof"] >= 0,
        zero["physical_dof"] >= 0,
        finite["secondaries_all"][-1] != 0,
        finite["physical_dof"] == 0,
        zero["physical_dof"] == 1,
    ]
    print("TENSOR-COMPENSATED DIRAC AUDIT")
    for name, data in (("k!=0", finite), ("k=0", zero)):
        print(f"\n[{name}]")
        print("velocity Hessian =", data["hessian"])
        print("Hessian rank =", data["hessian_rank"])
        print("primary constraints =", data["primaries"])
        print("secondary constraints =", data["secondaries_all"])
        print("active PB rank =", data["constraint_rank"])
        print("first/second class =", data["first_class"], data["second_class"])
        print("physical scalar DOF =", data["physical_dof"])
    passed = sum(bool(x) for x in checks)
    print("checks =", passed, "/", len(checks))
    result = {
        "status": "FINITE_K_SCALAR_CLOSED_ZERO_MODE_OPEN",
        "checks": {"count": len(checks), "passed": passed},
        "finite_k": {"hessian_rank": str(finite["hessian_rank"]),
                      "constraint_rank": str(finite["constraint_rank"]),
                      "first_class": str(finite["first_class"]),
                      "second_class": str(finite["second_class"]),
                      "physical_dof": str(finite["physical_dof"])},
        "zero_k": {"hessian_rank": str(zero["hessian_rank"]),
                   "constraint_rank": str(zero["constraint_rank"]),
                   "first_class": str(zero["first_class"]),
                   "second_class": str(zero["second_class"]),
                   "physical_dof": str(zero["physical_dof"])},
        "scope": "quadratic unitary-gauge scalar projection; full covariant tensor Dirac chain remains open",
    }
    print("RESULT_JSON=" + json.dumps(result, sort_keys=True))
    return 0 if all(checks) else 1


if __name__ == "__main__":
    sys.exit(main())
