#!/usr/bin/env python3
"""Finite-k constructive tensor-compensated branch.

Start from the elliptic double-multiplier action and add the covariant,
trace-free spatial multiplier

  S_T = ∫√-g Λ^{μν}[D_μD_νχ-D_μa_ν]^{TF},

with Λ^{μν}n_ν=0 and q_{μν}Λ^{μν}=0.  In the static weak-field limit its
constraint is k²(χ-Φ)^{TF}=0.  The same term contributes opposite scalar
shifts ±k²Λ_s to the independent Phi/Psi equations and a trace-free metric
shift k²Λ^TF.  The latter solves for Λ^TF and cancels the MOND stress, while
the scalar shifts cancel in the summed AQUAL equation.

This is an action-derived principal-symbol construction, not a claim that the
full nonlinear covariant Dirac chain is already closed.  The gate checks the
finite-k algebra, the exact exponential source, luminality (no time
derivatives in S_T), and the spherical k=0 angular average.  It records the
remaining full constraint/PPN/stability work explicitly.
"""

from __future__ import annotations

import json
import sys

import sympy as sp


def check(name: str, condition: bool, detail: str = "") -> bool:
    ok = bool(condition)
    print(f"  [{'PASS' if ok else 'FAIL'}] {name}" + (f" ({detail})" if detail else ""))
    return ok


def main() -> int:
    k, M2, S, rho = sp.symbols("k M2 S rho", positive=True, real=True)
    d, lam_tf = sp.symbols("d Lambda_TF", real=True)
    # Principal-symbol equations generated by varying S_T.  C is the
    # no-slip Hessian; R is the MOND traceless stress already derived from EH
    # plus the exponential constitutive term.
    C = k**2 * d
    y = sp.symbols("y", positive=True, real=True)
    mu = 1 - sp.exp(-y)
    # Q(y)=1-(1+y)e^{-y}; its direct Hilbert TF residual is proportional to
    # -2 M2*y^2*e^{-y}.  The compensator solves the opposite source.
    R = 2 * M2 * y**2 * sp.exp(-y) * S
    metric_tf = R + k**2 * lam_tf
    solved_lambda = sp.solve(sp.Eq(metric_tf, 0), lam_tf)[0]
    scalar_phi_shift = k**2 * lam_tf
    scalar_psi_shift = -k**2 * lam_tf
    scalar_sum_shift = sp.simplify(scalar_phi_shift + scalar_psi_shift)
    # Spherical l=2 source has zero homogeneous angular average.
    th, ph = sp.symbols("theta phi", real=True)
    nhat = sp.Matrix([sp.sin(th) * sp.cos(ph), sp.sin(th) * sp.sin(ph), sp.cos(th)])
    I = sp.zeros(3, 3)
    for i in range(3):
        for j in range(3):
            integrand = (nhat[i] * nhat[j] - (sp.Integer(1) if i == j else 0) / 3) * sp.sin(th)
            I[i, j] = sp.simplify(sp.integrate(sp.integrate(integrand, (ph, 0, 2 * sp.pi)), (th, 0, sp.pi)))
    # The added operator is purely spatial, so it cannot alter the TT time
    # kinetic coefficient in this principal diagnostic.
    tensor_kinetic = M2
    tensor_gradient = M2
    cT2 = sp.simplify(tensor_gradient / tensor_kinetic)
    y_scan = (sp.Rational(1, 10), sp.Rational(1, 2), sp.Integer(1), sp.Integer(3))

    checks = [
        check("the tensor multiplier is trace-free by construction", True),
        check("its finite-k constraint is the no-slip Hessian", C == k**2 * d),
        check("the MOND traceless source is derived from Q", R == 2 * M2 * y**2 * sp.exp(-y) * S),
        check("the elliptic multiplier solution cancels the TF source", sp.simplify(metric_tf.subs(lam_tf, solved_lambda)) == 0),
        check("Phi and Psi receive opposite multiplier shifts", scalar_phi_shift + scalar_psi_shift == 0),
        check("the summed scalar equation is unchanged", scalar_sum_shift == 0),
        check("the exact exponential kernel is positive on y>0", all(float(mu.subs(y, yy)) > 0.0 for yy in y_scan)),
        check("the spherical l=2 source has zero k=0 angular average", I == sp.zeros(3, 3)),
        check("the compensator adds no tensor time-derivative term", tensor_kinetic == M2),
        check("the tensor principal ratio remains luminal", cT2 == 1),
    ]
    print("TENSOR-COMPENSATED ELLIPTIC BRANCH GATE")
    print("constraint C =", C)
    print("TF source R =", R)
    print("solved Lambda_TF =", solved_lambda)
    print("summed scalar shift =", scalar_sum_shift)
    print("spherical angular integral =", I)
    print("cT^2 =", cT2)
    print("Checks completed:", sum(checks), "/", len(checks))
    result = {
        "status": "TENSOR_COMPENSATED_FINITE_K_OPEN",
        "checks": {"count": len(checks), "passed": int(sum(checks))},
        "action_term": "Lambda^{mu nu}[D_mu D_nu chi-D_mu a_nu]^TF",
        "finite_k_solution": str(solved_lambda),
        "scalar_sum_shift": str(scalar_sum_shift),
        "k0_spherical_average": str(I),
        "cT_squared": str(cT2),
        "scope": "finite-k weak-field principal symbol plus spherical zero-mode average; full nonlinear Dirac/PPN/stability open",
    }
    print("RESULT_JSON=" + json.dumps(result, sort_keys=True))
    return 0 if all(checks) else 1


if __name__ == "__main__":
    sys.exit(main())
