"""Authored research specifications, not executed scientific results."""
import json
from pathlib import Path
out=Path(__file__).parent
items=[]
def group(code, start, branch, sources, principle, inputs, rows):
    lines=[x for x in rows.strip().splitlines() if x.strip()]
    assert len(lines)==25,(code,len(lines))
    for j,line in enumerate(lines):
        title,math,work,control=line.split(' || ')
        items.append(dict(id=f'AS{start+j:03d}',group=code,title=title,branch=branch,
          principle=principle,math=math,inputs=inputs,
          steps=[
            'Read the cited equations and write the precise claim, symbol dictionary, boundary conditions and assumptions needed for this task. Distinguish framework inputs from conclusions to be established.',
            work,
            'Show the intermediate algebra or integration, including all scale factors, signs and units. If the calculation uses a limiting regime, derive the leading neglected term and state its domain.',
            'Perform an independent check using a different representation: substitution into the original equation, direct differentiation, or a bounded high-precision calculation. Save the actual residual, not only a Boolean.',
            'Apply the specified negative control, then write the strongest surviving statement and the first additional implication needed to transfer it to the full theory. Do not import a different branch to repair a failed result.'
          ],checks=[control,'Check the deep and Newtonian limiting regimes wherever they exist; otherwise check normalization and a boundary case. Distinguish an exact identity from a finite numerical consistency check.'],
          completion='Deliver a self-contained derivation or explicit counterexample to the named claim, with reproducible checks. A conditional theorem must list every condition; missing dynamics or data is an explicit open dependency, never a pass.',
          sources=sources,depends_on=[],priority='P0' if j<5 else 'P1',kind='derivation' if j%4 else 'audit'))
group('A01',1,'CORE scale identities; branches remain labelled',
 ['README.md','qwen_claude_field_theory/closure_2026/FRIED_CHICKEN_SPEC.md','campaign_fresh_gravity_astra/DERIVATIONS.md'],
 'The proposed vacuum acceleration scale must be dimensionally consistent and give the same prediction in equivalent variables without adding independent fitted inputs.',
 'Use G=6.67430e-11 SI and c=299792458 m/s; carry a0=9.3619e-11 and 1.1279e-10 m/s^2 as separately labelled footings. Dimensionless witnesses use positive variables; no observational fit is requested.',r'''
Mass-density versus energy-density normalization || a0=kappa*c*sqrt(G*rho_L); epsilon_L=rho_L*c^2; a0=kappa*sqrt(G*epsilon_L). Here rho_L is kg/m^3 and epsilon_L is J/m^3. || Construct the exponent vectors in M,L,T for all three expressions and a reversible conversion table for the vacuum term used in the sources. Identify exactly where c disappears in energy-density units. || Replace rho_L with epsilon_L without changing the coefficient and require the dimensional checker to reject it.
Lambda conversion without a hidden Einstein factor || rho_L=Lambda_eff*c^2/(8*pi*G_E); a0^2=G_N*c^2*rho_L/4; hence Lambda_eff=32*pi*(G_E/G_N)*a0^2/c^4. The familiar identity assumes G_E=G_N; G_E is the Einstein coupling. || Derive both directions starting from the Einstein vacuum stress definition. First solve the framework same-G case on each footing, then retain G_E/G_N for a candidate action. Do not silently identify these couplings. || Remove the 8*pi from the density definition and demonstrate that the reconstructed scale changes.
Critical-density closure as a dependency problem || Under a common G, rho_crit=3*H0^2/(8*pi*G) and Omega_L=32*pi*a0^2/(3*H0^2*c^2). If rho_crit uses G_cosmo while the scale uses G_N, the latter expression acquires G_cosmo/G_N. || Calculate the Jacobian of the map (a0,H0)->Omega_L and state its rank. Show whether assigning two of these quantities makes the third a prediction or merely a re-expression of an input. || Feed an Omega_L used to define a0 back into the equation and flag the resulting agreement as circular.
Natural units and reduced Planck mass || In c=hbar=1 units define M_L^4=epsilon_L, M_Planck=G^(-1/2), Mbar_P=(8*pi*G)^(-1/2); a0=M_L^2/(2*M_Planck)=M_L^2/(2*sqrt(8*pi)*Mbar_P). These symbols must not be interchanged with an action using reduced M_P. || Re-derive the reduced-mass expression independently and restore SI dimensions. Supply a conversion dictionary that distinguishes vacuum mass scale from geometric Lambda. || Substitute Mbar_P for M_P without the sqrt(8*pi) factor and expose the mismatch.
Horizon normalization and Z || H_L=c*sqrt(Lambda_eff/3); R_dS=c/H_L; Z_H=c*H_L/a0=sqrt[(32*pi/3)*(G_E/G_N)], reducing to sqrt(32*pi/3) when the Einstein and measured couplings coincide; Z_H is not the spatial auxiliary Z. || Derive the equalities from the adopted kappa relation and the stated Einstein-to-measured-G ratio; mark whether Z is an independent explanation. Calculate the implied R_dS on both acceleration footings without mixing cosmological inputs. || Treat Z and kappa as independent fitted constants and show the redundant constraint.
The MOND radius as a dimensionless reduction || r_M=sqrt(G*M_b/a0); x=r/r_M; B/a0=x^(-2) for a spherical point baryon. || Reduce point-source equations to x and show which mass and scale dependences disappear. Provide translations for M_b=1e6,1e9,1e12 solar masses. || Use r_M=G*M_b/a0 and require units and forward-substitution to fail.
Flat speed and scale sensitivity || v_flat=(G*M_b*a0)^(1/4); d ln v_flat=(d ln G+d ln M_b+d ln a0)/4. || Derive the sensitivity vector and the ratio of predicted flat speeds between the two footings. Keep this a conditional deep-law statement rather than a fitted BTFR. || Deliberately use a square-root speed law and verify the mass-scaling residual.
Deep temperature as a velocity scale || C=sqrt(G*M_b*a0); sigma^2=C/2; k_B*T=m*sigma^2. || Separate the mass-independent velocity dispersion from the mass-dependent temperature; prove that a measured sigma alone cannot select m. Derive the transformation m->lambda*m,T->lambda*T. || Claim a unique particle mass from sigma and exhibit two different masses with identical dynamics.
Surface-density dimensions and coefficient bookkeeping || Sigma0=a0/G has units kg/m^2; Sigma_pi=a0/(pi*G). || Derive which projected or spherical density convention produces each coefficient in the cited framework. If no geometry fixes pi, leave it as an unproved normalization. || Equate a local volume density directly to Sigma0 and reject the comparison by units.
Pressure normalization at the MOND radius || rho_ph=C/(4*pi*G*r^2); P=(C/2)*rho_ph; P(r_M)=a0^2/(8*pi*G). || Derive the boundary pressure and compare its energy-density dimensions with epsilon_L=4*a0^2/G. Distinguish physical pressure from mass-equivalent density. || Drop c^2 when comparing pressure with rho_L and expose the dimensional mismatch.
Alternative footing as a separate hypothesis || R_a=1.1279e-10/9.3619e-11; kappa_alt=a0_alt/(c*sqrt(G*rho_L)) if rho_L is held fixed. || Compute the effective kappa under fixed vacuum density and under fixed kappa with changed density. Show why these are different model comparisons. || Hold both rho_L and kappa fixed while changing a0 and flag inconsistent inputs.
Propagating correlated vacuum uncertainties || ln a0=ln kappa+ln c+(ln G+ln rho_L)/2; Var(ln a0)=J*Cov*J^T. || Derive the full covariance expression including kappa-rho_L correlation; give a positive-semidefinite synthetic covariance with and without correlation. || Use a covariance with a negative eigenvalue and refuse to interpret its uncertainty.
A distance scaling degeneracy of the deep law || M_b proportional to D^2 for fixed flux; v_flat^4=G*M_b*a0 implies a0 proportional to D^(-2) at fixed velocity. || Derive the distance-scale degeneracy and compare it with inclination scaling v=v_los/sin(i). State the combined invariance explicitly. || Change D in a mock while freezing M_b and demonstrate the internally inconsistent update.
Measured G versus bare action coupling || G_N=G_bare/C_N; a0=(c/2)*sqrt(G_N*rho_L) unless a different convention is derived. || Insert C_N symbolically throughout r_M, BTFR and the vacuum identity. Derive the error when the action uses G_bare but the galaxy calculation assumes G_N. || Choose C_N=2 and check that the unconverted formula fails the physical normalization.
Constant vacuum versus H-dependent scale || a_vac(z)/a_vac(0)=1 for fixed rho_L; a_H(z)/a_H(0)=E(z)=H(z)/H0. || Derive the relative changes in r_M, v_flat and sigma for both hypotheses, retaining a symbolic E(z). Do not mix the historical H branch into the constant-vacuum baseline. || Apply E(z) to the vacuum branch while holding rho_L constant and detect the violated identity.
Pressure mapping versus density mapping || a_p^2 proportional to -p_DE; p_DE=w*epsilon_DE; a_rho^2 proportional to epsilon_DE. || Derive the relative scale evolution for w(z)<0 and identify the extra w(z)/w(0) factor. State where the pressure expression ceases to define real a0. || Use w=0 with positive epsilon_DE and demonstrate that the two mappings cannot agree.
Local versus global vacuum input || a0(x)^2=kappa^2*G*epsilon_L(x) as a proposed local extension; delta a0/a0=delta epsilon_L/(2*epsilon_L). || Derive the gradient terms that appear when a0 is spatially dependent in a constitutive function. Label the extension as a candidate and identify the absent vacuum evolution equation. || Replace a constant a0 inside a derivative by a0(x) while omitting its derivative and show the missing term.
Reference potential and gauge-independent force || Phi=C*ln(r/r_ref); g=dPhi/dr=C/r; changing r_ref shifts Phi by a constant. || Prove force invariance and track the shift in fixed-well energy E=int rho*Phi dV at fixed mass. Explain what boundary energy convention is required. || Interpret the arbitrary potential zero as a measured extra vacuum density and reject that inference.
Deep-law source mass conventions || B=G*M_b(<r)/r^2; v^4=G*M_b*a0 only in a flat outer region with settled enclosed baryon mass. || Derive the running circular speed for nonconstant M_b(<r) and the logarithmic slope. State the condition for using total rather than enclosed mass. || Apply total mass inside a uniform-density baryon sphere and detect the wrong radial power.
Scale relation invariance under unit changes || a0'=a0*T_unit^2/L_unit; G'=G*M_unit*T_unit^2/L_unit^3; rho'=rho*L_unit^3/M_unit. || Implement the symbolic SI-to-kpc-km/s-solar-mass conversion and demonstrate invariance of a0/(c*sqrt(G*rho)). || Convert lengths but leave acceleration in SI and make the dimensionless ratio fail.
Sign and domain of the vacuum scale || a0=kappa*c*sqrt(G*rho_L), G>0,kappa>0 requires rho_L>=0 for a real acceleration. || Classify the zero and negative vacuum-density cases without analytically continuing into an unphysical branch. Derive which limiting gravitational law survives as a0 approaches zero. || Feed a negative density and prevent absolute-value repair from being labelled the original theory.
What a scale identity can actually derive || Constraints F1=4*a0^2-G*c^2*rho_L=0 and F2=Lambda-8*pi*G*rho_L/c^2=0 act on three variables. || Compute constraint rank and parameterize the solution set. State the independent datum still required even when both equalities hold exactly. || Count rearranged copies of F1 as new equations and show their rank remains one.
Footing sensitivity of physical radii and pressures || r_M proportional to a0^(-1/2); rho_ph(r) proportional to a0^(1/2); P(r_M) proportional to a0^2. || Produce an exact scaling table at fixed physical radius and separately at fixed r/r_M. Identify the terms that differ between these two comparisons. || Compare fixed-r and fixed-x densities as if they were the same experiment.
No cosmological prediction from an inverted datum || a0=(c/2)*sqrt(G*rho_L) and rho_L=4*a0^2/(G*c^2). || Construct a directed input/output graph for two possible experiments: independent galaxy scale versus vacuum scale, and vacuum-derived a0 inverted again. Derive the independent residual only for the first. || Give the circular experiment an arbitrarily small numerical residual and confirm it earns no empirical evidence.
Dimensional closure of a proposed new coefficient || General monomial a=A*c^p*G^q*rho_L^r has acceleration dimensions. || Solve the dimensional exponent equations and show the remaining dimensionless coefficient A is not fixed by dimensions. Relate its freedom to the adopted kappa. || Assert dimensional analysis alone forces A=1/2 and refute it with another dimensionally valid A.
''')
group('A02',26,'Separate Q, RAR, MU2, historical EXP and operative MONO',
 ['README.md','qwen_claude_field_theory/closure_2026/FRIED_CHICKEN_SPEC.md','real_research/peer_review_2026_09_26/README.md'],
 'A constitutive response, its inverse, and its filtered field equation must agree on their declared branch; matching one asymptote does not make two kernels equivalent.',
 'Work primarily in y=B/a0>0 and x=g/a0. Use symbolic limits and a diagnostic grid y=10^k for k from -10 to 8 in steps of 0.1; explicitly bracket any roots instead of treating the grid as a proof.',r'''
Exact inverse of the algebraic a0 line || Q: g^2=B^2+a0*B; B=2*g^2/(sqrt(a0^2+4*g^2)+a0). || Derive the stable inverse by rationalization and prove its monotonicity for positive g. Compare with the subtractive quadratic root near g=0. || Perturb the inverse sign and require the forward law to reject it.
Effective AQUAL response of the Q branch || x=g/a0; mu_Q(x)=B/g=(sqrt(1+4*x^2)-1)/(2*x). || Derive the equivalent spherical mu function from Q and compute its small-x and large-x series. State why this does not equate all nonspherical QUMOND and AQUAL solutions. || Substitute mu=1-exp(-x) and show that it differs at a finite positive x.
RAR deep expansion with stable evaluation || nu_RAR(y)=1/(1-exp(-sqrt(y))); g=a0*y*nu_RAR(y). || Derive at least three nonzero deep terms and use expm1 for numerical evaluation. Bound cancellation error against high precision over the declared grid. || Evaluate the naive denominator at very small y and exhibit loss of accuracy.
MU2 implicit force cubic || mu2(x)=1-(1+x/2)^(-2); y=x*mu2(x). || Clear denominators to derive the cubic in x, prove uniqueness of its positive physical root, and supply a bracketing strategy. || Accept a negative or complex algebraic root and make the physical-domain check fail.
A shared deep limit is not a shared finite law || Q: x=sqrt(y^2+y); RAR: x=y/(1-exp(-sqrt(y))); MU2: y=x*mu2(x). || Derive the first correction beyond sqrt(y) on each branch and evaluate their signed differences at y=0.01,1,100. || Test equality only at y tending to zero and show it cannot certify equality at y=1.
Historical exponential AQUAL inversion || EXP: y=x*(1-exp(-x)), x>=0. || Derive dy/dx, prove monotonicity, and construct an inverse with deep and high-field initial brackets. Preserve its historical-comparison label. || Treat x=y*nu_RAR(y) as this exact inverse and compute its nonzero residual.
RAR phantom acceleration maximum || h_RAR(y)=y*(nu_RAR(y)-1)=y/(exp(sqrt(y))-1). || Derive h' and solve the peak condition in t=sqrt(y). Isolate the positive nonzero root and compare with the repository's rounded peak. || Mistake the t=0 boundary solution for the positive peak and fail the classification.
MONO splice location from its derivative rule || h'_mono=max(h'_RAR,delta*h_p/(y+y_p)), delta=0.05; h_p=h_RAR(y_p). || Solve equality of the two derivatives to define y_star rather than hard-code 2.3374; carry the same h_p and y_p throughout. || Change the peak definition while retaining the old splice and show discontinuity of h'.
Constructing the MONO continuation by integration || For y>y_star, h_mono=h_RAR(y_star)+delta*h_p*ln((y+y_p)/(y_star+y_p)); nu_mono=1+h_mono/y. || Derive the integrated branch and verify value and first-derivative matching. Locate the exact regularity class at the splice. || Match the derivative but omit the integration constant and detect a force jump.
High-field recovery of MONO || h_mono(y) grows logarithmically while nu_mono-1=h_mono/y. || Derive the large-y asymptotic and distinguish fractional Newtonian recovery from the absolute phantom-acceleration tail. Explain the implication for subsequent Solar-System tests. || Conclude h_mono tends to zero from nu_mono tending to one and exhibit the contradiction.
Physical monotonicity versus phantom monotonicity || g/a0=y+h(y); dg/dB=1+h'(y), whereas h' alone describes extra acceleration. || Derive separate conditions for invertibility of total force and monotonicity of phantom force. Compare RAR and MONO on their stated domains. || Declare total-force noninvertibility merely from a negative h' whose magnitude is below one.
Constitutive Hessian eigenvalues of an AQUAL branch || Flux A(v)=mu(|v|/a0)*v has transverse eigenvalue mu and longitudinal eigenvalue mu+x*mu'. || Derive the Jacobian directly and classify strict versus degenerate ellipticity for MU2 and EXP. Keep the branch-specific source action explicit. || Drop x*mu' and demonstrate the wrong response to a perturbation parallel to v.
Recover an AQUAL energy primitive || F(X)=int_0^X mu(sqrt(t)) dt, X=|grad Phi|^2/a0^2. || Integrate the MU2 primitive or provide a verified derivative representation and track the additive constant. Vary the static functional with its source sign explicitly. || Differentiate with respect to x instead of X without the factor 2x and fail the Euler equation.
Deep homogeneity of the static energy || mu(x)~x implies F(X)~(2/3)*X^(3/2). || Derive the scaling under grad Phi->lambda*grad Phi and the second variation near zero field. State what vanishes and what remains nonsmooth. || Replace X^(3/2) with X and show that the deep force becomes Newtonian.
AQUAL and QUMOND spherical correspondence || mu(x)*x=y and x=nu(y)*y imply mu(x)=1/nu(y) only at matched arguments. || Prove this dictionary and construct a lookup routine that checks both implicit equations. State the geometry restriction. || Evaluate mu(y)*nu(y) at the same numerical argument and use its mismatch as the negative control.
Nonspherical obstruction to an algebraic vector law || Candidate g=nu(|g_N|/a0)*g_N has curl g=grad nu cross g_N even when curl g_N=0. || Use a two-dimensional polynomial Newtonian potential with nonparallel gradient and gradient magnitude to compute a nonzero curl. Identify the field solve needed to restore a potential. || Use a spherical point source as the only test and demonstrate why it misses the curl.
Filter order is part of the gravity law || Operative source is S* div[(nu(|grad S u|/a0)-1)*grad S u], not div[(nu(|grad u|/a0)-1)*grad u]. || Expand the heat operator to first order in xi^2 on a smooth nonuniform field and derive the leading difference. Restrict the comparison to nonzero gradients. || Commute S through the nonlinear nu without a commutator and show the missing term.
Constant acceleration and the external field || For a constant vector e, S e=e on flat unbounded or periodic derivatives; nu(|e+grad S u|/a0) is nonlinear. || Derive the linearized response around nonzero e, including directional derivatives and the outer filter. Label a prescribed e as boundary data. || Add scalar magnitudes instead of vectors and expose the incorrect transverse response.
Deep point-source potential and boundary matching || g=sqrt(G*M_b*a0)/r; Phi=C*ln(r/r_ref). || Integrate the deep force and match it to a finite-radius transition without imposing a globally logarithmic potential. Track continuity and the chosen integration constant. || Extend the logarithmic branch to infinity while demanding a finite zero potential there.
Newtonian tail ordering of the three kernels || Q, RAR and MU2 each give nu-1 with different large-y asymptotics. || Derive the leading absolute and relative anomalous accelerations and rank them symbolically. Avoid transferring a local acceleration estimate into a Cassini quadrupole verdict. || Compare only nu-1 while forgetting its multiplication by B in the absolute force.
Numerical inverse conditioning || For B=F^(-1)(g), dB/dg=1/F'(B); relative condition number is g/(B*F'(B)). || Derive conditioning for Q analytically and estimate it for RAR and MU2 with bounded brackets. Identify where inferred source uncertainty is amplified. || Use absolute conditioning as though it were relative and catch the unit dependence.
Uniform force-error versus derivative-error control || |nu_mono/nu_RAR-1| small does not bound |h'_mono-h'_RAR| or higher derivatives. || Calculate separate force and derivative differences at the splice and high-field tail; formulate the norm required by a stability claim. || Infer matching Hessians from a 0.0104-dex force envelope and display a derivative counterexample.
MONO splice smoothing as a declared new candidate || Replace max(a,b) locally by a C2 patch h_epsilon with fixed endpoint h,h',h''. || Construct a bounded interpolation patch, test monotonicity and quantify its force deviation. Record epsilon as a new regulator and do not label the new action identical to the frozen MONO branch. || Choose an endpoint-matching polynomial that overshoots h'<0 and require rejection.
Scale derivatives of a constitutive force || g(B,a0)=B*nu(B/a0); partial g/partial a0=-(B^2/a0^2)*nu'(B/a0). || Derive the response at fixed B and separately along B proportional to a0. Check deep and Newtonian limits for each supported branch. || Confuse fixed B with fixed y and show the resulting derivative disagrees with finite differences.
A branch-specific primitive cannot fix its zero || If F'(X)=mu(sqrt X), then F(X)+C has identical static constitutive response. || Prove the static invariance and identify what changes when the same constant is coupled to a dynamical metric. State the extra vacuum condition needed. || Treat F(0)=a chosen number as a derived field equation and reject the claimed coefficient derivation.
''')
group('A03',51,'CORE coefficient; conditional MU_n statistical response',
 ['deepseek_push/PD01_polarization_count.py','deepseek_push/PD08_particle_free_derivation.py','kappa_closure/k01_zero_mode_theorem_and_lambda_free_vacuum.py'],
 'A derivation of kappa must remove a genuinely independent freedom. A channel count, algebraic identity or adopted normalization is useful only with its physical identification separately justified.',
 'Use s=c*sqrt(G*rho_L), Y=g/s, positive finite dimensionless parameters, and symbolic n>=1. Evaluate diagnostic counterexamples at lambda=1/2,1,2; do not use observational preference as a mathematical proof.',r'''
General deep-slope matching theorem || If mu(Y)=b*Y+O(Y^2) with b>0 and mu(Y)*g=B, then g^2=(s/b)*B+corrections and kappa=1/b. || Prove the asymptotic theorem with an explicit remainder bound and identify which hypothesis fixes b. Keep the measured vacuum scale s independent of a0 until the last step. || Change b while preserving both endpoint limits and verify the inferred kappa changes.
OR composition with unequal channel slopes || mu=1-product_i(1-p_i(Y)); p_i(Y)=b_i*Y+O(Y^2); mu'(0)=sum_i b_i. || Derive the full quadratic coefficient for two channels and state the exact equal-slope assumption needed for kappa=1/n. || Set b1=1,b2=2 and show that two channels alone do not force kappa=1/2.
Dimensionless slope freedom in a single-scale action || p_lambda(Y)=lambda*Y/(1+lambda*Y), lambda>0, has p(0)=0,p(infinity)=1 but p'(0)=lambda. || Vary the corresponding static energy primitive and show whether lambda adds a dimensional scale or a dimensionless coupling. Identify the premise in PD08 that would have to exclude this family. || Assert one dimensional scale prohibits lambda and use the explicit family as the counterexample.
Channel-composition nonuniqueness || mu_OR=1-(1-p)^2 and mu_avg=(p+p)/2 both saturate to one for p->1 but have different deep slopes. || Construct both responses from the same p and examine positivity and monotonicity. Name the physical principle that would distinguish them; leave it open if absent. || Claim saturation alone uniquely selects the OR response and test mu_avg.
Correlation freedom in the two-channel response || P(A union B)=2*p-P(A intersection B); parameterize P(A intersection B)=p^2+C(p). || Derive admissible probability bounds on C and how a nonzero linear term changes the deep slope. Do not assume statistical events actually exist in the gravity field. || Take perfectly correlated channels and show that the slope is one rather than two.
Static Einstein channel count versus propagating DOF || In 3D, G00^(1)=2*Delta(Psi), sum_i Gii^(1)=2*Delta(Phi-Psi). || Re-derive these operators in the stated metric convention, then list the constraints needed before counting propagating modes. Determine what the static rank does and does not certify. || Identify two static elliptic equations with two stochastic independent modes and mark the unsupported inference.
Dimension dependence of static-channel rank || In d spatial dimensions, the cited trace contains (d-1)*Delta(Phi-Psi)+(d-1)*(3-d)*Delta(Psi). || Derive the determinant of the two-by-two coefficient matrix for d=1,2,3,4 and symbolically for d>1. Separate the special d=3 decoupling from rank. || Extend a d>1 invertibility statement to d=1 and make the determinant expose the exception.
Field redefinition and the channel slope || Let Phi'=lambda*Phi and source coupling rho*Phi= rho*Phi'/lambda; Y=|grad Phi|/s. || Track kinetic and source coefficients under this redefinition and identify the invariant quantity entering measured acceleration. Test whether a slope claim survives normalization changes. || Rescale the field but keep its matter coupling unchanged and flag the changed theory.
Deep coefficient in a general static action || E[Phi]=A*s^2*int K(|grad Phi|/s)dV+B*int rho*Phi dV; K'(Y)/(2Y) defines a response after normalization. || Vary the functional with all constants retained and derive the combination of A,B and the cubic deep coefficient that sets kappa. || Set A and B to convenient values before variation and compare the lost freedom.
The PD08 quadratic OR expansion || p(Y)=Y+c2*Y^2+O(Y^3); 1-(1-p)^2=2*Y+(2*c2-1)*Y^2+O(Y^3). || Recompute the second-order term directly and compare every occurrence in the PD08 explanatory text and executable expression. State whether any discrepancy affects the leading kappa implication. || Use 2*c2+1 as the coefficient and show an explicit residual at c2=0.
Vacuum energy does not fix linear susceptibility || For X=|grad Phi|^2/s^2, take K(X)=C0+epsilon*X+alpha*X^(3/2), alpha>0; K(0)=C0 but K_X(0)=epsilon. || Vary the static functional and derive the zero-gradient linear-response tensor for epsilon>0 versus epsilon=0. Distinguish choosing zero vacuum energy from imposing a degenerate MOND susceptibility. || Set C0=0 and epsilon=1: the vacuum primitive vanishes but its linear Newtonian response remains nonzero.
Spherical source normalization and Gauss flux || int_sphere mu(g/s)*grad Phi dot dS=4*pi*G*M_b. || Derive the integrated radial equation retaining the 4*pi factor and boundary flux. Show which source-coupling convention must match the deep coefficient calculation. || Drop the source's 4*pi but keep the sphere area and detect the wrong kappa.
Identifiability of n and a per-channel slope || mu=1-(1+lambda*Y)^(-n) has deep slope n*lambda. || Compute the Jacobian of leading deep observables with respect to n and lambda and show its rank. State which transition-shape observable could break that degeneracy without claiming it does. || Fit n from deep data alone while fixing lambda silently and identify the conditional assumption.
Sensitivity of the selected coefficient to channel asymmetry || b1=1+epsilon,b2=1-epsilon gives total slope two but asymmetric higher-order terms. || Derive the first order at which asymmetry becomes visible for rational p_i and propose a dimensionless transition residual. || Conclude equality of slopes from kappa=1/2 and construct an asymmetric counterexample.
Closure of the OR class under coarse graining || For independent channels survival q_i=1-p_i, q_total=product q_i; grouped channels preserve products. || Derive regrouping invariance and ask whether the normalized group drive slope remains one after grouping. Distinguish a mathematical product identity from a physical scale-selection principle. || Group two channels and renormalize its slope by hand, then show how the count interpretation changes.
Horizon coefficient comparison without a theorem leap || kappa_h=sqrt(8*pi/3)/(2*pi), kappa_Z=1/2. || Compute the exact ratio and identify which proposed premises exclude kappa_h: channel integrality, unit slope or OR composition. State the weakest conditional exclusion precisely. || Describe the exclusion as universal while allowing lambda in p_lambda and exhibit a matching lambda.
Additive vacuum zero mode in the local action || J(Y)->J(Y)+C shifts Lambda_eff=Lambda+(2-K_B)*J(0)/2+K(Q0)/2. || Re-derive static invariance and the homogeneous constant shift with the action coefficients retained. State the action class and excluded assumptions rather than claiming all gravity theories are covered. || Fix Lambda to compensate C and show unchanged observables despite a changed primitive zero.
Can a boundary condition remove the zero mode || Impose J(Y_ref)=0 and J'=specified kernel; J(0)=-int_0^Y_ref J'(Y)dY. || Derive the determined constant and count the external data introduced through Y_ref. Decide whether a physically derived boundary or an adopted convention supplied the relation. || Vary Y_ref while retaining the static kernel and exhibit the changed vacuum prediction.
Dimensionless kernel parameter versus vacuum energy || For J(Y;lambda), the derivative fixes forces while C(lambda) changes vacuum energy independently if allowed. || Construct an explicit one-parameter primitive family and calculate the Jacobian of force and vacuum observables. Identify the condition needed to reduce its rank. || Set C(lambda) to produce kappa=1/2 and label that step calibration rather than derivation.
Coupling a proposed normalization constraint consistently || Candidate constraint F=4*a0^2-G*c^2*rho_L=0 enforced with multiplier eta in an action. || Vary eta and every quantity treated as dynamical, showing the extra equations or stresses. Determine whether the relation is now imposed or emergent. || Vary only eta and ignore its stress contribution while claiming an unchanged theory.
Physical response versus probability interpretation || mu(Y)=CDF(Y) ensures 0<=mu<=1; it does not specify what sample space maps to gravitational response. || Formulate the required map from a positive measure to the acceleration flux and derive one testable consequence beyond matching the CDF. If no dynamics supplies it, state the exact missing equation. || Assign two different underlying measures with identical CDF shape but different fluctuation spectra.
A normalization theorem with explicit assumptions || Assumptions: n=2; independent OR composition; p_i'(0)=1; measured source coupling; s fixed by vacuum. || Write a minimal implication chain to kappa=1/2 and remove one assumption at a time using explicit counterexamples. State which assumptions the cited scripts actually prove. || Mark all five assumptions as conclusions merely because the final algebra is certified.
Coefficient selection by a variational principle || Candidate objective I[mu] with fixed endpoint values has stationary equation delta I/delta mu=0. || Test whether a proposed functional read from the source exists; if absent, construct one clearly labelled example and show whether rescaling its argument leaves a free slope. Do not retrofit its minimizer as a discovery. || Choose I specifically to minimize at the target kernel and identify the reverse engineering.
Robustness of kappa under small kernel deformations || mu_base(Y)=1-(1+Y)^(-2), Y=g/s, s=c*sqrt(G*rho_L); mu_epsilon=mu_base+epsilon*f, f(0)=f(infinity)=0; kappa=1/(2+epsilon*f'(0)). This mu_base is MU2(x) at x=2Y, not MU2(Y). || Construct one deformation with zero derivative at zero and one with nonzero derivative. Derive which preserves the deep coefficient and which changes it while preserving endpoints. || Treat endpoint preservation as sufficient for coefficient preservation and use the second deformation.
Constructive missing-premise work order for kappa || Required mechanism must fix both a physical normalization b and a vacuum datum relation without a free additive shift. || Assemble the preceding source-normalized equations into a two-obligation theorem statement. Give an explicit mathematical observable or Ward identity that would establish each missing premise, or show why the current action cannot. || Present a re-labelled input relation as a new independent constraint and reject it by constraint rank.
''')
group('A04',76,'Conditional deep-equilibrium sector; no automatic particle ontology',
 ['deepseek_push/G084_maxentropy_law.py','deepseek_push/G091_virial_triad.py','deepseek_push/G233_eos_noscalar.py'],
 'A static maximum-entropy profile, virial balance, source normalization and dynamical attainment are distinct obligations. Derive the profile from the framework potential and keep finite boundaries explicit.',
 'Use C=sqrt(G*M_b*a0), r_M=sqrt(G*M_b/a0), positive finite shell r_in<=r<=R with r_in>0 and R<=r_M unless specified. Diagnostics use r_in/R=0.01,0.1,0.5 and R/r_M=0.62,1; these are controls, not a fit. R<=r_M fixtures test the historical imposed-log-well ansatz, not a controlled point-source deep-MOND domain. For the actual deep exterior use separate shells r_in/r_M=10,100 with R/r_in=2,10, or bound the full-kernel error. Do not transfer an interior ansatz to filtered MONO without that check.',r'''
Fixed-well Euler-Lagrange density || S=-int rho*ln(rho/rho_ref)dV; E=int rho*(3*sigma^2/2+C*ln(r/r_ref))dV. || Vary S-alpha*M-beta*E at fixed potential and sigma, solve for rho, and identify the extra condition beta=1/sigma^2. || Include rho-dependent self-gravity in E but keep the fixed-well variation and expose the missing term.
Finite-shell normalization of the isothermal profile || rho=A*r^(-2); M=4*pi*A*(R-r_in). || Derive A from a fixed M and compare it to C/(4*pi*G). State which choices of M,R,r_in allow both normalizations simultaneously. || Use A=M/(4*pi*R) at finite r_in and compute the mass deficit.
General slope normalizability || rho=A*r^(-gamma); M=4*pi*A*(R^(3-gamma)-r_in^(3-gamma))/(3-gamma), gamma!=3. || Derive the gamma=3 limit and classify divergences as r_in->0 and R->infinity. State why an untruncated gamma=2 halo has infinite mass. || Claim global normalization of r^-2 on all positive radii and show the divergent integral.
Entropy second variation on the constrained shell || delta^2 S=-int (delta rho)^2/rho dV at fixed potential; perturbations obey int delta rho=int Phi*delta rho=0. || Construct two explicit admissible perturbations by projecting smooth basis functions off the constraints and evaluate the sign. State the finite-domain hypotheses for strict concavity. || Use a perturbation that violates mass conservation and reject it as a constrained-mode test.
Hydrostatic slope-temperature relation || dP/dr=-rho*C/r and P=sigma^2*rho imply gamma=C/sigma^2. || Derive rho(r)=A*(r/r_ref)^(-C/sigma^2), identifying the single density normalization A, the fixed reference radius, and independently specified sigma^2. Show that slope two requires sigma^2=C/2. || Insert sigma^2=C/3 and observe a valid slope-three solution rather than forcing slope two.
Self-source and imposed baryon well are different || Delta(C*ln r)=C/r^2 for r>0; rho_source=C/(4*pi*G*r^2). || Derive the Poisson source and compare it with a compact baryonic source whose Newtonian potential is -G*M_b/r. Explain the exact premise needed to call the logarithmic well baryonic. || Assign the logarithmic potential to a point Newtonian baryon without a modified equation.
Inner boundary mass and self-gravity || For rho=A/r^2 on [r_in,R], M(r)=M_in+4*pi*A*(r-r_in). || Derive g_self(r) and identify the central mass M_in needed for exact C/r at every shell radius. Track its physical interpretation rather than hiding it in A. || Set M_in=0 at finite r_in while claiming exact logarithmic self-gravity.
Virial surface term with both boundaries || The pressure boundary contribution is 4*pi*(R^3*P(R)-r_in^3*P(r_in)). || Derive the scalar virial identity from hydrostatic balance on a shell and retain both surfaces. Compare with the one-boundary formula in the zero-inner-radius limit. || Retain finite r_in but omit the inner pressure term and measure the residual.
Self-gravitational virial energy with a central mass || W_vir,total=-int G*M(r)/r dM_shell(r), M(r)=M_in+4*pi*A*(r-r_in). This includes central-mass attraction and shell self-gravity; separate those terms before naming a self-energy. || Integrate exactly and identify the terms that disappear only when the singular sphere is used. Avoid conflating pair self-energy with the virial of an external potential. || Use -G*M(R)^2/R for every finite shell and test a nonzero r_in.
External Newtonian baryon virial term || W_bar=-int rho*r*dPhi_b/dr dV with Phi_b=-G*M_b/r outside r_b. || Integrate over the allowed shell and compare with the logarithmic expression quoted in G091. State the domain r>=r_b explicitly. || Extend the point-source integral to r=0 with no baryonic core and flag divergence.
External logarithmic-well virial term || For Phi_ext=C*ln(r/r_ref), W_ext=-int rho*r*dPhi_ext/dr dV=-C*M. || Derive this identity without inserting self-gravity, then compare the dispersion inferred with and without pressure boundaries. Identify any double counting of the same force. || Add both W_self and W_ext when both represent the identical logarithmic field.
Boundary pressure and the claimed half factor || For a full singular isothermal sphere, 2T=3*M*sigma^2 and 3*P_s*V=M*sigma^2. || Derive sigma^2=C/2 from the explicitly chosen force and boundary terms. Vary only the boundary condition to identify whether the coefficient is universal or conditional. || Impose zero surface pressure on the same truncated profile without changing the equilibrium.
Energy identity with nonzero surface pressure || For Newtonian self-gravity without a separately counted external field, W_vir=U_grav and 2T+W_vir=3*P_s*V give E=3*P_s*V-T. For an imposed log well, W_vir=-C*M while U_ext=int rho*C*ln(r/r_ref)dV, so W_vir cannot replace U_ext in E. || Separate the self-gravitating and imposed-log-well cases, substitute each valid boundary identity, and compute the corresponding energy. Compare the G091 first-law discussion with the retained potential and surface terms. || Use E=-T while keeping 3*P_s*V nonzero and require the residual to expose the inconsistency.
Anisotropic Jeans support of the same density || d(rho*sigma_r^2)/dr+2*beta_an*rho*sigma_r^2/r=-rho*C/r. || Solve for constant beta_an and constant sigma_r, deriving gamma-2*beta_an=C/sigma_r^2. State that observed line-of-sight dispersion requires projection. || Infer gamma=2 from sigma_r alone while allowing unknown beta_an.
Projected surface density of a capped phantom || Sigma(Rp)=2*int_Rp^R rho(r)*r/sqrt(r^2-Rp^2)dr for Rp>r_in. || Integrate rho=A/r^2 and compare the infinite-cap limit with the finite expression. Keep projected radius Rp distinct from outer cap R. || Use the infinite profile near Rp=R and detect the incorrect nonzero edge column.
Enclosed phantom mass and equipartition || M_ph(<r)=C*r/G for the zero-inner-radius deep sphere; M_ph(r_M)=M_b. || Derive the exact identity and identify dependence on the normalization A. Show whether the equality independently derives A or merely restates its definition. || Set A to twice its adopted value and check which equations cease to hold.
Baryon mass response of equilibrium density || At fixed r,a0, rho_ph proportional to M_b^(1/2), sigma^2 proportional to M_b^(1/2), and P proportional to M_b. || Derive the local response coefficients and distinguish them from an adiabatic evolution law for a changing host. || Treat a family of static solutions as a time evolution with no energy flux.
Radial pressure divergence at the center || rho=A/r^2 and P=(C/2)*rho imply finite enclosed mass but divergent central pressure. || Compute mass, pressure energy and force integrals near an inner cutoff and identify which remain finite. State the minimum core or weak-solution information required. || Equate finite enclosed mass with regularity of every local observable.
Isothermal gas entropy reference cancellation || S=-int rho ln(rho/rho_ref)dV; rho_ref->lambda*rho_ref shifts S by M ln lambda. || Show cancellation in same-mass entropy differences and failure when comparing states with different mass without a reservoir convention. || Compare absolute entropies with different reference densities and call the difference latent heat.
Mass versus energy constraint independence || Constraint Jacobian has rows int delta rho and int Phi*delta rho for nonconstant Phi. || Determine when the constraints are independent and when a degenerate constant-potential limit collapses rank. Construct a finite basis realization with at least four modes. || Normalize two proportional constraints as if they supplied two independent multipliers.
Canonical versus microcanonical profile stability || For mass-weighted S=-int rho*ln(rho/rho_ref)dV, use F_v=E-sigma^2*S at fixed velocity-temperature sigma^2; E has energy units and S mass units. Equivalently use F=E-T*S_phys with S_phys=(k_B/m)*S. The microcanonical problem instead fixes E. || Derive the two constrained Hessians for the fixed-well system and identify which is tested by G084. State why self-gravitating ensemble conclusions cannot be transferred automatically. || Change ensembles while reusing an unconstrained Hessian sign.
Radial flux required to attain the equilibrium || Continuity gives partial_t rho+(1/r^2)*partial_r(r^2*rho*v_r)=0. || Insert a slowly varying family A(t)/r^2 on a finite shell and derive the necessary radial mass flux and boundary supply. This is a kinematic requirement, not a claimed relaxation mechanism. || Change A(t) with v_r=0 and no source and expose mass nonconservation.
Energy flux for a changing vacuum scale || C(t)=sqrt(G*M_b*a0(t)); rho and sigma follow the static family only if transport supplies dE/dt and boundary work. || Differentiate the finite-shell energy with a declared fixed or moving boundary and derive the missing power term. Label all additional evolution assumptions. || Vary a0(t) while imposing both constant total energy and the instantaneous static profile.
Cap pressure jump and mechanical support || Across a static interface with no surface stress, [P]=0; framework inner P=sigma^2*rho and outer dust P approximately 0. || Derive the momentum balance integrated across a thin interface and solve for the required surface stress or flux if pressure jumps. Do not call a nonzero jump a contact equilibrium without support. || Set both interface velocity and surface stress to zero with unequal pressures.
Equilibrium closure dependency theorem || Required chain: force C/r plus temperature plus finite normalization plus boundaries implies rho=A/r^2 and M(r_M)=M_b only under compatible choices. || Assemble a minimal theorem with independent assumptions and explicit finite-shell counterexamples when each is removed. Preserve a constructive list of the missing source and formation equations. || Count the same adopted C and A twice as independent derivations of the profile amplitude.
''')
group('A05',101,'Statistical-mechanics proposals linked to MU2 and deep equilibrium',
 ['deepseek_push/G228_lomax_maxent.py','deepseek_push/G230_dmdg_measure.py','deepseek_push/G235_typeIII_reading.md'],
 'A maximum-entropy identification needs a specified measure, constraints and dynamical observables. A probability density reproducing a kernel does not by itself derive its gravitational role or establish equilibration.',
 'Use u>=0, f(u)>=0, int f du=1 and c_log=E[ln(1+u)]>0. Keep this c_log distinct from light speed c. For truncated numerical checks use u_max=10,100,1000 and 128,256,512 cells; bound tails analytically.',r'''
Lomax Euler-Lagrange derivation at arbitrary log moment || Maximize -int f ln f du subject to normalization and E ln(1+u)=c_log; f=(lambda-1)*(1+u)^(-lambda). || Derive normalization and lambda=1+1/c_log without fixing c_log=1/2 first. State the exact admissible range and boundary conditions. || Insert c_log=1/2 into the constraints before solving and expose that the exponent was supplied.
Exact entropy of the constrained Lomax family || S(c_log)=1+c_log+ln(c_log), equivalently lambda/(lambda-1)-ln(lambda-1). || Integrate entropy analytically and differentiate to obtain dS/dc_log=lambda. Check the concavity in c_log and its interpretation as a multiplier. || Use the entropy formula of a different base measure and detect the changed derivative.
Change of variables and entropy measure || t=ln(1+u), f_t(t)=exp(t)*f_u(exp(t)-1); H_t=H_u-E[t]. || Derive the Jacobian and show how the constrained entropy objective changes under the transformation. Establish precisely when the exponential and Lomax optimizations agree. || Omit the Jacobian and show the incorrect exponent in f_t.
Uniqueness by relative entropy || For the matching Lomax f_star, D(f||f_star)=int f ln(f/f_star)du and S(f_star)-S(f)=D under the same constraints. || Prove the equality and nonnegativity under finite-entropy assumptions. Identify which competing distributions qualify. || Compare to a distribution with a different log moment and reject the supposed maximality test.
Finite-window normalization bias || f_U(u)=f(u)/F(U) for 0<=u<=U; its log moment differs from the infinite-support c_log. || Derive the exact truncated normalization and expectation, then quantify the bias in a naive fitted lambda at the stated U values. || Use the infinite-support moment equation on a small truncated window and recover the expected mismatch.
Tail bounds for finite-grid entropy || For lambda>1, tail mass=(1+U)^(1-lambda); tail log moment and entropy have analytic integrals. || Derive all three tail corrections and use them to bound a numerical quadrature. Show convergence when both resolution and U grow. || Increase grid resolution at fixed U and falsely claim the missing tail has vanished.
Which moments of the shape-two Lomax exist || f=2*(1+u)^(-3); E[u] finite and E[u^2] divergent. || Derive the general moment convergence condition and exact first moment. State the consequence for Gaussian standard-error calculations on the raw acceleration variable. || Report a stable finite variance from a finite cutoff as an infinite-support property.
Generalized log constraint selects a different kernel || E[ln(1+(u/b)^p)]=c_log with b,p>0 changes the max-entropy stationary family and measure. || Derive the stationary density and conditions for normalization. Show which additional choices recover the original Lomax and which remain free. || Claim the log-moment constraint is the unique conceivable power-law generator without fixing its functional form.
Separable joint entropy cannot dynamically couple sectors || S_total[rho,f]=S_rho[rho]+S_f[f] gives mixed second derivative zero. || Derive the block Hessian and demonstrate that independent constraints leave independent multipliers. State the explicit coupling constraint required to make a common temperature substantive. || Identify two numerically chosen multipliers as a single dynamical temperature without a coupling equation.
Testing a proposed shared constraint constructively || Candidate constraint C_joint=E_f ln(1+u)-F(E_rho,M)=0 links the two sectors. || Vary the full constrained functional including derivatives of F and derive the changed density equation. Label F as a new proposal and test whether the old profile survives. || Add the constraint after solving both sectors and claim unchanged variational equations.
Radial-to-acceleration Jacobian for a power-law density || On [r_in,R], rho=A*r^(-gamma) gives M(r)=M_in+4*pi*A*(r^(3-gamma)-r_in^(3-gamma))/(3-gamma). For 0<gamma<3 and M_in=4*pi*A*r_in^(3-gamma)/(3-gamma), g=D*r^(1-gamma), D=4*pi*G*A/(3-gamma). Exclude gamma=1 when inverting g(r). || Derive |dM/dg| with the complete Jacobian and finite bounds on the normalized special branch first; then show how a different M_in alters the map. Compare the resulting exponent with the proposed shape lock. || Infer the exponent from dM/dr without multiplying by |dr/dg|.
PDF tail versus survival exponent || Lomax PDF behaves as u^(-n-1), survival as u^(-n); a mass density dM/dg is a PDF-type object after normalization. || Compare the mass-pushforward exponent with each Lomax exponent and identify which equality is being imposed in the claimed n-gamma lock. || Equate a PDF exponent to a survival exponent and demonstrate an off-by-one inconsistency.
Acceleration pushforward for an imposed logarithmic well || g=C/r and rho=A/r^2 imply |dM/dg|=4*pi*A*C/g^2 on a finite interval. || Derive the normalized finite-interval density, CDF and survival. Compare its support and full shape with 2*(1+u)^(-3). || Claim equality to the full Lomax from a shared power-law description alone.
Selection function changes the observed acceleration distribution || f_obs(g)=w(g)*f_true(g)/int w*f_true dg, with w a declared selection weight. || Derive a forward observation model for mass, volume and ring-count weights separately. Construct a finite example where the same physical profile yields different apparent slopes. || Combine equal-ring and mass weights without tracking w and fail a recovery test.
Correct weighted survival ordering || For sorted g_i ascending and weights w_i, S_i=sum_{j>=i}w_j/sum_j w_j. || Derive and implement the reverse cumulative sum and compare with reversing a forward cumulative sum as done in the cited script. Use an unequal-weight three-point witness. || Weights (1,2,7) must distinguish the correct survival from the reversed-prefix implementation.
Correlated-shell uncertainty without false sample size || Weighted empirical CDF F(g)=sum_i w_i*1[g_i<=g]/sum_i w_i; shells in one galaxy share nuisance parameters. || Construct a two-level bootstrap with galaxy resampling and within-galaxy fixed shell blocks; compare uncertainty with an iid ring bootstrap on a synthetic correlated sample. || Duplicate every shell ten times and require the independent-information estimate not to improve spuriously.
Conditioning a Lomax null on the deep window || F_cond(u)=(F(u)-F(u_min))/(F(u_max)-F(u_min)) within a fixed window. || Derive the conditional CDF, density and likelihood with the truncation normalization retained. Keep the physical scale fixed unless its estimation is explicitly part of the null. || Fit the unconditional CDF to the selected window and detect spurious rejection.
Scale fitting changes a goodness-of-fit null || For Lomax f(g|s)=2/s*(1+g/s)^(-3), estimate s on each simulated replicate before computing its statistic. || Specify a parametric bootstrap for weighted or clustered observations with the same scale-estimation rule. Do not use an iid KS p value for fitted weighted data. || Freeze s at its generating value in the bootstrap but fit it in the observed statistic and detect miscalibration.
Log-moment constraint uncertainty maps to kappa || n=1/c_log for the Lomax family and kappa=1/n only under the separate response identification, hence kappa=c_log conditionally. || Propagate an interval for c_log through the conditional chain and state the additional slope/scale premises. Distinguish a measured moment from a mechanism fixing it. || Declare kappa exact while c_log is inferred with nonzero uncertainty.
Stationary distribution does not determine relaxation || Fokker-Planck candidate partial_t f=partial_u[D(u)*(partial_u f+V'(u)*f)], V=3*ln(1+u). || Derive zero-flux f proportional to exp(-V) and show that many positive diffusion functions D share it with different relaxation rates. Treat the dynamics as proposed, not inherited. || Infer a unique equilibration time from f alone and refute it by scaling D.
Constructing a detailed-balance operator on a finite interval || L f=partial_u[D*f_star*partial_u(f/f_star)] with reflecting endpoints. || Derive mass conservation and relative-entropy decay for D>0; identify how the truncation changes f_star. State the physical coupling equation still absent. || Use an absorbing endpoint while claiming conserved mass and expose the boundary flux.
Velocity FDT requires a response convention || Langevin prototype dv/dt=-gamma*v+eta+a_ext; E[eta(t)eta(t')]=2*gamma*sigma^2*delta(t-t'). || Derive the stationary velocity spectrum and acceleration-to-velocity response, then verify the classical FDT with sigma^2=C/2. Label gamma and stochastic dynamics as extra assumptions. || Mix position mobility with velocity mobility and require units to catch the wrong diffusion formula.
Temperature normalization is not a spectral FDT test || k_B*T/m=sigma^2 is an identity; spectral test compares S_v(omega) to 2*sigma^2*Re[chi_v(omega)]. || Build two synthetic spectra with the same integrated variance but different frequency dependence and test one stated response. Identify which additional measured or derived object is missing from G235. || Accept both spectra simply because they integrate to the same temperature.
Classical entropy does not classify an operator algebra || Coarse-grained H_delta=-sum_i p_i ln p_i; H_delta+ln(delta) may approach differential entropy in one variable. || Calculate refinement behavior for the framework Lomax distribution and explain which algebraic structure, representation and state would be needed for a type classification. Avoid importing a classification from a finite entropy number. || Infer type I or III solely from the finite entropy of one discretization.
Minimum constructive statistical-to-gravity bridge || Needed chain: microscopic or continuum dynamics -> invariant measure -> response mu -> source coupling -> vacuum scale normalization. || On the finite reflecting interval from AS121, perturb V to V+eta*A(u), normalize f_eta proportional to exp(-V-eta*A), and derive d E_eta[B]/deta at eta=0 as -Cov_f0(A,B), where A and B are specified bounded observables. State the missing physical identification of eta with gravitational acceleration and source coupling. This is one response identity, not the full bridge. || Present a CDF fit and a temperature identity as proof of the entire chain.
''')
dependencies={
 'AS027':['AS026'], 'AS033':['AS032'], 'AS034':['AS033'], 'AS035':['AS034'],
 'AS047':['AS033','AS034'], 'AS048':['AS033','AS034','AS047'],
 'AS068':['AS067'], 'AS069':['AS067'], 'AS072':['AS051','AS052','AS053','AS054','AS056','AS062'],
 'AS075':['AS059','AS067','AS072'], 'AS079':['AS076'], 'AS087':['AS083','AS084','AS086'],
 'AS088':['AS083','AS087'], 'AS096':['AS076','AS079'], 'AS098':['AS088','AS097'],
 'AS100':['AS077','AS080','AS081','AS082','AS083','AS087','AS099'],
 'AS102':['AS101'], 'AS104':['AS101','AS102'], 'AS106':['AS105'],
 'AS110':['AS076','AS101','AS109'], 'AS112':['AS111'], 'AS118':['AS117'],
 'AS119':['AS051','AS101'], 'AS121':['AS120'], 'AS123':['AS122'],
 'AS125':['AS109','AS110','AS112','AS113','AS121','AS123']}
for task in items:
    task['depends_on']=dependencies.get(task['id'],[])
    if task['id']=='AS014': task['sources']=task['sources'][:2]+['real_research/common_action_2026_09_26/action/FINAL_ACTION.md']
    if task['id']=='AS118': task['checks'].append('Verify the sampler before the bootstrap: unit shape-two Lomax draws are rng.pareto(2.0,size), without subtracting one, or (1-U)^(-1/2)-1 for U uniform on (0,1). Check nonnegative support and empirical CDF. The cited script subtracts one from an already shifted Pareto draw; preserve that as a failing control, not a sampler to reuse.')
assert len(items)==125
(out/'foundations.json').write_text(json.dumps(items,indent=2,ensure_ascii=False)+'\n')
print(f'Wrote {len(items)} authored foundation task records')
