#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
GP1 -- THE GENERATED-PHANTOM CONSTRUCTION: a MOND kernel whose SOURCE is the baryons of bound regions only; the web's
gas and the dark component are invisible to it; the kernel term itself is not switched.

WHY.  The record closes three routes to a phantom that follows galaxies without spoiling cosmology:
  * a CONSERVED phantom carried by a dark fluid (the Blanchet-Skordis class) is closed for any kinetic function: the
    galactic mass term equals the late Jeans scale (BSX3, PAPER33 v2);
  * a kernel that reads the whole web's field (C-H/K + switch) is excluded by KiDS-1000 through its external-field
    effect (BS2/BS3); reading the web's gas is still +133..+241 (BS3, L355);
  * a switch on the kernel's FLUX is Gauss-cancelled at its edge (L352): beyond it the lens weighs its baryons, so a
    switch that keeps the web and the forest Newtonian also removes the Mpc phantom KiDS sees (the KiDS-forest pincer,
    L358/L362; opened only by a time gate, L359, with a region-local kernel, L361).
This lane builds the alternative the record lists but has not built: switch the kernel's SOURCE, not its flux.  The
phantom is generated by the baryons of bound regions (as in QUMOND: a field configuration, not a conserved fluid), it
extends beyond the region because the kernel term acts everywhere, and nothing outside bound regions can source it or
feel it.

THE CONSTRUCTION (a construction, not a derivation; C-H's NR action as in L353, with L353's subtraction pair):
    L = -(rho_b + rho_d) Phi - [2 grad Phi . grad u - |grad u|^2 - a0^2 q(|grad S(u - v)|^2/a0^2)]/(8 pi G)
        + lambda (Lap v - 4 pi G [rho_d + (1 - w) rho_b])
  w = w(x_m), x_m = 4 pi G rho_m / H^2 = 36 pi G (n.T.n)/K^2: a smooth step at a virial-like threshold x_c, built from
  the matter's energy density in the preferred frame and the leaves' expansion (no curvature: see N5).
  S = the Yukawa high-pass S(k) = (k lam)^2/(1 + (k lam)^2) (BK1's screening; lam = inf switches it off).
  Field equations (N1):
      dPhi:    Lap u = 4 pi G (rho_b + rho_d)               (u = Newtonian potential of all matter)
      dlambda: Lap v = 4 pi G (rho_d + (1 - w) rho_b)       =>  u - v = u_B, the Newtonian potential of BOUND baryons
      du:      Lap Phi = Lap u + S div[q' grad S u_B]       =>  Phi = u + Phi_ph[u_B]   (the metric: Newtonian(all) + phantom)
      dv:      4 pi G lambda = -Phi_ph[u_B]
  Species: bound baryons (w = 1) move in Phi = Newtonian(all) + phantom; unbound baryons (w = 0, the web's gas, the
  forest) and the dark component move in Phi + 4 pi G lambda = Newtonian(all).  Light follows the metric Phi.
  Baryons crossing a region's edge feel -Phi_ph grad w: a potential step of height Phi_ph(edge) (N4).

CHECKS
  N1 THE FIELD EQUATIONS (symbolic Euler-Lagrange with an arbitrary kernel primitive, 1-D operator identities as L353):
     kernel argument = Newtonian potential of w rho_b; metric = Newtonian(all) + phantom; the potential felt by a baryon
     is Phi_N + w Phi_ph; by the dark component Phi_N.
  N2 GAUSS -- THE DIFFERENCE FROM EVERY SWITCH ON THE RECORD: for an isolated galaxy whose bound region ends at r_e,
     the lensing mass beyond r_e keeps the phantom (source switch) instead of returning to M_b (flux switch, L352 Z1;
     L361's region-local kernel).  Spherical QUMOND with L340's nu_mono and BK1's screening.
     (Reported with it: the enclosed lensing mass of the Lagrangian screening form, S* div[q' grad S u_B], against BK1's
     form, div[q' grad S u_B], used by BK1 and GP2 -- the action's variation re-screens the phantom's source.)
  N3 RECIPROCITY (L353 N2): the linearised response of the construction's phantom is symmetric (a Lagrangian), and the
     species-response matrix [bound, unbound, dark] is symmetric; the non-Lagrangian alternative (unbound gas feels the
     phantom but does not source it) is not -- measured on a grid.  BK1's one-S form is reported alongside.
  (Record: the first run failed N2 on a tolerance bug -- it compared the flux switch's mass beyond the edge with M_b
   instead of the enclosed Hernquist mass (0.994 M_b at 1 Mpc) -- and N3 used a 1e8 Msun test mass whose own field
   (~1e-5 a0) is not small against the ambient 3e-5 a0, so the "linear" response was not linear (3.6% asymmetry).  Both
   fixed before commit; N3 now uses 1e6 and 1e4 Msun and reports the convergence.)
  N4 THE EDGE STEP (documentary): Phi_ph at the edge of the bound region for a dwarf, the Milky Way, a group and a
     cluster, as the speed sqrt(2|Phi_ph|) against the flat circular speed -- the energy per unit mass a baryon gains
     entering a bound region (a prediction: accreting gas is heated/kicked by it, outflows must climb it).
  N5 THE SWITCH'S BACK-REACTION: with w built from the matter density, varying the coupling's metric dependence is
     suppressed by |Phi_ph|/c^2 (<~ 1e-6) and the khronon's to <~ 1e-2 of its c2 K^2 term at the Planck cap
     (L350); built from the leaves' curvature (L342's x~ = 9 R3/(4K^2)) the same term is O(1) at every edge.  The
     density switch is also tensor-blind (n.T.n and K are unperturbed by a transverse-traceless mode), so c_T = 1 of
     C-H/K without the flux switch (L351) stands.
  N6 (documentary) what the construction inherits unchanged inside bound regions: the Sun reads the Galaxy (BK1 C1,
     lam >= 0.5 Mpc), 1PN = GR (KM3), the moving-source gate and health (L340), no new mode (L353 N3: elliptic pair;
     w is a function of existing fields).
MUTATE=1 removes the source switch (w = 1: every baryon sources the kernel -- L353's baryons-only kernel): N1's
unbound-gas identity must FAIL (rc = 1).
SCOPE.  Non-relativistic identities (the relativistic embedding follows L353's pattern: two leafwise elliptic
auxiliaries, the dark source n.T_d.n, and here the weighted baryon source w n.T_b.n); w is a prescribed function of the
local matter density in N1 (its density dependence adds the edge pressure that N4 quantifies); the cosmology is GP3,
KiDS is GP2.

Run from the repository root:  python3 real_research/generated_phantom_2026/GP1_generated_phantom_construction.py
"""
import os, sys, json, math, time, io, contextlib, warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
import numpy as np
import sympy as sp
from sympy.calculus.euler import euler_equations

HERE = os.path.dirname(os.path.abspath(__file__)); REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
MUTATE = os.environ.get("MUTATE", "0") == "1"
SLUG = "GP1_generated_phantom_construction"
T0 = time.time()
P = lambda *a: print(*a, flush=True)
CH, OUT = [], {"lane": "GP1", "mutate": MUTATE, "checks": {}, "numbers": {}}
_trap = getattr(np, "trapezoid", None) or np.trapz


def check(name, measured, ok, reading="", load_bearing=True):
    ok = bool(ok); CH.append((name, ok, load_bearing))
    OUT["checks"][name] = {"ok": ok, "measured": str(measured), "load_bearing": load_bearing}
    P(f"  [{'PASS' if ok else 'FAIL'}] {name}"); P(f"         measured: {measured}")
    if reading: P(f"         reading:  {reading}")
    return ok


def banner(t): P("\n" + "=" * 110); P(t); P("=" * 110)


P(__doc__.split("CHECKS")[0].strip())
if MUTATE: P("\n  *** MUTATE=1: no source switch (w = 1 for every baryon); N1's unbound-gas identity must FAIL ***")

# ---------------------------------------------------------------------------------- the kernel (L340's nu_mono, via BK1)
P1 = os.path.join(REPO, "real_research", "blind_kernel_2026", "BK1_screened_kernel.py")
NS = {"__name__": "bk1", "__file__": P1}
_src = open(P1).read().split("# ------------------------------------------------------------------ linear LCDM")[0]
_src = _src.replace('MUTATE = os.environ.get("MUTATE", "0") == "1"', "MUTATE = False")
with contextlib.redirect_stdout(io.StringIO()):
    exec(_src, NS)
nu_mono = NS["nu_mono_arr"]
G = 6.67430e-11; MSUN = 1.98892e30; KPC = 3.0856775814913673e19; MPC = 1e3 * KPC; C_LIGHT = 2.99792458e8
A0 = {"canonical": 9.3619e-11, "alt": 1.1279e-10}

# ============================================================================================ N1
banner("N1  THE FIELD EQUATIONS (symbolic Euler-Lagrange; arbitrary kernel primitive Q; source weight w(x))")
x = sp.symbols('x', real=True)
Gs, a0s = sp.symbols('G a_0', positive=True)
Phi, u, v, lam = [sp.Function(n)(x) for n in ('Phi', 'u', 'v', 'lam')]
rb, rd, wfun = sp.Function('rho_b')(x), sp.Function('rho_d')(x), sp.Function('w')(x)
Q = sp.Function('Q')
W_ = sp.Integer(1) if MUTATE else wfun
arg = u - v
L = (-(rb + rd) * Phi - (2 * Phi.diff(x) * u.diff(x) - u.diff(x) ** 2 - a0s ** 2 * Q(arg.diff(x) ** 2 / a0s ** 2)) / (8 * sp.pi * Gs)
     + lam * (v.diff(x, 2) - 4 * sp.pi * Gs * (rd + (1 - W_) * rb)))
EL = {f.func.__name__: sp.simplify(e.lhs) for f, e in zip((Phi, u, v, lam), euler_equations(L, [Phi, u, v, lam], x))}
# (u - v)'' = 4 pi G w rho_b  <=  4 pi G dPhi - dlam
id_arg = sp.simplify(4 * sp.pi * Gs * EL["Phi"] - EL["lam"] - (arg.diff(x, 2) - 4 * sp.pi * Gs * W_ * rb))
# metric: Phi'' = u'' + [Q'(.) (u-v)']'  (deep-MOND primitive to make Q' explicit)
sq = sp.Symbol('s_', positive=True)
Qc = sp.Lambda(sq, sp.Rational(4, 3) * sq ** sp.Rational(3, 4) - sq)
Lc = L.subs(Q, Qc).doit()
ELc = {f.func.__name__: sp.simplify(e.lhs) for f, e in zip((Phi, u, v, lam), euler_equations(Lc, [Phi, u, v, lam], x))}
Xc = sp.diff(sp.diff(Qc(sq), sq).subs(sq, arg.diff(x) ** 2 / a0s ** 2) * arg.diff(x), x)
id_metric = sp.simplify(4 * sp.pi * Gs * ELc["u"] - (Phi.diff(x, 2) - u.diff(x, 2) - Xc))
# lambda: 4 pi G lambda'' = -X  (so 4 pi G lambda = -Phi_ph with decaying boundary conditions)
id_lam = sp.simplify(4 * sp.pi * Gs * ELc["v"] - (4 * sp.pi * Gs * lam.diff(x, 2) + Xc))
# potential felt by baryons: Phi + 4 pi G (1 - w) lambda; with 4 pi G lambda = -Phi_ph and Phi = u + Phi_ph:
Phi_ph = sp.Function('Phi_ph')(x)
felt_b = sp.simplify((u + Phi_ph) + (1 - W_) * (-Phi_ph))
felt_d = sp.simplify((u + Phi_ph) + (-Phi_ph))
unbound_invisible = sp.simplify(felt_b.subs(wfun, 0) - u) == 0 if not MUTATE else sp.simplify(felt_b - u) == 0
bound_boosted = sp.simplify(felt_b.subs(wfun, 1) - (u + Phi_ph)) == 0 if not MUTATE else sp.simplify(felt_b - (u + Phi_ph)) == 0
P(f"    dPhi:    {EL['Phi']} = 0")
P(f"    dlambda: {EL['lam']} = 0")
P(f"    (u - v)'' - 4 pi G w rho_b  = 4 pi G dPhi - dlambda          residual: {id_arg}")
P(f"    Phi'' - u'' - [Q'(u-v)']'   = 4 pi G du   (deep-MOND Q)      residual: {id_metric}")
P(f"    4 pi G lambda'' + [Q'(u-v)']' = 4 pi G dv                    residual: {id_lam}")
P(f"    potential felt by baryons: {felt_b}  (w = 0: {sp.simplify(felt_b.subs(wfun, 0)) if not MUTATE else felt_b};  w = 1: "
  f"{sp.simplify(felt_b.subs(wfun, 1)) if not MUTATE else felt_b});  by the dark component: {felt_d}")
n1 = (id_arg == 0) and (id_metric == 0) and (id_lam == 0) and unbound_invisible and bound_boosted and sp.simplify(felt_d - u) == 0
OUT["numbers"]["N1"] = {"id_arg": str(id_arg), "id_metric": str(id_metric), "id_lam": str(id_lam), "felt_b": str(felt_b),
                        "felt_d": str(felt_d), "unbound_invisible": bool(unbound_invisible), "bound_boosted": bool(bound_boosted)}
check("N1 the Euler-Lagrange equations give: kernel argument = Newtonian potential of the BOUND baryons; metric = Newtonian(all) "
      "+ phantom; unbound baryons and the dark component feel Newtonian(all) only; bound baryons feel the phantom",
      {"identities": [str(id_arg), str(id_metric), str(id_lam)], "unbound feels Newtonian only": bool(unbound_invisible),
       "bound feels phantom": bool(bound_boosted)}, n1,
      "the web's gas (the forest) and the dark component neither source nor feel the phantom: the web stays Newtonian")

# ============================================================================================ N2
banner("N2  GAUSS: the phantom beyond the bound region's edge -- source switch (this construction) vs flux switch (L352, L361)")
a0c = A0["canonical"]
r = np.geomspace(0.1, 5000.0, 20000) * KPC                            # m
Mb, ab = 6e10 * MSUN, 3.0 * KPC                                         # Hernquist baryons (L353's N1 galaxy)
Mb_r = Mb * r ** 2 / (r + ab) ** 2
r_e = 250 * KPC                                                         # bound region's edge (virial-like)
n2 = {}
for lam_s in (2.0, 3.0, float("inf")):
    s = np.ones_like(r) if not np.isfinite(lam_s) else (1 + r / (lam_s * MPC)) * np.exp(-r / (lam_s * MPC))
    gN = G * Mb_r / r ** 2; y = np.maximum(s * gN / a0c, 1e-14)
    M_src = Mb_r * (1 + s * (nu_mono(y) - 1))                          # source switch: phantom everywhere (QUMOND, spherical)
    M_flux = np.where(r <= r_e, M_src, Mb_r)                           # flux switch: Gauss-compensated beyond the edge (L352 Z1)
    row = {}
    for R_ in (0.1, 0.3, 1.0, 3.0):
        i = int(np.argmin(np.abs(r - R_ * MPC)))
        row[R_] = {"source_switch": float(M_src[i] / Mb), "flux_switch": float(M_flux[i] / Mb), "flux_over_baryons": float(M_flux[i] / Mb_r[i])}
    n2[lam_s] = row
    P(f"    lambda = {lam_s} Mpc: M_dyn/M_b at 0.1 / 0.3 / 1 / 3 Mpc -- source switch " +
      " / ".join(f"{row[R_]['source_switch']:.1f}" for R_ in (0.1, 0.3, 1.0, 3.0)) +
      ";  flux switch " + " / ".join(f"{row[R_]['flux_switch']:.1f}" for R_ in (0.1, 0.3, 1.0, 3.0)))
# the Lagrangian form re-screens the phantom's source: rho_2 = rho_1 - Y_lam * rho_1 (Yukawa, normalised); spherical
def lagrangian_mass(M_bk1, rgrid, lam_m):
    rho1 = np.gradient(M_bk1, rgrid) / (4 * np.pi * rgrid ** 2)
    w_ = np.gradient(rgrid)
    Rr, Rp_ = rgrid[:, None], rgrid[None, :]
    ker = Rp_ / (2 * lam_m * Rr) * (np.exp(-np.abs(Rr - Rp_) / lam_m) - np.exp(-(Rr + Rp_) / lam_m))
    conv = ker @ (rho1 * w_)
    rho2 = rho1 - conv
    return np.concatenate([[0.0], np.cumsum(0.5 * (4 * np.pi * rgrid[1:] ** 2 * rho2[1:] + 4 * np.pi * rgrid[:-1] ** 2 * rho2[:-1]) * np.diff(rgrid))])
n2L = {}
rs_ = np.geomspace(1.0, 30000.0, 2500) * KPC
Mb_rs = Mb * rs_ ** 2 / (rs_ + ab) ** 2
for lam_s in (2.0, 3.0):
    s_ = (1 + rs_ / (lam_s * MPC)) * np.exp(-rs_ / (lam_s * MPC)); gN_ = G * Mb_rs / rs_ ** 2
    Mph1 = Mb_rs * s_ * (nu_mono(np.maximum(s_ * gN_ / a0c, 1e-14)) - 1)
    Mph2 = lagrangian_mass(Mph1, rs_, lam_s * MPC)
    n2L[lam_s] = {R_: float((Mb + Mph2[int(np.argmin(np.abs(rs_ - R_ * MPC)))]) / (Mb + Mph1[int(np.argmin(np.abs(rs_ - R_ * MPC)))]))
                  for R_ in (0.1, 0.3, 1.0, 2.6)}
    P(f"    lambda = {lam_s} Mpc: Lagrangian / BK1-form enclosed lensing mass at 0.1 / 0.3 / 1 / 2.6 Mpc: " +
      " / ".join(f"{n2L[lam_s][R_]:.3f}" for R_ in (0.1, 0.3, 1.0, 2.6)))
OUT["numbers"]["N2"] = {str(k): {str(a): b for a, b in v.items()} for k, v in n2.items()}
OUT["numbers"]["N2_lagrangian_over_bk1"] = {str(k): {str(a): b for a, b in v.items()} for k, v in n2L.items()}
check("N2 GAUSS: beyond the bound region's edge (250 kpc) the source-switched phantom survives (M_dyn(1 Mpc) >= 10 M_b at "
      "lambda >= 2 Mpc) while a flux switch returns the lens to its baryons (M_dyn = M_b)",
      {str(k): f"1 Mpc: {v[1.0]['source_switch']:.1f} vs {v[1.0]['flux_switch']:.1f}" for k, v in n2.items()},
      all(n2[l][1.0]["source_switch"] >= 10 and abs(n2[l][1.0]["flux_over_baryons"] - 1) < 1e-9 for l in (2.0, 3.0)),
      "the switch threshold is decoupled from KiDS: it can sit at the virial density without truncating any lens")

# ============================================================================================ N3
banner("N3  RECIPROCITY: the linearised phantom response is symmetric; the species-response matrix is symmetric")
# 3-D periodic grid, screened QUMOND: phantom potential from bound-baryon density in an ambient field e (deep MOND regime)
Ng, Lg = 64, 8.0                                                      # 8 Mpc box, 125 kpc cells
kk = np.fft.fftfreq(Ng, d=Lg / Ng) * 2 * np.pi; KX, KY, KZ = np.meshgrid(kk, kk, kk, indexing="ij"); K2 = KX ** 2 + KY ** 2 + KZ ** 2
lam_g = 2.0


def phantom_potential(rho, outer=True):
    """Phi_ph (m^2/s^2) for density rho (Msun/Mpc^3) on the grid, screened QUMOND with an ambient uniform Newtonian
    field E0 (the rest of the universe) in the kernel's argument.  outer=True: the Lagrangian form S* div[q' grad S u_B]
    (the screening applied to the argument AND to the phantom's source, as the action's variation requires);
    outer=False: BK1's form (argument screened only)."""
    rk = np.fft.fftn(rho) * MSUN / MPC ** 3
    den = K2 + 1 / lam_g ** 2
    psik = -4 * np.pi * G * rk / den * MPC ** 2
    g = [np.real(np.fft.ifftn(-1j * KK_ * psik)) / MPC for KK_ in (KX, KY, KZ)]    # g = -grad psi
    g[0] = g[0] + E0
    gm = np.sqrt(g[0] ** 2 + g[1] ** 2 + g[2] ** 2); f = nu_mono(gm / a0c) - 1
    divk = sum(1j * KK_ * np.fft.fftn(f * gc) for KK_, gc in zip((KX, KY, KZ), g)) / MPC
    K2s = K2.copy(); K2s[0, 0, 0] = 1
    phk = -divk / (-K2s / MPC ** 2); phk[0, 0, 0] = 0                             # Lap Phi_ph = -div[(nu-1) g]
    if outer: phk = phk * K2 / (K2 + 1 / lam_g ** 2)                              # S*(k) = (k lam)^2/(1 + (k lam)^2)
    return np.real(np.fft.ifftn(phk))


E0 = 3e-5 * a0c
rho0 = np.zeros((Ng, Ng, Ng)); c0 = Ng // 2
rho0[c0 - 3:c0 + 4, c0 - 3:c0 + 4, c0 - 3:c0 + 4] = 5e10 / (7 * Lg / Ng) ** 3    # a galaxy (5e10 Msun) as the background
pA, pB = (c0 + 10, c0, c0), (c0, c0 + 14, c0 + 5)
RESP = {}
for mt in (1e6, 1e4):                                                  # test masses: linear regime (their own field << ambient)
    dm = mt / (Lg / Ng) ** 3
    rA = rho0.copy(); rA[pA] += dm; rB = rho0.copy(); rB[pB] += dm
    for outer in (True, False):
        base = phantom_potential(rho0, outer)
        RESP[(mt, outer)] = ((phantom_potential(rA, outer)[pB] - base[pB]) / mt, (phantom_potential(rB, outer)[pA] - base[pA]) / mt)
def _asym(t): return abs(t[0] - t[1]) / max(abs(t[0]), abs(t[1]))
resp_BA, resp_AB = RESP[(1e4, True)]                                   # potential at B per unit source at A, and back (per Msun)
asym = _asym(RESP[(1e4, True)]); asym_bk1 = _asym(RESP[(1e4, False)])
conv = abs(RESP[(1e4, True)][0] / RESP[(1e6, True)][0] - 1)
# species matrix [bound, unbound, dark]: potential felt by s per unit source of t (linear response, test masses)
KN = 1.0; KP = resp_BA / max(abs(resp_BA), 1e-300)                  # normalised Newtonian and phantom kernels (sign kept)
Mcon = np.array([[KN + KP, KN, KN], [KN, KN, KN], [KN, KN, KN]])     # construction: only bound-bound carries the phantom
Madd = np.array([[KN + KP, KN, KN], [KN + KP, KN, KN], [KN, KN, KN]])  # unbound gas feels bound's phantom, does not source it
sym_con = float(np.max(np.abs(Mcon - Mcon.T))); sym_add = float(np.max(np.abs(Madd - Madd.T)))
for (mt, outer), t in RESP.items():
    P(f"    test mass {mt:.0e} Msun, {'Lagrangian S* div[q grad S u_B]' if outer else 'BK1 one-S form             '}: B<-A {t[0]:.4e}, "
      f"A<-B {t[1]:.4e} (m^2/s^2 per Msun) -> asymmetry {_asym(t):.1e}")
P(f"    linearity: Lagrangian response changes by {conv:.1e} between 1e6 and 1e4 Msun test masses")
P(f"    species-response matrix asymmetry: construction {sym_con:.1e}; 'unbound gas feels but does not source' {sym_add:.2f}")
OUT["numbers"]["N3"] = {"resp_BA": resp_BA, "resp_AB": resp_AB, "asym": asym, "asym_bk1_form": asym_bk1, "linearity": conv,
                        "all": {f"{k[0]:.0e}|{'lagr' if k[1] else 'bk1'}": v for k, v in RESP.items()},
                        "matrix_asym_construction": sym_con, "matrix_asym_additive": sym_add}
check("N3 RECIPROCITY: the linearised phantom response (Lagrangian form) is symmetric to < 2% on the grid and the construction's "
      "species matrix is symmetric; the non-Lagrangian alternative is not",
      f"response asymmetry {asym:.1e} (BK1's one-S form {asym_bk1:.1e}); matrices {sym_con:.1e} vs {sym_add:.2f}",
      asym < 0.02 and sym_con == 0 and sym_add > 0.1,
      "action = reaction: whatever cannot source the phantom cannot feel it (L353 N2 extended to the web's gas)")

# ============================================================================================ N4
banner("N4  THE EDGE STEP: Phi_ph at the bound region's edge (screened, isolated, nu_mono), as sqrt(2|Phi_ph|) vs v_flat")
objs = {"dwarf (M_B 1e9, edge 60 kpc)": (1e9, 60.0), "Milky Way (6e10, 250 kpc)": (6e10, 250.0),
        "group (1e12, 600 kpc)": (1e12, 600.0), "cluster (1.5e13, 1.8 Mpc)": (1.5e13, 1800.0)}
n4 = {}
for lab, (Mo, re_) in objs.items():
    row = {}
    for lam_s in (1.0, 2.0, 3.0):
        rr_ = np.geomspace(re_, re_ + 40 * lam_s * 1e3, 6000) * KPC
        s = (1 + rr_ / (lam_s * MPC)) * np.exp(-rr_ / (lam_s * MPC)); gN = G * Mo * MSUN / rr_ ** 2
        gph = s * gN * (nu_mono(np.maximum(s * gN / a0c, 1e-14)) - 1)
        Phi_e = -_trap(gph, rr_)                                        # Phi_ph(edge), zero far away
        vflat = (G * Mo * MSUN * a0c) ** 0.25
        row[lam_s] = {"Phi_ph_edge_km2s2": Phi_e / 1e6, "v_step_kms": math.sqrt(2 * abs(Phi_e)) / 1e3, "v_flat_kms": vflat / 1e3}
    n4[lab] = row
    P(f"    {lab:28s}: v_flat {row[2.0]['v_flat_kms']:.0f} km/s; step speed sqrt(2|Phi_ph|) = " +
      ", ".join(f"{row[l]['v_step_kms']:.0f} (lam {l})" for l in (1.0, 2.0, 3.0)) + " km/s")
OUT["numbers"]["N4"] = {k: {str(a): b for a, b in v.items()} for k, v in n4.items()}
check("N4 (documentary) the edge step: a baryon entering a bound region gains |Phi_ph(edge)| per unit mass (~2-3 v_flat^2 at "
      "lambda = 2 Mpc) -- a prediction for accretion shocks and outflows, not a free parameter",
      {k: f"{v[2.0]['v_step_kms']:.0f} vs v_flat {v[2.0]['v_flat_kms']:.0f} km/s" for k, v in n4.items()}, True, "", load_bearing=False)

# ============================================================================================ N5
banner("N5  THE SWITCH'S BACK-REACTION: density switch vs curvature switch; tensor blindness")
H0 = 67.36e3 / MPC; OmL, Om = 0.6847, 0.3153
Hz = H0 * math.sqrt(Om * 1.25 ** 3 + OmL)                              # z = 0.25
c2_cap = (0.6e-3, 2.9e-3)                                               # L350: Planck cap on c2
n5 = {}
for lab, (Mo, re_) in objs.items():
    Phi_e = abs(n4[lab][2.0]["Phi_ph_edge_km2s2"]) * 1e6
    x_c, dlnx = 50.0, 1.0                                               # threshold and the switch's log-width
    w_prime = 1 / (x_c * dlnx)                                          # dw/dx at the edge
    fb_edge = 0.157                                                     # baryon share of the density at the edge
    # (a) density switch: the coupling -rho_b (1 - w(x_m)) Phi_ph varies with the metric through n.T.n ~ rho sqrt(gamma):
    dens_metric = 3 * fb_edge * Phi_e / C_LIGHT ** 2
    # khronon: d/dK of the coupling relative to the c2 K^2/(8 pi G) term: (2/9) f_b x^2 w' |Phi|/(c2 c^2) (x_m ~ x_c at the edge)
    dens_khronon = [(2 / 9) * fb_edge * x_c ** 2 * w_prime * Phi_e / (c2 * C_LIGHT ** 2) for c2 in c2_cap]
    # (b) curvature switch x~ = 9 R3/(4K^2): the same coupling enters the metric equation with weight |Phi| w'/(H^2 l^2)
    ell = re_ * KPC                                                     # the edge's radial width ~ r_e (x ~ r^-2)
    curv_metric = fb_edge * Phi_e * w_prime * x_c / (Hz ** 2 * ell ** 2) / x_c   # = f_b |Phi| w' / (H^2 l^2)
    n5[lab] = {"density_switch_metric": dens_metric, "density_switch_khronon": dens_khronon, "curvature_switch_metric": curv_metric}
    P(f"    {lab:28s}: density switch -> metric {dens_metric:.1e}, khronon {dens_khronon[0]:.1e}..{dens_khronon[1]:.1e};  "
      f"curvature switch -> metric {curv_metric:.2f}")
# tensor blindness (symbolic): det of the TT metric diag(e^h, e^-h, 1) is 1 -> sqrt(gamma), n.T.n (dust at rest) and K unperturbed
hh = sp.symbols('h', real=True)
det_tt = sp.simplify(sp.Matrix([[sp.exp(hh), 0, 0], [0, sp.exp(-hh), 0], [0, 0, 1]]).det())
P(f"    tensor blindness: det(TT spatial metric) = {det_tt} -> sqrt(gamma) and the dust density n.T.n are unchanged; "
  f"K is unperturbed by a TT mode (L359 S1) -> c_T = 1 of C-H/K without the flux switch (L351) stands")
OUT["numbers"]["N5"] = {**n5, "det_tt": str(det_tt)}
ok5 = all(v["density_switch_metric"] < 1e-3 and max(v["density_switch_khronon"]) < 1e-1 for v in n5.values()) and det_tt == 1 \
      and any(v["curvature_switch_metric"] > 0.1 for v in n5.values())
check("N5 the density-built switch perturbs the metric by < 1e-3 and the khronon by < 10% of its c2 term at every edge, and is "
      "tensor-blind; the curvature-built switch (x~) would perturb the metric at O(0.1-1)",
      {k: f"{v['density_switch_metric']:.0e} / {max(v['density_switch_khronon']):.0e} vs curvature {v['curvature_switch_metric']:.2f}"
       for k, v in n5.items()}, ok5, "the switch must read the matter density, not the leaves' curvature")

# ============================================================================================ N6
banner("N6  WHAT IS INHERITED UNCHANGED INSIDE BOUND REGIONS (committed lanes, not recomputed)")
bk1 = json.load(open(os.path.join(REPO, "real_research", "blind_kernel_2026", "BK1_screened_kernel_results.json")))
lam_min = bk1["numbers"]["lambda_min"]
P(f"    Sun: inside the Galaxy's bound region (w = 1); the kernel reads the Galaxy -- BK1 C1: lambda >= {lam_min} Mpc keeps it to >= 99.9%")
P("    1PN = GR (KM3); moving-source gate + health with the monotone law (L340); no new mode (L353 N3: the pair is elliptic; w is a")
P("    function of existing fields); c_T = 1 (N5 + L351).  KiDS: GP2.  Growth, forest, lensing power: GP3.")
OUT["numbers"]["N6"] = {"lambda_min_Mpc": lam_min}
check("N6 (documentary) inherited local limits", f"lambda_min = {lam_min} Mpc (BK1 C1); KM3, L340, L351, L353 N3", True, "", load_bearing=False)

# ============================================================================================ verdict
banner("VERDICT")
P("""  THE CONSTRUCTION IS WRITTEN DOWN AND ITS STRUCTURE CHECKED.  One Lagrangian: Newtonian gravity for all matter, a QUMOND
  kernel whose argument is the Newtonian potential of the baryons of bound regions (w(x_m), a matter-density switch), and
  L353's subtraction pair extended to the unbound baryons.  Bound baryons feel their phantom; the web's gas, the forest
  and the dark component feel Newtonian gravity only; light sees the phantom.  The phantom is GENERATED (a field of the
  bound baryons, not a conserved fluid) and, unlike every switch on the record, it is NOT Gauss-cancelled at the edge:
  the switch threshold no longer sets where a lens's phantom ends.  Costs: a potential step |Phi_ph(edge)| ~ 2-3 v_flat^2
  for baryons entering a bound region, and (for KiDS) the screening length lambda of BK1.""")
n_fail = sum(1 for _, ok, lb in CH if lb and not ok)
OUT["n_checks"], OUT["n_fail_load_bearing"] = len(CH), n_fail
outname = f"{SLUG}_results{'_MUTATE' if MUTATE else ''}.json"
json.dump(OUT, open(os.path.join(HERE, outname), "w"), indent=1, default=str)
P(f"\n  {sum(1 for _, ok, _ in CH if ok)}/{len(CH)} checks pass; load-bearing failures: {n_fail}; wrote {outname} ({time.time() - T0:.0f} s)")
sys.exit(0 if n_fail == 0 else 1)
