import numpy as np
print("="*100)
print("[E] BOTH WAYS: what SURVIVES the dissolution, precisely. The no-go has TWO distinct claims;")
print("    the door dissolves ONE and leaves the OTHER. Separate them cleanly.")
print("="*100)
print()
print("CLAIM 1 (the ENERGETICS / passivity claim): 'the mu(0)<mu(inf) inversion REQUIRES an ACTIVE")
print("         (energy-injecting) medium, because every PASSIVE bath gives anti-MOND.'")
print("  STATUS UNDER THIS DOOR: DISSOLVED for the closed isolated system.")
print("  - Milgrom 2208.07073 Eq.(11)+text: the time-nonlocal MI CONSERVES phi+E_k. No net energy gain.")
print("  - The instantaneous reading is 1-DOF autonomous => conserves a modified energy (part3b: 1.5e-6).")
print("  - A passive conservative NONLINEAR element (softening spring) reproduces the 'modulus inversion'")
print("    with oint F dx = 0 (part5 D1). 'Inversion at two operating points' != 'Im chi sign-flip'.")
print("  - The passivity theorem (Im chi>=0) binds a LINEAR response of an OPEN system (input separable")
print("    from output). Milgrom states the MI is a CLOSED system where this framing does not apply.")
print("  => On bound orbits (galaxies) BOTH ledgers give ZERO net energy exchange (part4 C2). The galactic")
print("     phenomenology lives entirely on closed/quasi-bound orbits. So the ENERGETIC no-go does NOT bind")
print("     the physical regime. The 'active kernel' is NOT required for energy reasons. <-- GAP DISSOLVES here.")
print()
print("CLAIM 2 (the REPRESENTATION claim): 'the MI memory kernel K cannot be realized as a PASSIVE")
print("         linear bath / positive spectral measure (a Caldeira-Leggett-type auxiliary field).'")
print("  STATUS UNDER THIS DOOR: SURVIVES, but is DEMOTED from 'energetic no-go' to 'representation no-go'.")
print("  - X2 constructive (agentX_sk_kernel.out [3]): NNLS positive-measure fit residual 92.7%; a negative")
print("    DC target is infeasible for any positive measure. TRUE -- but this only says the linearized kernel")
print("    is not a PASSIVE-LTI-BATH kernel. It does NOT say the dynamics injects energy (Claim 1).")
print("  - This is the SAME content as Milgrom's own remark: a Caldeira-Leggett passive bath gives standard")
print("    (renormalized, anti-MOND-direction) inertia; MOND-direction inertia needs a non-Caldeira-Leggett")
print("    structure. That is a STATEMENT ABOUT THE DERIVATION ROUTE (no passive-bath UV completion), not")
print("    an instability or an energy-conservation violation.")
print()
print("NET: the 'missing ACTIVE kernel K_active' splits into:")
print("   (a) 'missing because energy must be injected' -> FALSE under this door (closed system conserves).")
print("   (b) 'the kernel is not a passive-linear-bath kernel'  -> TRUE, but that is a property the FINAL")
print("       theory is ALLOWED to have (Milgrom's MI is a real, conservative, non-bath nonlocal action).")
print()
print("CONSEQUENCE FOR THE CAPSTONE: the flagged 'MISSING piece K_active' was framed as an ENERGETIC")
print("obstruction (needs a sustained MOND-direction PUMP / a cosmological active source). Under this door")
print("that energetic framing is an ARTIFACT of (i) linearizing a nonlinear closed-system relation and")
print("(ii) representing it as an open causal LTI bath. The CORRECT statement is weaker: the MI kernel is")
print("a conservative time-nonlocal functional (Milgrom Eq.3,11) that is simply NOT of passive-bath form.")
print("No cosmological energy source is needed; the '4-source hunt came up empty' is therefore answering")
print("a question (where is the pump?) that the closed-system MI does not pose.")
print()
print("WHAT THE CAPSTONE STILL CORRECTLY FLAGS (does NOT dissolve):")
print("  - There is still NO explicit covariant action whose NR limit IS Milgrom's nonlocal I[{r},w,a0]")
print("    with the framework's specific mu_fw + a0=c^2 sqrt(L/32pi). Milgrom gives the NR template (Eq.3-5)")
print("    but explicitly leaves the covariant 'Fundamond' OPEN, and the kappa=1/2 / Z coefficient unforced.")
print("  - AeST (2007.00082) is modified GRAVITY: matter couples to g (S_m[g], Eq.5), inertia standard,")
print("    MOND from the modified Poisson Eq.(1). So AeST is NOT the covariant MI home (gap's AeST premise OK).")
print("  - The MI<->MG join (Milgrom-1994 no-go) is untouched by this door.")
