#!/usr/bin/env python3
"""
The E6 skyscraper, floor N: orbifold doublet-triplet splitting + proton-decay fix.
=================================================================================

Building the E6 -> SM orbifold GUT honestly. Two notorious problems of 4D SUSY GUTs:
  (1) Doublet-Triplet (DT) splitting: the Higgs lives in a 5 of SU(5) = color
      triplet T + weak doublet H. We need H light (~100 GeV) and T heavy (~M_GUT,
      or it mediates fast proton decay). In 4D this needs fine-tuning to 1 part in
      ~10^14 -- the DT problem.
  (2) Dimension-5 proton decay: the color-triplet Higgsino exchange gives p->nu-bar K+,
      which is TOO FAST in minimal SUSY SU(5) -- it is essentially EXCLUDED.

The orbifold solves BOTH geometrically (Kawamura 2001; Hall-Nomura 2001): the same Z2
parity that breaks SU(5)->SM assigns the doublet a surviving zero mode (+) and projects
the triplet out (-). No fine-tuning; and with no triplet zero mode, the dim-5 operator
is absent. This turns the proton-decay TENSION I raised earlier into a resolved feature.

Pure stdlib + numpy.  Run:  python reviews/e6_doublet_triplet.py
"""

import numpy as np

# SU(5) fundamental orbifold parity that breaks SU(5) -> SU(3)xSU(2)xU(1):
#   P = diag(-1,-1,-1,+1,+1)   (minus on color, plus on weak)
P = np.diag([-1, -1, -1, +1, +1])

LABELS = ["c1", "c2", "c3", "w1", "w2"]   # 3 color + 2 weak indices


def part1_higgs():
    print("=" * 76)
    print("(1) The Higgs 5_H of SU(5) under the orbifold parity P")
    print("=" * 76)
    print("   5_H = T(3,1)_-1/3  +  H(1,2)_+1/2   (color triplet + weak doublet)")
    print("   Parity of each component (diagonal of P):")
    for lab, p in zip(LABELS, np.diag(P)):
        kind = "triplet T" if lab.startswith("c") else "doublet H"
        zmode = "SURVIVES (massless)" if p > 0 else "PROJECTED (KK mass ~1/R)"
        print(f"     {lab} ({kind}):  P = {int(p):+d}  -> {zmode}")
    print("   => doublet H survives as the light SM Higgs; triplet T is projected out.")
    print("      DOUBLET-TRIPLET SPLITTING with NO fine-tuning. ✓\n")


def part2_gauge():
    print("=" * 76)
    print("(2) The SAME parity breaks SU(5) -> SM (consistency check)")
    print("=" * 76)
    # adjoint 24: M -> P M P  (P^2 = I). Count parities of the gauge generators.
    plus, minus = 0, 0
    for i in range(5):
        for j in range(5):
            if i == j:
                continue
            par = P[i, i] * P[j, j]      # parity of the E_ij generator
            if par > 0:
                plus += 1
            else:
                minus += 1
    # plus generators: within color (3x3, off-diag) + within weak (2x2) + the U(1)s
    print(f"   adjoint generators with P=+ (unbroken): SU(3)xSU(2)xU(1) directions")
    print(f"   adjoint generators with P=- (broken):   the X,Y leptoquark bosons")
    print(f"   off-diagonal generator parities: {plus} even (+), {minus} odd (-)")
    print("   The 12 X,Y bosons (color<->weak, 3x2x2) get P=- and are projected:")
    print("   SU(5) -> SU(3)xSU(2)xU(1). Same P, both jobs. ✓\n")


def part3_proton_decay():
    print("=" * 76)
    print("(3) Consequence: dimension-5 proton decay is removed")
    print("=" * 76)
    print("   The dim-5 operators QQQL / u^c u^c d^c e^c that drive p -> nu-bar K+ in")
    print("   minimal SUSY SU(5) are generated by COLOR-TRIPLET HIGGSINO exchange.")
    print("   With the triplet projected out (no zero mode, part 1), that exchange has")
    print("   no light mediator -- the dangerous dim-5 operator is ABSENT/suppressed.")
    print("   => the orbifold REMOVES the dim-5 proton-decay problem that excludes")
    print("      minimal 4D SUSY SU(5). (The tension I flagged earlier is resolved here.)")
    print("   Residual: dim-6 (gauge X,Y) proton decay remains, tau(p->e+pi0) ~ 10^36 yr,")
    print("   above the Super-K bound and a Hyper-K target. A real, surviving prediction.\n")


def main():
    part1_higgs()
    part2_gauge()
    part3_proton_decay()
    print("=" * 76)
    print("VERDICT -- a genuine advantage of the orbifold skyscraper")
    print("=" * 76)
    print("  Building the GUT on (T^2)^3/(Z2xZ2) rather than in 4D buys two real things")
    print("  that 4D SUSY GUTs cannot get for free:")
    print("   * doublet-triplet splitting with NO 10^14 fine-tuning;")
    print("   * removal of the dim-5 proton decay that excludes minimal SUSY SU(5).")
    print("  This is standard orbifold-GUT physics (Kawamura; Hall-Nomura), and it is")
    print("  a legitimate, positive result for the construction.")
    print()
    print("  HONEST status (so the skyscraper isn't oversold):")
    print("   * it still requires SUSY (unseen at the LHC);")
    print("   * the parity assignment is a CHOICE (the orbifold embedding);")
    print("   * the exotic-free 3-generation vacuum + moduli stabilization remain the")
    print("     hard, open problems;")
    print("   * none of this DERIVES the SM parameter values (still moduli-dependent).")
    print("  Net: a competent, legitimate SUSY orbifold GUT with a real DT/proton-decay")
    print("  advantage -- not a theory of everything, but honest, standard physics.")


if __name__ == "__main__":
    main()
