#!/usr/bin/env python3
"""Independent regression tests for the slipless exact-MOND center theorem."""

from __future__ import annotations

import importlib
import hashlib
import json
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest

import sympy as sp


try:
    core = importlib.import_module(
        "qwen_claude_field_theory.closure_2026."
        "slipless_exact_mond_center_nogo_2026."
        "slipless_exact_mond_center_nogo_2026"
    )
except ModuleNotFoundError:
    core = None


class SliplessCenterTheoremTests(unittest.TestCase):
    def test_manifest_hashes_pin_every_source_and_output(self) -> None:
        """Catches stale code, report, or result bytes behind a valid schema."""

        here = Path(__file__).resolve().parent
        repository = here.parents[2]
        manifest = json.loads(
            (here / "computation_manifest.json").read_text(encoding="utf-8")
        )
        for item in manifest["sources"] + manifest["outputs"]:
            payload = (repository / item["path"]).read_bytes()
            self.assertEqual(
                hashlib.sha256(payload).hexdigest(),
                item["sha256"],
                item["path"],
            )

    def test_derivation_module_exists(self) -> None:
        """Catches a missing executable derivation, not a prose-only claim."""

        self.assertIsNotNone(core, "the symbolic derivation module is missing")

    @unittest.skipIf(core is None, "derivation module not implemented yet")
    def test_exponential_constitutive_series_is_derived(self) -> None:
        """Catches a wrong exponential sign or a phenomenologically inserted root."""

        a0, b = sp.symbols("a0 b", positive=True)
        coefficients = core.derive_exponential_puiseux(a0=a0, b=b)
        self.assertEqual(sp.simplify(coefficients[1] ** 2 - a0 * b), 0)
        self.assertEqual(sp.simplify(coefficients[2] - b / 4), 0)
        self.assertEqual(
            sp.simplify(coefficients[3] - 7 * b ** sp.Rational(3, 2) /
                        (96 * sp.sqrt(a0))),
            0,
        )

    @unittest.skipIf(core is None, "derivation module not implemented yet")
    def test_no_slip_curvature_coefficients(self) -> None:
        """Catches wrong metric signs, contractions, or radial Hessian weights."""

        r, acceleration_coefficient = sp.symbols("r C", positive=True)
        phi_amplitude = sp.Rational(2, 3) * acceleration_coefficient
        ricci, kretschmann = core.linearized_radial_curvature_on_axis(
            power=sp.Rational(3, 2),
            phi_amplitude=phi_amplitude,
            psi_amplitude=phi_amplitude,
            radius=r,
        )
        self.assertEqual(
            sp.simplify(ricci * sp.sqrt(r) / acceleration_coefficient), 5
        )
        self.assertEqual(
            sp.simplify(kretschmann * r / acceleration_coefficient**2), 43
        )

    @unittest.skipIf(core is None, "derivation module not implemented yet")
    def test_schwarzschild_weak_field_benchmark(self) -> None:
        """Catches a curvature contraction that cannot reproduce 48 M^2/r^6."""

        r, mass = sp.symbols("r M", positive=True)
        ricci, kretschmann = core.linearized_radial_curvature_on_axis(
            power=-1,
            phi_amplitude=-mass,
            psi_amplitude=-mass,
            radius=r,
        )
        self.assertEqual(sp.simplify(ricci), 0)
        self.assertEqual(sp.simplify(kretschmann * r**6 / mass**2), 48)

    @unittest.skipIf(core is None, "derivation module not implemented yet")
    def test_de_sitter_weak_field_benchmark(self) -> None:
        """Checks R=12H_geo^2 and K=24H_geo^4 for H_geo=H_phys/c."""

        r, hubble = sp.symbols("r H", positive=True)
        ricci, kretschmann = core.linearized_radial_curvature_on_axis(
            power=2,
            phi_amplitude=-hubble**2 / 2,
            psi_amplitude=hubble**2 / 4,
            radius=r,
        )
        self.assertEqual(sp.simplify(ricci / hubble**2), 12)
        self.assertEqual(sp.simplify(kretschmann / hubble**4), 24)

    @unittest.skipIf(core is None, "derivation module not implemented yet")
    def test_serialized_puiseux_powers_are_unambiguous(self) -> None:
        """Catches labels that turn r^(n/2) into the different expression r^n/2."""

        keys = set(core.derive_audit_results()["puiseux_g_coefficients"])
        self.assertEqual(keys, {"r^(1/2)", "r^1", "r^(3/2)"})

    @unittest.skipIf(core is None, "derivation module not implemented yet")
    def test_recorded_symbolic_result_equals_fresh_derivation(self) -> None:
        """Catches a manifest-pinned result generated by older code."""

        recorded = json.loads(
            Path(__file__).with_name("calculation_results.json").read_text(
                encoding="utf-8"
            )
        )
        self.assertEqual(recorded, core.derive_audit_results())

    @unittest.skipIf(core is None, "derivation module not implemented yet")
    def test_standalone_status_is_derived_from_live_symbolic_checks(self) -> None:
        """Catches an unconditional success exit or hard-coded verdict label."""

        certificate = core.derive_symbolic_certificate()
        self.assertTrue(certificate["checks"])
        self.assertTrue(all(certificate["checks"].values()))
        self.assertTrue(certificate["passed"])
        results = core.derive_audit_results()
        self.assertEqual(results["certificate"], certificate)
        self.assertEqual(
            results["classification"]["result"],
            "NO_GO_UNDER_STATED_CENTER_ASSUMPTIONS",
        )

    @unittest.skipIf(core is None, "derivation module not implemented yet")
    def test_generic_mu_power_center_universality_class(self) -> None:
        """Catches an exponential-only argument masquerading as the general theorem."""

        n, kappa, a0, b, r = sp.symbols(
            "n kappa a0 b r", positive=True
        )
        deriver = getattr(core, "derive_generic_center_scaling", None)
        if deriver is None:
            self.fail("generic center-scaling derivation is missing")
        result = deriver(
            mu_power=n,
            mu_coefficient=kappa,
            a0=a0,
            b=b,
            radius=r,
        )
        s = sp.Rational(1, 1) / (n + 1)
        coefficient = (b * a0**n / kappa) ** s
        self.assertEqual(sp.simplify(result["acceleration_power"] - s), 0)
        self.assertEqual(
            sp.simplify(result["acceleration_coefficient"] / coefficient), 1
        )
        self.assertEqual(
            sp.simplify(
                result["Ricci_scalar"] * r ** (1 - s) / coefficient
                - 2 * (s + 2)
            ),
            0,
        )
        self.assertEqual(
            sp.simplify(
                result["Kretschmann"] * r ** (2 - 2 * s) / coefficient**2
                - 4 * (3 * s**2 + 4 * s + 8)
            ),
            0,
        )
        self.assertEqual(
            result["derivative_hypothesis"],
            "r*g'(r)/g(r) -> 1/(n+1)",
        )

    @unittest.skipIf(core is None, "derivation module not implemented yet")
    def test_value_asymptotic_nogo_uses_undifferentiated_tangential_field(self) -> None:
        """Catches differentiating an uncontrolled little-o constitutive remainder."""

        n, kappa, a0, b, r, c_light = sp.symbols(
            "n kappa a0 b r c_light", positive=True
        )
        result = core.derive_value_asymptotic_curvature_lower_bound(
            mu_power=n,
            mu_coefficient=kappa,
            a0=a0,
            source_coefficient=b,
            radius=r,
            speed_of_light=c_light,
        )
        s = 1 / (n + 1)
        coefficient = (b * a0**n / kappa) ** s
        expected = 8 * coefficient**2 * r ** (2 * s - 2) / c_light**4
        self.assertEqual(sp.simplify(result["acceleration_power"] - s), 0)
        self.assertEqual(
            sp.simplify(result["tangential_K_lower_bound"] - expected), 0
        )
        self.assertEqual(
            sp.simplify(result["tangential_K_lower_bound_power"] - (2 * s - 2)),
            0,
        )

    @unittest.skipIf(core is None, "derivation module not implemented yet")
    def test_physical_curvature_units_cannot_be_silently_set_to_one(self) -> None:
        """Catches mixing physical acceleration with dimensionless metric potentials."""

        n, kappa, a0, b, r, c_light = sp.symbols(
            "n kappa a0 b r c_light", positive=True
        )
        generic = core.derive_generic_center_scaling(
            mu_power=n,
            mu_coefficient=kappa,
            a0=a0,
            b=b,
            radius=r,
            speed_of_light=c_light,
        )
        self.assertEqual(
            sp.simplify(
                generic["Ricci_scalar"].subs(c_light, 2)
                / generic["Ricci_scalar"].subs(c_light, 1)
            ),
            sp.Rational(1, 4),
        )
        self.assertEqual(
            sp.simplify(
                generic["Kretschmann"].subs(c_light, 2)
                / generic["Kretschmann"].subs(c_light, 1)
            ),
            sp.Rational(1, 16),
        )

        s, c_phi, c_psi = sp.symbols("s C_phi C_psi", positive=True)
        slipped = core.derive_arbitrary_slip_center_curvature(
            acceleration_power=s,
            phi_acceleration_coefficient=c_phi,
            psi_acceleration_coefficient=c_psi,
            radius=r,
            speed_of_light=c_light,
        )
        expected_ricci = (
            2 * (s + 2) * (2 * c_psi - c_phi) * r ** (s - 1) / c_light**2
        )
        expected_k = 4 * r ** (2 * s - 2) * (
            c_phi**2 * (s**2 + 2)
            + c_psi**2 * (2 * s**2 + 4 * s + 6)
        ) / c_light**4
        self.assertEqual(sp.simplify(slipped["Ricci_scalar"] - expected_ricci), 0)
        self.assertEqual(sp.simplify(slipped["Kretschmann"] - expected_k), 0)

    @unittest.skipIf(core is None, "derivation module not implemented yet")
    def test_curvature_obstruction_does_not_depend_on_zero_slip(self) -> None:
        """Catches a false loophole in which tuning Psi cancels all curvature."""

        s, c_phi, c_psi, r = sp.symbols("s C_phi C_psi r", positive=True)
        deriver = getattr(core, "derive_arbitrary_slip_center_curvature", None)
        if deriver is None:
            self.fail("arbitrary-slip curvature derivation is missing")
        result = deriver(
            acceleration_power=s,
            phi_acceleration_coefficient=c_phi,
            psi_acceleration_coefficient=c_psi,
            radius=r,
        )
        expected_ricci = 2 * (s + 2) * (2 * c_psi - c_phi) * r ** (s - 1)
        expected_kretschmann = 4 * r ** (2 * s - 2) * (
            c_phi**2 * (s**2 + 2)
            + c_psi**2 * (2 * s**2 + 4 * s + 6)
        )
        self.assertEqual(sp.simplify(result["Ricci_scalar"] - expected_ricci), 0)
        self.assertEqual(
            sp.simplify(result["Kretschmann"] - expected_kretschmann), 0
        )
        self.assertEqual(
            sp.simplify(result["Kretschmann"].subs(c_psi, 0)
                        / (4 * c_phi**2 * (s**2 + 2) * r ** (2 * s - 2))),
            1,
        )

    @unittest.skipIf(core is None, "derivation module not implemented yet")
    def test_exact_exponential_inner_kepler_series(self) -> None:
        """Catches loss of the kernel-specific corrections beyond deep MOND."""

        a0, b, z = sp.symbols("a0 b z", positive=True)
        deriver = getattr(core, "derive_inner_kepler_series", None)
        if deriver is None:
            self.fail("inner Kepler-series derivation is missing")
        series = sp.expand(deriver(a0=a0, b=b, sqrt_radius=z))
        self.assertEqual(sp.simplify(series.coeff(z, 0) - a0 * b), 0)
        self.assertEqual(
            sp.simplify(series.coeff(z, 1) - b * sp.sqrt(a0 * b) / 2), 0
        )
        self.assertEqual(sp.simplify(series.coeff(z, 2) - 5 * b**2 / 24), 0)

    def test_independent_high_precision_root_audit(self) -> None:
        """Catches a formal series that does not approach the exact implicit root."""

        script = Path(__file__).with_name("independent_numeric_audit.py")
        if not script.exists():
            self.fail("independent numerical root audit is missing")
        with tempfile.TemporaryDirectory() as temporary:
            output = Path(temporary) / "numeric.json"
            run = subprocess.run(
                [sys.executable, str(script), "--json", "--output", str(output)],
                check=False,
                capture_output=True,
                text=True,
            )
            self.assertEqual(run.returncode, 0, run.stderr or run.stdout)
            result = json.loads(run.stdout)
            self.assertEqual(result, json.loads(output.read_text(encoding="utf-8")))
        self.assertGreater(result["relative_error_log_slope"], 1.49)
        self.assertLess(result["relative_error_log_slope"], 1.51)
        self.assertLess(result["max_equation_residual"], 1e-60)
        self.assertLess(result["scaled_error_limit_deviation"], 5e-6)

    @unittest.skipIf(core is None, "derivation module not implemented yet")
    def test_density_kernel_regular_center_matching_law(self) -> None:
        """Catches an escape criterion that ignores the source's vanishing order."""

        n, m = sp.symbols("n m", positive=True)
        deriver = getattr(core, "derive_density_power_threshold", None)
        if deriver is None:
            self.fail("density/kernel regularity-threshold derivation is missing")
        result = deriver(mu_power=n, density_power=m)
        self.assertEqual(
            sp.simplify(
                result["acceleration_power"] - (m + 1) / (n + 1)
            ),
            0,
        )
        self.assertEqual(
            sp.simplify(
                result["Kretschmann_tangential_lower_bound_power"]
                - 2 * (m - n) / (n + 1)
            ),
            0,
        )
        constant_core = deriver(mu_power=1, density_power=0)
        marginal_core = deriver(mu_power=1, density_power=1)
        self.assertEqual(
            constant_core["Kretschmann_tangential_lower_bound_power"], -1
        )
        self.assertEqual(
            marginal_core["Kretschmann_tangential_lower_bound_power"], 0
        )
        self.assertEqual(result["regularity_claim"], "necessary_not_sufficient")

    @unittest.skipIf(core is None, "derivation module not implemented yet")
    def test_exact_exponential_operator_is_elliptic_only_off_zero(self) -> None:
        """Catches silently treating the y=0 degeneracy as a positive eigenvalue."""

        y = sp.symbols("y", positive=True)
        transverse, longitudinal = core.derive_operator_eigenvalues(y)
        self.assertEqual(sp.simplify(transverse - (1 - sp.exp(-y))), 0)
        self.assertEqual(
            sp.simplify(longitudinal - (1 + (y - 1) * sp.exp(-y))), 0
        )
        self.assertEqual(sp.limit(transverse, y, 0, dir="+"), 0)
        self.assertEqual(sp.limit(longitudinal, y, 0, dir="+"), 0)
        for sample in (sp.Rational(1, 100), sp.Rational(1, 2), 1, 10):
            self.assertGreater(float(transverse.subs(y, sample)), 0.0)
            self.assertGreater(float(longitudinal.subs(y, sample)), 0.0)


if __name__ == "__main__":
    unittest.main(verbosity=2)
