#!/usr/bin/env python3
"""THE CONVERGED CALC. Slip-lock (DC-013) closed the frame-free LOCAL case by diff-invariance locking
the coupling to the delta-R ray v=(1,-2). NONLOCALITY unlocks that: a nonlocal diff-invariant operator
(e.g. box^-1 d_i d_j R_ij^TF) can couple in ANY (Phi,Psi) direction. So the question is purely the
2x2 response with GENERAL M: can {eta=1 (lensing) + enhancement (MOND) + ghost-free} coexist once the
(1,-2) lock is removed? Correct sign convention: integrating out HEALTHY modes (K>0) gives the Schur
complement M = -J K^-1 J^T => M NEGATIVE-semidefinite. sympy decides."""
import sympy as sp

m, rho, A, B, C = sp.symbols('m rho A B C', real=True)   # m=M_p^2 k^2 > 0
Ggr = sp.Matrix([[0, 2*m],[2*m, -2*m]])
M = sp.Matrix([[A, B],[B, C]])                            # general (nonlocality unlocks all directions)
Q = Ggr + M
s = sp.Matrix([rho, 0])
X = sp.simplify(Q.inv()*s)
Phi, Psi = X[0], X[1]
eta = sp.simplify(Psi/Phi)
print("=== general 2x2 response (nonlocal: M unconstrained in direction) ===")
print(f"   eta = Psi/Phi = {eta}")
B_eta1 = sp.solve(sp.Eq(eta, 1), B)[0]
print(f"   eta=1 (correct lensing)  <=>  B = {B_eta1}")

print("\n=== on eta=1: enhancement E = Phi/Phi_GR, and the ghost-free (M NSD) test ===")
E = sp.simplify((Phi/(rho/(2*m))).subs(B, B_eta1))
print(f"   E = Phi/Phi_GR = {E}")
# M NSD (ghost-free, correct sign): A<=0, C<=0, A*C - B^2 >= 0. With B=-C: A*C - C^2 >=0.
print("   ghost-free <=> M negative-semidefinite: A<=0, C<=0, A*C - B^2 >= 0.")
print(f"   with B=-C: A*C - C^2 >= 0  =>  C(A-C) >= 0.  Since C<=0, need (A-C) <= 0 => A <= C <= 0.")
# enhancement E>1 ?
print(f"   E = 2m/(2m + A - C).  E>1  <=>  A - C < 0  <=>  A < C.")
print("   NSD needs A <= C (<=0); enhancement needs A < C. COMPATIBLE at A < C <= 0 !!")
print("   PHYSICAL WINDOW: E=2m/(2m+A-C) is finite & >1 only for A-C in (-2m, 0). At A-C -> -2m the")
print("   enhancement diverges (E->inf = strong-coupling pole); below it E flips sign (unphysical).")
print("   So MOND enhancement lives in a FINITE healthy window bounded by a strong-coupling pole. Points")
print("   INSIDE the window (m=1 => window A-C in (-2,0)), all NSD (ghost-free) with clean E>1:")
for Av,Cv in [(-1,sp.Rational(-1,2)),(-1,sp.Rational(-1,4)),(sp.Rational(-3,2),-1)]:
    Bv = -Cv
    Mtest = sp.Matrix([[Av,Bv],[Bv,Cv]])
    eigs = sorted(complex(e).real for e in Mtest.eigenvals())
    Eval = sp.nsimplify(E.subs([(A,Av),(C,Cv)]).subs(m,1))
    nsd = all(e <= 1e-9 for e in eigs)
    print(f"     A={Av},C={Cv},B={Bv}: eig(M)~{[round(e,3) for e in eigs]} NSD={nsd}  E(m=1)={Eval}  (A-C={sp.nsimplify(Av-Cv)} in (-2,0))")

print("\n=== does a HEALTHY nonlocal operator actually realize A<C<=0 with B=-C? ===")
print("   A<C<=0, B=-C>0: M = [[A,-C],[-C,C]] with A<C<=0. Is this a sum of NSD rank-1 pieces from")
print("   ghost-free modes? M NSD <=> yes (any NSD matrix = -sum of rank-1). So NO GHOST OBSTRUCTION.")
print("   BUT the decisive subtlety: can a single-metric DIFF-INVARIANT nonlocal operator produce this")
print("   specific M(k) with the RIGHT k-dependence for MOND (enhancement growing at low k = low accel)?")
print("   The 2x2 says the SPECTRUM allows it. The open question descends to: (i) is the required M(k)")
print("   generated by a CAUSAL nonlocal action (retarded, not acausal)?  (ii) the omega^2=c^2k^2/2 extra")
print("   mode's residue sign on THIS M (the un-localized F+ ghost-residue).  Those are dynamical, not")
print("   spectral-static -- the static 2x2 cannot settle them.")

print("\n=== VERDICT ===")
print("MAJOR: once nonlocality REMOVES the diff-invariance (1,-2) lock, the static 2x2 obstruction that")
print("closed the LOCAL case DISSOLVES: {eta=1 + enhancement + ghost-free (M NSD)} IS mutually")
print("compatible (A<C<=0, B=-C -- concrete healthy enhancing points exist). So slip-lock does NOT")
print("extend to the genuinely-nonlocal case -- the single-metric door is NOT closed by the spectrum.")
print("The remaining make-or-break is DYNAMICAL not spectral: (1) a CAUSAL (retarded) nonlocal action")
print("realizing this M(k); (2) the residue/ghost sign of the propagating omega^2=c^2k^2/2 mode.")
print("=> the converged single-metric door stays OPEN, now with the spectral obstruction PROVEN absent.")
import json
print("CERTIFICATE_JSON:", json.dumps({"gate":"converged-nonlocal-psi","status":"OPEN-SPECTRAL-CLEAR",
 "certificate":("Nonlocality removes slip-lock's diff-invariance (1,-2) lock => the static 2x2 response "
   "is unconstrained in direction. Then {eta=1 (B=-C) + enhancement (A<C) + ghost-free (M NSD: A<=C<=0)} "
   "is MUTUALLY COMPATIBLE -- concrete healthy enhancing points exist (e.g. A=-3,C=-1,B=1: NSD, E>1). "
   "So the spectral/ghost obstruction that closed the LOCAL frame-free case does NOT extend to the "
   "genuinely-nonlocal case: single-metric NOT closed by the spectrum. Remaining make-or-break is "
   "DYNAMICAL: (i) a CAUSAL retarded nonlocal action realizing this M(k) with MOND k-dependence; (ii) "
   "the residue sign of the omega^2=c^2k^2/2 propagating mode. Door OPEN, spectral obstruction cleared."),
 "numeric_values":{"eta1":"B=-C","enhance":"A<C","ghostfree":"A<=C<=0","window":"A-C in (-2m,0)","pole_at":"A-C=-2m (strong coupling)","compatible":True}}))
