#!/usr/bin/env python3
r"""Stratified Hamiltonian and pole audit of the localized DW auxiliary action.

The localized scalar density in a homogeneous, fixed-lapse reduction is

  L = Xdot*xidot/N + lambda*N*(1-phidot**2/N**2)
      + (M+f(Z))*phidot*nudot/N - (a0**2/kappa)*M*N,
  Z = -4*Xdot**2/(N**2*a0**2).

This file makes three deliberately separate statements.

1. On the generic Q=M+f(Z) != 0 stratum, exact Hessian minors and an exact
   Poisson matrix give the complete Dirac chain of this HOMOGENEOUS,
   FROZEN-METRIC auxiliary reduction. No symbolic rank heuristic is used.
2. Q=0 is a different Legendre stratum. It is inspected directly at the
   Lagrangian Hessian, never by dividing by Q. Its restarted full Dirac chain
   (with spatial dependence and the metric retained) remains OPEN.
3. Independently, the fixed-background (X,xi) quadratic operator is audited at
   k!=0 and k=0. The unrestricted local representative contains two scalar
   light-cone channels with opposite residues. Retarded history conditions
   select solutions; they are not constraints generated by this Hamiltonian.

Exit 0 means the audit calculations agree with their analytic controls. It
does NOT mean the candidate theory passes. The explicit status is:

  unrestricted local representative : DEAD (extra scalar ghost channel),
  retarded fixed-history reading     : OPEN_NONCANONICAL,
  Q=0 restarted Dirac chain          : OPEN.
"""
import itertools
import sys

import sympy as sp


STATUS_UNRESTRICTED_LOCAL = "DEAD"
STATUS_RETARDED_HISTORY = "OPEN_NONCANONICAL"
STATUS_Q0_DIRAC = "OPEN"


def exact_rank_by_minors(matrix):
    """Return generic symbolic rank and a nonzero maximal-minor witness."""
    rows, cols = matrix.shape
    for size in range(min(rows, cols), 0, -1):
        for row_ids in itertools.combinations(range(rows), size):
            for col_ids in itertools.combinations(range(cols), size):
                minor = sp.factor(matrix.extract(row_ids, col_ids).det())
                if minor != 0:
                    return size, minor, row_ids, col_ids
    return 0, sp.S.Zero, (), ()


def homogeneous_hessian_data():
    """Derive Hessian minors on Q!=0, Q=0/lambda!=0, and Q=lambda=0."""
    N, a0, kappa = sp.symbols("N a0 kappa", nonzero=True)
    vX, vxi, vphi, vnu = sp.symbols("vX vxi vphi vnu")
    lam, M = sp.symbols("lambda M")
    f = sp.Function("f")
    Q = sp.symbols("Q")
    Z = -4 * vX**2 / (N**2 * a0**2)
    Q_expr = M + f(Z)
    L = (
        vX * vxi / N
        + lam * N * (1 - vphi**2 / N**2)
        + Q_expr * vphi * vnu / N
        - a0**2 * M * N / kappa
    )
    velocities = (vX, vxi, vphi, vnu)
    hessian = sp.hessian(L, velocities)

    generic_rank, generic_witness, generic_rows, generic_cols = exact_rank_by_minors(hessian)
    generic_minor = sp.factor(generic_witness.subs(M, Q - f(Z)))

    # Q=0 is taken in Lagrangian variables, before any Legendre inversion.
    hessian_Q0 = hessian.subs(M, -f(Z)).applyfunc(sp.factor)
    rank_Q0_lam, witness_Q0_lam, rows_Q0_lam, cols_Q0_lam = exact_rank_by_minors(hessian_Q0)
    hessian_Q0_lam0 = hessian_Q0.subs(lam, 0).applyfunc(sp.factor)
    rank_Q0_lam0, witness_Q0_lam0, rows_Q0_lam0, cols_Q0_lam0 = exact_rank_by_minors(hessian_Q0_lam0)

    # Stable canonical witnesses, independently selected from the matrices.
    Q0_lambda_minor = sp.factor(hessian_Q0.extract((0, 1, 2), (0, 1, 2)).det())
    Q0_lambda0_minor = sp.factor(hessian_Q0_lam0.extract((0, 1), (0, 1)).det())
    return {
        "hessian": hessian,
        "generic_minor": generic_minor,
        "generic_rank": generic_rank,
        "generic_witness_indices": (generic_rows, generic_cols),
        "rank_Q0_lambda_nonzero": rank_Q0_lam,
        "Q0_lambda_minor": Q0_lambda_minor,
        "Q0_lambda_witness": witness_Q0_lam,
        "Q0_lambda_witness_indices": (rows_Q0_lam, cols_Q0_lam),
        "rank_Q0_lambda_zero": rank_Q0_lam0,
        "Q0_lambda0_minor": Q0_lambda0_minor,
        "Q0_lambda0_witness": witness_Q0_lam0,
        "Q0_lambda0_witness_indices": (rows_Q0_lam0, cols_Q0_lam0),
    }


def generic_constraint_data():
    """Derive the Q!=0 Hamiltonian, secondary constraints, and PB matrix."""
    N, a0, c = sp.symbols("N a0 c", nonzero=True)
    Q = sp.symbols("Q")
    X, xi, phi, lam, M, nu = sp.symbols("X xi phi lambda M nu")
    pX, pxi, pphi, plam, pM, pnu = sp.symbols("pX pxi pphi plambda pM pnu")
    f = sp.Function("f")
    Zp = -4 * pxi**2 / a0**2
    Q_expr = M + f(Zp)
    coordinates = (X, xi, phi, lam, M, nu)
    momenta = (pX, pxi, pphi, plam, pM, pnu)

    def PB(left, right):
        return sp.factor(
            sum(
                sp.diff(left, q) * sp.diff(right, p)
                - sp.diff(left, p) * sp.diff(right, q)
                for q, p in zip(coordinates, momenta)
            )
        )

    Hc = N * (
        pX * pxi
        + pphi * pnu / Q_expr
        + lam * (pnu**2 / Q_expr**2 - 1)
        + c * M
    )
    primary = (plam, pM)

    # Generated by preservation. Multiplication by Q is legal only in this
    # explicitly named Q!=0 chart.
    secondary_lambda = sp.factor(-(Q_expr**2 / N) * PB(primary[0], Hc))
    secondary_M = sp.factor((Q_expr**3 / N) * PB(primary[1], Hc))
    constraints = primary + (secondary_lambda, secondary_M)
    pb_matrix_expr = sp.Matrix([[PB(left, right) for right in constraints] for left in constraints])

    # Replace the composite Q only after taking canonical brackets.
    pb_matrix = pb_matrix_expr.subs(M, Q - f(Zp)).applyfunc(sp.factor)
    constraints_Q = tuple(sp.factor(item.subs(M, Q - f(Zp))) for item in constraints)
    det_pb = sp.factor(pb_matrix.det())
    det_pb_on_shell = sp.factor(
        sp.rem(sp.Poly(det_pb, pnu), sp.Poly(pnu**2 - Q**2, pnu)).as_expr()
    )
    rank_generic, rank_witness, rank_rows, rank_cols = exact_rank_by_minors(pb_matrix)
    formal_Q0 = pb_matrix.subs(Q, 0).applyfunc(sp.factor)
    formal_rank_Q0, formal_witness_Q0, _, _ = exact_rank_by_minors(formal_Q0)

    return {
        "Hc": Hc,
        "primary": primary,
        "secondary": (secondary_lambda, secondary_M),
        "constraints_Q": constraints_Q,
        "pb_matrix": pb_matrix,
        "det_pb": det_pb,
        "det_pb_on_shell": det_pb_on_shell,
        "rank_generic": rank_generic,
        "rank_witness": rank_witness,
        "rank_witness_indices": (rank_rows, rank_cols),
        # Warning only: this is NOT the Q=0 Dirac rank because the Hamiltonian
        # chart was obtained by dividing by Q.
        "formal_off_shell_rank_Q0": formal_rank_Q0,
        "formal_off_shell_witness_Q0": formal_witness_Q0,
        "generic_chart_valid_at_Q0": False,
        "preservation_Hc": (PB(secondary_lambda, Hc), PB(secondary_M, Hc)),
    }


def localization_quadratic_data():
    """Derive finite-k poles, residue signature, and retarded-branch energy."""
    kappa = sp.symbols("kappa", positive=True)
    f1 = sp.symbols("f1", positive=True)
    omega, k = sp.symbols("omega k", real=True)

    # -W0*f1*Z with W0=-a0^2/kappa gives
    # -(4 f1/kappa)(Xdot^2-|grad X|^2) = (a/2)(...), hence:
    a = -8 * f1 / kappa
    kinetic = sp.Matrix([[a, 1], [1, 0]])
    operator = (omega**2 - k**2) * kinetic
    finite_k_operator_det = sp.factor(operator.det())
    k0_operator_det = sp.factor(operator.subs(k, 0).det())
    residue_signature = "opposite" if sp.factor(kinetic.det()) == -1 else "undetermined"
    retarded_energy = sp.factor(-a / 2)
    return {
        "a": a,
        "kinetic": kinetic,
        "det_kinetic": sp.factor(kinetic.det()),
        "finite_k_operator_det": finite_k_operator_det,
        "k0_operator_det": k0_operator_det,
        "residue_signature": residue_signature,
        "a_at_f1_half": sp.factor(a.subs(f1, sp.Rational(1, 2))),
        "retarded_energy": retarded_energy,
        "retarded_energy_at_f1_half": sp.factor(retarded_energy.subs(f1, sp.Rational(1, 2))),
    }


def clock_transport_symbol_data():
    """Linear Minkowski symbol for the two zero-speed clock/transport modes."""
    omega, k = sp.symbols("omega k", real=True)
    c, Q0, lam0 = sp.symbols("c Q0 lambda0", real=True)
    shell = omega**2 - k**2
    operator = sp.Matrix(
        [
            [2 * sp.I * omega, 0, 0, 0],
            [-sp.I * c * omega, 0, 0, -sp.I * omega],
            [Q0 * shell, 0, sp.I * omega, 0],
            [-2 * lam0 * shell, -2 * sp.I * omega, sp.I * c * omega, Q0 * shell],
        ]
    )
    return {"operator": operator, "det_operator": sp.factor(operator.det())}


def _history_witnesses():
    """Exact past-source witnesses at k=1 and k=0, evaluated at t0=0."""
    s = sp.symbols("s", real=True)
    source = (s + 4) ** 2 * (s + 3) ** 2  # understood as supported on [-4,-3]
    X_k1 = sp.integrate(sp.sin(-s) * source, (s, -4, -3))
    Xdot_k1 = sp.integrate(sp.cos(-s) * source, (s, -4, -3))
    X_k0 = sp.integrate(-s * source, (s, -4, -3))
    Xdot_k0 = sp.integrate(source, (s, -4, -3))
    return tuple(sp.simplify(value) for value in (X_k1, Xdot_k1, X_k0, Xdot_k0))


def main():
    checks = []

    def check(label, condition, detail=""):
        ok = bool(condition)
        checks.append(ok)
        print(f"  [{'PASS' if ok else 'FAIL'}] {label}" + (f"   ({detail})" if detail else ""))

    def header(label):
        print("\n" + "=" * 96)
        print(label)
        print("=" * 96)

    header("PART 1 -- EXACT HESSIAN MINORS AND LEGENDRE STRATA (homogeneous, metric frozen)")
    hdata = homogeneous_hessian_data()
    print("  generic maximal minor =", hdata["generic_minor"])
    print("  Q=0, lambda!=0 rank/witness =", hdata["rank_Q0_lambda_nonzero"], hdata["Q0_lambda_minor"])
    print("  Q=0, lambda=0  rank/witness =", hdata["rank_Q0_lambda_zero"], hdata["Q0_lambda0_minor"])
    # Reuse the symbols (including their assumptions) returned by the
    # derivation.  Same-printed-name symbols with different assumptions are
    # intentionally distinct objects in SymPy.
    N = next(symbol for symbol in hdata["generic_minor"].free_symbols if symbol.name == "N")
    Q = next(symbol for symbol in hdata["generic_minor"].free_symbols if symbol.name == "Q")
    lam = next(symbol for symbol in hdata["Q0_lambda_minor"].free_symbols if symbol.name == "lambda")
    check("Q!=0 rank is obtained from a nonzero 4x4 minor", hdata["generic_rank"] == 4)
    check("generic Hessian determinant is Q^2/N^4", sp.factor(hdata["generic_minor"] - Q**2 / N**4) == 0)
    check("Q=0, lambda!=0 has rank 3 from exact minors", hdata["rank_Q0_lambda_nonzero"] == 3)
    check("Q=0, lambda=0 has rank 2 from exact minors", hdata["rank_Q0_lambda_zero"] == 2)
    check(
        "Q=0 witnesses are 2*lambda/N^3 and -1/N^2",
        sp.factor(hdata["Q0_lambda_minor"] - 2 * lam / N**3) == 0
        and sp.factor(hdata["Q0_lambda0_minor"] + 1 / N**2) == 0,
    )

    header("PART 2 -- GENERIC Q!=0 DIRAC CHAIN AND ACTUAL POISSON MATRIX")
    cdata = generic_constraint_data()
    print("  primary constraints =", cdata["primary"])
    print("  secondary constraints (before Q abbreviation) =", cdata["secondary"])
    print("  denominator-free constraints (Q abbreviation) =", cdata["constraints_Q"])
    print("  Poisson matrix =")
    sp.pprint(cdata["pb_matrix"])
    print("  det(PB) =", cdata["det_pb"])
    print("  det(PB) reduced by pnu^2-Q^2 =", cdata["det_pb_on_shell"])
    print(
        "  formal off-shell rank after setting Q=0 in the INVALID generic chart =",
        cdata["formal_off_shell_rank_Q0"],
    )
    check("two primaries generate two independent secondaries", len(cdata["secondary"]) == 2)
    check(
        "secondary preservation by Hc adds no tertiary before multiplier equations",
        all(item == 0 for item in cdata["preservation_Hc"]),
    )
    check("PB matrix is antisymmetric", cdata["pb_matrix"] + cdata["pb_matrix"].T == sp.zeros(4))
    check("generic PB rank is derived as 4", cdata["rank_generic"] == 4)
    check(
        "on-shell PB determinant is 16 Q^6, not a supplied rank",
        sp.factor(cdata["det_pb_on_shell"] - 16 * sp.Symbol("Q") ** 6) == 0,
    )
    aux_dof = sp.Rational(12 - cdata["rank_generic"], 2)
    check(
        "generic frozen-metric homogeneous auxiliary count is 4 DOF",
        aux_dof == 4,
        f"(12 phase dimensions - 4 second-class)/2 = {aux_dof}",
    )
    check("generic Q!=0 chart is explicitly forbidden at Q=0", not cdata["generic_chart_valid_at_Q0"])

    header("PART 3 -- k!=0 POLES, k=0 MODES, RESIDUES, AND RETARDED ENERGY")
    qdata = localization_quadratic_data()
    omega, k = sp.symbols("omega k", real=True)
    kappa = sp.symbols("kappa", positive=True)
    print("  localization kinetic matrix =", qdata["kinetic"].tolist())
    print("  det K =", qdata["det_kinetic"])
    print("  finite-k det O =", qdata["finite_k_operator_det"])
    print("  k=0 det O =", qdata["k0_operator_det"])
    print(
        "  f'(0)=1/2: a =",
        qdata["a_at_f1_half"],
        "; retarded-branch energy coefficient -a/2 =",
        qdata["retarded_energy_at_f1_half"],
    )
    check("det K=-1 gives opposite-sign kinetic residues", qdata["residue_signature"] == "opposite")
    check(
        "k!=0 has two scalar light-cone channels",
        sp.factor(qdata["finite_k_operator_det"] + (omega**2 - k**2) ** 2) == 0,
    )
    check(
        "k=0 is a separate omega^4 zero-mode sector",
        sp.factor(qdata["k0_operator_det"] + omega**4) == 0,
    )
    check(
        "correct action sign gives a=-4/kappa at f'(0)=1/2",
        sp.factor(qdata["a_at_f1_half"] + 4 / kappa) == 0,
    )
    check(
        "equal-retarded particular branch has POSITIVE +2/kappa coefficient",
        sp.factor(qdata["retarded_energy_at_f1_half"] - 2 / kappa) == 0,
    )

    ctdata = clock_transport_symbol_data()
    print("  clock+transport det O =", ctdata["det_operator"])
    check(
        "clock+transport determinant is -4 omega^4 (zero-speed modes, still canonical DOF)",
        sp.factor(ctdata["det_operator"] + 4 * omega**4) == 0,
    )

    history = _history_witnesses()
    print("  retarded past-source data at k=1 and k=0 =", history)
    check("finite-k retarded data depend on the past source", all(value != 0 for value in history[:2]))
    check("k=0 retarded data also depend on the past source", all(value != 0 for value in history[2:]))

    header("VERDICT -- THREE DISTINCT OBJECTS, THREE DISTINCT STATUSES")
    print("  unrestricted local representative :", STATUS_UNRESTRICTED_LOCAL)
    print("    Reason: the nondegenerate (X,xi) block has two finite-k scalar channels with opposite residues.")
    print("  retarded fixed-history reading     :", STATUS_RETARDED_HISTORY)
    print("    Reason: history conditions remove free auxiliary data only as a solution prescription; this")
    print("            script derives no Dirac constraint implementing that prescription.")
    print("  Q=0 MOND Legendre stratum          :", STATUS_Q0_DIRAC)
    print("    Reason: rank bifurcates (3 for lambda!=0, 2 for lambda=0); the full spatial+metric Dirac")
    print("            chain must be restarted there and is not inferred by a Q->0 limit.")
    print("  Full ADM N_grav count              : NOT COMPUTED HERE")
    print("    The exact generic result is only the homogeneous frozen-metric auxiliary reduction.")
    print(f"  computational checks passed: {sum(checks)}/{len(checks)}")

    sys.exit(0 if all(checks) else 1)


if __name__ == "__main__":
    main()
