#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""k_cross-scale_bridge -- CANDIDATE 1 of the cross-scale angle:
    "the solar-circle boost constant B(R) -- one predicted number, four independent observables,
     fifteen decades of mass".

THE CLAIM.  With B(e) = nu(e)[1 + L(e)/3], nu(e) e = g_ext/a_0, g_ext = V_c^2/R and a_0 = (c/2) sqrt(G rho_DE),
the SAME number B is measured at the same R by four unrelated observables:
     gamma_v^2 (wide binaries, 1e-4 pc, 1 Msun)
   = M_dyn/M_phot (open clusters, 1 pc, 1e3 Msun)
   = alpha_vir (molecular clouds, 10 pc, 1e5 Msun)
   = K_z/K_z,baryons (the disc, 1 kpc, 1e10 Msun),
and B rises with R as nu(V_c^2/(R a_0)) -- 1.09 at 4 kpc to 1.79 at 20 kpc.

THIS SCRIPT DECIDES THREE THINGS, in this order, and the first one is fatal on its own:
  A. IS THE UNIVERSALITY CLAIM EVEN TRUE IN THE THEORY?  Before any data: are the four observables the same
     function of the same argument?  Computed here, they are not.  [checks that CAN fail]
  B. WHAT DO THE RUNGS ACTUALLY MEASURE?  Four rungs are on disk, each with its own committed script; the
     fifth (wide binaries) is frozen for Gaia DR4.  They are assembled, with their own Upsilon levers.
  C. DOES THE ASSEMBLY MEET THE FIVE KEPLER-GRADE CRITERIA?

RUNG SOURCES (numbers read from the committed .out files named, not re-derived here):
  globular clusters   hunt_2026/k02_gc_efe_saturation_law.out   (157 clusters, Baumgardt & Hilker)
  molecular clouds    hunt_2026/k03_gmc_efe_saturation_law.out  (8107 clouds, Miville-Deschenes+2017)
  open clusters       hunt_2026/k_cross-scale_opencluster.out   (this session, Hunt & Reffert 2024)
  vertical force      hunt_2026/h34_h35_h38_milky_way.out       (Bovy & Rix 2013 Table 3, 43 MAPs)
  wide binaries       prep_2026/gaia_dr4_prep/  -- FROZEN, NOT MEASURED, ~Dec 2026 (never modified here)

Both footings; Newtonian alternative beside the framework; mutation control on a_0.
Run:  python3 k_cross-scale_bridge.py       (exit 0 = all checks pass)
"""
import os, sys, math
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from hunt_lib import A0, G, Msun, kpc, c_light, nu, nu_s, Check, P, info
from hunt_efe_lib import dlnnu_dlny

R0_KPC = 8.122
VC_KMS = 233.0
X_EXT_REG = 1.89929
ck = Check()


def L_of(y): return float(dlnnu_dlny(np.array([float(y)]))[0])
def B_of_e(e): return nu_s(e)*(1.0 + L_of(e)/3.0)
def e_from_true(x):
    lo, hi = 1e-8, 1e8
    for _ in range(200):
        m = math.sqrt(lo*hi)
        if nu_s(m)*m < x: lo = m
        else: hi = m
    return math.sqrt(lo*hi)
def field_at_R(R_kpc, a0): return (VC_KMS*1e3)**2/(R_kpc*kpc)/a0


P("="*118)
P("k_cross-scale_bridge -- CANDIDATE 1: is B(R) = nu(e)[1+L(e)/3] one number shared by four system classes?")
P("="*118)

# ============================================================ A. the structural test, before any data
P("")
P("-"*118); P("A.  DO THE FOUR OBSERVABLES MEASURE THE SAME FUNCTION?  This is decided by the theory, not the data."); P("-"*118)
e_reg = e_from_true(X_EXT_REG)
info(f"at the registered solar-circle field x_ext = {X_EXT_REG} a_0:  e = {e_reg:.5f}, nu(e) = {nu_s(e_reg):.5f}, "
     f"L(e) = {L_of(e_reg):+.5f}")
P("")
P(f"  {'observable':<52}{'what QUMOND actually predicts':<34}{'value':>10}")
P(f"  {'-'*96}")
B_sat = B_of_e(e_reg)
nu_reg = nu_s(e_reg)
rows_th = [
    ("wide binary / open cluster / cloud (g_int -> 0)", "B = nu(e)[1 + L(e)/3]", B_sat),
    ("the same, if one wrongly drops the [1+L/3] trace", "nu(e)", nu_reg),
    ("wide binary, FULL two-body solve (frozen band, canonical)", "gamma_v^2, registered", 0.5*(1.1614**2 + 1.1814**2)),
    ("wide binary, FULL two-body solve (frozen band, alt)", "gamma_v^2, registered", 0.5*(1.1917**2 + 1.2267**2)),
]
for lab, what, v in rows_th:
    P(f"  {lab:<52}{what:<34}{v:10.4f}")
P("")
info("AND THE FOURTH RUNG IS NOT THE SAME OBJECT AT ALL.  The vertical force K_z is generated by the Milky Way")
info("disc ITSELF.  The disc is not a small system embedded in someone else's field -- it IS the field.  Its")
info("boost is therefore nu evaluated at its OWN total Newtonian field, nu(|g_N|/a_0), with no [1+L/3] factor")
info("and at a DIFFERENT argument (the total field, not the in-plane circular one).  From the committed h34")
info("run at R_0 that number is nu = 1.444, against B = "
     f"{B_sat:.4f}: they differ by {100*(1.444/B_sat - 1):.0f}%.")
ck("the [1+L/3] trace factor is NOT negligible -- dropping it changes the predicted boost by more than 5% "
   "[CAN FAIL]", abs(nu_reg/B_sat - 1) > 0.05,
   f"nu(e) = {nu_reg:.4f} vs B = {B_sat:.4f}, a factor {nu_reg/B_sat:.4f} ({100*(nu_reg/B_sat-1):.1f}%)")
ck("THE UNIVERSALITY CLAIM FAILS IN THE THEORY: the four observables are NOT one number.  The vertical-force "
   "rung predicts nu(y_local) = 1.444 while the embedded-system rungs predict B = 1.341, and the full "
   "two-body wide-binary solve predicts a third value  [CAN FAIL -- this is the candidate's own claim]",
   max(abs(1.444/B_sat - 1), abs(rows_th[2][2]/B_sat - 1)) > 0.02,
   f"B = {B_sat:.4f}, two-body gamma_v^2 = {rows_th[2][2]:.4f} ({100*(rows_th[2][2]/B_sat-1):+.1f}%), "
   f"vertical force nu = 1.444 ({100*(1.444/B_sat-1):+.1f}%) -- a spread of "
   f"{100*(1.444/B_sat-1):.0f}% before a single measurement")
info("So 'the same B measured four ways' is not a law the theory states.  The theory states THREE different")
info("numbers spanning 7.7%, and the law as proposed would be falsified by the theory's own arithmetic.")
info("What the theory DOES state is weaker and still worth writing down: all FOUR boosts are set by the")
info("EXTERNAL/local field and none of them by the system's own acceleration.  That is section B's test.")

# ============================================================ the B(R) curve
P("")
P("-"*118); P("A2.  THE RADIAL RUN OF B, which is the candidate's distinctive content."); P("-"*118)
P(f"  {'R [kpc]':>9}{'g_ext/a_0 (can)':>17}{'B (can)':>10}{'g_ext/a_0 (alt)':>17}{'B (alt)':>10}{'nu(e) (can)':>13}")
Bcurve = {}
for Rk in (4, 6, 8, 8.122, 10, 12, 15, 20):
    xa = field_at_R(Rk, A0["canonical"]); xb = field_at_R(Rk, A0["alt"])
    ea, eb = e_from_true(xa), e_from_true(xb)
    Bcurve[Rk] = (B_of_e(ea), B_of_e(eb))
    P(f"  {Rk:9.3f}{xa:17.4f}{B_of_e(ea):10.4f}{xb:17.4f}{B_of_e(eb):10.4f}{nu_s(ea):13.4f}")
ck("the radial run reproduces the candidate's own quoted range 1.09 (4 kpc) to 1.79 (20 kpc) on the canonical "
   "footing  [CAN FAIL]", abs(Bcurve[4][0] - 1.09) < 0.03 and abs(Bcurve[20][0] - 1.79) < 0.05,
   f"B(4 kpc) = {Bcurve[4][0]:.4f}, B(20 kpc) = {Bcurve[20][0]:.4f}")
info("THE PROBLEM WITH THAT LEVER, stated before it is tested: every class that can be measured with Gaia-class")
info("astrometry lives within ~1 kpc of the Sun.  Molecular clouds reach 4-12 kpc but only in projection and")
info("with a metallicity/X_CO gradient running the OTHER way (k03); globular clusters reach 150 kpc but are")
info("internally DENSER than the local field for R_GC < 15 kpc, so they leave the solar-circle end untested.")

# ============================================================ B. the rungs
P("")
P("-"*118); P("B.  THE FIVE RUNGS, ASSEMBLED.  Numbers read from the committed .out files named in the header."); P("-"*118)

# --- vertical force: recompute the measured boost from the committed h34 numbers
KZ_BARYON = 60.1        # h34: K_z,1.1(R0)/2piG with nu = 1 (McMillan baryons), Msun/pc^2
KZ_OBS_BR, KZ_ERR_BR = 67.5, 1.7      # Bovy & Rix 2013 refit + their formal error
KZ_OBS_MC, KZ_ERR_MC = 73.9, 6.0      # McMillan 2017's independent value for the same quantity
KZ_NU_PRED = 1.444                    # h34's nu(|g_N|/a_0) at R_0, canonical
b_kz_br = KZ_OBS_BR/KZ_BARYON; e_kz_br = KZ_ERR_BR/KZ_BARYON
b_kz_mc = KZ_OBS_MC/KZ_BARYON; e_kz_mc = KZ_ERR_MC/KZ_BARYON

RUNGS = [
    dict(name="wide binaries (1e-4 pc, 1 Msun)", scale=1e-4, meas=None, err=None,
         pred=0.5*(1.1614**2 + 1.1814**2), predalt=0.5*(1.1917**2 + 1.2267**2),
         ups="d log(gamma_v)/d log(Upsilon_ML) = -0.500, so d log(gamma_v - 1)/d log Upsilon ~ -3.6",
         src="FROZEN, Gaia DR4 ~Dec 2026 -- NOT MEASURED", kind="B"),
    dict(name="open clusters (1 pc, 1e3 Msun)", scale=1.0, meas=0.589, err=0.139,
         pred=B_sat, predalt=B_of_e(e_from_true(field_at_R(R0_KPC, A0["alt"]))),
         ups="d log(M_dyn/M_phot)/d log(Upsilon) = -1.000 (measured by re-running)",
         src="k_cross-scale_opencluster.out, 91 clusters", kind="B"),
    dict(name="molecular clouds (10 pc, 1e5 Msun)", scale=10.0, meas=None, err=None,
         pred=B_sat, predalt=B_of_e(e_from_true(field_at_R(R0_KPC, A0["alt"]))),
         ups="d log(alpha_vir)/d log(Upsilon_star) = 0.000 EXACTLY; replaced by d/d log X_CO = -1.000",
         src="k03_gmc_efe_saturation_law.out -- CONFIRMS the EFE exists (isolated MOND out at 5.7 sigma), "
             "but the predicted boost is 0.07 dex, under the scatter: NO measurement of B", kind="B"),
    dict(name="vertical force (1 kpc, 1e10 Msun)", scale=1000.0, meas=b_kz_br, err=e_kz_br,
         pred=KZ_NU_PRED, predalt=1.505,
         ups="d log(K_z/K_z,bar)/d log(Upsilon) = -1.000 (Sigma_star proportional to Upsilon)",
         src="h34_h35_h38_milky_way.out, Bovy & Rix 2013, 43 MAPs", kind="nu"),
    dict(name="globular clusters (10 pc, 1e5 Msun, LOW e)", scale=10.0, meas=None, err=None,
         pred=float("nan"), predalt=float("nan"),
         ups="d log(M/L_V)/d log(Upsilon_V) = -1.000 for the amplitude; 0.000 for the slope",
         src="k02_gc_efe_saturation_law.out -- the SLOPE of log(M/L_V) on log B_pred is -0.036 +- 0.109 "
             "where the law needs +1: EXCLUDED at 9.5 sigma over 0.98 dex of predicted signal", kind="slope"),
]
P(f"  {'rung':<40}{'measured':>18}{'predicted (can/alt)':>24}{'sigma from prediction':>23}")
P(f"  {'-'*105}")
sig_list = []
for r in RUNGS:
    if r["meas"] is None:
        P(f"  {r['name']:<40}{'--':>18}"
          f"{('%.3f / %.3f' % (r['pred'], r['predalt'])) if np.isfinite(r['pred']) else 'slope +1':>24}{'--':>23}")
    else:
        s = abs(r["meas"] - r["pred"])/r["err"]
        sig_list.append((r["name"], s))
        P(f"  {r['name']:<40}{('%.3f +- %.3f' % (r['meas'], r['err'])):>18}"
          f"{('%.3f / %.3f' % (r['pred'], r['predalt'])):>24}{s:23.1f}")
P("")
for r in RUNGS:
    info(f"{r['name']}:")
    info(f"    source : {r['src']}")
    info(f"    Upsilon: {r['ups']}")

# the Newtonian alternative, computed beside
P("")
P(f"  {'rung':<40}{'sigma from FRAMEWORK':>22}{'sigma from NEWTON (boost = 1)':>32}")
P(f"  {'-'*94}")
for r in RUNGS:
    if r["meas"] is None: continue
    P(f"  {r['name']:<40}{abs(r['meas']-r['pred'])/r['err']:22.1f}{abs(r['meas']-1.0)/r['err']:32.1f}")

ck("no rung on disk is within 3 sigma of the framework's own prediction for that rung  [CAN FAIL -- and it "
   "FAILS AGAINST THE FRAMEWORK, which is the result]",
   all(s > 3 for _, s in sig_list), "; ".join(f"{n}: {s:.1f} sigma" for n, s in sig_list))
ck("the vertical-force rung's measured boost is BELOW its own prediction, i.e. the disc is boosted LESS than "
   "the kernel requires  [CAN FAIL]", b_kz_br < KZ_NU_PRED,
   f"measured {b_kz_br:.3f} +- {e_kz_br:.3f} (Bovy & Rix) or {b_kz_mc:.3f} +- {e_kz_mc:.3f} (McMillan) "
   f"vs predicted {KZ_NU_PRED:.3f}")
info("BOTH WAYS, and it matters: on the McMillan normalisation the vertical-force rung is "
     f"{abs(b_kz_mc-KZ_NU_PRED)/e_kz_mc:.1f} sigma from")
info(f"the framework and {abs(b_kz_mc-1.0)/e_kz_mc:.1f} sigma from Newton -- that rung's 10% inter-measurement "
     "disagreement is larger")
info("than the whole signal, so it is not decisive either.  Only the Bovy & Rix normalisation makes it look sharp.")

# ============================================================ the equality test
P("")
P("-"*118); P("B2.  THE EQUALITY TEST the candidate actually proposes: is ONE B consistent with the rungs?"); P("-"*118)
meas = [(r["name"], r["meas"], r["err"]) for r in RUNGS if r["meas"] is not None]
w = np.array([1.0/m[2]**2 for m in meas]); v = np.array([m[1] for m in meas])
Bhat = float(np.sum(w*v)/np.sum(w)); eBhat = float(1.0/math.sqrt(np.sum(w)))
chi2 = float(np.sum(w*(v - Bhat)**2)); dof = len(meas) - 1
P(f"  best single B across the {len(meas)} MEASURED rungs: {Bhat:.3f} +- {eBhat:.3f}   "
  f"chi2 = {chi2:.1f} / {dof} dof  (p = {math.exp(-chi2/2) if dof == 1 else float('nan'):.3g} for 1 dof)")
for n, mv, me in meas:
    P(f"     {n:<44}{mv:8.3f} +- {me:.3f}   ({(mv-Bhat)/me:+.1f} sigma from the common value)")
ck("the two measured rungs are NOT consistent with a single shared B, so the cross-class equality is refuted "
   "by the data as well as by the theory  [CAN FAIL]", chi2/max(dof, 1) > 4.0,
   f"chi2/dof = {chi2/max(dof,1):.1f} on {len(meas)} rungs")
info("AND NOTE WHAT THAT CHI-SQUARED IS NOT.  With only two measured rungs (open clusters and the vertical")
info("force) a 'cross-class law spanning fifteen decades of mass' has TWO points, both inside 1 kpc of the Sun,")
info(f"and their separation ({abs(meas[0][1]-meas[1][1]):.3f}) is dominated by systematics neither script can close.")
P("")
info("SO THE CHI-SQUARED MUST BE REDONE WITH SYSTEMATICS, and doing so REVERSES it -- reported because it goes")
info("against the kill, not for it.  The open-cluster rung's B swings 0.59 -> 1.06 on one modelling choice (a")
info("free vs zero non-virial floor) and 0.59 -> 1.02 on another (whether M_phot carries the catalogue's IMF")
info("extrapolation).  The vertical-force rung swings 1.123 -> 1.230 between two published measurements of the")
info("same quantity.  Carrying those as systematics:")
meas_sys = [("open clusters", 0.82, 0.25), ("vertical force", 1.18, 0.09)]
w2 = np.array([1.0/m[2]**2 for m in meas_sys]); v2 = np.array([m[1] for m in meas_sys])
B2 = float(np.sum(w2*v2)/np.sum(w2)); chi2s = float(np.sum(w2*(v2 - B2)**2))
P(f"     open clusters   B = 0.82 +- 0.25 (stat + the two modelling swings, half-range)")
P(f"     vertical force  B = 1.18 +- 0.09 (stat + the Bovy-Rix / McMillan disagreement)")
P(f"     -> common B = {B2:.3f}, chi2 = {chi2s:.2f} / 1 dof: the two rungs ARE mutually consistent once")
P(f"        systematics are carried, and the common value is {abs(B2-1.0)/ (1/math.sqrt(np.sum(w2))):.1f} sigma "
  f"from Newton's 1.000 and {abs(B2-B_sat)/(1/math.sqrt(np.sum(w2))):.1f} sigma from the law's {B_sat:.3f}.")
ck("with systematics carried, the equality is NOT refuted by the data -- so the honest statement is that the "
   "DATA cannot test the cross-class claim, and only the THEORY refutes it  [CAN FAIL]", chi2s < 4.0,
   f"chi2 = {chi2s:.2f}/1 dof with systematics vs {chi2:.1f}/1 without")
info(f"The systematics-inclusive common value {B2:.3f} sits BETWEEN Newton's 1.000 and the law's {B_sat:.3f} and")
info("is consistent with both.  That is the whole measurement status of candidate 1 today.")

# ============================================================ mutation control
P("")
P("-"*118); P("B3.  MUTATION CONTROL AND THE NEWTONIAN ALTERNATIVE."); P("-"*118)
for lab, sc in (("a_0 x 10", 10.0), ("a_0 x 1 (truth)", 1.0), ("a_0 x 0.1", 0.1)):
    a0 = A0["canonical"]*sc
    e = e_from_true(field_at_R(R0_KPC, a0))
    info(f"   {lab:16}: e = {e:9.4f}, B = {B_of_e(e):7.4f}, nu(e) = {nu_s(e):7.4f}, "
         f"B(20 kpc)/B(4 kpc) = {B_of_e(e_from_true(field_at_R(20, a0)))/B_of_e(e_from_true(field_at_R(4, a0))):.3f}")
a0x10 = A0["canonical"]*10
ck("mutation control bites: a_0 x 10 changes the predicted solar-circle B by more than the combined "
   "measurement error  [CAN FAIL]",
   abs(B_of_e(e_from_true(field_at_R(R0_KPC, a0x10))) - B_sat) > 1.0/math.sqrt(np.sum(w2)),
   f"B: {B_sat:.4f} -> {B_of_e(e_from_true(field_at_R(R0_KPC, a0x10))):.4f} vs sigma_combined = "
   f"{1.0/math.sqrt(np.sum(w2)):.3f}")
info("nu = 1 foil: every boost becomes exactly 1.000 at every R and in every class.  That is the Newtonian/")
info("LambdaCDM alternative, and it is computed in every row of the tables above.")

# ============================================================ restatement test
P("")
P("-"*118); P("C.  THE RESTATEMENT TEST, EXECUTED."); P("-"*118)
AU = 1.495978707e11; pc = 3.0857e16
cases = [("wide binary, 30 kAU, 1.5 Msun", G*1.5*Msun/(30e3*AU)**2),
         ("open cluster, 400 Msun, r_h = 4 pc", G*400*Msun/(4*pc)**2),
         ("molecular cloud, 1e5 Msun, R = 20 pc", G*1e5*Msun/(20*pc)**2),
         ("the disc at R_0, Sigma = 50 Msun/pc^2", 2*math.pi*G*50*Msun/pc**2)]
P(f"  {'system':<42}{'g_int/a_0':>12}{'BTFR boost sqrt(a_0/g)':>24}{'the law B':>12}")
bt = []
for lab, g in cases:
    y = g/A0["canonical"]; b = math.sqrt(1.0/y); bt.append(b)
    P(f"  {lab:<42}{y:12.4f}{b:24.3f}{B_sat:12.4f}")
ck("the restatement test does NOT close: the BTFR boost sqrt(a_0/g_int) varies by more than a factor 3 across "
   "these classes while B varies by 0%  [CAN FAIL]", max(bt)/min(bt) > 3.0,
   f"BTFR boosts span {min(bt):.2f}-{max(bt):.2f}, a factor {max(bt)/min(bt):.1f}; B is a single number")
info("is_restatement = FALSE.  The content is the EXTERNAL-FIELD EFFECT, which is standard published MOND")
info("(Milgrom 1983 ApJ 270 365; Bekenstein & Milgrom 1984 ApJ 286 7; Famaey & McGaugh 2012 Living Rev. Rel. 15,")
info("Sec. 6.3), and nu(e)[1+L/3] is the angle-average of the KNOWN anisotropic EFE dilation, not a new object.")

# ============================================================ verdict
P("")
P("="*118); P("VERDICT ON CANDIDATE 1"); P("="*118)
tests = [("(1) a relation between MEASURED quantities", True,
          "yes for each rung individually"),
         ("(2) a_0 appears with a PREDICTED coefficient", True,
          "yes -- B(e) is parameter-free once a_0 is fixed"),
         ("(3) holds across many systems to <= 0.1 dex", False,
          "NO.  Two rungs are measured, not four; they sit 0.53 apart in B; and once their own modelling "
          "systematics are carried each is uncertain by 0.09-0.25 in B, i.e. 0.03-0.12 dex, against a "
          f"predicted signal of {math.log10(B_sat):.3f} dex.  The measurement is at best marginal, never 0.1 dex."),
         ("(4) nobody has stated it", False,
          "the external-field effect and its dilation coefficient are long published; only the four-way "
          "assembly is new phrasing"),
         ("(5) NOT a restatement of v^4 = G M_b a_0", True,
          "confirmed by execution in section C")]
for nm, ok, why in tests:
    P(f"  [{'PASS' if ok else 'FAIL'}] {nm}\n         {why}")
P("")
P("  >>> 3 of 5 criteria met.  CANDIDATE 1 IS NOT A SECOND KEPLER-GRADE LAW.")
P("")
P("  >>> THE DECISIVE FINDING IS STRUCTURAL AND NEEDED NO DATA (section A): the four observables do NOT")
P("      measure one number.  The vertical force is generated BY the disc, so its boost is nu(y_local) = 1.444,")
P(f"      not the embedded-system B = {B_sat:.3f}; and the frozen wide-binary band comes from a full two-body")
P(f"      solve at finite internal field, {rows_th[2][2]:.4f}, not from the point-mass asymptote.  The claim's own")
P(f"      three numbers span {100*(1.444/B_sat-1):.1f}% in B, which is {100*(1.444-B_sat)/(B_sat-1):.0f}% of the ENTIRE")
P(f"      signal against Newton (B - 1 = {B_sat-1:.3f}).  A law whose four members disagree by a third of the")
P("      effect they are supposed to share is not a law -- and no data are needed to see it.")
P("")
P("  >>> WHAT SURVIVES, and it is real but weaker: the EFE must be switched on.  Three independent classes now")
P("      say so -- molecular clouds (isolated MOND out at 5.7 sigma, k03), open clusters (out at 36 sigma, this")
P("      session), and the fact that open clusters and wide binaries do not look dark-matter dominated at all.")
P("      That is a confirmation of standard MOND, not a new law, and it is credited above.")
P("")
P("  >>> AGAINST INTEREST, twice.  (a) Both measured rungs sit BELOW their own framework prediction, and the")
P("      vertical-force rung sits below Newton's 1.000 as well on the Bovy & Rix normalisation.  (b) The one")
P("      rung the candidate calls decisive -- globular clusters at low e -- already EXCLUDES the saturation")
P("      law at 9.5 sigma over 0.98 dex of predicted signal (k02), and that kill is on disk and is not new.")
P("")
P("  UPSILON LEVERS, per rung, as the task requires:")
for r in RUNGS:
    P(f"    {r['name']:<44}{r['ups']}")
P("    SHAPE statements (the cross-class equality, the R_gal rise) carry d/d log Upsilon = 0.000 exactly,")
P("    because each rung's boost is a ratio of a dynamical quantity to a photometric one at fixed geometry --")
P("    but every AMPLITUDE, which is what the law actually predicts, carries a lever of -0.5 to -1.0.")
sys.exit(ck.done())
