#!/usr/bin/env python3
"""Action-level audit of a timelike mimetic clock used to localize memory.

This is a bounded symbolic calculation, not a full covariant Dirac analysis of
the Einstein equations.  It addresses one precise claim made in the
Deffayet--Woodard/memory route: that the clock can be a non-propagating
auxiliary while still carrying a nonzero FLRW dust density.

Clock action (signature -+++):

    S_c = -1/2 int d^4x sqrt(-g) lambda
             (g^{mu nu} d_mu phi d_nu phi + 1).

The spatial Fourier mode is represented by K = 1 + k^2 phi^2/a^2.  The
homogeneous branch is k=0.  The lapse is retained long enough to derive the
unit-gradient constraint, and a,N,a-dot are treated as background variables in
this reduced clock-sector audit.  A full gravity-plus-clock algebra is outside
this script's contract.

The key result is obtained from the action, not inserted: p_lambda=0 and the
unit-gradient condition form a generic second-class pair, leaving one clock
configuration degree of freedom whenever lambda != 0.  The same lambda is the
FLRW dust density, lambda proportional to a^-3.  Thus the nonzero-density
branch cannot simultaneously call the clock a zero-DOF auxiliary.
"""

from __future__ import annotations

import json
from pathlib import Path
import argparse
import sympy as sp


def pb(f: sp.Expr, g: sp.Expr, q: tuple[sp.Symbol, ...], p: tuple[sp.Symbol, ...]) -> sp.Expr:
    """Canonical Poisson bracket for the displayed reduced sector."""
    return sp.simplify(sum(sp.diff(f, qi) * sp.diff(g, pi)
                           - sp.diff(f, pi) * sp.diff(g, qi)
                           for qi, pi in zip(q, p)))


def derive() -> dict[str, object]:
    a, N, lam = sp.symbols("a N lambda", positive=True, finite=True)
    phi, phidot = sp.symbols("phi phidot", real=True)
    k2 = sp.symbols("k2", nonnegative=True, finite=True)
    A = a**3
    K = 1 + k2 * phi**2 / a**2

    # Minisuperspace/Fourier-mode action density, with a sign that makes
    # lambda positive for positive dust density.
    L = sp.Rational(1, 2) * A * lam * (phidot**2 / N - N * K)
    p_phi = sp.diff(L, phidot)
    p_lam = sp.Integer(0)
    phidot_from_p = sp.solve(sp.Eq(sp.Symbol("p_phi"), p_phi), phidot)[0]
    p = sp.Symbol("p_phi", real=True)
    phidot_from_p = sp.solve(sp.Eq(p, p_phi), phidot)[0]
    H0 = sp.simplify((p * phidot_from_p - L.subs(phidot, phidot_from_p)) / N)

    # Primary and secondary constraints from the action and its preservation.
    C1 = sp.Symbol("p_lambda", real=True)
    C2 = sp.simplify(sp.diff(H0, lam))  # dot p_lambda = -N*dH0/dlambda
    # Multiplying C2 by -1 would define the same surface; retain this sign so
    # the result is directly tied to the Hamiltonian derivative.
    q = (phi, lam)
    mom = (p, C1)
    constraint_pb = sp.simplify(pb(C1, C2, q, mom))
    dirac_matrix = sp.Matrix([[pb(C1, C1, q, mom), pb(C1, C2, q, mom)],
                              [pb(C2, C1, q, mom), pb(C2, C2, q, mom)]])

    # Preservation of C2 under H_T = N H0 + u C1.  A nonzero coefficient of
    # u fixes the multiplier and does not create a tertiary constraint.
    u = sp.Symbol("u", real=True)
    c2_h0 = sp.simplify(pb(C2, H0, q, mom))
    c2_c1 = sp.simplify(pb(C2, C1, q, mom))
    preservation = sp.factor(N * c2_h0 + u * c2_c1)

    # Flat FLRW homogeneous equations.  On C2, phidot/N = +1 is the future
    # branch and rho_clock=lambda follows from lapse variation.
    K0 = sp.Integer(1)
    L0 = sp.simplify(L.subs(k2, 0))
    p0 = sp.simplify(p_phi.subs(k2, 0))
    rho0 = sp.simplify(-sp.diff(L0, N) / A)
    # For L_m = N a^3 p, pressure is (3 N a^2)^-1 dL_m/da at fixed
    # phidot.  This is only a diagnostic before imposing C2.
    pressure0 = sp.simplify(sp.diff(L0, a) / (3 * N * a**2))
    # phi Euler-Lagrange equation: d/dt (a^3 lambda phidot/N)=0.
    clock_charge = sp.Symbol("clock_charge", real=True)
    rho_scaling = sp.Eq(A * lam, clock_charge)
    sound_speed_sq = sp.Integer(0)  # p=0 and rho=lambda on the homogeneous branch

    # Preferred-frame coefficients are not generated by the mimetic
    # multiplier itself.  If one adds Einstein-aether kinetic terms to make a
    # dynamical clock, the standard c13=0,c4=0 specialization is derived here
    # symbolically as a contrast, not as a claim about the mimetic route.
    c1, c2, c3, c4 = sp.symbols("c1 c2 c3 c4", real=True)
    c13, c14, c123 = c1 + c3, c1 + c4, c1 + c2 + c3
    alpha1_ea = sp.factor(-8 * (c3**2 + c1*c4) /
                          (2*c1 - c1**2 + c3**2))
    alpha2_ea = sp.factor(alpha1_ea / 2
                          - (c1 + 2*c3 - c4) * (2*c1 + 3*c2 + c3 + c4)
                          / (c123 * (2 - c14)))
    khronon = {c3: -c1, c4: 0}
    alpha1_k = sp.factor(alpha1_ea.subs(khronon))
    alpha2_k = sp.factor(alpha2_ea.subs(khronon))
    alpha2_zero = sp.solve(sp.Eq(alpha2_k, 0), c2)
    sample = {c1: sp.Rational(1, 100000), c2: sp.Rational(1, 10)}
    alpha_sample = {
        "alpha1": sp.N(alpha1_k.subs(sample)),
        "alpha2": sp.N(alpha2_k.subs({**sample, c3: -sample[c1], c4: 0})),
    }

    # Generic-rank statements are computed, not hard-coded.  SymPy's generic
    # rank sees the nonzero symbolic bracket.  We also state the exceptional
    # locus explicitly: lambda=0 (or the fully zero clock charge) is a
    # degenerate branch and cannot represent nonzero dust.
    generic_rank = int(dirac_matrix.rank())
    phase_dimension = 4
    reduced_phase_dimension = phase_dimension - generic_rank
    reduced_configuration_dimension = sp.Rational(reduced_phase_dimension, 2)
    sectors = {}
    for name, kval in (("k=0", 0), ("k!=0", sp.Symbol("kappa2", positive=True))):
        mat = sp.simplify(dirac_matrix.subs(k2, kval))
        sectors[name] = {
            "dirac_matrix": mat,
            "generic_rank": int(mat.rank()),
            "configuration_dof": sp.Rational(phase_dimension - int(mat.rank()), 2),
            "bracket": sp.factor(mat[0, 1]),
        }

    return {
        "action": str(L),
        "momenta": {"p_phi": str(p_phi), "p_lambda": str(p_lam)},
        "hamiltonian_density_over_lapse": str(H0),
        "constraints": {"primary": [str(C1)], "secondary": [str(C2)]},
        "dirac_matrix": str(dirac_matrix),
        "generic_dirac_rank": generic_rank,
        "reduced_phase_dimension": reduced_phase_dimension,
        "reduced_configuration_dof": str(reduced_configuration_dimension),
        "preservation": {"{C2,H0}": str(c2_h0), "{C2,C1}": str(c2_c1),
                         "dot_C2": str(preservation)},
        "sectors": sectors,
        "flrw": {"L_homogeneous": str(L0), "p_phi_homogeneous": str(p0),
                 "rho_clock": str(rho0), "pressure_diagnostic": str(pressure0),
                 "charge_equation": str(rho_scaling),
                 "sound_speed_squared": str(sound_speed_sq),
                 "expanding_friedmann_source": "rho_clock=lambda=clock_charge/a^3, p_clock=0"},
        "preferred_frame_contrast": {
            "alpha1_general_ea": str(alpha1_ea),
            "alpha2_general_ea": str(alpha2_ea),
            "alpha1_c13_0_c4_0": str(alpha1_k),
            "alpha2_c13_0_c4_0": str(alpha2_k),
            "alpha2_zero_locus": [str(x) for x in alpha2_zero],
            "sample_c1_1e-5_c2_0.1": {k: str(v) for k, v in alpha_sample.items()},
            "interpretation": "These Einstein-aether formulas apply only after adding aether kinetic terms; the mimetic multiplier has no c_i kinetic block.",
        },
        "interpretation": {
            "nonzero_density_branch": "lambda != 0 and p_phi != 0 gives a nonzero Dirac bracket and one reduced clock configuration DOF in both k sectors.",
            "zero_density_exception": "lambda=0 is a rank-degenerate zero-clock branch; it cannot supply the FLRW dust density used by the memory proposal.",
            "scope": "Reduced clock-sector audit; not a substitute for the full gravity-plus-clock functional constraint algebra.",
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        default=str(Path(__file__).with_name("mimetic_clock_dirac_results.json")),
        help="JSON result path (default: beside this script)",
    )
    args = parser.parse_args()
    result = derive()
    print("MIMETIC CLOCK DIRAC / FLRW AUDIT")
    print("=================================")
    print("action:", result["action"])
    print("primary constraints:", result["constraints"]["primary"])
    print("secondary constraints:", result["constraints"]["secondary"])
    print("Dirac matrix:", result["dirac_matrix"])
    print("generic Dirac rank:", result["generic_dirac_rank"])
    print("reduced phase dimension:", result["reduced_phase_dimension"])
    print("reduced configuration DOF:", result["reduced_configuration_dof"])
    for name, sector in result["sectors"].items():
        print(f"{name}: rank={sector['generic_rank']} DOF={sector['configuration_dof']} bracket={sector['bracket']}")
    print("preservation {C2,H0}:", result["preservation"]["{C2,H0}"])
    print("preservation {C2,C1}:", result["preservation"]["{C2,C1}"])
    print("FLRW:", result["flrw"])
    print("preferred-frame contrast:", result["preferred_frame_contrast"])
    print("RESULT: nonzero-density mimetic clock is not a zero-DOF auxiliary in this reduced action audit.")

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(result, indent=2, default=str) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
