"""Generate Axioms_all2.lean: `#print axioms` for EVERY theorem declared in the nine certificate modules of this directory
(the per-file #print lines cover the headline theorems; this audit covers all of them, so no theorem is left unchecked).
Namespace-aware: `namespace X` / `end X` (also nested) are tracked so that the printed names are fully qualified."""
import re
mods = ["P1_wall_dS", "P2_sds_surface_gravity", "P3_record_iff", "P4_macdowell_mansouri", "P5_ext_thermo", "P6_dimension",
        "P7_offset_family", "P8_omega_lambda", "PuzzleChain"]
names = []
for m in mods:
    src = open(m + ".lean", encoding="utf-8").read()
    src = re.sub(r"/-.*?-/", "", src, flags=re.S)          # drop block comments / docstrings
    stack = []
    for line in src.splitlines():
        mm = re.match(r"\s*namespace\s+([A-Za-z0-9_.]+)", line)
        if mm:
            stack.append(mm.group(1)); continue
        mm = re.match(r"\s*end\s+([A-Za-z0-9_.]+)\s*$", line)
        if mm and stack and stack[-1] == mm.group(1):
            stack.pop(); continue
        mm = re.match(r"\s*theorem\s+([A-Za-z0-9_'.]+)", line)
        if mm:
            names.append(".".join(stack + [mm.group(1)]))
assert len(names) == len(set(names)), "duplicate theorem names: " + str([n for n in names if names.count(n) > 1])
with open("Axioms_all2.lean", "w", encoding="utf-8") as f:
    f.write("import Mathlib\n" + "".join("import %s\n" % m for m in mods) + "\n")
    f.write("-- generated by gen_axioms2.py: one #print axioms per theorem of the nine modules\n")
    for n in names:
        f.write("#print axioms %s\n" % n)
print(len(names), "theorems")
