#!/usr/bin/env python3
"""Re-execute lightweight tests with actual timing; preserve older bespoke provenance."""
import pathlib,os,sys,subprocess,json,hashlib,datetime,time
HERE=pathlib.Path(__file__).resolve().parent;REPO=HERE.parents[2]
for stem in ['replacement_joint','replacement_covariance']:
 src=HERE/(stem+'_manifest.json');dst=HERE/(stem+'_provenance.json')
 if not dst.exists():dst.write_bytes(src.read_bytes())
version=subprocess.check_output(['/usr/bin/python3','-c','import sys,numpy,scipy; print(sys.version.split()[0]); print(numpy.__version__); print(scipy.__version__)'],text=True).splitlines()
validation=[]
for family,script,suffix,mut,ref,fac in [('joint','replacement_joint_gate.py','',0,0,'1.4'),('joint','replacement_joint_gate.py','_MUTATE',1,0,'1.4'),('joint','replacement_joint_gate.py','_REFINE',0,1,'1.4'),('joint','replacement_joint_gate.py','_FAC1.0',0,0,'1.0'),('joint','replacement_joint_gate.py','_FAC2.0',0,0,'2.0'),('covariance','replacement_covariance_fit.py','',0,0,'1.4'),('covariance','replacement_covariance_fit.py','_MUTATE',1,0,'1.4')]:
 stem='replacement_'+family;env=os.environ.copy();env.update(MUTATE=str(mut),REFINE=str(ref),KIDS_MB_MS=fac)
 argv=['/usr/bin/python3',str(HERE/'record_child.py'),str(HERE/script),str(HERE/(stem+'_inputs'+suffix+'.json'))]
 started=datetime.datetime.now(datetime.timezone.utc).isoformat();t=time.monotonic()
 with (HERE/(stem+suffix+'.out')).open('w') as so,(HERE/(stem+suffix+'.err')).open('w') as se:p=subprocess.run(argv,env=env,stdout=so,stderr=se)
 elapsed=time.monotonic()-t;j=json.loads((HERE/(stem+'_results'+suffix+'.json')).read_text());inputs=json.loads((HERE/(stem+'_inputs'+suffix+'.json')).read_text())
 scientific=[{'name':k,'passed':v['ok']} for k,v in j['checks'].items()];nfail=sum(not x['passed'] for x in scientific)
 def artifact(path):return {'path':str(path.relative_to(REPO)),'sha256':hashlib.sha256(path.read_bytes()).hexdigest()}
 m={'schema_version':1,'claim_id':'HR01_'+stem+(suffix or '_MAIN'),'repository':{'commit':'48905ae11213afcb9ff1b7726530bb5dd1933fe3','dirty':True},'command':f'MUTATE={mut} REFINE={ref} KIDS_MB_MS={fac} '+ ' '.join(argv),'environment':{'software':['Python '+version[0],'NumPy '+version[1],'SciPy '+version[2]],'hardware':'arm64'},'mathematics':{'assertion_tested':('Full-covariance bounded nuisance optimization with fixed Moster endpoints and explicit benchmark/mutation controls' if family=='covariance' else 'Conditional conserved reservoir-cap KiDS/SPARC scoring with inherited Moster mapping; meaningful Gauss retention and baseline controls'),'coefficient_domain':'IEEE-754 float64 numerical linear algebra and quadrature','conventions':'Point-baryon spherical P2 cap; SI mass/acceleration; canonical and alternate a0; kappa=1/2 fitted','inputs':[str((HERE/script).relative_to(REPO)),str((HERE/(stem+'_inputs'+suffix+'.json')).relative_to(REPO))],'bounds':{'Mb_grid_log10_Msun':[9.8,11.8,.05],'SPARC_galaxies':175 if family=='joint' else 'not rescored','mapping_Mb_over_Mstar':float(fac) if family=='joint' else [1.,1.4,2.],'A_bounds':[0,2],'starts_per_fit':200 if family=='covariance' else 'inherited grid; no multistart','free_A_starts':201 if family=='covariance' else 'not applicable','mutation':bool(mut),'refinement':bool(ref)},'non_claims':['No global-minimum proof, formation dynamics, covariant action, or universal observational viability.','Version1 records do not certify enforced resource limits; tests are bounded by explicit finite grids and optimizer iterations.']},'randomness':{'used':family=='covariance','generator':'numpy.default_rng PCG64' if family=='covariance' else 'none used in scores; imported FP1 unused Gaussian table seeded7','seed':20260927 if family=='covariance' else None},'run':{'started_at':started,'runtime_seconds':elapsed,'exit_status':p.returncode},'outputs':[artifact(HERE/(stem+'_results'+suffix+'.json')),artifact(HERE/(stem+suffix+'.out')),artifact(HERE/(stem+suffix+'.err')),artifact(HERE/(stem+'_inputs'+suffix+'.json'))],'checks':scientific+[{'name':'all recorded input hashes unchanged','passed':all(r['before']==r['after'] for r in inputs)}],'result':f'Completed; exit {p.returncode}; {nfail} of {len(scientific)} named checks fail. '+('Deliberate mutation scientific failure expected.' if mut else 'See explicit scientific scores; control success is not an observational pass.'),'residual_risks':['Legacy v1 has no required machine-checkable resource caps or declared result contract; no upgrade of provenance is implied.','Python audit-hook input hashes do not record all C-library reads; all recorded source/data reads remained unchanged.','Finite multi-start optimization and supplied empirical cross-population mapping are conditional evidence.']}
 name=HERE/(stem+suffix+'_manifest.json');name.write_text(json.dumps(m,indent=2))
 v=subprocess.run(['/usr/bin/python3',str(pathlib.Path.home()/'.codex/plugins/cache/openai-curated-remote/mathbox/3.2.0/skills/computation-audit/scripts/validate_manifest.py'),str(name),'--root',str(REPO)],capture_output=True,text=True)
 validation.append({'manifest':str(name.relative_to(REPO)),'exit_status':v.returncode,'stdout':v.stdout,'stderr':v.stderr});print(name.name,'run',p.returncode,'validation',v.returncode,flush=True)
(HERE/'replacement_manifest_validation.json').write_text(json.dumps(validation,indent=2));sys.exit(0 if all(v['exit_status']==0 for v in validation) else 1)
