#!/usr/bin/env python3
"""
M4 PyRosetta FlexPepDock Pipeline
===================================

Implements induced-fit flexible peptide docking using PyRosetta.
Critical for modeling peptide-receptor interactions where both
peptide and receptor undergo conformational changes upon binding.

METHODOLOGY:
- FlexPepDock: Rosetta's gold-standard peptide docking protocol
- Induced-fit modeling: Both peptide and receptor flexible
- Monte Carlo sampling with Rosetta energy function
- Refinement with minimization and repacking

PHYSICS:
- REF2015 energy function (Rosetta's latest)
- van der Waals, electrostatics, solvation (implicit)
- Hydrogen bonding and aromatic interactions
- Backbone and side-chain flexibility

OUTPUT:
- Docked peptide-receptor complex PDB
- Interface energy (ΔGinterface)
- Per-residue energy contributions
- Interface RMSD analysis

LICENSE: AGPL-3.0-or-later
AUTHOR: Carl Zimmerman & Claude Opus 4.5
DATE: April 2026

REQUIREMENTS:
- PyRosetta (academic license required)
- pip install pyrosetta-installer && python -c "import pyrosetta_installer; pyrosetta_installer.install_pyrosetta()"
"""

import json
import os
from pathlib import Path
from datetime import datetime
from dataclasses import dataclass, asdict
from typing import List, Dict, Optional, Tuple
import subprocess


@dataclass
class FlexPepDockConfig:
    """Configuration for FlexPepDock simulation."""
    # Input
    peptide_sequence: str
    peptide_id: str
    receptor_pdb: str

    # Protocol settings
    n_decoys: int = 200            # Number of docking models to generate
    lowres_cycles: int = 5         # Low-resolution Monte Carlo cycles
    highres_cycles: int = 8        # High-resolution refinement cycles

    # Flexibility
    peptide_full_flex: bool = True   # Full backbone flexibility for peptide
    receptor_bb_flex: bool = True    # Receptor backbone flexibility near interface
    receptor_flex_distance: float = 8.0  # Å from peptide for receptor flexibility

    # Scoring
    score_function: str = "ref2015"  # Rosetta REF2015 scoring

    # Output
    n_top_models: int = 10         # Number of top models to output


@dataclass
class DockingResult:
    """Results from a FlexPepDock run."""
    peptide_id: str
    model_rank: int
    total_score: float
    interface_score: float
    peptide_score: float
    rmsd_to_input: float
    interface_contacts: int
    hbonds: int
    pdb_path: str


def generate_peptide_pdb(sequence: str, output_path: Path) -> bool:
    """
    Generate initial peptide structure from sequence.

    Uses Rosetta's PeptideStubMover or PyMOL's builder.
    For production, use AlphaFold2 predicted structure.
    """
    # This is a placeholder - in practice use:
    # 1. AlphaFold2 for peptide structure prediction
    # 2. PyMOL's build peptide feature
    # 3. Rosetta's PeptideStubMover

    pdb_template = f"""REMARK Generated by M4 FlexPepDock Pipeline
REMARK Sequence: {sequence}
REMARK Date: {datetime.now().isoformat()}
REMARK NOTE: Replace with AlphaFold2 predicted structure for production use
"""

    # Generate extended chain coordinates
    # (Simplified - real implementation would use proper backbone geometry)
    x, y, z = 0.0, 0.0, 0.0
    atom_num = 1
    res_num = 1

    lines = [pdb_template]

    for aa in sequence.upper():
        # Add backbone atoms (simplified extended chain)
        lines.append(f"ATOM  {atom_num:5d}  N   {aa_3letter(aa)} A{res_num:4d}    {x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00           N")
        atom_num += 1
        x += 1.458  # N-CA distance

        lines.append(f"ATOM  {atom_num:5d}  CA  {aa_3letter(aa)} A{res_num:4d}    {x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00           C")
        atom_num += 1
        x += 1.523  # CA-C distance

        lines.append(f"ATOM  {atom_num:5d}  C   {aa_3letter(aa)} A{res_num:4d}    {x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00           C")
        atom_num += 1

        lines.append(f"ATOM  {atom_num:5d}  O   {aa_3letter(aa)} A{res_num:4d}    {x:8.3f}{y+1.2:8.3f}{z:8.3f}  1.00  0.00           O")
        atom_num += 1
        x += 1.329  # C-N distance

        res_num += 1

    lines.append("END")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    return True


def aa_3letter(aa: str) -> str:
    """Convert 1-letter to 3-letter amino acid code."""
    mapping = {
        'A': 'ALA', 'C': 'CYS', 'D': 'ASP', 'E': 'GLU', 'F': 'PHE',
        'G': 'GLY', 'H': 'HIS', 'I': 'ILE', 'K': 'LYS', 'L': 'LEU',
        'M': 'MET', 'N': 'ASN', 'P': 'PRO', 'Q': 'GLN', 'R': 'ARG',
        'S': 'SER', 'T': 'THR', 'V': 'VAL', 'W': 'TRP', 'Y': 'TYR'
    }
    return mapping.get(aa.upper(), 'UNK')


def generate_rosetta_script(config: FlexPepDockConfig, output_dir: Path) -> str:
    """
    Generate RosettaScripts XML for FlexPepDock.

    This defines the docking protocol in Rosetta's XML format.
    """
    xml_content = f"""<ROSETTASCRIPTS>
    <!-- M4 FlexPepDock Protocol -->
    <!-- Peptide: {config.peptide_id} -->
    <!-- Generated: {datetime.now().isoformat()} -->

    <SCOREFXNS>
        <ScoreFunction name="ref15" weights="{config.score_function}"/>
        <ScoreFunction name="soft_rep" weights="soft_rep_design"/>
        <ScoreFunction name="interchain_cen" weights="interchain_cen"/>
    </SCOREFXNS>

    <RESIDUE_SELECTORS>
        <!-- Select peptide chain (assumed chain B) -->
        <Chain name="peptide" chains="B"/>

        <!-- Select receptor (assumed chain A) -->
        <Chain name="receptor" chains="A"/>

        <!-- Interface residues -->
        <Neighborhood name="interface_receptor" selector="peptide"
                      distance="{config.receptor_flex_distance}"/>

        <!-- Combined interface -->
        <Or name="interface" selectors="peptide,interface_receptor"/>
    </RESIDUE_SELECTORS>

    <TASKOPERATIONS>
        <!-- Allow repacking at interface -->
        <OperateOnResidueSubset name="repack_interface" selector="interface">
            <RestrictToRepackingRLT/>
        </OperateOnResidueSubset>

        <!-- Prevent design (keep sequence) -->
        <RestrictToRepacking name="no_design"/>

        <!-- Include current rotamer -->
        <IncludeCurrent name="include_current"/>

        <!-- Extra chi sampling for better accuracy -->
        <ExtraRotamersGeneric name="extra_chi" ex1="1" ex2="1"/>
    </TASKOPERATIONS>

    <MOVE_MAP_FACTORIES>
        <!-- Peptide fully flexible -->
        <MoveMapFactory name="peptide_flex" bb="false" chi="false">
            <Backbone residue_selector="peptide" enable="true"/>
            <Chi residue_selector="peptide" enable="true"/>
        </MoveMapFactory>

        <!-- Receptor interface flexible -->
        <MoveMapFactory name="receptor_flex" bb="false" chi="false">
            <Backbone residue_selector="interface_receptor" enable="{str(config.receptor_bb_flex).lower()}"/>
            <Chi residue_selector="interface_receptor" enable="true"/>
        </MoveMapFactory>

        <!-- Combined flexibility -->
        <MoveMapFactory name="interface_flex" bb="false" chi="false">
            <Backbone residue_selector="interface" enable="true"/>
            <Chi residue_selector="interface" enable="true"/>
        </MoveMapFactory>
    </MOVE_MAP_FACTORIES>

    <MOVERS>
        <!-- Initial setup -->
        <SwitchChainOrder name="setup_chains" chain_order="AB"/>

        <!-- Low-resolution centroid docking -->
        <FlexPepDocking name="lowres_dock" lowres_preoptimize="true"
                        pep_fold_only="false" ppk_only="false"
                        flexpep_score_only="false"/>

        <!-- High-resolution refinement -->
        <FlexPepDocking name="highres_dock" lowres_preoptimize="false"
                        pep_refine="true" min_receptor_bb="true"/>

        <!-- Minimization -->
        <MinMover name="minimize" scorefxn="ref15"
                  movemap_factory="interface_flex" type="lbfgs_armijo_nonmonotone"
                  tolerance="0.01" max_iter="200"/>

        <!-- Side-chain repacking -->
        <PackRotamersMover name="repack" scorefxn="ref15"
                           task_operations="repack_interface,no_design,include_current,extra_chi"/>

        <!-- Interface analysis -->
        <InterfaceAnalyzerMover name="analyze" scorefxn="ref15"
                                pack_separated="true" pack_input="false"
                                compute_interface_sc="true"
                                compute_separated_sasa="true"
                                calc_hbond_sasaE="true"/>
    </MOVERS>

    <FILTERS>
        <!-- Interface score filter -->
        <ScoreType name="interface_score" scorefxn="ref15"
                   score_type="total_score" threshold="0"
                   confidence="0"/>

        <!-- Total score filter -->
        <TotalScore name="total_score" scorefxn="ref15"
                    confidence="0"/>

        <!-- SASA filter (buried surface area) -->
        <Sasa name="buried_sasa" threshold="500" confidence="0"/>
    </FILTERS>

    <PROTOCOLS>
        <!-- FlexPepDock Protocol -->
        <Add mover="setup_chains"/>

        <!-- Low-resolution phase -->
        <Add mover="lowres_dock"/>

        <!-- High-resolution refinement cycles -->
        <Add mover="highres_dock"/>
        <Add mover="repack"/>
        <Add mover="minimize"/>

        <!-- Final analysis -->
        <Add mover="analyze"/>

        <!-- Filters for output -->
        <Add filter="total_score"/>
        <Add filter="interface_score"/>
    </PROTOCOLS>

    <OUTPUT scorefxn="ref15"/>
</ROSETTASCRIPTS>
"""
    return xml_content


def generate_pyrosetta_script(config: FlexPepDockConfig, output_dir: Path) -> str:
    """
    Generate Python script using PyRosetta API directly.

    This is the preferred method for programmatic access.
    """
    script = f'''#!/usr/bin/env python3
"""
M4 FlexPepDock - PyRosetta Implementation
==========================================
Peptide: {config.peptide_id}
Sequence: {config.peptide_sequence}
Generated: {datetime.now().isoformat()}

LICENSE: AGPL-3.0-or-later
"""

import os
import json
from datetime import datetime
from pathlib import Path

# Initialize PyRosetta
import pyrosetta
from pyrosetta import *
from pyrosetta.rosetta.core.scoring import *
from pyrosetta.rosetta.protocols.flexpep_docking import *
from pyrosetta.rosetta.protocols.analysis import InterfaceAnalyzerMover
from pyrosetta.rosetta.core.select.residue_selector import *
from pyrosetta.rosetta.protocols.minimization_packing import MinMover, PackRotamersMover

# Configuration
PEPTIDE_ID = "{config.peptide_id}"
PEPTIDE_SEQUENCE = "{config.peptide_sequence}"
N_DECOYS = {config.n_decoys}
RECEPTOR_PDB = "{config.receptor_pdb}"
SCORE_FUNCTION = "{config.score_function}"
RECEPTOR_FLEX_DIST = {config.receptor_flex_distance}


def setup_pyrosetta():
    """Initialize PyRosetta with appropriate options."""
    init_options = [
        "-ex1", "-ex2",                    # Extra rotamer sampling
        "-use_input_sc",                   # Use input side chains
        "-flip_HNQ",                       # Consider Asn/Gln/His flips
        "-no_optH", "false",              # Optimize hydrogens
        "-ignore_zero_occupancy", "false", # Include all atoms
        "-mute", "all",                    # Reduce output
        "-unmute", "protocols.FlexPepDocking"
    ]
    pyrosetta.init(" ".join(init_options))
    print("PyRosetta initialized")


def load_structures(receptor_pdb: str, peptide_pdb: str) -> Pose:
    """Load and combine receptor and peptide structures."""
    # Load receptor
    receptor = pose_from_pdb(receptor_pdb)
    print(f"Receptor loaded: {{receptor.total_residue()}} residues")

    # Load peptide
    peptide = pose_from_pdb(peptide_pdb)
    print(f"Peptide loaded: {{peptide.total_residue()}} residues")

    # Combine into single pose
    # Append peptide as chain B
    for i in range(1, peptide.total_residue() + 1):
        receptor.append_residue_by_jump(
            peptide.residue(i),
            receptor.total_residue(),
            "",
            "",
            True  # New chain
        )

    print(f"Complex created: {{receptor.total_residue()}} total residues")
    return receptor


def create_complex_from_sequence(receptor_pdb: str, peptide_seq: str) -> Pose:
    """Create complex by building peptide from sequence."""
    # Load receptor
    receptor = pose_from_pdb(receptor_pdb)
    print(f"Receptor loaded: {{receptor.total_residue()}} residues")

    # Build peptide from sequence
    peptide = Pose()
    make_pose_from_sequence(peptide, peptide_seq, "fa_standard")
    print(f"Peptide built: {{peptide.total_residue()}} residues")

    # Set peptide to extended conformation
    for i in range(1, peptide.total_residue() + 1):
        peptide.set_phi(i, -150)
        peptide.set_psi(i, 150)
        peptide.set_omega(i, 180)

    # Append to receptor
    for i in range(1, peptide.total_residue() + 1):
        receptor.append_residue_by_jump(
            peptide.residue(i),
            receptor.total_residue(),
            "",
            "",
            True
        )

    return receptor


def setup_flexpep_docking(pose: Pose, scorefxn) -> FlexPepDockingProtocol:
    """Set up FlexPepDocking protocol."""
    # Identify chains
    # Assume receptor = chain A, peptide = chain B
    peptide_start = 0
    for i in range(1, pose.total_residue() + 1):
        if pose.pdb_info().chain(i) == 'B':
            peptide_start = i
            break

    if peptide_start == 0:
        # Find chain break
        for i in range(1, pose.total_residue()):
            if pose.chain(i) != pose.chain(i + 1):
                peptide_start = i + 1
                break

    print(f"Peptide starts at residue {{peptide_start}}")

    # Create FlexPepDocking mover
    flexpep = FlexPepDockingProtocol()

    # Configure protocol
    flexpep.set_scorefxn(scorefxn)

    return flexpep


def run_docking(pose: Pose, n_decoys: int, output_dir: Path) -> list:
    """Run FlexPepDock and generate multiple decoys."""
    # Scoring function
    scorefxn = get_score_function()  # REF2015 by default

    # Results storage
    results = []

    print(f"\\nGenerating {{n_decoys}} docking models...")

    for i in range(n_decoys):
        # Clone pose for this decoy
        work_pose = Pose(pose)

        # Set up docking
        flexpep = setup_flexpep_docking(work_pose, scorefxn)

        # Run docking protocol
        try:
            flexpep.apply(work_pose)
        except Exception as e:
            print(f"  Decoy {{i+1}} failed: {{e}}")
            continue

        # Analyze interface
        analyzer = InterfaceAnalyzerMover()
        analyzer.set_scorefunction(scorefxn)
        analyzer.set_pack_separated(True)
        analyzer.apply(work_pose)

        # Get scores
        total_score = scorefxn(work_pose)
        interface_score = work_pose.scores.get("dG_separated", 0.0)

        # Get interface metrics
        interface_hbonds = work_pose.scores.get("hbonds_int", 0)
        interface_contacts = work_pose.scores.get("nres_int", 0)

        # Save model
        model_path = output_dir / f"model_{{i+1:04d}}.pdb"
        work_pose.dump_pdb(str(model_path))

        result = {{
            "model": i + 1,
            "total_score": total_score,
            "interface_score": interface_score,
            "hbonds": interface_hbonds,
            "contacts": interface_contacts,
            "pdb_path": str(model_path)
        }}
        results.append(result)

        if (i + 1) % 10 == 0:
            print(f"  Completed {{i+1}}/{{n_decoys}} models")

    return results


def analyze_results(results: list, output_dir: Path) -> dict:
    """Analyze and rank docking results."""
    # Sort by interface score (more negative = better)
    results_sorted = sorted(results, key=lambda x: x["interface_score"])

    # Summary statistics
    summary = {{
        "peptide_id": PEPTIDE_ID,
        "peptide_sequence": PEPTIDE_SEQUENCE,
        "n_models": len(results),
        "timestamp": datetime.now().isoformat(),
        "best_model": results_sorted[0] if results_sorted else None,
        "top_10_models": results_sorted[:10],
        "score_stats": {{
            "best_interface": results_sorted[0]["interface_score"] if results_sorted else None,
            "best_total": min(r["total_score"] for r in results) if results else None,
            "avg_interface": sum(r["interface_score"] for r in results) / len(results) if results else None
        }},
        "interface_stats": {{
            "max_hbonds": max(r["hbonds"] for r in results) if results else 0,
            "avg_contacts": sum(r["contacts"] for r in results) / len(results) if results else 0
        }}
    }}

    # Save summary
    with open(output_dir / "docking_summary.json", "w") as f:
        json.dump(summary, f, indent=2)

    # Print results
    print("\\n" + "=" * 60)
    print("DOCKING RESULTS")
    print("=" * 60)
    print(f"Peptide: {{PEPTIDE_ID}}")
    print(f"Sequence: {{PEPTIDE_SEQUENCE}}")
    print(f"Models generated: {{len(results)}}")
    print()
    print("TOP 5 MODELS:")
    print("-" * 60)
    for i, r in enumerate(results_sorted[:5]):
        print(f"  {{i+1}}. Model {{r['model']:4d}} | Interface: {{r['interface_score']:8.2f}} | "
              f"Total: {{r['total_score']:8.2f}} | HBonds: {{r['hbonds']}}")
    print()
    print(f"Best interface score: {{summary['score_stats']['best_interface']:.2f}} REU")

    # Estimate Kd (rough approximation)
    # ΔG ≈ Interface score in REU × 1.0 kcal/mol/REU (very rough)
    if summary['score_stats']['best_interface']:
        dG_approx = summary['score_stats']['best_interface'] * 1.0  # kcal/mol approx
        # Kd = exp(ΔG/RT), RT ≈ 0.593 kcal/mol at 300K
        import math
        Kd_approx = math.exp(dG_approx / 0.593) * 1e9  # nM
        print(f"Estimated Kd (rough): {{Kd_approx:.2e}} nM")
        summary["estimated_Kd_nM"] = Kd_approx

    return summary


def main():
    """Main FlexPepDock workflow."""
    print("=" * 60)
    print("M4 FlexPepDock - PyRosetta")
    print("=" * 60)
    print(f"Peptide: {{PEPTIDE_ID}}")
    print(f"Sequence: {{PEPTIDE_SEQUENCE}}")
    print()

    # Setup
    setup_pyrosetta()

    # Create output directory
    output_dir = Path("flexpep_results") / PEPTIDE_ID
    output_dir.mkdir(parents=True, exist_ok=True)

    # Build complex
    if os.path.exists(RECEPTOR_PDB):
        complex_pose = create_complex_from_sequence(RECEPTOR_PDB, PEPTIDE_SEQUENCE)
    else:
        print(f"WARNING: Receptor PDB not found: {{RECEPTOR_PDB}}")
        print("Creating demo pose...")
        complex_pose = Pose()
        make_pose_from_sequence(complex_pose, PEPTIDE_SEQUENCE, "fa_standard")

    # Run docking
    results = run_docking(complex_pose, N_DECOYS, output_dir)

    # Analyze
    if results:
        summary = analyze_results(results, output_dir)

        print("\\n" + "=" * 60)
        print("COMPLETE")
        print("=" * 60)
        print(f"Results saved to: {{output_dir}}")
    else:
        print("No successful docking models generated")


if __name__ == "__main__":
    main()
'''
    return script


def generate_bash_wrapper(config: FlexPepDockConfig, output_dir: Path) -> str:
    """Generate bash script to run FlexPepDock."""
    script = f"""#!/bin/bash
# M4 FlexPepDock Wrapper Script
# Generated: {datetime.now().isoformat()}
# Peptide: {config.peptide_id}

set -e

WORKDIR="{output_dir}"
PEPTIDE_ID="{config.peptide_id}"
N_DECOYS={config.n_decoys}

echo "=============================================="
echo "M4 FlexPepDock: $PEPTIDE_ID"
echo "=============================================="

cd "$WORKDIR"

# Option 1: Use PyRosetta (preferred)
if python3 -c "import pyrosetta" 2>/dev/null; then
    echo "Using PyRosetta..."
    python3 flexpep_pyrosetta.py
    exit 0
fi

# Option 2: Use Rosetta command line
if command -v FlexPepDocking.default.linuxgccrelease &> /dev/null; then
    echo "Using Rosetta FlexPepDocking..."

    # Run FlexPepDock
    FlexPepDocking.default.linuxgccrelease \\
        -s complex.pdb \\
        -native complex.pdb \\
        -flexPepDocking:receptor_chain A \\
        -flexPepDocking:peptide_chain B \\
        -nstruct $N_DECOYS \\
        -out:prefix flexpep_ \\
        -out:path:pdb "$WORKDIR/models" \\
        -out:path:score "$WORKDIR" \\
        -ex1 -ex2aro \\
        -use_input_sc \\
        -pep_refine \\
        -flexpep_score_only false \\
        -lowres_preoptimize true

    echo "Docking complete"
    exit 0
fi

# Option 3: Use RosettaScripts
if command -v rosetta_scripts.default.linuxgccrelease &> /dev/null; then
    echo "Using RosettaScripts..."

    rosetta_scripts.default.linuxgccrelease \\
        -s complex.pdb \\
        -parser:protocol flexpep_protocol.xml \\
        -nstruct $N_DECOYS \\
        -out:prefix flexpep_ \\
        -out:path:pdb "$WORKDIR/models"

    echo "Docking complete"
    exit 0
fi

echo "ERROR: Neither PyRosetta nor Rosetta found!"
echo ""
echo "Installation options:"
echo "1. PyRosetta (academic): pip install pyrosetta-installer && python -c 'import pyrosetta_installer; pyrosetta_installer.install_pyrosetta()'"
echo "2. Rosetta Suite: Request license at https://www.rosettacommons.org/software/license-and-download"
exit 1
"""
    return script


def setup_flexpep_pipeline(peptide_id: str, peptide_sequence: str,
                            receptor_pdb: str, output_base: Path) -> Dict:
    """
    Set up complete FlexPepDock pipeline for a peptide-receptor pair.
    """
    print("=" * 70)
    print("M4 PyRosetta FlexPepDock PIPELINE SETUP")
    print("=" * 70)
    print(f"Peptide: {peptide_id}")
    print(f"Sequence: {peptide_sequence}")
    print(f"Receptor: {receptor_pdb}")
    print()

    # Configuration
    config = FlexPepDockConfig(
        peptide_sequence=peptide_sequence,
        peptide_id=peptide_id,
        receptor_pdb=receptor_pdb
    )

    # Create output directory
    output_dir = output_base / peptide_id
    output_dir.mkdir(parents=True, exist_ok=True)

    models_dir = output_dir / "models"
    models_dir.mkdir(exist_ok=True)

    # Generate files
    print("Generating pipeline files...")

    # 1. RosettaScripts XML
    xml_content = generate_rosetta_script(config, output_dir)
    with open(output_dir / "flexpep_protocol.xml", "w") as f:
        f.write(xml_content)
    print("  - flexpep_protocol.xml (RosettaScripts)")

    # 2. PyRosetta Python script
    pyrosetta_script = generate_pyrosetta_script(config, output_dir)
    with open(output_dir / "flexpep_pyrosetta.py", "w") as f:
        f.write(pyrosetta_script)
    print("  - flexpep_pyrosetta.py (PyRosetta)")

    # 3. Bash wrapper
    bash_script = generate_bash_wrapper(config, output_dir)
    with open(output_dir / "run_flexpep.sh", "w") as f:
        f.write(bash_script)
    (output_dir / "run_flexpep.sh").chmod(0o755)
    print("  - run_flexpep.sh (wrapper script)")

    # 4. Generate placeholder peptide PDB
    generate_peptide_pdb(peptide_sequence, output_dir / "peptide.pdb")
    print("  - peptide.pdb (placeholder - replace with AlphaFold2)")

    # 5. Configuration JSON
    config_dict = {
        "peptide_id": peptide_id,
        "peptide_sequence": peptide_sequence,
        "receptor_pdb": receptor_pdb,
        "config": asdict(config),
        "output_directory": str(output_dir),
        "generated": datetime.now().isoformat(),
        "files": [
            "flexpep_protocol.xml",
            "flexpep_pyrosetta.py",
            "run_flexpep.sh",
            "peptide.pdb"
        ]
    }

    with open(output_dir / "flexpep_config.json", "w") as f:
        json.dump(config_dict, f, indent=2)

    print(f"\nConfiguration saved: {output_dir / 'flexpep_config.json'}")

    return config_dict


def run_demo():
    """Run a demonstration of FlexPepDock setup."""
    print("=" * 70)
    print("M4 PyRosetta FlexPepDock - DEMONSTRATION")
    print("=" * 70)
    print()
    print("This pipeline implements induced-fit peptide docking using")
    print("Rosetta's FlexPepDock protocol for peptide-receptor modeling.")
    print()
    print("PHYSICS:")
    print("  - REF2015 energy function (Rosetta's latest)")
    print("  - Full peptide backbone flexibility")
    print("  - Receptor flexibility near binding interface")
    print("  - Monte Carlo + gradient minimization")
    print()
    print("METHODOLOGY:")
    print("  - Low-resolution centroid docking phase")
    print("  - High-resolution all-atom refinement")
    print("  - Side-chain repacking at interface")
    print("  - Interface energy analysis (ΔGinterface)")
    print()

    # Demo with top peptide candidate
    demo_peptide = {
        "peptide_id": "METAB_GLP1R_002",
        "sequence": "HAEGTFTSDVSSYLEGQAAKEFIAWLVKGR",
        "receptor": "GLP1R_6X18.pdb"
    }

    output_base = Path(__file__).parent / "flexpep_simulations"

    summary = setup_flexpep_pipeline(
        peptide_id=demo_peptide["peptide_id"],
        peptide_sequence=demo_peptide["sequence"],
        receptor_pdb=demo_peptide["receptor"],
        output_base=output_base
    )

    print()
    print("=" * 70)
    print("NEXT STEPS")
    print("=" * 70)
    print()
    print("1. Obtain receptor PDB structure (e.g., PDB: 6X18 for GLP-1R)")
    print("2. Replace placeholder peptide.pdb with AlphaFold2 structure")
    print("3. Position peptide near binding site (use pymol or manual)")
    print("4. Run: ./run_flexpep.sh")
    print()
    print("REQUIREMENTS:")
    print("  - PyRosetta: pip install pyrosetta-installer")
    print("    then: python -c \"import pyrosetta_installer; pyrosetta_installer.install_pyrosetta()\"")
    print("  - OR Rosetta Suite (academic license required)")
    print()
    print("OUTPUT:")
    print("  - models/model_XXXX.pdb - Docked complexes")
    print("  - docking_summary.json - Scores and rankings")
    print()

    return summary


if __name__ == "__main__":
    run_demo()
