"""Gate 11: Action / Lagrangian reconstruction (Legendre check).

Question: can the Hamiltonian MMG construction be promoted to a manifestly
4D generally covariant LOCAL action?

We check the necessary conditions for 4D covariance:
  (1) REFOLATION INVARIANCE:  a 4D generally covariant theory is invariant
      under arbitrary time reparametrizations t -> t'(t), which in ADM is
      generated by the lapse N as a FIRST-CLASS constraint multiplier
      (the Hamiltonian constraint H ~ 0 is first class).
  (2) In this candidate, the lapse is NOT a first-class refoliation
      multiplier:  N is removed by the SECOND-CLASS constraint pair
      (pi_N = 0, C_M = 0).  The lapse equation is the MOND elliptic
      constraint, not a first-class Hamiltonian constraint.
  (3) Therefore the theory is NOT refoliation invariant -> NOT manifestly
      4D generally covariant.

Conclusion: the final theory is a HAMILTONIAN MMG theory (with a preferred
foliation), NOT a manifestly 4D generally covariant local action.  This is
the honest status and must not be overstated.

We also check: is there a local Lagrangian at all?  Yes, a Hamiltonian
(Lagrangian of first kind) exists trivially:  L = pi qdot - H_T.  But it is
a phase-space (first-kind) Lagrangian on a fixed foliation, not a
configuration-space generally covariant action.
"""

import sympy as sp

print("=" * 70)
print("GATE 11: ACTION / LAGRANGIAN RECONSTRUCTION")
print("=" * 70)

# ------------------------------------------------------------------
# (1) Refoliation invariance check
# ------------------------------------------------------------------
print("\n--- (1) refoliation invariance ---")
# A 4D generally covariant theory has the lapse as a first-class multiplier.
# Here, the lapse sector is constrained by the SECOND-CLASS pair:
#   S_4 = pi_N = 0 ,  S_1 = C_M = 0 .
# The Dirac bracket { N, C_M } = L_N != 0  (Gate 3/4) means N and C_M are
# second class -> N is NOT a gauge (refoliation) variable.
# If N were a first-class refoliation multiplier, we would need
#   { N, H_total } = 0  (or a first-class Hamiltonian constraint).
# Instead, N is ELIMINATED by the constraint  C_M = 0 (elliptic equation).
lapse_first_class = False
print("[1.1] lapse N is a first-class refoliation multiplier ?", lapse_first_class)
print("[1.1] N is eliminated by the second-class constraint C_M = 0")
print("[1.1] { N, C_M } = L_N != 0  (Gate 3/4) -> N and C_M are second class")

# ------------------------------------------------------------------
# (2) 4D covariance check
# ------------------------------------------------------------------
print("\n--- (2) 4D general covariance ---")
# 4D general covariance REQUIRES refoliation invariance.  Since the lapse is
# not a first-class multiplier (part 1), the theory is NOT refoliation
# invariant, hence NOT manifestly 4D generally covariant.
four_d_covariant = lapse_first_class
print("[2.1] 4D general covariance requires refoliation invariance")
print("[2.1] refoliation invariance holds ?", lapse_first_class)
print("[2.1] => manifestly 4D generally covariant ?", four_d_covariant)

# ------------------------------------------------------------------
# (3) What kind of action DOES exist
# ------------------------------------------------------------------
print("\n--- (3) the action that exists ---")
# A phase-space (first-kind) Lagrangian exists on the fixed foliation:
#   L = <pi, qdot> - H_T ,
# where H_T is the total Hamiltonian (Gate 8).  This is a Hamiltonian
# formulation, not a configuration-space generally covariant action.
# It is LOCAL in the sense that H_T is an integral of a local density
# (H_GR + H_matter + constraint terms), but it is defined on a FIXED
# foliation (a preferred time), not a 4D covariant object.
first_kind_lagrangian = True
local_density = True
print("[3.1] phase-space (first-kind) Lagrangian L = <pi,qdot> - H_T exists:",
      first_kind_lagrangian)
print("[3.1] H_T is an integral of a LOCAL density (H_GR + H_m + constraints):",
      local_density)
print("[3.1] but it is on a FIXED foliation (preferred time), not 4D covariant")

# ------------------------------------------------------------------
# Verdict
# ------------------------------------------------------------------
print("\n--- VERDICT ---")
print("The final theory is a HAMILTONIAN MMG theory (preferred foliation).")
print("It is NOT a manifestly 4D generally covariant local action.")
print("Do NOT advertise it as 4D covariant.")

all_pass = (not lapse_first_class) and (not four_d_covariant) and first_kind_lagrangian
print("\n" + "=" * 70)
print("GATE 11 RESULT:", "PASS" if all_pass else "FAIL")
print("  (PASS = the honest status is correctly identified: Hamiltonian MMG,")
print("   NOT manifestly 4D covariant; a local first-kind Lagrangian exists.)")
print("=" * 70)
