"""Refresh explicit pinned local dependencies; use before, not during, the run."""
from pathlib import Path
import hashlib,json,subprocess
root=Path.cwd();folder=Path('sol61_push/recombination_and_structure_growth/new_doors_2026_10_05/transfer_null_test');site=Path('fable_independent_2026/L183_class_mond_kernel/site/classy')
files=[folder/'transfer_checks.py',site/'__init__.py',site/'_classy.cpython-313-darwin.so',site/'python/classy.pyx',site/'source/perturbations.c',site/'source/input.c',site/'include/precisions.h',site/'include/common.h',Path('sol61_push/recombination_and_structure_growth/growth_and_identity/REPORT.md'),Path('campaign_fresh_gravity/CFG345_cold_component_small_scales/README.md'),Path('campaign_fresh_gravity/CFG345_cold_component_small_scales/FROZEN_CRITERIA.md'),Path('campaign_fresh_gravity/CFG345_cold_component_small_scales/cfg345_small_scales.py')]
# CFG345 name can differ: pin the actual read path.
files=[p for p in files if p.exists()]
files+=sorted((folder/'sources').glob('*'))
records=[]
for p in files:
    records.append({'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
sources={'start_HEAD':'614eab208a205314e7076c4edfe018c9b78e47f7','HEAD_at_contract':subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip(),'requested_base':'11b994fee','local_CLASS':'v3.3.4, L183 patched binary, mond_a0=0; upstream build commit unknown; content hashes authenticate local binary/source, not a fresh upstream build','python_executable':{'path':'/opt/homebrew/Caskroom/miniconda/base/bin/python3.13','sha256':hashlib.sha256(Path('/opt/homebrew/Caskroom/miniconda/base/bin/python3.13').read_bytes()).hexdigest(),'version':subprocess.check_output(['/opt/homebrew/Caskroom/miniconda/base/bin/python3.13','--version'],text=True).strip()},'sources':[{'url':'https://arxiv.org/pdf/astro-ph/0003365v2','version':'astro-ph/0003365v2, 26 March 2000','claims':'effective cold-wave sound speed eq7; HBG cutoff eq8-9 previously provisional is authenticated; not used to generate this transfer run'},{'url':'https://arxiv.org/pdf/astro-ph/9506072v1','version':'astro-ph/9506072v1','claims':'Newtonian baryon/CDM continuity/Euler eq43 and67; velocity convention and parallel gas/Thomson terms'},{'url':'https://github.com/lesgourg/class_public','version':'official project pointer only; runtime local CLASS binary content-pinned separately','claims':'CLASS provenance; do not equate moving master with local patched build'}],'files':records}
(folder/'sources.json').write_text(json.dumps(sources,indent=2)+'\n')
inputs=[str(p) for p in files]+[str(folder/'sources.json')]
c={'claim_id':'SOL61-REAL-CLASS-RELATIVE-TRANSFER-NULL','mathematics':{'assertion_tested':'Integrate actual CLASS density/velocity baryon-minus-cold Euler source; distinguish restricted wave/gas/gate templates over multiple k/epochs while demonstrating initial-U and force degeneracies','coefficient_domain':'binary64 CLASS transfer solve and trapezoid integration; EdS identities derived independently in report','conventions':'Newtonian gauge, c=1 with H in1/Mpc, k converted fromh/Mpc; U=-a(theta_b-theta_c); mond_a0=0, no massive neutrinos, no perturbed recombination; standard baryon sound speed approximation','inputs':inputs,'bounds':{'z':[19,99],'epochs_fine':601,'epochs_coarse':301,'kmax_Mpc_inverse':10,'k_picks':[.01,.03,.1,.3,1,3,8],'tol_perturbations_integration':1e-9,'perturbations_sampling_stepsize':.02,'mass_eV':[1e-22,2e-20,2e-19],'forecast_epochs':'three loga-spaced epochs; seven k; deterministic equal-independent-noise design only'},'non_claims':['Not full wave transfer through radiation era','No observation likelihood or achievable survey noise forecast','k4 pressure not unique microscopic identity','Cold transfer reconstruction depends on gravitational/tracer model','EdS projection instantaneous; real CLASS future not exactEdS','Declaration is explicit local dependency pinning, not full dynamic-library/environment closure']},'execution_artifacts':inputs,'software':[{'name':'child Python','version':subprocess.check_output(['/opt/homebrew/Caskroom/miniconda/base/bin/python3.13','--version'],text=True).strip()},{'name':'CLASS','version':'v3.3.4 L183 local patched binary; mond_a0=0'},{'name':'NumPy','version':'1.26.4'},{'name':'SciPy','version':'1.14.1'}],'randomness':{'used':False,'generator':'','seed':None}}
(folder/'contract.json').write_text(json.dumps(c,indent=2)+'\n')
