#!/usr/bin/env python3
"""Exact MOND versus tensor-luminality no-go for curvature-sourced QUMOND.

The calculation concerns the one action

    S = (16 pi G)^-1 int sqrt(-g) [R - 2 Lambda
        - 2 lambda (Delta_h chi - R_nn) + 2 a0^2 Q(Y)] + S_m[g,psi],

with ``Y=h^mn nabla_m chi nabla_n chi/a0^2``.  Requiring the exact
exponential MOND law fixes ``2 Q_Y=exp(-sqrt(Y))``.  The radial chi equation
then fixes the multiplier gradient on the regular, source-free auxiliary
branch.  Independently, the TT principal action fixes the local graviton
speed.  The two equations are incompatible at every finite nonzero MOND
gradient if the physical metric light cone is required exactly.

This is deliberately narrower than a universal relativistic-MOND no-go.  It
does not use the disputed nonlinear no-slip inference or decide whether the
quadratic scalar pole is an allowed clock mode.
"""

from __future__ import annotations

from typing import Any

import sympy as sp


def _euler_radial(
    density: sp.Expr, field: sp.Expr, radius: sp.Symbol
) -> sp.Expr:
    """Euler derivative for a one-dimensional radial reduced density."""

    return sp.simplify(
        sp.diff(density, field)
        - sp.diff(sp.diff(density, sp.diff(field, radius)), radius)
    )


def derive_luminality_no_go() -> dict[str, Any]:
    """Generate the constitutive, radial, and TT characteristic equations."""

    y = sp.symbols("y", positive=True, finite=True, real=True)
    Y = sp.symbols("Y", positive=True, finite=True, real=True)
    a0 = sp.symbols("a0", positive=True, finite=True, real=True)

    mu = 1 - sp.exp(-y)
    Q_of_y = 1 - (1 + y) * sp.exp(-y)
    Q_Y = sp.simplify(sp.diff(Q_of_y, y) / (2 * y))
    exact_law_residual = sp.simplify(2 * Q_Y - (1 - mu))

    # Vary the radial reduction before integrating its chi equation.  The
    # positive-gradient chart is sufficient because y=|chi'|/a0 and the
    # opposite orientation changes both radial derivatives together.
    r = sp.symbols("r", positive=True, finite=True, real=True)
    chi = sp.Function("chi")(r)
    phi = sp.Function("Phi")(r)
    lam = sp.Function("lambda")(r)
    chi_r = sp.diff(chi, r)
    local_y = chi_r / a0
    local_Q = 1 - (1 + local_y) * sp.exp(-local_y)
    radial_density = sp.expand(
        2 * r**2 * sp.diff(lam, r) * (chi_r - sp.diff(phi, r))
        + 2 * r**2 * a0**2 * local_Q
    )
    chi_euler = sp.factor(_euler_radial(radial_density, chi, r))
    expected_chi_euler = sp.factor(
        -2
        * sp.diff(
            r**2 * (sp.diff(lam, r) + sp.exp(-local_y) * chi_r),
            r,
        )
    )
    chi_euler_residual = sp.simplify(chi_euler - expected_chi_euler)

    # The integrated radial equation has an auxiliary-flux constant C.  A
    # regular centre with finite y cannot support its C/r^2 singularity, so C
    # is generated by solving the vanishing singular-coefficient condition.
    flux_constant = sp.symbols("C_aux", finite=True, real=True)
    lambda_r_general = flux_constant / r**2 - a0 * y * sp.exp(-y)
    singular_coefficient = sp.limit(r**2 * lambda_r_general, r, 0, dir="+")
    regular_flux_constant = sp.solve(
        sp.Eq(singular_coefficient, 0), flux_constant
    )[0]
    lambda_radial_derivative = sp.simplify(
        lambda_r_general.subs(flux_constant, regular_flux_constant)
    )

    # ADM decomposition of the same action gives
    # (1-2 lambda)(K_ij K^ij-K^2)+2K L_n lambda.  A TT perturbation has K=0,
    # so the mixed trace term drops out.  The Einstein-Hilbert R^(3) term is
    # untouched and supplies the unit spatial-gradient coefficient.
    lambda_value = sp.symbols("lambda", finite=True, real=True)
    tensor_velocity, tensor_gradient = sp.symbols(
        "h_TT_dot h_TT_gradient", finite=True, real=True
    )
    tensor_principal_density = (
        (1 - 2 * lambda_value) * tensor_velocity**2 / 2
        - tensor_gradient**2 / 2
    )
    kinetic_coefficient = sp.diff(
        tensor_principal_density, tensor_velocity, 2
    )
    gradient_coefficient = -sp.diff(
        tensor_principal_density, tensor_gradient, 2
    )
    c_t_squared = sp.simplify(gradient_coefficient / kinetic_coefficient)
    luminal_lambda_solutions = sp.solve(
        sp.Eq(c_t_squared, 1), lambda_value
    )

    # Exact local luminality on an open radial MOND branch requires lambda=0
    # pointwise, hence lambda'=0.  The independently varied chi equation says
    # lambda'=-a0*y*exp(-y), which is strictly negative for finite y>0.
    luminality_implied_lambda_derivative = sp.diff(sp.Integer(0), r)
    derivative_contradiction = sp.simplify(
        lambda_radial_derivative - luminality_implied_lambda_derivative
    )

    return {
        "action": (
            "(16 pi G)^-1 int sqrt(-g)[R-2 Lambda"
            "-2 lambda(Delta_h chi-R_nn)+2 a0^2 Q(Y)] + S_m[g,psi]"
        ),
        "constitutive": {
            "y": y,
            "Y": Y,
            "mu": mu,
            "Q_of_y": Q_of_y,
            "Q_Y": Q_Y,
            "exact_law_residual": exact_law_residual,
        },
        "static_spherical_branch": {
            "radial_density": radial_density,
            "chi_euler": chi_euler,
            "expected_chi_euler": expected_chi_euler,
            "chi_euler_residual": chi_euler_residual,
            "flux_constant": flux_constant,
            "singular_coefficient": singular_coefficient,
            "regular_flux_constant": regular_flux_constant,
            "lambda_radial_derivative": lambda_radial_derivative,
            "lambda_radial_derivative_nonzero": bool(
                lambda_radial_derivative.is_nonzero
            ),
            "branch_assumptions": (
                "spherical positive-gradient chart, finite y>0, regular centre, "
                "no singular auxiliary charge"
            ),
        },
        "tensor_principal_part": {
            "lambda": lambda_value,
            "principal_density": tensor_principal_density,
            "kinetic_coefficient": kinetic_coefficient,
            "gradient_coefficient": gradient_coefficient,
            "c_T_squared": c_t_squared,
            "luminal_lambda_solutions": luminal_lambda_solutions,
            "positive_kinetic_condition": sp.Gt(kinetic_coefficient, 0),
        },
        "obstruction": {
            "luminality_implied_lambda_derivative": (
                luminality_implied_lambda_derivative
            ),
            "mond_implied_lambda_derivative": lambda_radial_derivative,
            "derivative_contradiction": derivative_contradiction,
            "contradiction_nonzero": bool(derivative_contradiction.is_nonzero),
        },
        "scope": (
            "No-go for the displayed scalar curvature-sourced elliptic action "
            "on a regular finite-y spherical MOND branch with exact physical-"
            "metric tensor luminality; not a universal MOND no-go."
        ),
    }


def main() -> int:
    result = derive_luminality_no_go()
    constitutive = result["constitutive"]
    static = result["static_spherical_branch"]
    tensor = result["tensor_principal_part"]
    obstruction = result["obstruction"]

    print("=" * 92)
    print("CURVATURE-QUMOND EXACT MOND / TENSOR-LUMINOSITY NO-GO")
    print("=" * 92)
    print("Action:", result["action"])
    print("\n[1] Exact constitutive law")
    print("  mu(y) =", constitutive["mu"])
    print("  Q(y^2) =", constitutive["Q_of_y"])
    print("  2 Q_Y-(1-mu) =", constitutive["exact_law_residual"])
    print("\n[2] Varied regular spherical chi equation")
    print("  delta S/dchi =", static["chi_euler"])
    print("  Euler residual =", static["chi_euler_residual"])
    print("  integrated singular coefficient =", static["singular_coefficient"])
    print("  regular auxiliary flux constant =", static["regular_flux_constant"])
    print("  MOND branch lambda' =", static["lambda_radial_derivative"])
    print("\n[3] TT characteristic from the same ADM action")
    print("  L_TT,principal =", tensor["principal_density"])
    print("  tensor kinetic coefficient =", tensor["kinetic_coefficient"])
    print("  tensor gradient coefficient =", tensor["gradient_coefficient"])
    print("  c_T^2 =", tensor["c_T_squared"])
    print("  solve(c_T^2=1, lambda) =", tensor["luminal_lambda_solutions"])
    print("\n[4] Pointwise incompatibility")
    print(
        "  exact luminality implies lambda' =",
        obstruction["luminality_implied_lambda_derivative"],
    )
    print(
        "  exact MOND implies lambda' =",
        obstruction["mond_implied_lambda_derivative"],
    )
    print("  contradiction =", obstruction["derivative_contradiction"])

    checks = (
        constitutive["exact_law_residual"] == 0,
        static["chi_euler_residual"] == 0,
        static["regular_flux_constant"] == 0,
        static["lambda_radial_derivative_nonzero"],
        tensor["luminal_lambda_solutions"] == [0],
        obstruction["contradiction_nonzero"],
    )
    print("\n[VERDICT]")
    print(
        "  DEAD within the stated action class: a regular finite-y MOND branch "
        "requires nonconstant lambda,"
    )
    print(
        "  while exact tensor luminality relative to the minimally coupled "
        "physical metric requires lambda=0 pointwise."
    )
    print(
        "  This result does not rely on the incomplete nonlinear no-slip "
        "calculation or on classifying the clock scalar."
    )
    print(f"  Generated checks: {sum(checks)}/{len(checks)}")
    return 0 if all(checks) else 1


if __name__ == "__main__":
    raise SystemExit(main())
