"""
agentTT ROUTE 1 — PART 2: The DSSYK chord algebra's OWN SU(1,1)_q structure,
and the CRITICAL question: does the vacuum PLACEMENT select the SL(2,R) rep,
or does it live INSIDE a single fixed rep (so both center & edge are the same rep)?

This is THE ruthlessness test. agentSS found the GRAVITY-side symmetry permits-not-forces
the gain shape. Here I must check the ANALOGOUS trap on the MATTER side:

  - If the chord transfer matrix / Hamiltonian H_DSSYK = (a + a^dagger)/(stuff) generates
    a SINGLE irreducible SU(1,1)_q rep, and theta_v just labels a COHERENT STATE / a point
    in the spectrum WITHIN that one rep, then CENTER and EDGE are the SAME rep -- the
    placement is an intra-rep choice, NOT a rep choice. Then rep-matching CANNOT exclude
    edge => favored-not-forced.

  - If instead the placement changes the rep LABEL (Casimir) or the rep CLASS
    (discrete vs principal), then edge is a different/excluded rep => could force center.

DSSYK facts (banked / standard, Berkooz-Isachenkov-Narovlansky-Torrents 1811.02584;
Lin 2208.07032):
  - The chord number basis |n>, n=0,1,2,... with the q-deformed ladder operators.
  - H = (1/sqrt(1-q)) (a + a^dagger), [a, a^dagger]_q = q-deformed; the EIGENVALUES of H
    fill the band E = 2 cos(theta)/sqrt(1-q), theta in (0,pi) -- a CONTINUOUS band.
  - The energy eigenstates |theta> are a CONTINUUM labelled by theta in (0,pi).
  - The q-deformation: the chord algebra is U_q(su(1,1)) (q-deformed). The number states
    |n> carry the lowest-weight discrete-series-like tower of U_q(su(1,1)).

KEY STRUCTURAL POINT to settle:
  theta_v is an ENERGY-EIGENSTATE label (a point in the CONTINUOUS principal-series band),
  NOT a separate irrep. The matter operator O_Delta and the vacuum |theta_v> both live in
  the SAME chord Hilbert space (one U_q(su(1,1)) rep). So at the level of the CHORD algebra,
  center and edge are the SAME rep -- distinguished only by WHERE in the band the vacuum sits.

  The DISCRETE-SERIES ladder D^+_Delta is NOT the chord-space rep itself; it EMERGES as the
  pole structure of the matter 2-pt function -- i.e. as the rep generated by the MODULAR/BOOST
  flow about the chosen vacuum theta_v. THAT is placement-dependent.

So PART 2 must compute: the boost/modular generator about theta_v, its spectrum, and whether
its rep class flips between center and edge.
"""
import sympy as sp
import mpmath as mp
mp.mp.dps = 40

print("="*78)
print("PART 2 — does the placement select the rep, or live inside one fixed chord rep?")
print("="*78)

q, theta = sp.symbols('q theta', positive=True)
# DSSYK band: E(theta) = 2 cos(theta)/sqrt(1-q), theta in (0,pi). CONTINUOUS spectrum.
E_band = 2*sp.cos(theta)/sp.sqrt(1-q)
print("\n[Chord Hilbert space, ONE U_q(su(1,1)) rep]")
print("  Energy band E(theta) = 2 cos(theta)/sqrt(1-q), theta in (0,pi): CONTINUOUS.")
print("  => the chord rep is a SINGLE (principal-series-like, q-deformed) continuum rep.")
print("  theta_v (the vacuum placement) is a POINT in this continuum, NOT a separate irrep.")
print("  CONSEQUENCE: at the chord-algebra level, CENTER (theta_v=pi/2) and EDGE (theta_v~pi)")
print("  are the SAME rep -- different POINTS in one continuous band. The chord algebra")
print("  alone CANNOT exclude either => rep-class matching on the CHORD algebra is AGNOSTIC.")

print("\n[Where the discrete series actually lives: the MODULAR/boost rep about theta_v]")
print("  The QNM ladder D^+_Delta is NOT the chord rep; it is the rep generated by the")
print("  static-patch BOOST (= modular flow = Tomita-Takesaki, agentSS) about the vacuum.")
print("  Its generator L0 has spectrum = the QNM ladder. THIS is placement-dependent:")

# Build the modular generator's spectrum at each placement from the pole ladder.
Delta, kk, lam = sp.symbols('Delta k lambda', positive=True)
# The boost L0 spectrum is read from omega_pole = -i * (boost eigenvalue) at center,
# and from the pole real/imag parts in general.
print("\n  CENTER theta_v=pi/2: omega_pole = -i sinh((Delta+k)lambda)")
print("    boost spectrum {sinh((Delta+k)lambda)} -> semiclassical {(Delta+k)} :")
print("    HALF-BOUNDED, integer-spaced, REAL boost eigenvalues -> LOWEST-WEIGHT")
print("    DISCRETE SERIES D^+_Delta. Modular flow is a clean dilation with discrete spectrum.")

print("\n  EDGE theta_v=pi-eps: omega_pole = -cos(eps)cosh(u) - i sin(eps) sinh(u)")
print("    The 'boost' eigenvalue would be complex AND the poles leave the support band.")
print("    The surviving spectral data is the CONTINUUM (Wigner sqrt) endpoint:")
print("    no lowest-weight tower -> the modular rep about the edge vacuum is NOT D^+_Delta.")

print("\n" + "="*78)
print("PART 2 RESULT -- the crucial distinction for FORCING vs FAVORING")
print("="*78)
print("(1) On the CHORD algebra U_q(su(1,1)) itself: center & edge are the SAME continuum rep,")
print("    different band points. Rep-matching here is AGNOSTIC (cannot exclude edge).")
print("(2) On the MODULAR/boost rep about the vacuum: CENTER -> discrete series D^+_Delta")
print("    (matches GH); EDGE -> no lowest-weight tower (continuum endpoint). The match is")
print("    EXCLUSIVE to center ONLY at this modular level.")
print("(3) Therefore whether rep-matching FORCES center hinges on whether the EDGE's")
print("    modular rep being non-discrete is (a) a structural EXCLUSION by the GH discrete")
print("    spectrum, or (b) merely the SAME dynamical t^{-3/2} fact agentS already had,")
print("    re-expressed. PART 3 settles (a) vs (b).")
