#!/usr/bin/env python3
"""
agentZZ STAGE 5 — consolidated coarse-graining ledger + final verdict (JOINED/PARTIAL/FAILS).

Closes three loose ends rigorously:
  (5A) Does the coarse-grained scalar's deep-MOND coefficient MATCH AeST's (2/3) normalization
       AND give the correct deep-MOND rotation law v^4=GMa0?  (sympy, end to end)
  (5B) The F^2 aether-kinetic and K(Q) cosmology terms: produced or not? (the gap)
  (5C) The directionality of the conjecture: which way does the implication run, and what
       grade does that earn (JOINED vs PARTIAL vs FAILS)?
"""
import sympy as sp

print("="*78)
print("STAGE 5: consolidated ledger + verdict")
print("="*78)

# ---- (5A) deep-MOND coefficient + rotation law from the coarse-grained scalar ----
print("\n[5A] Deep-MOND closure of the coarse-grained scalar (AQUAL), end-to-end:")
G, M, a0, r = sp.symbols('G M a_0 r', positive=True)
# AQUAL deep-MOND: div(|grad phi|/a0 grad phi) = 4 pi G rho. For a point mass, spherical:
# (1/r^2) d/dr( r^2 (|phi'|/a0) phi' ) = 4 pi G M delta -> integrate: (phi'^2/a0) r^2 = G M
# (Gauss law with enclosed mass M). So phi'^2 = G M a0 / r^2 => phi' = sqrt(GMa0)/r.
phip = sp.sqrt(G*M*a0)/r
# circular speed: v^2/r = |grad phi| = phi'  => v^2 = r*phip = sqrt(GMa0)
v2 = sp.simplify(r*phip)
v4 = sp.simplify(v2**2)
print("   point-mass deep-MOND: phi'(r) = sqrt(GMa0)/r ; v^2 = r*phi' =", v2)
print("   v^4 =", v4, "  =>  v^4 = G M a0  (the deep-MOND/BTFR law). CORRECT.")
# Coefficient: the Lagrangian f(y)=(2/3)y^{3/2}; AeST Eq(2) J(Y)->(2 lam_s/(3(1+lam_s)a0))Y^{3/2}.
# In the single-field (lam_s->inf, screening) limit J->(2/(3 a0))Y^{3/2}: the (2/3) and 1/a0 match.
lam_s = sp.symbols('lambda_s', positive=True)
coeff_aest = 2*lam_s/(3*(1+lam_s))   # times (1/a0) Y^{3/2}
coeff_screen = sp.limit(coeff_aest, lam_s, sp.oo)
print("   AeST Eq(2) coeff of (1/a0)Y^{3/2}: 2 lam_s/(3(1+lam_s)); screening lam_s->inf:", coeff_screen)
print("   coarse-grained AQUAL f(y)=(2/3)y^{3/2} => coeff 2/3. MATCH in the screening limit.")
print("   => FORM and the (2/3) normalization match; a0 itself is route-degenerate (prior result).")

# ---- (5B) the two missing terms ----
print("""
[5B] The two AeST terms the worldline coarse-graining does NOT produce:
   (i)  -(K_B/2) F^{mn}F_{mn}  (aether kinetic): the worldline treats u^mu as a FIXED bath
        label; there is no (grad A)^2 dynamics generated. AeST PUTS this term in by hand to
        give the aether propagating dynamics + ensure c_GW=c. The coarse-graining does not
        supply K_B. => the aether KINETIC sector is an INPUT to AeST, not an output of the MI EFT.
   (ii) F(Y,Q)|_Q-sector, K(Q)=-2Lam+K2(Q-Q0)^2 (cosmology/CDM-like dust): the worldline MI
        sector is the SPATIAL (Y) sector. The TEMPORAL Q-sector (the a^-3 dust mode that makes
        the CMB work) is a SEPARATE shift-symmetric k-essence posit in AeST too (their Eq 3-4,
        'the Higgs phase'). The MI coarse-graining produces NEITHER Lambda NOR the dust mode.
   => Two of AeST's load-bearing sectors (the aether propagator, the CDM-mimicking cosmology)
      are NOT generated by the worldline MI. They are AeST's own posits.
""")

# ---- (5C) directionality + grade ----
print("[5C] Directionality of the conjecture and the grade:")
print("""
   The conjecture: 'AeST is the PASSIVE/LOCAL coarse-grained EFT of the in-in worldline MI;
   the in-in action is the ACTIVE/NONLOCAL completion.'

   What the calculation establishes (BOTH WAYS):

   IN FAVOR (the structural match is REAL, credit at full weight):
    - The field content is FORCED and MATCHES: g (background), A_mu unit-timelike (Deser-Levin
      forces the dS rest frame), phi shift-symmetric (Hubbard-Stratonovich of the bath kernel).
    - The deep-MOND Y^{3/2} term with the (2/3)/a0 coefficient is reproduced (form + normalization).
    - The frame-orthogonal projector q=g+AA (=> Y reads SPATIAL gradients, CMB-safe q^00=0) is
      exactly what 'accel measured in the cosmic rest frame' gives.
    - The scalar-aether mixing (Eq6 grad Psi.grad phi) emerges in the quasi-static limit.
    => This is a genuine PARTIAL structural join: AeST's galaxy sector field-content + MOND term
       is the natural passive truncation of the MI worldline EFT.

   AGAINST a FULL join (do NOT manufacture it):
    - PASSIVITY OBSTRUCTION (rigorous, two-channel): the MI kernel mu_fw(0)=0<mu_fw(inf)=1
      VIOLATES the passive-vacuum sum rule => the in-in MI is IRREDUCIBLY ACTIVE. AeST is
      passive (conserved symmetric stress, by its action's structure). An active theory's
      coarse-grained EFT is the time-symmetric truncation of itself, NOT a different passive
      Lagrangian that equals it. So AeST != the MI theory; AeST is a passive APPROXIMATION
      that DROPS the active/noise content carrying the MI-distinctive physics.
    - CASSINI: MI and AeST(MG) give DIFFERENT Solar-System predictions (7e-7 vs 1e-3 at Saturn);
      a real identity of theories would give identical predictions. They are observably distinct.
    - TWO MISSING SECTORS: the aether kinetic F^2 (K_B) and the cosmological K(Q) are NOT
      produced by the coarse-graining; they are AeST's own posits.
    - The coefficient a0 is NOT forced by the coarse-graining (route-degenerate; prior corpus result).

   GRADE: **PARTIAL** — a real structural match (field content + Y^{3/2} + q-projector + the
   quasi-static mixing) with THREE hard gaps (the passivity/active obstruction is the decisive
   one; the missing F^2 and K(Q) sectors; the unforced a0). The two pillars are NOT joined into
   ONE theory: AeST is the PASSIVE/LOCAL/MG cousin that shares the galaxy-sector field content and
   MOND term, but it is NOT the EFT of the (active, MI) worldline dynamics — it is a different
   theory that agrees in the galaxy quasi-static limit and disagrees where the MI content lives
   (Solar System, the active kernel, the sigma-spread/EFE). The conjecture is REFUTED as an
   IDENTITY and SUPPORTED as a STRUCTURAL ANALOGY.
""")
