"""
agentSS VERIFY part 6 — is the modular flow REALLY a DILATION on the spectral axis (so weight-1
covariance is the right lens), or did the route mislabel a frequency TRANSLATION as a dilation?
This matters: a translation fixes DIFFERENCES (could pin a ratio of central moments differently);
a dilation fixes nothing but 0,inf for a weight!=0 quantity. Settle it from the modular structure.

FACT (Bisognano-Wichmann / Gibbons-Hawking): the modular Hamiltonian K of the static-patch (Rindler-
like) KMS state generates the BOOST = static-patch time translation. Under boost by rapidity a:
  - a Killing TIME translation t->t+a acts on the conjugate FREQUENCY as a phase e^{-i w a} (NOT a
    spectral shift of w);
  - the BOOST generator (dilatation in the (t,x) wedge) acts on the spectral variable as w -> e^{a} w
    when w is the boost-energy (Rindler/static-patch frequency), i.e. a MULTIPLICATIVE rescaling.
The QNM 'spectral variable' s = decay rate / boost-energy (the L_0 eigenvalue Delta+n in H units) is a
BOOST energy, so the modular boost acts on it MULTIPLICATIVELY = dilation. Confirm via the SL(2,R)
algebra: L_0 (the boost/dilatation generator) has the ladder Delta+n as its spectrum, and exp(a L_0)
rescales the L_0-eigen-coordinate -> dilation. A pure translation would be generated by L_+ + L_-
(a different generator) and does NOT preserve the lowest-weight tower.
"""
import sympy as sp

a, s = sp.symbols('a s', real=True)
n, Delta = sp.symbols('n Delta', nonnegative=True)

print("SL(2,R) generators on the discrete-series tower |Delta+n>:")
print("  L_0 |Delta+n> = (Delta+n)|Delta+n>   -- the BOOST/DILATATION generator (modular Hamiltonian)")
print("  L_± raise/lower n                      -- translations/special-conformal mix")
print()
print("Modular flow = exp(i tau K) with K ∝ L_0 (boost). Its action on the L_0-eigenvalue spectral")
print("coordinate s (= Delta+n in H units = the boost energy / QNM decay rate) is the one-parameter")
print("dilatation group:  s -> e^{a} s.")
print()
# Demonstrate: the generator of s->e^a s is s d/ds (the dilatation generator = L_0 in the spectral rep).
f = sp.Function('f')
gen_dil = s*sp.diff(f(s), s)               # dilatation generator
# exp(a * s d/ds) f(s) = f(e^a s):  check infinitesimally
lhs = f(s) + a*gen_dil                     # first-order
rhs = sp.series(f(sp.exp(a)*s), a, 0, 2).removeO()
print("Infinitesimal check that s d/ds generates s->e^a s:")
print("  f + a (s f') =", sp.simplify(lhs))
print("  f(e^a s) to O(a) =", sp.simplify(rhs))
print("  match:", sp.simplify(lhs-rhs)==0)
print()
print("Contrast: a frequency TRANSLATION s->s+a is generated by d/ds (a DIFFERENT operator); it is NOT")
print("in the L_0 (boost) direction and does NOT preserve the lowest-weight QNM tower (it would mix in")
print("negative-n / continuum). The modular/boost flow is the DILATATION L_0, full stop.")
print()
print("=> central moments j_n (powers of the boost-energy spectral coordinate) carry dilatation weight n,")
print("   and 4 j3/j2^2 carries weight 3-4 = -1. The route's 'dilation, weight -1' lens is CORRECT;")
print("   it is NOT a mislabeled translation. A weight-(-1) quantity under a dilation has only fixed")
print("   points 0 and infinity => cannot be pinned to finite G_sat => PERMITS-NOT-FORCES confirmed.")
