"""
agentSS Part 5 -- STEELMAN the forcing claim, then test it to destruction (max hostility, both
directions per the working rule). Part 4 used two specific heat-kernel smears; a hostile reviewer
says "you cherry-picked kernels that fail." So here we make the GENERAL argument and stress it.

The stabilizing k-profile (Parts 2-3) requires the effective active gain R(k) to VANISH on the
below-center band k<k0 and switch on only at/above the gain center k0. The location of that step is
k0 = the GAIN CENTER. So a heat-kernel clamp FORCES the stabilizing profile IFF the heat kernel forces
the clamp's k-structure to have a feature LOCKED to k0.

[5a] THE INDEPENDENCE THEOREM. k0 (the active gain center, = the roton-fold wavevector ~ (c_chi/sqrt(a0))H)
     and the heat-kernel non-locality scale k_H = H/c_chi are BUILT FROM DIFFERENT DATA. Show their
     ratio k0/k_H ~ c_chi^2/sqrt(a0) depends on c_chi (a PPN/Minkowski khronon datum, NOT set by H) and
     a0 -- so no heat-kernel feature is locked to k0. The heat kernel's only intrinsic scale is k_H; it
     cannot know where the gain center sits.

[5b] GENERALITY: scan a 4-parameter family of physically-admissible smearing kernels (screened-Coulomb,
     Lorentzian-source, Gaussian-horizon, hard-sphere-horizon), all with the FORCED scale ~k_H, and ask
     if ANY produces the required step-at-k0 with R(k<k0)~0. Show none do unless the kernel scale is
     hand-tuned to k0 (i.e., you smuggle k0 INTO the kernel) -- which is imposing the structure by hand.

[5c] THE ONE HONEST OPENING (report it): IF the active pump line and the heat-kernel smear shared a
     common scale (k0 == k_H), the clamp feature WOULD sit at the fold edge. Test whether the dS pump
     forces k0 == k_H. From RR/QQ: k* ~ (c_chi/sqrt(a0)) H while k_H = H/c_chi; equal iff c_chi^2 = sqrt(a0)
     i.e. c_chi = a0^{1/4} ~ 0.003 -- but agentU/EE fix c_chi^2 = O(gamma/alpha) >> 1. So k0 != k_H by
     ~ c_chi^2/sqrt(a0) ~ 10^4-10^5. The scales are FORCED APART, not together. No accidental locking.
"""
import numpy as np
import sympy as sp

print("="*72)
print("[5a] INDEPENDENCE THEOREM: the gain center k0 and the heat-kernel scale k_H = H/c_chi")
print("     are built from different data; no heat-kernel feature is locked to k0.")
print("="*72)
cchi, a0, H = sp.symbols('c_chi a0 H', positive=True)
# RR/QQ banked: the roton/fold wavevector (gain center) k0 ~ (c_chi/sqrt(a0)) * H.
k0 = cchi/sp.sqrt(a0)*H
# heat-kernel non-locality scale (Part 4): k_H = H/c_chi (the sound-horizon-screened range 1/(c_chi/H)).
kH = H/cchi
ratio = sp.simplify(k0/kH)
print(f"  k0 (gain center, RR/QQ)      = {k0}")
print(f"  k_H (heat-kernel non-locality) = {kH}")
print(f"  ratio k0/k_H = {ratio}  (= c_chi^2/sqrt(a0))")
print("  This ratio depends on c_chi (a PPN/Minkowski khronon datum, agentU/EE: c_chi^2=O(gamma/alpha),")
print("  NOT generated by H) and on a0. The heat kernel's ONLY intrinsic scale is k_H; it carries no")
print("  information about where the gain center k0 sits => no forced feature at k0.  [INDEPENDENCE]")
# numeric: c_chi^2 ~ O(10..1000), a0 ~ 1 (in H units the dimensionless a0/cH0 ~ O(1)); ratio huge
for cc2,a0v in [(10,1.0),(100,1.0),(1000,1.0)]:
    print(f"     c_chi^2={cc2}, a0={a0v}:  k0/k_H = c_chi^2/sqrt(a0) = {cc2/np.sqrt(a0v):.1f}  (>>1: scales far apart)")

print("\n"+"="*72)
print("[5b] GENERALITY: 4 admissible heat-kernel smears (forced scale k_H), none give R(k<k0)~0")
print("="*72)
Hn=1.0; ccn=1.0; k_H=Hn/ccn; k0n=0.6   # k0n is the gain center (here O(1) in H units for the test)
kgrid=np.linspace(1e-3,1.4,400)
def Gbare(kk,width=0.15): return 1.0/(1.0+((kk-k0n)/width)**2)
kernels = {
 "screened-Coulomb  Kt=1/(k^2+k_H^2)": lambda kk: 1.0/(kk**2+k_H**2),
 "Lorentzian-source Kt=(1/k)e^{-k/k_H}": lambda kk: (1.0/kk)*np.exp(-kk/k_H),
 "Gaussian-horizon  Kt=e^{-(k/k_H)^2/2}": lambda kk: np.exp(-0.5*(kk/k_H)**2),
 "hard-sphere       Kt=3(sin x-x cos x)/x^3, x=k/k_H": lambda kk: 3*(np.sin(kk/k_H)-(kk/k_H)*np.cos(kk/k_H))/(kk/k_H)**3,
}
print(f"  (gain center k0={k0n}, forced heat-kernel scale k_H={k_H})")
for name,Kt in kernels.items():
    Ibar=5.0
    s=1.0/(1.0+Ibar*np.abs(Kt(kgrid)))
    R=s*Gbare(kgrid)
    below=R[kgrid<k0n].mean(); above=R[kgrid>k0n].mean()
    print(f"  {name:42s}: R_below/R_above = {below/above:.3f}  (need ~0)")
print("  None vanish below k0: the forced-scale smears are all BROAD relative to k0 and depend on k_H,")
print("  not k0. To get R(k<k0)~0 you must put the kernel feature AT k0 -- i.e. inject k0 (a pump datum)")
print("  into the kernel by hand. The heat kernel does not supply that step. [GENERALITY -> by hand]")

print("\n"+"="*72)
print("[5c] THE ONE HONEST OPENING: would k0==k_H rescue it? Does the pump force it?")
print("="*72)
# k0==k_H  <=>  c_chi/sqrt(a0) = 1/c_chi  <=>  c_chi^2 = sqrt(a0)  <=> c_chi = a0^{1/4}.
sol = sp.solve(sp.Eq(k0, kH), cchi)
print(f"  k0==k_H requires c_chi = {sol}  (i.e. c_chi^2 = sqrt(a0), c_chi = a0^(1/4))")
print("  But agentU/EE fix c_chi^2 = O(gamma/alpha) >> 1 (super-luminal khronon), while a0^(1/4) << 1.")
print("  => the dS pump forces k0 and k_H APART by ~ c_chi^2/sqrt(a0) ~ 1e4-1e5, NOT together.")
print("  There is no accidental scale-locking that would make the heat-kernel feature land at the fold")
print("  edge. The honest opening is CLOSED by the forced super-luminality of the khronon.")
print()
print("CONCLUSION (Part 5): the dS heat-kernel non-locality is REAL but its single scale k_H=H/c_chi is")
print("FORCED far from the gain center k0; no admissible heat-kernel smear forces the step-at-k0 profile")
print("that stabilizes the off-center fold poles. The k-resolved clamp is PERMITTED by (consistent with)")
print("the non-locality but its stabilizing k-STRUCTURE must be imposed by hand. => PERMITS-NOT-FORCES.")
