"""
agentTT ROUTE 1 — PART 3: THE DECISIVE (a)-vs-(b) TEST.

The static-patch boost generator B (= modular Hamiltonian = -ln Delta_mod /(2pi*T)) is a
FIXED operator on the chord Hilbert space: it is the generator of the static-patch
time-translation/dilation. agentSS: B IS the static-patch SL(2,R) L0, spectrum = the QNM ladder.

The vacuum |theta_v> is a state. The modular flow about a CHOSEN vacuum is generated by the
modular operator of the algebra in that vacuum. For a thermal (KMS) vacuum the modular flow IS
the boost. The QUESTION: as we slide theta_v from center (pi/2) to edge (pi), does the rep
generated by the boost on the cyclic subspace built from |theta_v> change CLASS?

I will compute, FULLY EXPLICITLY, the boost eigenvalues that appear in the matter 2-pt function
pole ladder as a function of theta_v, and classify:
  - discrete series D^+: REAL boost spectrum, bounded below, integer-spaced, Casimir Delta(Delta-1)>... .
  - principal/continuous: boost spectrum on a line / unbounded both ways, Casimir = -1/4 + s^2 (s real).

The pole ladder gives omega_k = E_pole(theta_v,k). The boost eigenvalue associated to rung k is
the modular 'energy' = the coefficient of the exponential decay/oscillation. Decompose:
   omega_k = R(theta_v) e^{-i phi(theta_v,k)}  with the DECAY = Im part, RING = Re part.

DISCRETE-SERIES SIGNATURE (center): Re omega_k = 0 for all k => pure decay => the boost
acts as a pure real dilation generator with DISCRETE spectrum {Delta+k}. Modular flow is
geometric (KMS, single temperature), the hallmark of a thermal/discrete-series modular orbit.

EDGE SIGNATURE: Re omega_k != 0 ('ringing') => the modular generator has COMPLEX spectrum on
this ladder => the would-be boost orbit is NOT a single-temperature KMS flow. Combined with the
poles LEAVING the band (so the ladder is not even normalizable/contributing), the cyclic
subspace from |theta_v=edge> is carried by the CONTINUUM, whose boost rep is the
PRINCIPAL/CONTINUOUS series, NOT D^+_Delta.

THIS PART: quantify Re/Im of the boost eigenvalue vs theta_v, find where 'ringing' onsets,
and check the Casimir / rep-class label on each side EXPLICITLY (sympy + mpmath numbers).
"""
import sympy as sp
import mpmath as mp
mp.mp.dps = 40

print("="*78)
print("PART 3 — boost-eigenvalue rep class vs placement (the (a)/(b) decider)")
print("="*78)

Delta, kk, lam = sp.symbols('Delta k lambda', positive=True)
theta_v = sp.symbols('theta_v', real=True)
u = (Delta + kk)*lam
omega = sp.cos(theta_v)*sp.cosh(u) - sp.I*sp.sin(theta_v)*sp.sinh(u)

# Symbolic Re/Im of the boost eigenvalue (the pole position = modular energy)
re_w = sp.re(omega.rewrite(sp.exp))  # cos(theta_v) cosh(u)
im_w = sp.im(omega.rewrite(sp.exp))  # -sin(theta_v) sinh(u)
re_w = sp.simplify(sp.cos(theta_v)*sp.cosh(u))
im_w = sp.simplify(-sp.sin(theta_v)*sp.sinh(u))
print("\nBoost eigenvalue (pole) at rung k, placement theta_v:")
print("  Re =", re_w, "  (RINGING; =0 only at theta_v=pi/2)")
print("  Im =", im_w, "  (DECAY)")

# The 'fake temperature' / decay rate is proportional to sin(theta_v) [Lin-Susskind].
print("\nDecay rate ~ sin(theta_v) sinh(u). Ring ~ cos(theta_v) cosh(u).")
print("Ring/Decay ratio per rung = cot(theta_v) * coth(u).")
ratio = sp.cos(theta_v)/sp.sin(theta_v) * sp.cosh(u)/sp.sinh(u)
print("  Ring/Decay =", sp.simplify(ratio))

print("\n--- DISCRETE-SERIES TEST: is the boost spectrum REAL & bounded-below? ---")
# A lowest-weight discrete series D^+_Delta requires:
#   spectrum of L0 (here the modular generator's REAL eigenvalues) = {Delta+k}, k>=0, integer-spaced.
#   For that the pole ladder must be PURELY IMAGINARY in omega (pure decay): Re omega = 0.
print("Re omega = 0  <=>  cos(theta_v)=0  <=>  theta_v = pi/2 (CENTER) EXACTLY.")
print("  At center: Im omega = -sinh((Delta+k)lambda); semiclassical -> -(Delta+k)lambda.")
print("  => real modular spectrum {Delta+k}: HALF-BOUNDED integer-spaced = D^+_Delta. CHECK.")

print("\n--- EDGE: rep class of the boost on the cyclic subspace ---")
# numbers at the banked edge eps=1e-3, q=0.7 (lam=-ln q), Delta=0.5
lam_v = mp.mpf(-1)*mp.log(mp.mpf('0.7'))
Dv = mp.mpf('0.5')
print(f"  banked numbers: q=0.7 -> lambda={float(lam_v):.5f}, Delta=0.5")
# eps_c where cosh(Delta*lam) = sec(eps): the lowest rung (k=0) leaves support
sec_thr = mp.cosh(Dv*lam_v)
eps_c = mp.acos(1/sec_thr)
print(f"  lowest rung k=0 exits band when cos(eps) < 1/cosh(Delta*lam) = {float(1/sec_thr):.5f}")
print(f"  => eps_c = {float(eps_c):.5f} rad (banked agentS eps_c~0.177 at these values)")
print(f"  BANKED edge eps=1e-3 << eps_c => ALL rungs exit the band: no discrete poles.")

# Boost eigenvalue Re/Im at edge for first few rungs (eps=1e-3)
eps_v = mp.mpf('1e-3')
tv = mp.pi - eps_v
print("\n  Boost eigenvalue (Re=ring, Im=decay) at EDGE eps=1e-3, first rungs:")
for kv in range(4):
    uu = (Dv + kv)*lam_v
    rew = mp.cos(tv)*mp.cosh(uu)
    imw = -mp.sin(tv)*mp.sinh(uu)
    band_floor = mp.cos(eps_v) - 1
    in_band = "IN band" if rew >= band_floor else "BELOW band (excluded)"
    print(f"    k={kv}: Re={float(rew):+.5f}  Im={float(imw):+.6f}  ring/decay={float(rew/imw):+.2e}  [{in_band}]")
print(f"  spectral floor omega_min = cos(eps)-1 = {float(mp.cos(eps_v)-1):.3e}")
print("  => ring/decay BLOWS UP (1e3+): the boost spectrum is NOT real -> NOT D^+.")
print("     Poles below floor => the cyclic subspace is the CONTINUUM band -> principal series.")

print("\n" + "="*78)
print("PART 3 RESULT")
print("="*78)
print("CENTER (theta_v=pi/2): Re omega = 0 EXACTLY -> boost spectrum real, half-bounded,")
print("   integer-spaced {Delta+k} -> DISCRETE SERIES D^+_Delta. Casimir Delta(Delta-1).")
print("   This MATCHES the GH modular rep (agentSS) EXACTLY.")
print("EDGE: Re omega != 0 (ring/decay ~ 1e3) AND poles exit the band -> boost spectrum")
print("   complex/continuous, no lowest-weight tower -> PRINCIPAL/CONTINUOUS series, NOT D^+.")
print("   The GH modular rep is DISCRETE; the edge's modular rep is CONTINUOUS -> MISMATCH.")
