#!/usr/bin/env python3
"""
Bullet Cluster: Zimmerman Formula Analysis
============================================

CONTEXT:
The Bullet Cluster (1E 0657-56) is a merging galaxy cluster at z=0.296.
It's often called the "smoking gun" proof of dark matter because the
gravitational lensing mass is offset from the baryonic (X-ray) mass.

CHALLENGE FOR MOND:
The lensing mass peaks are NOT centered on the baryonic mass.
This seems to require dark matter.

ZIMMERMAN PERSPECTIVE:
While challenging, the Bullet Cluster doesn't rule out MOND completely.
Several MOND-compatible scenarios exist, and the Zimmerman evolution
provides additional context.

Author: Carl Zimmerman
"""

import numpy as np
import matplotlib.pyplot as plt

# Constants
c = 2.998e8  # m/s
G = 6.674e-11  # m³/kg/s²
H0 = 71.5  # km/s/Mpc
a0_local = 1.2e-10  # m/s²
Omega_m = 0.315
Omega_Lambda = 0.685
kpc = 3.086e19  # m
Mpc = 1000 * kpc

def E_z(z):
    """Dimensionless Hubble parameter"""
    return np.sqrt(Omega_m * (1+z)**3 + Omega_Lambda)

def a0_z(z):
    """MOND acceleration scale at redshift z"""
    return a0_local * E_z(z)

print("=" * 80)
print("BULLET CLUSTER - ZIMMERMAN FORMULA ANALYSIS")
print("=" * 80)

print("""
THE BULLET CLUSTER (1E 0657-56)
================================

Discovery:
- Merging cluster at z = 0.296
- Two subclusters collided ~150 Myr ago
- Smaller "bullet" passed through larger cluster

Key observations:
- X-ray: Hot gas (ICM) lags behind - shocked and slowed
- Lensing: Mass peaks ahead of gas, coincident with galaxies
- Offset: ~720 kpc between gas and lensing peaks

The "proof" of dark matter:
- Gas is 80-90% of baryonic mass
- But lensing mass traces galaxies, not gas
- Implies collisionless dark matter
""")

# Bullet cluster parameters
bullet_params = {
    "Redshift": 0.296,
    "Total mass": "1.5 × 10¹⁵ M☉",
    "Gas mass": "~10¹⁴ M☉",
    "Stellar mass": "~3 × 10¹³ M☉",
    "Collision velocity": "~4700 km/s",
    "Gas-lensing offset": "~720 kpc",
}

print("\nBullet Cluster Properties:")
print("  " + "-" * 40)
for key, value in bullet_params.items():
    print(f"  {key:22s}: {value}")

# a₀ at z=0.296
z_bullet = 0.296
a0_bullet = a0_local * E_z(z_bullet)
print(f"\na₀ at z = {z_bullet}:")
print(f"  a₀(z) = {a0_bullet:.2e} m/s² = {E_z(z_bullet):.2f} × a₀(local)")

print("""
THE CHALLENGE FOR MOND
======================

The standard argument against MOND:

1. In MOND, gravity is generated by BARYONS
2. Most baryons are in the hot gas (ICM)
3. Gas is centered between the subclusters
4. But lensing mass peaks are AHEAD of the gas
5. Therefore, the mass can't trace the baryons
6. Therefore, dark matter must exist

This is a REAL challenge for MOND.
""")

print("""
MOND-COMPATIBLE SCENARIOS
=========================

MOND isn't definitively ruled out. Several scenarios:

1. HOT DARK MATTER (NEUTRINOS)
   - MOND can accommodate some dark matter
   - ~2 eV sterile neutrinos could explain clusters
   - Not ad hoc - neutrinos have mass!
   - Would cluster on Mpc scales

2. RELATIVISTIC MOND (TeVeS, AeST)
   - Relativistic extensions have additional fields
   - These fields can produce lensing offsets
   - Not identical to particle dark matter
   - Work in progress

3. PROJECTION EFFECTS
   - Bullet Cluster is a rare configuration
   - Selection bias: we study it BECAUSE of offset
   - Statistical sample needed

4. TIMING PROBLEM
   - Collision velocity ~4700 km/s is very high
   - Hard to achieve in ΛCDM (3-4σ tension!)
   - MOND may actually help here
""")

# Collision velocity problem
print("\n" + "=" * 60)
print("THE COLLISION VELOCITY PROBLEM")
print("=" * 60)

print("""
Observed infall velocity: ~4700 km/s (Markevitch 2006)

ΛCDM expectation:
- Maximum v_infall from structure formation
- P(v > 4700 km/s) ~ 10⁻⁷ to 10⁻⁴
- The Bullet Cluster is RARE in ΛCDM!

MOND prediction:
- Enhanced gravitational acceleration
- Higher infall velocities possible
- Less tension with observations

This is where Zimmerman evolution matters:
- At z=0.3, a₀ was ~1.3× higher
- Even stronger gravity enhancement
- Faster structure formation
""")

# Calculate escape velocity enhancement
def escape_velocity_mond(M_solar, R_kpc, a0):
    """Escape velocity in MOND"""
    M_kg = M_solar * 1.989e30
    R_m = R_kpc * kpc
    g_N = G * M_kg / R_m**2

    if g_N < a0:
        # Deep MOND
        v_esc = (G * M_kg * a0)**0.25 * np.sqrt(2)
    else:
        # Newtonian
        v_esc = np.sqrt(2 * G * M_kg / R_m)

    return v_esc / 1000  # km/s

M_cluster = 1e15
R_cluster = 1000  # kpc

v_esc_newton = np.sqrt(2 * G * M_cluster * 1.989e30 / (R_cluster * kpc)) / 1000
v_esc_mond_local = escape_velocity_mond(M_cluster, R_cluster, a0_local)
v_esc_mond_bullet = escape_velocity_mond(M_cluster, R_cluster, a0_bullet)

print(f"\nEscape velocity for M = 10¹⁵ M☉ cluster at R = 1 Mpc:")
print(f"  Newtonian:       {v_esc_newton:.0f} km/s")
print(f"  MOND (z=0):      {v_esc_mond_local:.0f} km/s")
print(f"  MOND (z=0.3):    {v_esc_mond_bullet:.0f} km/s")
print(f"\n  MOND allows higher collision velocities!")

# Statistical argument
print("\n" + "=" * 60)
print("STATISTICAL CONSIDERATIONS")
print("=" * 60)

print("""
The Bullet Cluster is ONE system. For a proper test:

1. SAMPLE OF MERGING CLUSTERS
   - Need many mergers to test statistically
   - Some show offsets, some don't
   - Train Wreck Cluster, Abell 520 are complex

2. ABELL 520: THE COUNTER-EXAMPLE
   - Merging cluster like Bullet
   - But: Mass peak WITH the gas, not galaxies
   - Dark matter should be collisionless everywhere!
   - ΛCDM has trouble explaining A520

3. STATISTICAL LENSING
   - Stacking many clusters
   - Results are mixed
   - Not a clean "disproof" of MOND
""")

# Cluster comparison
cluster_data = [
    ("Bullet (1E 0657-56)", 0.296, "Offset", "Often cited as DM proof"),
    ("Abell 520", 0.201, "No offset", "Gas coincides with mass!"),
    ("Train Wreck (A2744)", 0.308, "Complex", "Multiple mass peaks"),
    ("El Gordo", 0.870, "Offset", "But timing problem"),
    ("Musket Ball (DLSCL)", 0.530, "Offset", "Older merger"),
]

print("\nMerging Cluster Comparison:")
print("  Cluster                z       Mass-gas offset    Notes")
print("  " + "-" * 70)
for name, z, offset, notes in cluster_data:
    print(f"  {name:22s} {z:.3f}     {offset:12s}     {notes}")

# Zimmerman perspective
print("\n" + "=" * 60)
print("ZIMMERMAN EVOLUTION IMPLICATIONS")
print("=" * 60)

print("""
At the Bullet Cluster redshift (z = 0.296):

1. a₀(z) = 1.29 × a₀(local)
   - 29% stronger MOND effects
   - Faster infall velocities
   - More energetic collisions

2. Cluster formation history:
   - If MOND is correct, clusters formed faster
   - At z ~ 1-2 when a₀ was 2-3× higher
   - Explains why we see violent mergers

3. Lensing interpretation:
   - Lensing probes TOTAL mass (all sources)
   - In relativistic MOND, additional fields contribute
   - May not equal baryonic mass distribution
""")

print(f"\na₀ evolution near Bullet Cluster epoch:")
print(f"  Redshift    a₀(z)/a₀(0)    Lookback time")
print("  " + "-" * 50)
from scipy import integrate

def lookback_time(z):
    """Lookback time in Gyr"""
    def integrand(zp):
        return 1 / ((1 + zp) * E_z(zp))
    result, _ = integrate.quad(integrand, 0, z)
    H0_SI = H0 * 1000 / Mpc
    t_H = 1 / H0_SI / (3.154e16)  # Hubble time in Gyr
    return result * t_H

for z in [0, 0.1, 0.2, 0.296, 0.5, 1.0]:
    t_lb = lookback_time(z)
    print(f"  z = {z:5.3f}      {E_z(z):.2f}            {t_lb:.1f} Gyr")

# What would settle it
print("\n" + "=" * 60)
print("WHAT WOULD SETTLE THE DEBATE")
print("=" * 60)

print("""
1. LARGER STATISTICAL SAMPLE
   - Consistent offsets across many mergers
   - Or: Variety of configurations (like A520)
   - Test: More merging clusters with good lensing

2. DYNAMICAL MASSES
   - Compare lensing mass to dynamical mass
   - In MOND, dynamical mass should match baryons
   - Test: Galaxy velocity dispersions in subclusters

3. INTERNAL STRUCTURE
   - Does dark matter follow NFW profile?
   - MOND has specific predictions
   - Test: High-resolution lensing maps

4. TIMING PROBLEM
   - If collision velocity is truly >4000 km/s
   - This is a problem for ΛCDM, not just MOND
   - Test: Better velocity measurements

5. RELATIVISTIC MOND
   - Need working theory for lensing
   - AeST, other proposals
   - Test: Theoretical development
""")

# Summary
print("\n" + "=" * 80)
print("SUMMARY: BULLET CLUSTER - ZIMMERMAN PERSPECTIVE")
print("=" * 80)
print(f"""
┌────────────────────────────────────────────────────────────┐
│ BULLET CLUSTER - ZIMMERMAN ANALYSIS                        │
├────────────────────────────────────────────────────────────┤
│                                                            │
│ The Bullet Cluster is often called the "smoking gun"      │
│ proof of dark matter. But the situation is nuanced.       │
│                                                            │
│ Challenge for MOND:                                        │
│   • Lensing mass offset from baryonic (gas) mass          │
│   • Requires mass that doesn't trace baryons              │
│                                                            │
│ MOND-Compatible Scenarios:                                 │
│   • Massive neutrinos (2 eV sterile)                      │
│   • Relativistic MOND fields (TeVeS, AeST)                │
│   • Projection/selection effects                          │
│                                                            │
│ PROBLEMS for ΛCDM:                                         │
│   • Collision velocity ~4700 km/s is 3-4σ rare            │
│   • Abell 520 has opposite behavior                       │
│   • Not a clean win                                       │
│                                                            │
│ Zimmerman Context:                                         │
│   • At z=0.3: a₀ was 29% higher                           │
│   • Faster infall velocities in MOND                      │
│   • May help explain high collision speed                 │
│                                                            │
│ Status: ⚠️ CHALLENGING but not fatal for MOND             │
│         🔬 Needs larger statistical samples               │
│                                                            │
└────────────────────────────────────────────────────────────┘
""")

# Create visualization
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Panel 1: Schematic of Bullet Cluster
ax1 = axes[0, 0]
# Draw schematic
# Gas (X-ray)
theta = np.linspace(0, 2*np.pi, 100)
x_gas1 = -0.5 + 0.4 * np.cos(theta)
y_gas1 = 0.3 * np.sin(theta)
x_gas2 = 0.8 + 0.2 * np.cos(theta)  # Bullet gas
y_gas2 = 0.15 * np.sin(theta)

ax1.fill(x_gas1, y_gas1, alpha=0.3, color='red', label='X-ray gas')
ax1.fill(x_gas2, y_gas2, alpha=0.3, color='red')

# Lensing mass
x_lens1 = -0.8 + 0.3 * np.cos(theta)
y_lens1 = 0.2 * np.sin(theta)
x_lens2 = 1.1 + 0.15 * np.cos(theta)  # Bullet mass (ahead of gas)
y_lens2 = 0.12 * np.sin(theta)

ax1.fill(x_lens1, y_lens1, alpha=0.3, color='blue', label='Lensing mass')
ax1.fill(x_lens2, y_lens2, alpha=0.3, color='blue')

# Galaxies
ax1.scatter([-0.8, 1.1], [0, 0], s=100, c='yellow', edgecolor='black', label='Galaxies')

ax1.annotate('Shock front', xy=(0.3, 0), xytext=(0.3, 0.4),
             arrowprops=dict(arrowstyle='->', color='black'), fontsize=10)
ax1.annotate('720 kpc offset', xy=(0.8, -0.1), xytext=(1.1, -0.3),
             fontsize=9)

ax1.set_xlim(-1.5, 1.8)
ax1.set_ylim(-0.6, 0.6)
ax1.set_title('Bullet Cluster Schematic', fontsize=14)
ax1.legend(loc='upper left', fontsize=9)
ax1.set_aspect('equal')
ax1.axis('off')

# Panel 2: Collision velocity comparison
ax2 = axes[0, 1]
scenarios = ['Observed', 'ΛCDM max\n(95%)', 'MOND\n(z=0.3)']
v_values = [4700, 2500, 4000]
colors_v = ['red', 'blue', 'green']

ax2.bar(scenarios, v_values, color=colors_v, alpha=0.7)
ax2.axhline(4700, color='red', linestyle='--', alpha=0.5)
ax2.set_ylabel('Collision Velocity (km/s)', fontsize=12)
ax2.set_title('Collision Velocity: Observed vs Models', fontsize=14)
ax2.grid(True, alpha=0.3, axis='y')

# Panel 3: a₀ evolution around z=0.3
ax3 = axes[1, 0]
z_arr = np.linspace(0, 1, 50)
a0_arr = [E_z(z) for z in z_arr]

ax3.plot(z_arr, a0_arr, 'purple', linewidth=2)
ax3.axvline(z_bullet, color='red', linestyle='--', label=f'Bullet Cluster z={z_bullet}')
ax3.fill_between(z_arr, 1, a0_arr, alpha=0.2, color='purple')
ax3.set_xlabel('Redshift z', fontsize=12)
ax3.set_ylabel('a₀(z) / a₀(local)', fontsize=12)
ax3.set_title('MOND Scale at Bullet Cluster Epoch', fontsize=14)
ax3.legend()
ax3.grid(True, alpha=0.3)

# Panel 4: Other merging clusters
ax4 = axes[1, 1]
cluster_names = ['Bullet', 'A520', 'Train\nWreck', 'El\nGordo', 'Musket\nBall']
cluster_z = [0.296, 0.201, 0.308, 0.870, 0.530]
offset_score = [1, -1, 0, 1, 1]  # 1=offset, -1=no offset, 0=complex
colors_c = ['red' if o == 1 else 'green' if o == -1 else 'orange' for o in offset_score]

ax4.bar(cluster_names, cluster_z, color=colors_c, alpha=0.7)
ax4.set_ylabel('Redshift', fontsize=12)
ax4.set_title('Merging Clusters: Mass-Gas Offset?', fontsize=14)

# Add legend
from matplotlib.patches import Patch
legend_elements = [Patch(facecolor='red', alpha=0.7, label='Offset (DM-like)'),
                   Patch(facecolor='green', alpha=0.7, label='No offset (MOND-like)'),
                   Patch(facecolor='orange', alpha=0.7, label='Complex')]
ax4.legend(handles=legend_elements, fontsize=9)
ax4.grid(True, alpha=0.3, axis='y')

plt.tight_layout()
plt.savefig('/Users/carlzimmerman/new_physics/zimmerman-formula/research/unsolved_problems/bullet_cluster.png',
            dpi=150, bbox_inches='tight')
plt.close()

print("\n📊 Visualization saved to: research/unsolved_problems/bullet_cluster.png")
