import numpy as np
from numpy.linalg import eigvalsh
np.set_printoptions(precision=5, suppress=True)
rng = np.random.default_rng(7)

# =====================================================================
# TEST B: the CROSSED-PRODUCT / OBSERVER-DRESSING structure.
# The dS II_1 factor is N = M >< R (crossed product of the type III_1
# QFT algebra M by the modular boost flow), generated by M and the
# observer clock q. The II_1 STATE is omega = <Phi_max | . | Phi_max>
# where Phi_max = (max-entropy) = GH (x) (clock-density g(x)).
# The chord II_1 factor is similar with its own clock dressing.
#
# CRUCIAL STRUCTURE (CLPW 2206.10780, agentTT): the trace / state on the
# crossed product depends on the OBSERVER ENERGY DENSITY g(x). Different
# admissible g  ->  DIFFERENT states  ->  the modular GENERATOR (boost)
# is shared, but the FULL modular OPERATOR (Delta = e^{-beta H_mod}) and
# hence the GNS vector is g-DEPENDENT.
#
# We model the clock as an extra factor with a 1-param family of densities
# g_s, all KMS at the SAME beta w.r.t. the SAME generator, and ask:
# does sharing (generator, beta) pin the STATE, or does a residual
# placement/dressing parameter survive?
# =====================================================================

beta = 2*np.pi  # the GH/static-patch KMS inverse temperature (H=1 units)

# Boost generator spectrum on a truncated discrete-series ladder Delta+n
Delta = 0.5
n = np.arange(0, 40)
boost_spec = Delta + n        # L_0 eigenvalues (agentSS: modular flow = boost = L_0)

# KMS state weights at beta w.r.t. this generator:  w_n ~ e^{-beta (Delta+n)}
def kms_weights(beta, spec):
    w = np.exp(-beta*spec)
    return w/ w.sum()

w_GH = kms_weights(beta, boost_spec)

print("=== TEST B: does (shared generator + shared beta) pin the STATE? ===")
print("GH-side KMS weights (first 6):", w_GH[:6])

# Now: a DIFFERENT admissible clock dressing g_s multiplies the bare KMS
# weights by a slowly-varying (modular-flow-INVARIANT in the centralizer)
# function. The KEY operator-algebra fact: any function f(L_0) of the
# modular GENERATOR commutes with the modular flow (it's in the
# centralizer M_omega), so multiplying weights by f preserves:
#   (i) the modular GENERATOR (still L_0),
#   (ii) the KMS property? NO -- it changes beta UNLESS f is exp-linear.
# Test which deformations preserve BOTH generator AND KMS-at-beta:

def is_kms_at_beta(weights, spec, beta, tol=1e-9):
    # KMS at beta <=> weights proportional to exp(-beta*spec)
    logw = np.log(weights)
    # fit logw = a - beta*spec ; residual must vanish
    A = np.vstack([np.ones_like(spec), -spec]).T
    coef, res, *_ = np.linalg.lstsq(A, logw, rcond=None)
    pred = A@coef
    maxdev = np.max(np.abs(pred-logw))
    return maxdev < tol, coef[1], maxdev

ok, fitted_beta, dev = is_kms_at_beta(w_GH, boost_spec, beta)
print("GH weights KMS-at-beta? ", ok, " fitted beta =", round(fitted_beta,6), " dev=", dev)

# Deform by f(L_0) = (Delta+n)^p  -- a centralizer (generator-commuting) reweight
print("\n--- deform weights by centralizer function f(L_0)=(Delta+n)^p ---")
for p in [0.0, 1.0, 2.0, -1.0]:
    f = (boost_spec)**p
    w_def = w_GH * f
    w_def = w_def/w_def.sum()
    ok2, fb, dv = is_kms_at_beta(w_def, boost_spec, beta)
    print(f"  p={p:+.1f}: KMS-at-beta? {ok2}  fitted_beta={fb:.4f}  maxdev={dv:.2e}")
