import sympy as sp
# ============================================================
# ZZ2 - THE LOCKED-RATIO TEST (exact, full resolvent, Fourier).
# The decisive question: are the SLIP kernel and the POLLUTION kernel the SAME (locked -> dead,
# like KK) or DIFFERENT (the escape)?  In agentDD/KK the wall-4 identity locked them:
#   r^0-class of the exact lens-only condition = alpha^6 (slip/Phi').
# i.e. the matter-channel feed's irreducible geometric core IS the slip itself.
# ============================================================
k, L = sp.symbols('k L', positive=True)
Khat = 1/(1 + L**2*k**2)   # full resolvent multiplier (Yukawa propagator), exact

# In the quasi-static system the SLIP at mode k is generated by the operator acting on the
# smoothed key.  The POLLUTION (eqN feed) at mode k is the lapse response of that SAME operator.
# Build both from the SAME Lagrangian term B(chi)*(slip-generator), chi = K_L Phi.
#
# Slip generator structure (the spatial analog of the (D.b) divergence operator that worked in DD):
#   the slip in eqL ~ d/dPhi [ B(chi) * G ]   where G is the slip generator geometry.
#   the eqN feed   ~ d/dPhi [ B(chi) * G ] under the LAPSE variation (test function on N=1+Phi).
#
# The ONLY freedom a spatial kernel adds over a local key is WHERE the K_L lands.  Enumerate:
#   case (i)  operator = B(chi)*(grad Phi)^2-keyed, chi=K_L Phi  -> SLIP carries K_L^a, POLLUTION K_L^b
#   The lens-only identity forces a relation between a and b.  Compute it.

# Slip(k): the rr-constraint slip is LINEAR in the operator coefficient's response to Psi/Phi.
# For an operator B(chi) multiplying a slip generator that is itself built from the field at the
# SAME point, the slip at mode k inherits ONE power of K_L (the chi that keys it):  Slip ~ K_L(k).
# The eqN (Hamiltonian) feed is the LAPSE variation of the SAME term.  The lapse N enters BOTH
# through chi=K_L Phi (one K_L) AND through the explicit measure/curvature (NO K_L).  The
# DANGEROUS enhanced piece is the one that lands the second derivative geometrically -- and the
# question is whether it goes through the K_L-dressed channel or the bare channel.

# DERIVE the lens-only (Delta_Phi=0) condition's geometric class for the spatial operator, in k.
# Reuse the agentDD closed form: Delta_Phi^(r0) = (slip/Phi')/[r^2 (1+slip/Phi')].  In Fourier
# the geometric 1/r^2 <-> k^2.  The pollution's irreducible core is (slip)*k^2-class.  The
# spatial kernel multiplies the SLIP by K_L(k) and the POLLUTION's geometric core by ... the SAME
# K_L(k) IF AND ONLY IF the slip and the geometric core come from the same chi-keyed factor.

slip_kernel      = Khat            # the slip reads the smoothed key: one K_L
# The geometric eqN core = the lapse response of the keying factor.  If the key is chi=K_L Phi and
# the slip is keyed on chi, then the lapse response delta(slip-operator)/delta(Phi) ALSO carries
# exactly the chi-response = K_L (linear key) OR k^2-enhanced*K_L (gradient/acceleration key).
# BRANCH A (acceleration-keyed, the ONLY branch that gives nu(g_bar/a0)):
pollution_kernel_A = Khat * 1      # geometric core inherits the SAME K_L as the slip (both via chi)
ratio_A = sp.simplify(pollution_kernel_A/slip_kernel)
print("BRANCH A (acceleration-keyed): pollution/slip kernel ratio =", ratio_A)
print("  -> LOCKED: pollution suppression == slip suppression at EVERY mode. KK-1 pattern.")

# BRANCH B (potential-value-keyed chi=K_L Phi, key linear in chi):
# slip ~ B'(chi) ~ K_L; pollution geometric core: the lapse response of a POTENTIAL-keyed operator
# does NOT carry the (grad)^2 enhancement -> the (a0 r/c^2)^-1 factor is ABSENT.  BUT a
# potential-keyed slip is NOT acceleration-keyed -> wrong observable (no nu(g_bar/a0)).
print("\nBRANCH B (potential-value-keyed): pollution lacks the (a0 r/c^2)^-1 enhancement")
print("  BUT slip is potential-keyed, not acceleration-keyed -> does NOT produce nu(g_bar/a0).")
print("  (constant/potential-keyed slip = a dead wall-4 branch in agentY/agentW). Wrong observable.")

# THE LOCKED RATIO, quantified at halo vs linear scales.
print("\n--- The locked ratio across scales (Branch A) ---")
# halo: r ~ 30 kpc; linear: lambda ~ 100 Mpc.  k in 1/Mpc.
import math
data = []
for label, kval in [("halo k~30/Mpc (r~30kpc)", 30.0), ("galaxy outskirt k~3", 3.0),
                    ("cluster k~1", 1.0), ("BAO/linear k~0.1", 0.1), ("super-horizon-ish k~0.01", 0.01)]:
    data.append((label, kval))
for Lval in [0.03, 0.3, 3.0, 30.0]:  # L in Mpc
    print(f"\n  L = {Lval} Mpc:")
    for label, kval in data:
        s = 1.0/(1.0 + (Lval*kval)**2)
        print(f"    {label:32s}: Khat = {s:.4e}  (slip AND pollution both x this)")
