import numpy as np
# =====================================================================
# VERIFY (b) — the load-bearing dispute. Is the DSSYK chord algebra's
# AMENABILITY/AFD ESTABLISHED, or is the route's "single q-oscillator =>
# AFD" inference a smuggle?
#
# The route's argument (agentVV2_amenable.py):
#   "the DSSYK chord algebra is built from essentially ONE q-oscillator
#    (the chord-number/length operator + its conjugate shift), the
#    AFD/abelian-tame regime."
#
# HOSTILE PROBLEM 1 (representation theory of q-Gaussians, Bozejko-Speicher /
#   Nou math/0605789 / Sniady):
#   - A SINGLE q-Gaussian variable s = a + a*  generates an ABELIAN algebra
#     = L^infinity(spectrum, mu)  -- injective, YES, but NOT a II_1 FACTOR.
#   - The q-Gaussian factor Gamma_q(H) is a II_1 FACTOR only for dim H >= 2,
#     and it is NON-INJECTIVE for dim H >= 2 (Nou 2004; for all -1<q<1).
#   So: "single q-oscillator" => abelian (injective but not a factor);
#       ">=2 generators" => factor but possibly NON-injective.
#   The DSSYK algebra IS a II_1 FACTOR (Xu 2403.09021). A single self-adjoint
#   q-Gaussian can NOT give a factor. So the algebra is NOT "essentially one
#   q-oscillator" in the q-Gaussian sense -- the route's own template is
#   internally inconsistent with factoriality.
# =====================================================================

print("=== HOSTILE 1: a single self-adjoint q-Gaussian is ABELIAN (not a factor) ===")
# Build the q-Gaussian s = a + a* on q-Fock truncation; its generated vN algebra
# is the algebra of bounded functions of the single self-adjoint operator s,
# which is COMMUTATIVE. Show [s, f(s)] = 0 trivially but more importantly that
# the algebra <s>'' is abelian: it is generated by ONE self-adjoint op => abelian.
def qnum(n,q): return (1-q**n)/(1-q)
def aop(N,q):
    a=np.zeros((N,N))
    for n in range(1,N):
        a[n-1,n]=np.sqrt(qnum(n,q))
    return a
q=0.5; N=400
a=aop(N,q); ad=a.T
s = a+ad                      # single q-Gaussian, self-adjoint
# vN algebra generated by one self-adjoint operator is ALWAYS abelian:
# any two elements are functions of s, hence commute. Demonstrate with s and s^2, s^3:
for p1,p2 in [(1,2),(2,3),(1,3)]:
    M1=np.linalg.matrix_power(s,p1); M2=np.linalg.matrix_power(s,p2)
    comm=np.max(np.abs((M1@M2-M2@M1)[:N-20,:N-20]))
    print(f"  ||[s^{p1}, s^{p2}]|| on bulk = {comm:.2e}  (abelian: powers of s commute)")
print("  => <s>'' is ABELIAN = L^inf(spec(s)). Injective, but a II_1 FACTOR has")
print("     trivial center; abelian algebra is ALL center => NOT a factor.")
print("  => the DSSYK II_1 FACTOR is NOT 'essentially one q-Gaussian'. The route's")
print("     single-oscillator template cannot yield the factor it is claimed to model.\n")

print("=== HOSTILE 2: what makes the chord algebra a FACTOR is a, a* TOGETHER ===")
# The factor comes from the NON-self-adjoint generation: a and a* (raising/lowering),
# i.e. the *q-deformed CCR* algebra, NOT one self-adjoint q-Gaussian. The relevant
# vN algebra is generated by {a, a*} (equivalently {s, p} two q-Gaussians s=a+a*,
# p=(a-a*)/i). That is TWO q-Gaussian generators on the SAME mode.
p_op = (a-ad)/1j
comm_sp = np.max(np.abs((s@p_op - p_op@s)[:N-20,:N-20]))
print(f"  s=a+a*, p=(a-a*)/i: ||[s,p]|| on bulk = {comm_sp:.3f}  (NONZERO => noncommutative)")
print("  The chord *-algebra needs BOTH a and a* (raising+lowering) to be a factor.")
print("  Two q-Gaussians {s,p} = the dim-2 real Hilbert space case Gamma_q(R^2)...")
print("  ...and Gamma_q(R^2) is the case Nou 2004 proves NON-INJECTIVE for all q in (-1,1).\n")

print("=== HOSTILE 3: + INDEPENDENT MATTER CHORD operators b_L, b_L* (Xu 2403.09021) ===")
print("  Verified from Xu 2403.09021 (HTML full text): the algebra is generated by")
print("  the Hamiltonian chord pair {a, a*} AND SEPARATE matter chord operators")
print("  {b_L, b_L*} -- 'generated by chord operators', completion of finite linear")
print("  spans of STRINGS, explicitly NOT singly generated. So even the mode count")
print("  is >= 2 independent oscillators, deeper into the >=2 (possibly non-injective)")
print("  q-Gaussian regime, NOT the abelian-tame single-mode regime.\n")

print("CONCLUSION (b): the route's 'single q-oscillator => AFD' inference is UNSOUND")
print("as stated. A single q-Gaussian is abelian (not the factor); the factor needs")
print(">=2 q-Gaussian generators, which is EXACTLY the regime where the q-Gaussian")
print("von Neumann algebra is NON-INJECTIVE (Nou 2004, all -1<q<1). The structural")
print("template the route invokes points the OTHER way for >=2 generators.")
print()
print("CAVEAT (fair, both directions): the DSSYK chord algebra is NOT literally a")
print("q-Gaussian factor Gamma_q(H) -- it is a DIFFERENT q-deformed construction")
print("(transfer-matrix / Jacobi on a SEPARABLE space with a TRACE = II_1), whereas")
print("Gamma_q(R^d) for finite d is a fixed II_1 factor. The non-injectivity result")
print("does NOT directly transfer. But NEITHER does the abelian AFD inference. The")
print("honest status: the DSSYK side's hyperfiniteness is GENUINELY OPEN -- the one")
print("clean structural analogy the route leaned on (single q-oscillator = tame) is")
print("(i) factually wrong about factoriality and (ii) on the >=2-generator side,")
print("the nearest banked theorem (Nou) goes AGAINST injectivity, not for it.")
