# =====================================================================
# TEST F — IS THE PREMISE 'BOTH HYPERFINITE II_1' ACTUALLY ESTABLISHED?
# (The brief GRANTS it; we audit whether the grant is literature-backed
#  or itself an open assumption -- because if D1 is NOT actually free,
#  the reduction is even weaker.)
# =====================================================================
print("=== TEST F: hyperfiniteness status of each side ===\n")

facts = [
 ("dS QFT vacuum algebra (type III_1)",
  "HYPERFINITE (injective)",
  "STANDARD: free-field/CFT local algebras are the unique hyperfinite III_1 "
  "(Haag duality + Buchholz-Wichmann nuclearity; Araki). Well established."),
 ("dS observer algebra (CLPW crossed product, type II_1/II_inf)",
  "HYPERFINITE",
  "INHERITED: crossed product of an injective (hyperfinite) vN algebra by a "
  "(amenable, R) modular-flow group is injective => hyperfinite (Connes: "
  "injectivity stable under crossed product by amenable group). So dS II_1 = R."),
 ("DSSYK chord algebra (type II_1, Xu / Cao-Gao)",
  "NOT EXPLICITLY ESTABLISHED AS HYPERFINITE",
  "GAP: the papers prove 'type II_1 factor' but agentUU verify notes "
  "'hyperfiniteness/factoriality not even uniformly matched'. The chord "
  "algebra is generated by bounded chord operators on a SEPARABLE Fock-like "
  "space; physically expected amenable/AFD but NO published theorem that it "
  "is the HYPERFINITE R (vs L(F_n)-type). THIS IS THE WEAK LINK."),
]
for name, status, why in facts:
    print(f"* {name}\n    -> {status}\n    {why}\n")

print("=== VERDICT ON THE PREMISE ===")
print("dS side: hyperfinite II_1 = R is SOLID (injective III_1 crossed by R).")
print("DSSYK side: type II_1 PROVEN, but HYPERFINITE = R is PLAUSIBLE-NOT-PROVEN.")
print("So 'both hyperfinite II_1' is ONE-SIDE-SOLID + ONE-SIDE-PLAUSIBLE.")
print("If granted, Connes uniqueness gives D1 (abstract iso) FOR FREE.")
print("If the chord algebra is secretly NON-hyperfinite (e.g. L(F_n)-like from")
print("the free chord generators), then even D1 FAILS and phi is blocked at type.")
