#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
referee_gen2_adm_independent_2026.py
====================================
HOSTILE-REFEREE re-derivation of the Gen-2 constraint-reduced quadratic action.
Written from scratch; shares NO code with ya_tensor_exact_2026.py,
gen2_constraint_reduced_tensor_2026.py, constraint_reduced_scalar_2026.py,
gen2_constraint_reduced_quadratic_2026.py or gen2_adm_core_2026.py.

METHOD (different from all of the above): build the FULL ADM Lagrangian density from an
explicit 3-metric, computing 3-Christoffels and the 3-Ricci scalar by brute force, with
derivatives implemented as an exact chain rule on the plane-wave pair (C,S)=(cos,sin) of a
single phase.  Truncate at O(sigma^2), then project by phase-averaging.  No hand-derived
Fourier expansion is used anywhere.

FROZEN ACTION (not modified):
  unitary gauge T=t  =>  u_mu = -N delta^0_mu,  a_i = D_i ln N
  K_ij = (1/(2N))(dt h_ij - D_i N_j - D_j N_i)
  T_ij = D_i D_j lnN - (1/3) h_ij h^kl D_k D_l lnN
  X = a_i a^i/abar^2 , Y = T_ij T^ij/abar^4 , abar = a0/c^2
  S = INT N sqrt(h)[ R3 + K_ijK^ij - lam K^2 + eta a_i a^i - 2 abar^2 F ]   (M_Pl^2/2 = 1, c=1)
  F = -2 sqrt(X) + 2 ln(1+sqrt(X)) + eps A(X) Y ,  A(X)=X^2/(1+X)^4

BACKGROUND (ASSUMED): ln Nbar = q z, hbar = delta, Nbar^i = 0  =>  Tbar_ij = 0, Ybar = 0.
DECLARED APPROXIMATION (same as the claims'): the envelope e^{qz} is frozen to 1 while
every q generated by differentiation is kept exactly.  Dropped terms are relative O(q/k).
"""
import sympy as sp, math
from itertools import product

FAILS=[]
def ok(cond,label,detail=""):
    if not cond: FAILS.append(label)
    print(f"  [{'ok  ' if cond else 'FAIL'}] {label}"+(f"   {detail}" if detail else ""))
    return bool(cond)
def head(s): print("\n"+"="*100+f"\n{s}\n"+"="*100)

# ------------------------------------------------------------------ symbols
k, ab = sp.symbols('k abar', positive=True)
q     = sp.symbols('q', positive=True)
w     = sp.symbols('omega', real=True)
mu    = sp.symbols('mu', real=True)
lam, eta, eps = sp.symbols('lambda_K eta_K epsilon', real=True)
sig   = sp.symbols('sigma')
C, S  = sp.symbols('C S')                       # cos(phase), sin(phase)
st    = sp.sqrt(1-mu**2)
kv    = [k*st, 0, k*mu]                          # wavevector; a^(0) along z
e1    = sp.Matrix([mu,0,-st]); e2 = sp.Matrix([0,1,0])
Ep    = e1*e1.T - e2*e2.T
Ex    = e1*e2.T + e2*e1.T
X0    = q**2/ab**2
s0    = sp.sqrt(X0)
A0    = X0**2/(1+X0)**4

def T2(e):
    e = sp.expand(e)
    if not e.has(sig): return e
    p = sp.Poly(e, sig); out = 0
    for (n,),c in p.terms():
        if n<=2: out += c*sig**n
    return sp.expand(out)
def dX(e,i):  return T2(sp.diff(e,C)*(-kv[i]*S) + sp.diff(e,S)*(kv[i]*C))
def dT_(e):   return T2(sp.diff(e,C)*( w*S)     + sp.diff(e,S)*(-w*C))
def wave(ac,as_): return ac*C + as_*S
def phase_average(e):
    e = sp.expand(e)
    e = e.subs({C**2:sp.Rational(1,2), S**2:sp.Rational(1,2), C*S:0})
    e = e.subs({C:0, S:0})
    return sp.expand(e)

# ------------------------------------------------------------------ ADM builder
def lagrangian(gam=None, psi=0, phi=0, B=0, V=None):
    gam = sp.zeros(3,3) if gam is None else gam
    V   = sp.zeros(3,1) if V is None else V
    p   = sp.Matrix(3,3, lambda i,j: 2*psi*(1 if i==j else 0)+gam[i,j])
    h   = sp.eye(3) + sig*p
    hi  = sp.Matrix(3,3, lambda i,j: T2((sp.eye(3)-sig*p+sig**2*(p*p))[i,j]))
    trp = sum(p[i,i] for i in range(3)); trp2 = sum(p[i,j]*p[j,i] for i in range(3) for j in range(3))
    sqrth = T2(1 + sig*trp/2 + sig**2*(trp**2-2*trp2)/8)

    lnNpert = T2(sig*phi - sig**2*phi**2/2)      # ln N = q z + ln(1+sig phi)
    Nfac    = T2(1+sig*phi)
    Ninv    = T2(1-sig*phi+sig**2*phi**2)
    Ni      = sp.Matrix(3,1, lambda i,_: T2(sig*(dX(B,i)+V[i])))

    Gam=[[[None]*3 for _ in range(3)] for _ in range(3)]
    for a in range(3):
        for i in range(3):
            for j in range(3):
                Gam[a][i][j]=T2(sp.Rational(1,2)*sum(hi[a,l]*(dX(h[l,i],j)+dX(h[l,j],i)-dX(h[i,j],l))
                                                     for l in range(3)))
    Ric=sp.zeros(3,3)
    for i in range(3):
        for j in range(3):
            e=0
            for a in range(3):
                e+=dX(Gam[a][i][j],a)-dX(Gam[a][i][a],j)
                for b in range(3):
                    e+=Gam[a][a][b]*Gam[b][i][j]-Gam[a][i][b]*Gam[b][a][j]
            Ric[i,j]=T2(e)
    R3=T2(sum(hi[i,j]*Ric[i,j] for i in range(3) for j in range(3)))

    def DiNj(i,j): return T2(dX(Ni[j],i)-sum(Gam[a][i][j]*Ni[a] for a in range(3)))
    K=sp.zeros(3,3)
    for i in range(3):
        for j in range(3):
            K[i,j]=T2((dT_(h[i,j])-DiNj(i,j)-DiNj(j,i))*Ninv/2)
    Ktr=T2(sum(hi[i,j]*K[i,j] for i in range(3) for j in range(3)))
    Kup=sp.Matrix(3,3, lambda a,b: T2(sum(hi[a,i]*hi[b,j]*K[i,j] for i in range(3) for j in range(3))))
    KK =T2(sum(K[i,j]*Kup[i,j] for i in range(3) for j in range(3)))

    a_i=sp.Matrix(3,1, lambda i,_: T2((q if i==2 else 0)+dX(lnNpert,i)))
    aa =T2(sum(hi[i,j]*a_i[i]*a_i[j] for i in range(3) for j in range(3)))

    DD=sp.zeros(3,3)
    for i in range(3):
        for j in range(3):
            DD[i,j]=T2(dX(dX(lnNpert,i),j)-sum(Gam[a][i][j]*a_i[a] for a in range(3)))
    trDD=T2(sum(hi[i,j]*DD[i,j] for i in range(3) for j in range(3)))
    Tt  =sp.Matrix(3,3, lambda i,j: T2(DD[i,j]-sp.Rational(1,3)*h[i,j]*trDD))
    Ttu =sp.Matrix(3,3, lambda a,b: T2(sum(hi[a,i]*hi[b,j]*Tt[i,j] for i in range(3) for j in range(3))))
    Yv  =T2(sum(Tt[i,j]*Ttu[i,j] for i in range(3) for j in range(3)))/ab**4

    dXv=T2(aa/ab**2-X0)
    Xs=sp.Symbol('Xs',positive=True); Fsc=-2*sp.sqrt(Xs)+2*sp.log(1+sp.sqrt(Xs))
    F=T2(Fsc.subs(Xs,X0)+sp.diff(Fsc,Xs).subs(Xs,X0)*dXv
         +sp.diff(Fsc,Xs,2).subs(Xs,X0)*dXv**2/2 + eps*A0*Yv)
    L=T2(Nfac*sqrth*T2(R3+KK-lam*Ktr**2+eta*aa-2*ab**2*F))
    return phase_average(sp.Poly(L,sig).coeff_monomial(sig**2))

hpc,hps,hxc,hxs,pc,ps,Bc,Bs_,Pc,Ps = sp.symbols('hpc hps hxc hxs phic phis Bc Bs psic psis',real=True)
V1c,V1s,V2c,V2s = sp.symbols('V1c V1s V2c V2s',real=True)
GTT = sp.Matrix(3,3, lambda i,j: wave(hpc,hps)*Ep[i,j]+wave(hxc,hxs)*Ex[i,j])

# =====================================================================================
head("A0 -- a_i = D_i ln N (exact) and what it forces")
print("  T=t, u_mu=-N delta^0_mu  =>  a_i = u^a grad_a u_i = D_i ln N.  IMPORTED-standard")
print("  (khronometric/Horava, unitary gauge).  Consequence used throughout: at fixed N the")
print("  covector a_i is metric-INDEPENDENT; all h-dependence of X is via h^ij and all")
print("  h-dependence of T_ij is via Gamma^k_ij and h^ij.")
ok(True,"a_i = D_i ln N accepted (IMPORTED)")

head("A -- delta_1 T_ij for a TT mode: the three operator identities, at GENERAL angle")
gTT = sp.Matrix(3,3, lambda i,j: (hpc*Ep[i,j]+hxc*Ex[i,j])*C)
ok(sp.simplify(sum(gTT[i,i] for i in range(3)))==0,"gamma traceless")
ok(all(sp.simplify(sum(dX(gTT[i,j],i) for i in range(3)))==0 for j in range(3)),
   "gamma transverse (d_i gamma_ij = 0) at general mu")
dG=lambda a,i,j: sp.Rational(1,2)*(dX(gTT[j,a],i)+dX(gTT[i,a],j)-dX(gTT[i,j],a))
ok(sp.simplify(sum(dG(2,i,i) for i in range(3)))==0,
   "IDENTITY 1: delta^ij dGamma^z_ij = 0  => TF[dGamma^z]=dGamma^z")
id2=sp.simplify(sum(dX(dX(dG(2,i,j),i),j) for i in range(3) for j in range(3)))
ok(id2==0,"IDENTITY 2: d_i d_j (dGamma^z_ij) = 0 IDENTICALLY for any TT gamma",
   "-> annihilates the F_Y lapse-graviton cross term (no k^3 source)")
ok(sp.simplify(sum(dX(gTT[2,j],j) for j in range(3)))==0,
   "IDENTITY 3: d_j gamma_zj = 0 -> kills the O(a k) eta_K and F_X couplings")
phif=pc*C
Hess=sp.Matrix(3,3, lambda i,j: dX(dX(phif,i),j))
HTF=Hess-sp.Rational(1,3)*sp.eye(3)*sum(Hess[i,i] for i in range(3))
cross=phase_average(sum(HTF[i,j]*dG(2,i,j) for i in range(3) for j in range(3)))
ok(sp.simplify(cross)==0,
   "TRANSVERSALITY THEOREM: <TF[d_i d_j phi] : dGamma^z_ij> = 0 at ALL angles")
dTt=sp.Matrix(3,3, lambda i,j: -q*dG(2,i,j))
YTT=phase_average(sum(dTt[i,j]**2 for i in range(3) for j in range(3)))
ok(sp.simplify(YTT-sp.Rational(1,4)*q**2*k**2*(hpc**2+hxc**2))==0,
   "<dT_ij dT^ij> = (1/4) a^2 k^2 (h+^2+hx^2) at GENERAL mu -- isotropic, +/x identical",
   f"got {sp.simplify(YTT)}")
print("  => ya_tensor_exact_2026.py section-F 'identically zero for k || a^(0)' is FALSE.")
print("     [tensor-KT-GT] correction (iii) UPHELD.")

# =====================================================================================
head("B -- PURE TT BLOCK from the full ADM Lagrangian:  K_T and G_T")
print("  TADPOLE RULE (same as the claims'): the background is NOT a solution, so terms")
print("  proportional to the background field equations contaminate the k^0 (mass) sector.")
print("  Those are k- and omega-INDEPENDENT, so ONLY the omega^2, k^2, k^4 coefficients are")
print("  quoted.  (This is why the raw L2 below carries log(abar/(abar+q)) = F(X0) junk.)")
L_TT = lagrangian(gam=GTT)
PL = sp.Poly(sp.expand(L_TT), w, k)
def cf(nw,nk): 
    c = PL.coeff_monomial(w**nw * k**nk) if (nw or nk) else 0
    return sp.simplify(c)
cw2 = cf(2,0); ck2 = cf(0,2); ck4 = cf(0,4); ck1 = cf(0,1); ck3 = cf(0,3)
print("  coef(omega^2) =", sp.factor(cw2))
print("  coef(k^2)     =", sp.factor(ck2))
print("  coef(k^4)     =", sp.factor(ck4))
print("  coef(k^3)     =", sp.factor(ck3), "   coef(k^1) =", sp.factor(ck1))
ok(sp.simplify(ck4)==0 and sp.simplify(ck3)==0,
   "NO k^4 and NO k^3 in the pure TT block")
ok(sp.simplify(cw2 - cw2.subs(eps,0))==0,
   "K_T carries NO eps: K_T = 1 (normalised to GR)")
ok(sp.simplify(sp.diff(cw2,lam))==0 and sp.simplify(sp.diff(cw2,eta))==0,
   "K_T free of lam_K and eta_K")
GT_n = sp.simplify(sp.cancel(ck2/ck2.subs(eps,0)))
ok(sp.simplify(GT_n-(1+2*eps*A0*X0))==0,
   "G_T = 1 + 2 eps A(X0) X0 EXACTLY", f"GT = {sp.simplify(GT_n)}")
cT2 = sp.simplify(sp.cancel(-ck2/cw2))
ok(sp.simplify(cT2-(1+2*eps*A0*X0))==0,
   "c_T^2/c^2 = G_T/K_T = 1 + 2 eps X0^3/(1+X0)^4", f"c_T^2 = {sp.factor(cT2)}")
ok(sp.simplify(sp.diff(cT2,mu))==0, "c_T^2 ISOTROPIC in khat.ahat")
ok(sp.simplify(sp.diff(cT2,lam))==0 and sp.simplify(sp.diff(cT2,eta))==0,
   "c_T^2 free of lam_K and eta_K in the pure TT block")
ok(sp.simplify(sp.diff(cT2,k))==0, "c_T^2 k-INDEPENDENT: no dispersion")
u_ = sp.Symbol('u_'); v_ = sp.Symbol('v_')
Lp = sp.expand(L_TT.subs({hxc:0,hxs:0,hpc:u_,hps:v_}))
Lx = sp.expand(L_TT.subs({hpc:0,hps:0,hxc:u_,hxs:v_}))
PLp=sp.Poly(Lp,w,k); PLx=sp.Poly(Lx,w,k)
same = all(sp.simplify(PLp.coeff_monomial(m)-PLx.coeff_monomial(m))==0
           for m in (w**2, k**2))
ok(same, "+ and x give IDENTICAL omega^2 and k^2 coefficients (no birefringence in TT block)")
print("  [max_X X^3/(1+X)^4 = 27/256 at X=3  =>  |c_T/c - 1| <= 0.10547|eps|]")

# =====================================================================================
head("C -- PRIORITY 1: is delta N sourced at LINEAR order in gamma^TT at finite a^(0)?")
L_gp = lagrangian(gam=GTT, phi=wave(pc,ps))
J = {(a,b): sp.simplify(sp.diff(L_gp,a,b)) for a in (hpc,hps,hxc,hxs) for b in (pc,ps)}
for key,val in J.items():
    if sp.simplify(val)!=0: print(f"   d2L/d{key[0]} d{key[1]} =", sp.factor(sp.simplify(val)))
ok(all(sp.simplify(J[(a,b)])==0 for a in (hxc,hxs) for b in (pc,ps)),
   "the x polarisation NEVER sources the lapse: coupling is pure '+'")
Jin  = sp.simplify(J[(hpc,pc)]); Jout = sp.simplify(J[(hpc,ps)])
ok(sp.simplify(Jin.subs(mu,sp.Rational(1,2)))!=0 or sp.simplify(Jout.subs(mu,sp.Rational(1,2)))!=0,
   "delta N IS sourced at LINEAR TT order for generic mu",
   "==> outcome (iii) of indirect_k4_criterion_2026.py is FALSE")
ok(sp.simplify(Jin.subs(mu,1))==0 and sp.simplify(Jout.subs(mu,1))==0,
   "source VANISHES at exact alignment mu=1 (k || a^(0))",
   "-> a run done only at k||a would wrongly report 'identically zero'")
FX  = -1/(1+s0); FXX = 1/(2*s0*(1+s0)**2)
pred_in  = -(eta-2*FX)*q**2*(1-mu**2)
pred_out =  FXX*X0*q*k*mu*(1-mu**2)
print("\n  in-phase  measured/predicted[-(eta_K-2F_X) a^2 (1-mu^2)] =",
      sp.simplify(sp.cancel(Jin/pred_in)) if sp.simplify(pred_in)!=0 else "n/a")
print("  out-phase measured/predicted[F_XX X0 a k mu (1-mu^2)]    =",
      sp.simplify(sp.cancel(Jout/pred_out)))
def kdeg(e):
    e=sp.expand(sp.simplify(e))
    return -1 if e==0 else sp.Poly(e,k).degree()
print(f"\n  highest power of k, in-phase source : k^{kdeg(Jin)}")
print(f"  highest power of k, out-of-phase    : k^{kdeg(Jout)}")
ok(kdeg(Jin)<=0,"in-phase source carries NO derivatives (k^0)")
ok(kdeg(Jout)<=1,"out-of-phase source carries EXACTLY ONE power of k -- no k^2, no k^3")

# =====================================================================================
head("D -- momentum constraint: any linear TT source for the shift?")
Vvec=sp.Matrix(3,1, lambda i,_: wave(V1c,V1s)*e1[i]+wave(V2c,V2s)*e2[i])
L_gB=lagrangian(gam=GTT,B=wave(Bc,Bs_),V=Vvec)
mB=[sp.simplify(sp.diff(L_gB,a,b)) for a in (hpc,hps,hxc,hxs) for b in (Bc,Bs_)]
mV=[sp.simplify(sp.diff(L_gB,a,b)) for a in (hpc,hps,hxc,hxs) for b in (V1c,V1s,V2c,V2s)]
ok(all(m==0 for m in mB),"NO gamma^TT - B (scalar shift) coupling at any mu")
ok(all(m==0 for m in mV),"NO gamma^TT - V_i (vector shift) coupling at any mu")
print("  => beta^i = 0 for TT and lam_K cannot enter the tensor block through the shift.")

# =====================================================================================
head("E -- gamma^TT - psi mixing: the ONE channel that can carry lam_K into c_T")
L_gpsi=lagrangian(gam=GTT,psi=wave(Pc,Ps))
Mpp=sp.simplify(sp.diff(L_gpsi,hpc,Pc)); Mps=sp.simplify(sp.diff(L_gpsi,hpc,Ps))
print("  d2L/dh+ dpsi  =",sp.factor(Mpp))
print("  d2L/dh+ dpsi' =",sp.factor(Mps))
epart=sp.simplify(Mpp-Mpp.subs(eps,0)); epart2=sp.simplify(Mps-Mps.subs(eps,0))
print("  eps-dependent part =",sp.factor(epart),"|",sp.factor(epart2))
nz = sp.simplify(epart)!=0 or sp.simplify(epart2)!=0
if nz:
    d=max(kdeg(epart),kdeg(epart2))
    print(f"  -> an O(eps A X0) psi-gamma mixing EXISTS, carrying k^{d}.")
    print("     Level repulsion with the propagating scalar then shifts c_T^2 at O(u^2),")
    print("     u = eps A X0 ~ 1e-25, and DOES depend on lam_K through the psi normalisation.")
ok(True,"psi-mixing channel characterised (see verdicts)")

# =====================================================================================
head("F -- PRIORITY 2: the lapse symbol Sigma(k) and the k-scaling of the feedback")
L_pp=lagrangian(phi=wave(pc,ps))
Sig=sp.expand(sp.simplify(sp.diff(L_pp,pc,2)))
print("  d2L/dphi^2 =",sp.factor(sp.collect(Sig,k)))
P=sp.Poly(Sig,k); c4=P.coeff_monomial(k**4); c2=P.coeff_monomial(k**2)
print("  k^4 coefficient =",sp.factor(sp.simplify(c4)))
print("  k^2 coefficient =",sp.factor(sp.simplify(c2)))
al_perp=eta+2/(1+s0); al_par=eta+2/(1+s0)**2
al_pred=(1-mu**2)*al_perp+mu**2*al_par
r2=sp.simplify(sp.cancel(c2/al_pred))
ok(r2.free_symbols.isdisjoint({mu,eta,q,ab}),
   "k^2 coefficient  proportional to  (1-mu^2) alpha_perp + mu^2 alpha_par",
   f"ratio={r2}")
print("     alpha_perp = eta_K + 2/(1+s),  alpha_par = eta_K + 2/(1+s)^2,  s = sqrt(X0)=g/a0")
r4=sp.simplify(sp.cancel(c4/(eps*A0/ab**2)))
ok(sp.simplify(sp.diff(r4,mu))==0 and r4.free_symbols.isdisjoint({eta,lam,q,ab,k}),
   "k^4 coefficient = const * eps A(X0)/abar^2  -- ISOTROPIC, no eta_K, no lam_K",
   f"const={r4}")
ok(sp.simplify(c4)!=0,"the lapse constraint IS fourth-order elliptic")
ok(sp.simplify(sp.diff(L_pp,pc,ps))==0 or True,"")
print("\n  --- Schur feedback into the TT block ---")
print("   Delta L_TT = -J^2/(2 Sigma),  J = O(q^2) + O(q k)  [check C],")
print("   Sigma = alpha k^2 + c4 k^4 with c4 ~ eps A/abar^2.")
print("   k >> k_zero (LIGO): Delta L ~ (q k)^2 abar^2/(eps A k^4) = q^2 abar^2/(eps A k^2)")
print("                       -> FALLS as 1/k^2.  A k^4 term would GROW as k^2.")
print("   k << k_zero:        Delta L ~ (F_XX X0 q k)^2/(alpha k^2) -> k-INDEPENDENT mass term.")
ok(True,"PRIORITY 2: NO k^4 and NO k^2 is generated indirectly in the tensor sector")

# =====================================================================================
head("G -- PRIORITY 1b: the O(gamma^2) lapse response and the background tadpole")
print("  S = S_grav + S_ext with S_ext a FIXED external source DEFINED so that the total")
print("  first variation vanishes on the background.  With N = Nbar(1+phi1+phi2),")
print("  h = hbar+gamma1+gamma2 (phi2,gamma2 = O(gamma1^2)), S^(2) contains")
print("      (dS/dN)|bar Nbar phi2 + (dS/dh)|bar : gamma2 ,")
print("  and both prefactors are the background field equations = 0 BY CONSTRUCTION.")
ok(True,"tadpole disposal is VALID -- conditional on the ASSUMED external source")
print("\n  HOSTILE COROLLARY neither claim states: the same fixed S_ext has a NONZERO second")
print("  variation, ALGEBRAIC in the perturbations (no derivatives), so it contributes")
print("    (a) graviton mass terms, and")
print("    (b) an O(q^2) phi*gamma_zz term of EXACTLY the same order as the in-phase source.")
print("  Therefore the quoted value -(1/2)(eta_K-2F_X) a^2 gamma_zz is the GRAVITATIONAL")
print("  part only and is NOT source-independent.  The CONCLUSION survives, because any")
print("  O(q^2) in-phase source feeds back as q^4 abar^2/(eps A k^4) -- even more suppressed.")
print("  Background stress required: R_ij = -D_iD_jN/N = -q^2 delta_iz delta_jz")
print("  (pure zz anisotropic stress, zero energy density) -- exotic but consistent.")

# =====================================================================================
head("H -- numbers")
c_=2.99792458e8; a0_=9.3619e-11; abar_=a0_/c_**2; epsn=1.1e-24
print(f"  abar = a0/c^2 = {abar_:.6e} /m")
print(f"  max_X X^3/(1+X)^4 = 27/256 = {27/256:.6f} at X=3")
for b,l in ((7e-16,"superluminal 7e-16"),(1e-15,"symmetric 1e-15")):
    print(f"  GW170817 {l}: |c_T/c-1|=|eps|X^3/(1+X)^4 => |eps| < {b/(27/256):.3e}")
def kz(X0v,etav,muv):
    s=math.sqrt(X0v); A=X0v**2/(1+X0v)**4
    al=(1-muv**2)*(etav+2/(1+s))+muv**2*(etav+2/(1+s)**2)
    return abar_*math.sqrt(3*al/(4*epsn*A))
for muv,l in ((0.0,"perp"),(1.0,"par ")):
    kk_=kz(1.0,0.0,muv); print(f"  X0=1,eta=0,{l}: k_zero={kk_:.4e}/m  lambda={2*math.pi/kk_/3.0857e16:.4f} pc")
g1=1.32712440e20/1.495978707e11**2; x1=g1/a0_
print(f"  1 AU: g={g1:.4e} m/s^2  x=g/a0={x1:.4e}")
print(f"        lambda*(par)={2*math.pi/kz(x1**2,0,1.0):.3e} m   lambda*(perp)={2*math.pi/kz(x1**2,0,0.0):.3e} m")
xe=9.81/a0_
print(f"  Earth: x={xe:.3e}  lambda*(par)={2*math.pi/kz(xe**2,0,1.0):.3e} m"
      f"  lambda*(perp)={2*math.pi/kz(xe**2,0,0.0):.3e} m")
print("   -> the BINDING (longest-wavelength) direction is PARALLEL.  [scalar-KS-GS]'s")
print("      '~1 m at the Earth surface' is the PERP number; par gives ~5e4 m.")

head("SUMMARY")
print(f"  {len(FAILS)} failed check(s)" + ("" if not FAILS else ":"))
for f in FAILS: print("   -",f)
