import pathlib,json,hashlib,sys,subprocess
root=pathlib.Path(__file__).resolve().parents[4];own=pathlib.Path(__file__).resolve().parent;rel=own.relative_to(root)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
sources=[]
for stem,url,version,equations in [('bernardo_2021','https://arxiv.org/pdf/2101.00965v2','2101.00965v2, 27 Feb 2021','(2.1),(2.4),(3.28),(3.57),(3.65)-(3.71)'),('kobayashi_2011','https://arxiv.org/pdf/1105.5723v2','1105.5723v2, 3 Jun 2011','(56)-(64)')]:
 sources.append({'url':url,'version':version,'verified_equations':equations,'files':[{ 'path':str((own/'sources'/f'{stem}.{ext}').relative_to(root)), 'sha256':sha(own/'sources'/f'{stem}.{ext}')} for ext in ['pdf','txt']]})
(own/'sources.json').write_text(json.dumps({'search_scope':'Primary KGB self-tuning and full scalar constraint action; no global novelty claim','sources':sources,'restore':'Cached PDF/text files are ignored; restore exact URLs then verify hashes before source audit reruns. pdftotext -layout outputs must match recorded hashes.'},indent=2)+'\n')
inputs=[str(rel/x) for x in ['checks.py','REPORT.md','sources.json','sources/bernardo_2021.pdf','sources/bernardo_2021.txt','sources/kobayashi_2011.pdf','sources/kobayashi_2011.txt']]
contract={'claim_id':'SOL61-KGB-ROLLING-VACUUM-MAP-SOURCED-FORCE','mathematics':{'assertion_tested':'Exact functional KGB branch, full4D cosmological constraint coefficients, covariant logarithmic vacuum map, rolling static linear current and leading coupled force exponents','coefficient_domain':'SymPy exact identities and deterministic binary64 force slopes','conventions':'(-+++),X=-gradphi²/2,L=K-GBoxphi, minimal conserved matter; general n FRW, n3 source; G_N,b=1/(8pi Mpl²)','inputs':inputs,'bounds':{'z':[-.9,-.5,-.25,-.1,.5],'dimensionless_m':[1e-24,1e-21,1e-18],'r_over_rV':[.001,.01,1,100,1000],'slope_log_step':.0001,'q_rescaling':[1e-8,1,1e8]},'non_claims':['No full finite-gradient stability or EFT cutoff','Source response is leading weak-field subhorizon timelike expansion','No complete radiation/matter cosmology','No MOND or32pi selector','No global literature novelty']},'execution_artifacts':inputs,'software':[{'name':'Python','version':sys.version.split()[0]},{'name':'SymPy','version':__import__('sympy').__version__}],'randomness':{'used':False,'generator':'','seed':None}}
(own/'contract.json').write_text(json.dumps(contract,indent=2)+'\n')
(own/'input_snapshot.json').write_text(json.dumps({'requested_base':'81af81ba8a7207bca2bc4f13375c757feee7afcd','initial_HEAD':'81af81ba8a7207bca2bc4f13375c757feee7afcd','recorded_HEAD':subprocess.check_output(['git','rev-parse','HEAD'],cwd=root,text=True).strip(),'inputs':[{'path':x,'sha256':sha(root/x)} for x in inputs],'python_binary':str(pathlib.Path(sys.executable).resolve()),'python_binary_sha256':sha(pathlib.Path(sys.executable).resolve())},indent=2)+'\n')
