import Mathlib
noncomputable section
open scoped Real

#check Real.hasDerivAt_exp
#check Real.hasDerivAt_sin
#check Real.hasDerivAt_cos
#check HasDerivAt.mul
#check HasDerivAt.comp
#check HasDerivAt.const_mul
#check HasDerivAt.mul_const
#check HasDerivAt.add
#check HasDerivAt.deriv
#check Real.continuous_exp
#check Real.continuous_sin
#check Real.continuous_cos
#check Real.sin_zero
#check Real.cos_zero
#check Real.exp_zero
#check Real.sin_periodic
#check Real.cos_periodic
#check Function.Periodic.zsmul
#check Function.Periodic.nsmul
#check Function.Periodic.mul
#check Function.Periodic.add
#check Function.Periodic.comp
#check Real.sin_mul_sin
#check Real.cos_mul_cos
#check Real.sin_mul_cos
#check Real.cos_mul_sin
#check Real.sin_add
#check Real.cos_add
#check Continuous.comp
#check Continuous.mul
#check Continuous.add
#check Continuous.exp
#check Continuous.sin
#check Continuous.cos
#check ContinuousLinearMap.continuous
#check ContinuousLinearMap.hasDerivAt
#check DifferentiableAt.mul
#check DifferentiableAt.comp
#check DifferentiableAt.sin
#check DifferentiableAt.cos
#check DifferentiableAt.exp