import Mathlib

noncomputable section

#check Real.deriv_arctan
#check Real.deriv_arctan'
#check Filter.Tendsto.mono
#check Filter.Tendsto.mono_right
#check Filter.Tendsto.mono_left
#check nhdsWithin_le_nhds
#check nhds_le_nhdsWithin
#check Filter.tendsto_id
#check Filter.tendsto_id_atTop
#check Filter.Tendsto.atTop_mul_const
#check Filter.Tendsto.const_mul_atTop
#check Filter.Tendsto.atTop_div_const
#check Filter.Tendsto.div_const
#check Filter.Tendsto.div
#check Filter.Tendsto.div₀
#check Filter.Tendsto.mul
#check Filter.Tendsto.const_mul
#check Filter.Tendsto.const_nhds
#check measureTheory_integral_Ioi
#check intervalIntegral.integral_Ioi
#check MeasureTheory.integral_Ioi
#check MeasureTheory.integral_Ioi_eq_integral_Ici
#check MeasureTheory.integral_Ici
#check MeasureTheory.integral_eq_integral_Icc
#check intervalIntegral.integral_of_le
#check intervalIntegral.integral_congr
#check intervalIntegral.integral_const
#check intervalIntegral.integral_zero
#check intervalIntegral.integral_neg
#check HasDerivAt.deriv
#check DifferentiableAt.hasDerivAt
#check Real.arctan_neg
#check Real.arctan_bijective
#check tendsto_arctan_atTop
#check tendsto_nhdsWithin_iff
#check Filter.Tendsto.mono_right
#check tendsto_const_nhds_iff
#check one_div_pos
#check div_lt_iff₀
#check tendsto_atTop_add_const_right
#check Tendsto.add_const