import Mathlib

/-!
# MODULAR_S4_FIXED: which residual Z2 a modular fixed point can leave (atomos FS17, criteria 3a342d7)

Γ4 = PSL(2,Z)/Γ(4) ≅ S4, with presentation S² = (ST)³ = T⁴ = 1. Model: Equiv.Perm (Fin 4), T = finRotate 4 (the 4-cycle
i ↦ i+1), S = swap 2 3. At a fixed point τ0 = γ(i) the residual Z2 is generated by the image of γSγ⁻¹, a conjugate of S.

CERTIFIED (by `decide`, zero sorry):
- `T4`, `S2`, `ST3`: T⁴ = 1, S² = 1, (S T)³ = 1. These S, T satisfy Γ4's relations.
- `S_is_swap`: S is a transposition.
- `double_transposition_unreachable`: no conjugate g S g⁻¹ equals any of the three double transpositions (0 1)(2 3),
  (0 2)(1 3), (0 3)(1 2). No double transposition is a fixed-point residual Z2.
- `transposition_reachable`: every transposition swap a b (a ≠ b) is a conjugate of S.
READING (FS17 Q1, Python): in the T-diagonal charged basis, TM1's residual SU is a transposition, so it is reachable, while TM2's
residual S_King is a double transposition, so it is not. Note that the modular S and King's S are different elements.
CITED, not certified: a point of the upper half plane has a cyclic stabiliser in PSL(2,Z) (order 1, 2 or 3), so one modulus
cannot leave the charged-lepton Z3 and the neutrino Z2 together. The isomorphism Γ4 ≅ S4 is cited too.
-/

namespace ModularS4

def T : Equiv.Perm (Fin 4) := finRotate 4
def S : Equiv.Perm (Fin 4) := Equiv.swap 2 3

theorem T4 : T ^ 4 = 1 := by decide
theorem S2 : S ^ 2 = 1 := by decide
theorem ST3 : (S * T) ^ 3 = 1 := by decide
theorem S_is_swap : S.IsSwap := ⟨2, 3, by decide, rfl⟩

theorem double_transposition_unreachable :
    ∀ g : Equiv.Perm (Fin 4), g * S * g⁻¹ ≠ Equiv.swap 0 1 * Equiv.swap 2 3 ∧ g * S * g⁻¹ ≠ Equiv.swap 0 2 * Equiv.swap 1 3 ∧
      g * S * g⁻¹ ≠ Equiv.swap 0 3 * Equiv.swap 1 2 := by decide

theorem transposition_reachable :
    ∀ a b : Fin 4, a ≠ b → ∃ g : Equiv.Perm (Fin 4), g * S * g⁻¹ = Equiv.swap a b := by decide

end ModularS4

#print axioms ModularS4.T4
#print axioms ModularS4.S2
#print axioms ModularS4.ST3
#print axioms ModularS4.S_is_swap
#print axioms ModularS4.double_transposition_unreachable
#print axioms ModularS4.transposition_reachable
