#!/usr/bin/env python3
"""
ROUTE 4 (a) -- STATIONARY POINT / EXTREMUM of an S3-invariant flavor potential.

QUESTION: Is the 45-deg sqrt-mass configuration (r=sqrt2, cos^2=3/4 to (1,1,1)) the
EXTREMUM / stationary configuration of a natural S3-invariant potential on the sqrt-mass
vector v=(sqrt m_e, sqrt m_mu, sqrt m_tau) -- a potential DEFINED WITHOUT mentioning
2/3 / r=sqrt2 / cos^2=3/4 / Koide?

This is the Sumino/Yukawaon-class idea done HONESTLY (define the potential from S3
invariants, then look where dV=0 lands), but with the discipline: trace the definition for
a smuggled 2/3, and demand the extremum LAND at r=sqrt2 exactly, not be tuned there.

S3 acts on v by permuting components. The S3-invariant polynomials of v are generated by
the power sums (Newton):
    p1 = sum v_i        (degree 1, the 'democratic'/trivial mode)
    p2 = sum v_i^2      (degree 2, = total length^2)
    p3 = sum v_i^3      (degree 3)
Equivalently elementary symmetric e1,e2,e3. ANY S3-invariant potential V(v) is a function
V(p1,p2,p3). We will:
  (1) Confirm r is the SCALE-INVARIANT shape coordinate: r^2/2 = |std|^2/|dem|^2, and
      Q = p2/p1^2 = 1/3 + r^2/6. So r is fixed by the single ratio p2/p1^2 once we mod out
      overall scale. A potential's *shape* extremum is a stationary point of p2/p1^2 (or any
      function of the shape) on the unit sphere / at fixed scale.
  (2) Show the BRUTAL FACT: at fixed p1 (or fixed |v|), the ONLY S3-invariant stationary
      shapes are the SYMMETRIC ones -- the fully-democratic v=(1,1,1) (r=0) and the maximally
      broken permutation-axis configs -- NOT a generic 45-deg. So a single-invariant potential
      has NO stationary point at r=sqrt2 unless the potential is BUILT to put one there.
  (3) Enumerate the natural low-degree S3-invariant potentials V(p1,p2,p3) WITHOUT a 2/3 and
      sympy-solve dV=0 on the shape; check whether any forces r=sqrt2 with the extremum
      VALUE not smuggled. Trace each for a hidden 2/3.

DISCIPLINE: (i) definition must not contain 2/3/sqrt2/cos^2=3/4. (ii) extremum at r=sqrt2
EXACT. (iii) must be lepton-specific-compatible (handled in r4d). A flavor-blind potential
that forces 45deg is falsified by quarks.
"""
import sympy as sp

sp.init_printing()
print("="*80)
print("ROUTE 4(a) -- is r=sqrt2 the EXTREMUM of an S3-invariant flavor potential?")
print("="*80)

a, b, c = sp.symbols('a b c', positive=True)   # a=sqrt m_e, b=sqrt m_mu, c=sqrt m_tau
v = sp.Matrix([a, b, c])
n = sp.Matrix([1, 1, 1])

# scale-invariant shape: Q = p2/p1^2, and r via Q=1/3+r^2/6.
p1 = a + b + c
p2 = a**2 + b**2 + c**2
p3 = a**3 + b**3 + c**3
Q  = sp.simplify(p2/p1**2)
print("\n[1] shape coordinate")
print("    Q = p2/p1^2 = (sum m)/(sum sqrt m)^2   (Koide ratio, but used only as a COORDINATE)")
# r^2 = 6Q-2; r=sqrt2 <=> Q=2/3 <=> p2/p1^2 = 2/3.
r2_of_Q = 6*Q - 2
print("    r^2 = 6Q-2 ;  r=sqrt2  <=>  Q=2/3  <=>  p2/p1^2 = 2/3 (the target, NOT in any V below)")

# --------------------------------------------------------------------------
# [2] Stationary SHAPES of a generic single-invariant potential at fixed scale.
#     Use Lagrange: extremize f(v) subject to g(v)=const. The natural 'scale' constraints
#     are p1=const (fixed democratic length) or p2=const (fixed total length).
# --------------------------------------------------------------------------
print("\n[2] Stationary shapes: extremize an S3-invariant f at fixed scale (Lagrange).")
print("    The S3-symmetric critical points are forced by symmetry; check what r they have.")

lam = sp.symbols('lambda')

def stationary(fexpr, gexpr, label):
    # solve grad f = lam grad g, plus g=1 (set scale)
    eqs = [sp.diff(fexpr, x) - lam*sp.diff(gexpr, x) for x in (a, b, c)]
    eqs.append(gexpr - 1)
    sols = sp.solve(eqs, [a, b, c, lam], dict=True)
    print(f"\n  --- extremize {label} ---")
    out = []
    for s in sols:
        try:
            av, bv, cv = s[a], s[b], s[c]
        except KeyError:
            continue
        # only keep real, nonnegative shapes
        vals = [av, bv, cv]
        if any(val.free_symbols for val in vals):
            continue
        if any(sp.im(val) != 0 for val in vals):
            continue
        if any(sp.re(val) < 0 for val in vals):
            continue
        vv = sp.Matrix(vals)
        pp1 = sum(vals); pp2 = sum(x**2 for x in vals)
        if pp1 == 0:
            continue
        Qs = sp.nsimplify(pp2/pp1**2)
        r2 = sp.nsimplify(6*Qs - 2)
        out.append((tuple(vals), Qs, r2))
    seen = set()
    for vals, Qs, r2 in out:
        key = tuple(sorted([sp.nsimplify(x) for x in vals], key=lambda z: float(z)))
        if key in seen:
            continue
        seen.add(key)
        rstr = "sqrt(2)" if sp.simplify(r2-2)==0 else str(r2)
        flag = "  <==== r=sqrt2 !!" if sp.simplify(r2-2)==0 else ""
        print(f"     shape={tuple(str(x) for x in vals)}  Q={Qs}  r^2={r2}  (r={rstr}){flag}")
    if not out:
        print("     (no admissible nonneg real stationary shape besides trivial)")

# Try the lowest natural invariants as the 'potential', constrained to fixed scale p2=1.
stationary(p3, p2, "f=p3 at fixed p2 (length-normalized cubic)")
stationary(p1, p2, "f=p1 at fixed p2 (democratic projection, length-normalized)")
# and at fixed p1=1:
stationary(p2, p1, "f=p2 at fixed p1 (total length at fixed democratic)")
stationary(p3, p1, "f=p3 at fixed p1")

print("""
  READING: the stationary shapes of a SINGLE S3-invariant at fixed scale are the
  symmetric configs -- fully democratic (r=0) and the one-component / two-equal axes
  (r large). r=sqrt2 is a GENERIC interior shape and is NOT a stationary point of any
  single low invariant. (If one had appeared at r=sqrt2 here it would be a real lead.)
""")

# --------------------------------------------------------------------------
# [3] Two-invariant potentials V(Q) -- the Sumino/Yukawaon move. The ONLY S3+scale-
#     invariant shape coordinate is Q itself. So the most general scale-invariant S3
#     potential ON THE SHAPE is V = F(Q) for arbitrary F. dV/d(shape)=0 means F'(Q)*dQ=0,
#     i.e. EITHER F'(Q)=0 (a tuned stationary value of F -- SMUGGLE: you must put the
#     min of F at Q=2/3 by hand) OR dQ=0 (Q stationary in shape = the symmetric configs,
#     r=0 or boundary). So a scale-invariant S3 potential CANNOT have a non-symmetric
#     interior extremum at r=sqrt2 without F being tuned to extremize at Q=2/3.
# --------------------------------------------------------------------------
print("[3] General scale-invariant S3 potential on the shape is V=F(Q). Extremum analysis:")
Qsym = sp.symbols('Q', positive=True)
F = sp.Function('F')
print("    dV = F'(Q) dQ.  Interior shape-stationarity (dQ != 0 generic) forces F'(Q)=0,")
print("    i.e. you must TUNE F so its stationary value sits at Q=2/3 -> SMUGGLES 2/3.")
print("    The only definition-clean stationary shapes (dQ=0) are the SYMMETRIC ones (r=0,")
print("    boundary). => a scale-invariant S3 potential does NOT non-circularly land r=sqrt2.")

# --------------------------------------------------------------------------
# [4] The ESCAPE a scale-invariant V cannot give: a DIMENSIONFUL potential with a
#     competition between a degree-d 'attractive' term and a degree-d' 'repulsive' term
#     can fix BOTH scale AND shape. Test the most natural: V = A p2 - B p1^2  (the unique
#     two-term quadratic-in-v, S3-invariant, balancing total length vs democratic length).
#     This is the canonical 'mass-squared vs democratic' competition. Does its minimum
#     land at a definite shape r? And is 2/3 smuggled via A/B?
# --------------------------------------------------------------------------
print("\n[4] dimensionful 2-term quadratic V = A*p2 - B*p1^2  (length vs democratic), A,B>0")
A, B = sp.symbols('A B', positive=True)
V = A*p2 - B*p1**2
# This is a quadratic form; minimum over v>=0. grad:
grad = [sp.diff(V, x) for x in (a, b, c)]
print("    grad V =", [sp.simplify(g) for g in grad])
# = 2A v_i - 2B p1. Setting =0: v_i = (B/A) p1 for ALL i => v democratic (r=0), OR unbounded.
sol = sp.solve([sp.Eq(g, 0) for g in grad], [a, b, c], dict=True)
print("    grad=0 solutions:", sol, " -> all components equal (DEMOCRATIC, r=0), not r=sqrt2.")
print("    The quadratic competition only ever picks the SYMMETRIC point (or runs away);")
print("    it CANNOT pick a 45-deg broken shape. (Eigen-structure: democratic is the soft")
print("    mode, breaking it requires a higher-degree term that itself carries the scale.)")

print("""
[VERDICT 4a] An S3-invariant flavor potential does NOT non-circularly extremize at r=sqrt2:
  - single invariant at fixed scale -> stationary shapes are SYMMETRIC (r=0 or boundary);
  - general scale-invariant V=F(Q) -> interior extremum requires TUNING F'(Q)=0 at Q=2/3
    (= smuggling 2/3, the 168th re-labeling);
  - the natural dimensionful quadratic competition -> minimum is DEMOCRATIC (r=0).
  No clean potential puts a stationary point at the 45-deg shape. (Both ways: had one
  appeared at r=sqrt2 from a 2/3-free V, it would be flagged for max re-verification.)
""")
