from pathlib import Path
import json,math,hashlib,difflib
repo=Path(__file__).resolve().parents[3]; dest=Path(__file__).resolve().parent
source=repo/'qwen_claude_field_theory/papers_2026/PAPER6_kappa_no_go_2026.tex'
numbers=repo/'qwen_claude_field_theory/papers_2026/mnras_submission_2026_v2/paper_numbers.json'
j=json.loads(numbers.read_text()); budget=j['S2']['B_budget']; sigma=math.sqrt(sum(budget[k]**2 for k in ['ml_grid','gas','stat']))
assert abs(sigma-j['S2']['sigma_B'])<1e-14
assert abs(j['S2']['kappa_B']-.5470366412131537)<1e-15
original=source.read_text(); s=original
replacements=[
(r'(corrects the stability statement of Sec.~3)',r'(review copy: stability correction in Sec.~\ref{sec:fourform}; historical precision claims clarified)'),
(r'(measured $0.465\pm0.076$ from the baryonic Tully--Fisher intercept and $0.551\pm0.043$ by a distance-free estimator)',r'(historical baryonic Tully--Fisher estimate $0.465\pm0.076$; current distance-free shape-only estimate $0.5470\pm0.1747$ with the combined uncertainty budget)'),
(r', and we answer in the negative with a theorem and three computed dead ends.',r'. For this action and the tested repairs, we find a zero-mode obstruction and three failed constructions.'),
(r'On the observable side the only coefficient-free alternative left standing,',r'In the historical \texttt{k03} comparison, the coefficient-free alternative retained in the examined set,'),
(r'and is exactly degenerate with the $H_0$ tension:',r'and has an algebraic degeneracy with $H_0$ at fixed $\Omega_\Lambda$; the historical numerical illustration is that'),
(r'Every number is produced by a committed script with checks that can fail.',r'The historical calculations and their current corrections are identified separately below; no updated likelihood or $H_0$ precision claim is inferred from the superseded uncertainty.'),
(r'The \emph{empirical} one, $\kappa_{\rm obs}\simeq\tfrac12$, is a measurement with a $10$--$16\%$ error and is the frozen target of the programme.',r'The \emph{empirical} one, $\kappa_{\rm obs}\simeq\tfrac12$, is an estimate conditional on calibration choices, while $\kappa=\tfrac12$ remains the fitted target. The historical BTFR estimate has about $16\%$ uncertainty. The current shape-only record gives $\kappa_B=0.5470366412$ and $\sigma_B=0.1747148458$ (about $32\%$), with $\sigma_B^2=\sigma_{\rm ML\,grid}^2+\sigma_{\rm gas}^2+\sigma_{\rm stat}^2$; the three components are $0.1363438007$, $0.0446433321$, and $0.0997126785$. The older distance-free $0.551\pm0.043$ held the bulge mass-to-light calibration fixed and is retained below only as a historical conditional calculation, not as the current error budget.'),
(r'four simple candidates sit inside two sigma of the measurements.',r'the historical candidate comparison did not uniquely select the rational coefficient. The current combined error budget is not used here to construct a new joint likelihood.'),
(r'fix the primitive\'s zero by the only principle available to a local action, an empty Newtonian vacuum:',r'fix the primitive\'s zero by the tested empty-Newtonian-vacuum prescription:'),
(r'at least $6.8\sigma$ from the data;',r'at least $6.8\sigma$ in the historical conditional estimator comparison (not a significance recomputed with the current uncertainty budget);'),
(r'Closed on magnitude, independently of sign and of the $O(1)$ convention.',r'This tested averaging prescription fails in magnitude, independently of sign and of the $O(1)$ convention.'),
(r'\section{Reframing: the four-form promotion}',r'\section{Reframing: the four-form promotion}\label{sec:fourform}'),
(r'Amendment 13 records its instability.',r'a proposed Amendment 13 would record its instability; that amendment has not been filed in this review copy.'),
(r'Repairs 1 and 2 exhaust the principles that act on the scalar\'s zero;',r'The two tested repairs do not remove the scalar zero-mode obstruction;'),
(r'(This is not Milgrom\'s 1999 de Sitter--Unruh construction, which fixes $a_0=2cH_\Lambda$ and is excluded at $15.6\sigma$ in this programme.) Script \texttt{k03} puts it against what the observable side can do:',r'(The historical \texttt{k03} comparison distinguished this from Milgrom\'s 1999 de Sitter--Unruh construction, $a_0=2cH_\Lambda$, and quoted $15.6\sigma$ under its then-adopted estimator inputs. That significance is not a current inference.) The following \texttt{k03} numbers are historical conditional calculations, preserved to identify their inputs and limitations; their significances, likelihood ratio, forecasts and $H_0$ uncertainties have not been updated using $0.5470\pm0.1747$:'),
(r'the distance-free value $0.551\pm0.043$ is $1.2\sigma$ and $2.1\sigma$; combined, $\ln[L(\tfrac12)/L(0.461)]=+1.4$, undecided;',r'the historical fixed-calibration distance-free value $0.551\pm0.043$ gave $1.2\sigma$ and $2.1\sigma$; the historical combination gave $\ln[L(\tfrac12)/L(0.461)]=+1.4$. These conditional results are superseded as present-day precision claims; no current combined likelihood is asserted here;'),
(r'Run the other way, a frozen $\kappa=\tfrac12$ turns $a_0$ into an $H_0$ meter: the distance-free $a_0$ gives $H_0=74\pm6$ and the BTFR $a_0$ gives $63\pm10$ km s$^{-1}$ Mpc$^{-1}$, straddling the tension.',r'In the same historical calculation, fixing $\kappa=\tfrac12$ converted $a_0$ into an $H_0$ estimate: the then-adopted distance-free input gave $H_0=74\pm6$ and the BTFR input gave $63\pm10$ km s$^{-1}$ Mpc$^{-1}$. The distance-free $\pm6$ is a historical conditional uncertainty and is not supported by the current combined budget. This review copy does not recompute an $H_0$ posterior.'),
(r'the distance-free estimator avoids this and is the one to trust.',r'the distance-free estimator avoids that particular distance dependence but remains subject to its stellar and gas calibration budget.'),
(r'with $0.461$ recorded as the one un-excluded principle-shaped alternative,',r'with $0.461$ retained as an alternative in the examined historical set,'),
(r'The dark-sector completion hunt of the programme is frozen behind this result; its most recent candidate, a thermal relic, was closed the same day as a pincer with no interior between $N_{\rm eff}$, the radial acceleration relation and the cluster profile.',r'At the original 6 September checkpoint, the then-current dark-sector thermal-relic candidate had no interior in its tested $N_{\rm eff}$, radial-acceleration-relation and cluster-profile window. That historical result is scoped to the tested candidate and does not describe the status of later dark-sector continuations.'),
(r'\sloppy All numbers come from four scripts',r'\sloppy The historical calculations came from four scripts'),
(r'each with checks that can fail and whose FAIL lines mark requirements the framework does not meet: 3 of 6, 3 of 4, 4 of 4 and 2 of 6 respectively. Both $a_0$ footings ($9.3619\times10^{-11}$ and $1.1279\times10^{-10}$ m s$^{-2}$) are carried throughout.',r'each with checks that can fail. Their historical requirement-failure counts were 3 of 6, 3 of 4, 4 of 4 and 2 of 6 respectively; these counts are not a present validation of the withdrawn F6 stability check or of superseded estimator precision. The historical numerical calculations, including the four-form dimensional instability scales, used $a_0=9.3619\times10^{-11}$ and $1.1279\times10^{-10}$ m s$^{-2}$. The current campaign footings are $9.3603\times10^{-11}$ and $1.1312\times10^{-10}$ m s$^{-2}$; this review copy does not silently rescale the historical calculations to them. The current $\kappa_B$ and combined budget quoted above are read from \texttt{papers\_2026/mnras\_submission\_2026\_v2/paper\_numbers.json}, fields \texttt{S2.kappa\_B}, \texttt{S2.sigma\_B}, and \texttt{S2.B\_budget}; the three-component quadrature was checked directly.'),
(r'The one class of principle that removes an additive zero mode without choosing a constant is a global constraint',r'The tested class of principle for removing an additive zero mode without choosing a constant is a global constraint'),
(r'a positive $\Lambda$ must come from the geometric or boundary sector, where the only coefficient-free identification in hand is',r'within the examined constructions, the remaining positive-vacuum route lies in the geometric or boundary sector, where the coefficient-free identification considered here is'),
(r'nothing achieves (a) and (c) together.',r'none of the examined constructions achieves (a) and (c) together.'),

]
# Avoid escaping apostrophes in ordinary TeX prose while keeping replacement literals auditable.
replacements=[(a.replace("\\'","'"),b.replace("\\'","'")) for a,b in replacements]
for a,b in replacements:
 assert s.count(a)==1,(a[:90],s.count(a));s=s.replace(a,b)
# Scope dimensional values and existing withdrawal in the four-form paragraph before the numerical details.
needle='The promotion has a consequence that must be checked rather than inherited.'
s=s.replace(needle,needle+' The dimensional values in this section retain the historical numerical footings listed under Reproducibility; the dimensionless instability band refers to the specified kernel and couplings.')
copy=dest/'PAPER6_v2_review.tex';copy.write_text(s)
(dest/'PAPER6_v2_review.patch').write_text(''.join(difflib.unified_diff(original.splitlines(True),s.splitlines(True),fromfile=str(source.relative_to(repo)),tofile=str(copy.relative_to(repo)))))
provenance={'original_source':str(source.relative_to(repo)),'original_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'numbers_source':str(numbers.relative_to(repo)),'numbers_sha256':hashlib.sha256(numbers.read_bytes()).hexdigest(),'copy_sha256':hashlib.sha256(copy.read_bytes()).hexdigest(),'kappa_B':j['S2']['kappa_B'],'sigma_B_recorded':j['S2']['sigma_B'],'sigma_B_recomputed':sigma,'budget_components':{k:budget[k] for k in ['ml_grid','gas','stat']},'combined_relative_uncertainty':sigma/j['S2']['kappa_B'],'equation_and_theorem_bodies_changed':False,'external_publication':False}
(dest/'PAPER6_v2_review_provenance.json').write_text(json.dumps(provenance,indent=2));print(json.dumps(provenance,indent=2))
