#!/usr/bin/env python3
"""Exact real-mode FLRW ADM geometry for the frozen CDE-L4C-2Delta action.

The module deliberately stops before a quadratic action is asserted.  It
constructs the exact lapse, spatial metric, shift, acceleration, intrinsic
curvature, extrinsic curvature and multiplier operators for

    N = 1 + epsilon Phi cos(theta),
    h_ij = a^2 exp[-2 epsilon Psi cos(theta)] delta_ij,
    N_i = -epsilon k B sin(theta) delta_ix,

where ``theta=k x`` and a spatial x derivative is therefore
``k*d/dtheta``.  Downstream calculations can take epsilon coefficients and
the normalized real-mode average with the two public helper functions.
"""

from __future__ import annotations

from copy import deepcopy
from functools import lru_cache
from typing import Any

import sympy as sp


def series_coefficient(
    expression: sp.Expr | sp.MatrixBase,
    parameter: sp.Symbol,
    order: int,
) -> sp.Expr | sp.MatrixBase:
    """Return one Taylor coefficient, calculated from ``expression``.

    Matrix inputs are handled entry by entry so the same operation can be
    used on exact ADM tensors without first projecting them onto components.
    """

    if order < 0:
        raise ValueError("series order must be non-negative")
    if isinstance(expression, sp.MatrixBase):
        return expression.applyfunc(
            lambda entry: series_coefficient(entry, parameter, order)
        )
    truncated = sp.series(expression, parameter, 0, order + 1).removeO()
    return sp.simplify(sp.expand(truncated).coeff(parameter, order))


def exact_real_mode_average(expression: sp.Expr, theta: sp.Symbol) -> sp.Expr:
    """Return the exact normalized average over one real Fourier period."""

    return sp.simplify(
        sp.integrate(sp.expand_trig(expression), (theta, 0, 2 * sp.pi))
        / (2 * sp.pi)
    )


@lru_cache(maxsize=2)
def _derive_full_flrw_adm_geometry_cached(
    shift_sign: int = -1,
) -> dict[str, Any]:
    """Construct the exact scalar-sector ADM geometry before expansion.

    ``shift_sign=-1`` is the frozen convention.  The opposite sign is
    accepted only as a mutation control: it must reverse the shift-dependent
    kinetic mixing generated by the same geometric definitions.
    """

    if shift_sign not in (-1, 1):
        raise ValueError("shift_sign must be -1 (frozen) or +1 (mutation)")

    epsilon, theta = sp.symbols("epsilon theta", real=True)
    k, scale = sp.symbols("k a", positive=True, nonzero=True)
    H = sp.symbols("H", real=True)
    Phi, Psi, B, Psi_dot = sp.symbols(
        "Phi Psi B Psi_dot", real=True
    )

    mode = sp.cos(theta)
    s = epsilon * Psi * mode
    lapse = 1 + epsilon * Phi * mode
    conformal_factor = scale**2 * sp.exp(-2 * s)
    spatial_metric = conformal_factor * sp.eye(3)
    spatial_inverse = spatial_metric.inv().applyfunc(sp.simplify)
    spatial_determinant = sp.simplify(spatial_metric.det())
    sqrt_h = scale**3 * sp.exp(-3 * s)
    shift_covector = sp.Matrix(
        [shift_sign * epsilon * k * B * sp.sin(theta), 0, 0]
    )
    shift_vector = (spatial_inverse * shift_covector).applyfunc(sp.simplify)

    def spatial_derivative(expression: sp.Expr, index: int) -> sp.Expr:
        """Cartesian derivative with theta=kx and y,z-independent fields."""

        if index == 0:
            return k * sp.diff(expression, theta)
        return sp.Integer(0)

    # Levi-Civita connection of the exact spatial metric.
    christoffel = [
        [
            [
                sp.simplify(
                    sp.Rational(1, 2)
                    * sum(
                        spatial_inverse[upper, ell]
                        * (
                            spatial_derivative(spatial_metric[ell, right], left)
                            + spatial_derivative(
                                spatial_metric[ell, left], right
                            )
                            - spatial_derivative(
                                spatial_metric[left, right], ell
                            )
                        )
                        for ell in range(3)
                    )
                )
                for right in range(3)
            ]
            for left in range(3)
        ]
        for upper in range(3)
    ]

    # R_ij = d_k Gamma^k_ij - d_j Gamma^k_ik
    #        + Gamma^k_ij Gamma^l_kl - Gamma^l_ik Gamma^k_jl.
    ricci_components: list[list[sp.Expr]] = []
    for left in range(3):
        row = []
        for right in range(3):
            component = sp.Integer(0)
            for upper in range(3):
                component += spatial_derivative(
                    christoffel[upper][left][right], upper
                )
                component -= spatial_derivative(
                    christoffel[upper][left][upper], right
                )
                for ell in range(3):
                    component += (
                        christoffel[upper][left][right]
                        * christoffel[ell][upper][ell]
                    )
                    component -= (
                        christoffel[ell][left][upper]
                        * christoffel[upper][right][ell]
                    )
            row.append(sp.simplify(component))
        ricci_components.append(row)
    spatial_ricci = sp.Matrix(ricci_components)
    three_curvature = sp.simplify(
        sum(
            spatial_inverse[left, right] * spatial_ricci[left, right]
            for left in range(3)
            for right in range(3)
        )
    )

    acceleration_covector = sp.Matrix(
        [spatial_derivative(sp.log(lapse), index) for index in range(3)]
    ).applyfunc(sp.simplify)
    acceleration_vector = (
        spatial_inverse * acceleration_covector
    ).applyfunc(sp.simplify)

    def scalar_laplacian(expression: sp.Expr) -> sp.Expr:
        flux_divergence = sp.Integer(0)
        for left in range(3):
            contravariant_gradient = sum(
                spatial_inverse[left, right]
                * spatial_derivative(expression, right)
                for right in range(3)
            )
            flux_divergence += spatial_derivative(
                sqrt_h * contravariant_gradient, left
            )
        return sp.factor(flux_divergence / sqrt_h)

    divergence_acceleration = scalar_laplacian(sp.log(lapse))
    C_slip = sp.factor(three_curvature - 4 * divergence_acceleration)

    def time_derivative(expression: sp.Expr) -> sp.Expr:
        # The spatial metric depends on time only through a(t) and Psi(t).
        return sp.simplify(
            H * scale * sp.diff(expression, scale)
            + Psi_dot * sp.diff(expression, Psi)
        )

    covariant_shift_derivative = sp.MutableDenseMatrix.zeros(3, 3)
    for left in range(3):
        for right in range(3):
            covariant_shift_derivative[left, right] = sp.simplify(
                spatial_derivative(shift_covector[right], left)
                - sum(
                    christoffel[upper][left][right]
                    * shift_covector[upper]
                    for upper in range(3)
                )
            )

    metric_time_derivative = spatial_metric.applyfunc(time_derivative)
    extrinsic_curvature = sp.Matrix(
        3,
        3,
        lambda left, right: sp.simplify(
            (
                metric_time_derivative[left, right]
                - covariant_shift_derivative[left, right]
                - covariant_shift_derivative[right, left]
            )
            / (2 * lapse)
        ),
    )
    mixed_extrinsic_curvature = (
        spatial_inverse * extrinsic_curvature
    ).applyfunc(sp.simplify)
    extrinsic_trace_direct = sp.simplify(
        sum(
            spatial_inverse[left, right] * extrinsic_curvature[left, right]
            for left in range(3)
            for right in range(3)
        )
    )
    extrinsic_trace_matrix = sp.simplify(
        sp.trace(mixed_extrinsic_curvature)
    )

    D2_C_slip = scalar_laplacian(C_slip)
    D2_K = scalar_laplacian(extrinsic_trace_direct)

    kinetic_scalar = sp.simplify(
        sp.trace(mixed_extrinsic_curvature * mixed_extrinsic_curvature)
        - extrinsic_trace_direct**2
    )
    eh_kinetic_density = sp.factor(lapse * sqrt_h * kinetic_scalar)

    return {
        "epsilon": epsilon,
        "theta": theta,
        "k": k,
        "scale_factor": scale,
        "H": H,
        "Phi": Phi,
        "Psi": Psi,
        "B": B,
        "Psi_dot": Psi_dot,
        "mode": mode,
        "conformal_exponent": s,
        "lapse": lapse,
        "spatial_metric": spatial_metric,
        "spatial_inverse": spatial_inverse,
        "spatial_determinant": spatial_determinant,
        "sqrt_h": sqrt_h,
        "shift_sign": sp.Integer(shift_sign),
        "shift_covector": shift_covector,
        "shift_vector": shift_vector,
        "spatial_christoffel": christoffel,
        "spatial_ricci": spatial_ricci,
        "acceleration_covector": acceleration_covector,
        "acceleration_vector": acceleration_vector,
        "divergence_acceleration": divergence_acceleration,
        "three_curvature": three_curvature,
        "C_slip": C_slip,
        "metric_time_derivative": metric_time_derivative,
        "covariant_shift_derivative": covariant_shift_derivative,
        "extrinsic_curvature": extrinsic_curvature,
        "mixed_extrinsic_curvature": mixed_extrinsic_curvature,
        "extrinsic_trace_direct": extrinsic_trace_direct,
        "extrinsic_trace_matrix": extrinsic_trace_matrix,
        "D2_C": D2_C_slip,
        "D2_C_slip": D2_C_slip,
        "D2_K": D2_K,
        "eh_kinetic_scalar": kinetic_scalar,
        "eh_kinetic_density": eh_kinetic_density,
    }


def derive_full_flrw_adm_geometry(shift_sign: int = -1) -> dict[str, Any]:
    """Return an isolated copy of the cached exact symbolic construction.

    The construction is expensive enough to cache, but its result contains
    mutable matrices and a mutable dictionary.  A deep copy prevents a
    caller's diagnostic mutation from changing later derivations.
    """

    return deepcopy(_derive_full_flrw_adm_geometry_cached(shift_sign))


if __name__ == "__main__":
    geometry = derive_full_flrw_adm_geometry()
    print("exact FLRW ADM geometry constructed")
    print("R3 =", geometry["three_curvature"])
    print("K =", geometry["extrinsic_trace_direct"])
