#!/usr/bin/env python3
"""Exact real-mode FLRW ADM geometry for the frozen CDE-L4C-2Delta action.

The module first constructs the exact lapse, spatial metric, shift,
acceleration, intrinsic curvature, extrinsic curvature and multiplier
operators for

    N = 1 + epsilon Phi cos(theta),
    h_ij = a^2 exp[-2 epsilon Psi cos(theta)] delta_ij,
    N_i = -epsilon k B sin(theta) delta_ix,

where ``theta=k x`` and a spatial x derivative is therefore
``k*d/dtheta``.  It then generates the complete on-shell quadratic FLRW
action and its finite-k time-dependent Dirac chain.  Downstream calculations
can take epsilon coefficients and the normalized real-mode average with the
two public helper functions.
"""

from __future__ import annotations

from copy import deepcopy
from functools import lru_cache
from typing import Any

import sympy as sp


def series_coefficient(
    expression: sp.Expr | sp.MatrixBase,
    parameter: sp.Symbol,
    order: int,
) -> sp.Expr | sp.MatrixBase:
    """Return one Taylor coefficient, calculated from ``expression``.

    Matrix inputs are handled entry by entry so the same operation can be
    used on exact ADM tensors without first projecting them onto components.
    """

    if order < 0:
        raise ValueError("series order must be non-negative")
    if isinstance(expression, sp.MatrixBase):
        return expression.applyfunc(
            lambda entry: series_coefficient(entry, parameter, order)
        )
    truncated = sp.series(expression, parameter, 0, order + 1).removeO()
    return sp.simplify(sp.expand(truncated).coeff(parameter, order))


def exact_real_mode_average(expression: sp.Expr, theta: sp.Symbol) -> sp.Expr:
    """Return the exact normalized average over one real Fourier period."""

    return sp.simplify(
        sp.integrate(sp.expand_trig(expression), (theta, 0, 2 * sp.pi))
        / (2 * sp.pi)
    )


@lru_cache(maxsize=2)
def _derive_full_flrw_adm_geometry_cached(
    shift_sign: int = -1,
) -> dict[str, Any]:
    """Construct the exact scalar-sector ADM geometry before expansion.

    ``shift_sign=-1`` is the frozen convention.  The opposite sign is
    accepted only as a mutation control: it must reverse the shift-dependent
    kinetic mixing generated by the same geometric definitions.
    """

    if shift_sign not in (-1, 1):
        raise ValueError("shift_sign must be -1 (frozen) or +1 (mutation)")

    epsilon, theta = sp.symbols("epsilon theta", real=True)
    k, scale = sp.symbols("k a", positive=True, nonzero=True)
    H = sp.symbols("H", real=True)
    Phi, Psi, B, Psi_dot = sp.symbols(
        "Phi Psi B Psi_dot", real=True
    )

    mode = sp.cos(theta)
    s = epsilon * Psi * mode
    lapse = 1 + epsilon * Phi * mode
    conformal_factor = scale**2 * sp.exp(-2 * s)
    spatial_metric = conformal_factor * sp.eye(3)
    spatial_inverse = spatial_metric.inv().applyfunc(sp.simplify)
    spatial_determinant = sp.simplify(spatial_metric.det())
    sqrt_h = scale**3 * sp.exp(-3 * s)
    shift_covector = sp.Matrix(
        [shift_sign * epsilon * k * B * sp.sin(theta), 0, 0]
    )
    shift_vector = (spatial_inverse * shift_covector).applyfunc(sp.simplify)

    def spatial_derivative(expression: sp.Expr, index: int) -> sp.Expr:
        """Cartesian derivative with theta=kx and y,z-independent fields."""

        if index == 0:
            return k * sp.diff(expression, theta)
        return sp.Integer(0)

    # Levi-Civita connection of the exact spatial metric.
    christoffel = [
        [
            [
                sp.simplify(
                    sp.Rational(1, 2)
                    * sum(
                        spatial_inverse[upper, ell]
                        * (
                            spatial_derivative(spatial_metric[ell, right], left)
                            + spatial_derivative(
                                spatial_metric[ell, left], right
                            )
                            - spatial_derivative(
                                spatial_metric[left, right], ell
                            )
                        )
                        for ell in range(3)
                    )
                )
                for right in range(3)
            ]
            for left in range(3)
        ]
        for upper in range(3)
    ]

    # R_ij = d_k Gamma^k_ij - d_j Gamma^k_ik
    #        + Gamma^k_ij Gamma^l_kl - Gamma^l_ik Gamma^k_jl.
    ricci_components: list[list[sp.Expr]] = []
    for left in range(3):
        row = []
        for right in range(3):
            component = sp.Integer(0)
            for upper in range(3):
                component += spatial_derivative(
                    christoffel[upper][left][right], upper
                )
                component -= spatial_derivative(
                    christoffel[upper][left][upper], right
                )
                for ell in range(3):
                    component += (
                        christoffel[upper][left][right]
                        * christoffel[ell][upper][ell]
                    )
                    component -= (
                        christoffel[ell][left][upper]
                        * christoffel[upper][right][ell]
                    )
            row.append(sp.simplify(component))
        ricci_components.append(row)
    spatial_ricci = sp.Matrix(ricci_components)
    three_curvature = sp.simplify(
        sum(
            spatial_inverse[left, right] * spatial_ricci[left, right]
            for left in range(3)
            for right in range(3)
        )
    )

    acceleration_covector = sp.Matrix(
        [spatial_derivative(sp.log(lapse), index) for index in range(3)]
    ).applyfunc(sp.simplify)
    acceleration_vector = (
        spatial_inverse * acceleration_covector
    ).applyfunc(sp.simplify)

    def scalar_laplacian(expression: sp.Expr) -> sp.Expr:
        flux_divergence = sp.Integer(0)
        for left in range(3):
            contravariant_gradient = sum(
                spatial_inverse[left, right]
                * spatial_derivative(expression, right)
                for right in range(3)
            )
            flux_divergence += spatial_derivative(
                sqrt_h * contravariant_gradient, left
            )
        return sp.factor(flux_divergence / sqrt_h)

    divergence_acceleration = scalar_laplacian(sp.log(lapse))
    C_slip = sp.factor(three_curvature - 4 * divergence_acceleration)

    def time_derivative(expression: sp.Expr) -> sp.Expr:
        # The spatial metric depends on time only through a(t) and Psi(t).
        return sp.simplify(
            H * scale * sp.diff(expression, scale)
            + Psi_dot * sp.diff(expression, Psi)
        )

    covariant_shift_derivative = sp.MutableDenseMatrix.zeros(3, 3)
    for left in range(3):
        for right in range(3):
            covariant_shift_derivative[left, right] = sp.simplify(
                spatial_derivative(shift_covector[right], left)
                - sum(
                    christoffel[upper][left][right]
                    * shift_covector[upper]
                    for upper in range(3)
                )
            )

    metric_time_derivative = spatial_metric.applyfunc(time_derivative)
    extrinsic_curvature = sp.Matrix(
        3,
        3,
        lambda left, right: sp.simplify(
            (
                metric_time_derivative[left, right]
                - covariant_shift_derivative[left, right]
                - covariant_shift_derivative[right, left]
            )
            / (2 * lapse)
        ),
    )
    mixed_extrinsic_curvature = (
        spatial_inverse * extrinsic_curvature
    ).applyfunc(sp.simplify)
    extrinsic_trace_direct = sp.simplify(
        sum(
            spatial_inverse[left, right] * extrinsic_curvature[left, right]
            for left in range(3)
            for right in range(3)
        )
    )
    extrinsic_trace_matrix = sp.simplify(
        sp.trace(mixed_extrinsic_curvature)
    )

    D2_C_slip = scalar_laplacian(C_slip)
    D2_K = scalar_laplacian(extrinsic_trace_direct)

    kinetic_scalar = sp.simplify(
        sp.trace(mixed_extrinsic_curvature * mixed_extrinsic_curvature)
        - extrinsic_trace_direct**2
    )
    eh_kinetic_density = sp.factor(lapse * sqrt_h * kinetic_scalar)

    return {
        "epsilon": epsilon,
        "theta": theta,
        "k": k,
        "scale_factor": scale,
        "H": H,
        "Phi": Phi,
        "Psi": Psi,
        "B": B,
        "Psi_dot": Psi_dot,
        "mode": mode,
        "conformal_exponent": s,
        "lapse": lapse,
        "spatial_metric": spatial_metric,
        "spatial_inverse": spatial_inverse,
        "spatial_determinant": spatial_determinant,
        "sqrt_h": sqrt_h,
        "shift_sign": sp.Integer(shift_sign),
        "shift_covector": shift_covector,
        "shift_vector": shift_vector,
        "spatial_christoffel": christoffel,
        "spatial_ricci": spatial_ricci,
        "acceleration_covector": acceleration_covector,
        "acceleration_vector": acceleration_vector,
        "divergence_acceleration": divergence_acceleration,
        "three_curvature": three_curvature,
        "C_slip": C_slip,
        "metric_time_derivative": metric_time_derivative,
        "covariant_shift_derivative": covariant_shift_derivative,
        "extrinsic_curvature": extrinsic_curvature,
        "mixed_extrinsic_curvature": mixed_extrinsic_curvature,
        "extrinsic_trace_direct": extrinsic_trace_direct,
        "extrinsic_trace_matrix": extrinsic_trace_matrix,
        "D2_C": D2_C_slip,
        "D2_C_slip": D2_C_slip,
        "D2_K": D2_K,
        "eh_kinetic_scalar": kinetic_scalar,
        "eh_kinetic_density": eh_kinetic_density,
    }


def derive_full_flrw_adm_geometry(shift_sign: int = -1) -> dict[str, Any]:
    """Return an isolated copy of the cached exact symbolic construction.

    The construction is expensive enough to cache, but its result contains
    mutable matrices and a mutable dictionary.  A deep copy prevents a
    caller's diagnostic mutation from changing later derivations.
    """

    return deepcopy(_derive_full_flrw_adm_geometry_cached(shift_sign))


@lru_cache(maxsize=2)
def _derive_full_quadratic_action_cached(
    shift_sign: int = -1,
) -> dict[str, Any]:
    """Derive the real-mode quadratic action from the exact ADM geometry."""

    geometry = _derive_full_flrw_adm_geometry_cached(shift_sign)
    epsilon = geometry["epsilon"]
    theta = geometry["theta"]
    k = geometry["k"]
    scale = geometry["scale_factor"]
    lapse = geometry["lapse"]
    sqrt_h = geometry["sqrt_h"]

    Mpl2, Lambda = sp.symbols("M_Pl_sq Lambda", real=True)
    Mc2, potential = sp.symbols("M_c_sq V", real=True)
    H_dot = sp.symbols("H_dot", real=True)
    ell0 = sp.symbols("ell_0", positive=True, nonzero=True)
    q = sp.symbols("q", real=True)
    A = Mpl2 * scale**3 / 2

    eh_cosmological_density = (
        sp.Rational(1, 2)
        * Mpl2
        * lapse
        * sqrt_h
        * (
            geometry["three_curvature"]
            + geometry["eh_kinetic_scalar"]
            - 2 * Lambda
        )
    )
    eh_cosmological_quadratic = exact_real_mode_average(
        series_coefficient(eh_cosmological_density, epsilon, 2),
        theta,
    )
    normalized_eh_cosmological = sp.factor(
        (eh_cosmological_quadratic / A).subs(k, scale * q)
    )

    # At y=0 the exact norm is directionally nonanalytic, so obtain the
    # quadratic term from the exact primitive's Hessian before inserting
    # y^2=ell_0^2 a_i a^i.  This also keeps the first omitted term visible.
    y = sp.symbols("y", real=True)
    amplitude, y_hat = sp.symbols("amplitude y_hat", real=True)
    exponential_primitive = 2 * ((1 + y) * sp.exp(-y) - 1)
    primitive_at_zero = exponential_primitive.subs(y, 0)
    primitive_slope_at_zero = sp.diff(exponential_primitive, y).subs(y, 0)
    primitive_hessian_at_zero = sp.diff(
        exponential_primitive, y, 2
    ).subs(y, 0)
    scaled_y = amplitude * y_hat
    primitive_remainder = sp.simplify(
        exponential_primitive.subs(y, scaled_y)
        - primitive_at_zero
        - primitive_slope_at_zero * scaled_y
        - primitive_hessian_at_zero * scaled_y**2 / 2
    )
    acceleration_squared = sp.simplify(
        (
            geometry["acceleration_covector"].T
            * geometry["acceleration_vector"]
        )[0]
    )
    y_squared = ell0**2 * acceleration_squared
    exponential_quadratic = sp.simplify(
        -Mpl2
        / ell0**2
        * primitive_hessian_at_zero
        / 2
        * exact_real_mode_average(
            series_coefficient(lapse * sqrt_h * y_squared, epsilon, 2),
            theta,
        )
    )
    normalized_exponential = sp.factor(
        (exponential_quadratic / A).subs(k, scale * q)
    )

    lambda_s_bar, lambda_K_bar = sp.symbols(
        "lambda_s_bar lambda_K_bar", real=True
    )
    delta_lambda_s, delta_lambda_K = sp.symbols(
        "delta_lambda_s delta_lambda_K", real=True
    )
    lambda_s_field = (
        lambda_s_bar
        + epsilon * delta_lambda_s * sp.cos(theta)
    )
    lambda_K_field = (
        lambda_K_bar
        + epsilon * delta_lambda_K * sp.cos(theta)
    )
    lambda_s_density = (
        sp.Rational(1, 2)
        * Mpl2
        * lapse
        * sqrt_h
        * lambda_s_field
        * geometry["D2_C"]
    )
    lambda_K_density = (
        sp.Rational(1, 2)
        * Mpl2
        * lapse
        * sqrt_h
        * lambda_K_field
        * geometry["D2_K"]
    )
    lambda_s_quadratic = exact_real_mode_average(
        series_coefficient(lambda_s_density, epsilon, 2), theta
    )
    lambda_K_quadratic = exact_real_mode_average(
        series_coefficient(lambda_K_density, epsilon, 2), theta
    )
    normalized_lambda_s = sp.factor(
        (lambda_s_quadratic / A).subs(k, scale * q)
    )
    normalized_lambda_K = sp.factor(
        (lambda_K_quadratic / A).subs(k, scale * q)
    )

    # In unitary gauge on the positive-clock branch, sqrt(X)=1/N.  The
    # lapse therefore cancels from N sqrt(h) M_c^2 sqrt(X), while it remains
    # in the potential density.  No matter perturbation action is specified.
    cuscuton_density = Mc2 * sqrt_h
    potential_density = -potential * lapse * sqrt_h
    cuscuton_quadratic = exact_real_mode_average(
        series_coefficient(cuscuton_density, epsilon, 2), theta
    )
    potential_quadratic = exact_real_mode_average(
        series_coefficient(potential_density, epsilon, 2), theta
    )
    normalized_cuscuton = sp.factor(cuscuton_quadratic / A)
    normalized_potential = sp.factor(potential_quadratic / A)

    # Reuse the independently varied homogeneous minisuperspace equations;
    # do not infer background equations from the vanishing average of a
    # nonzero cosine mode.
    from cde_l4c_2delta_flrw_gate_2026 import derive_flrw_gate

    minisuperspace = derive_flrw_gate()["minisuperspace"]
    mini_scale = minisuperspace["a"]
    mini_lapse = minisuperspace["N"]
    mini_clock = minisuperspace["T"]
    mini_time = minisuperspace["t"]
    vacuum_flrw_substitution = {
        minisuperspace["Mpl2"]: Mpl2,
        minisuperspace["Mc2"]: Mc2,
        minisuperspace["Lambda"]: Lambda,
        minisuperspace["V"]: potential,
        minisuperspace["rho"]: 0,
        minisuperspace["pressure"]: 0,
        sp.diff(mini_clock, mini_time): 1,
        sp.diff(mini_lapse, mini_time): 0,
        sp.diff(mini_scale, mini_time, 2): (
            H_dot + geometry["H"] ** 2
        )
        * scale,
        sp.diff(mini_scale, mini_time): geometry["H"] * scale,
        mini_lapse: 1,
        mini_scale: scale,
    }
    friedmann_residual = sp.factor(
        minisuperspace["friedmann_equation"].subs(
            vacuum_flrw_substitution, simultaneous=True
        )
    )
    raychaudhuri_residual = sp.factor(
        minisuperspace["raychaudhuri_equation"].subs(
            vacuum_flrw_substitution, simultaneous=True
        )
    )
    friedmann_substitution = sp.solve(
        sp.Eq(friedmann_residual, 0), potential, dict=True
    )[0]
    raychaudhuri_substitution = sp.solve(
        sp.Eq(raychaudhuri_residual, 0), Mc2, dict=True
    )[0]

    # Substitute the explicit expanding vacuum witness back into the three
    # independently varied minisuperspace Euler equations.  This is distinct
    # from (and stronger than) the kinematic zero of a nonzero cosine's
    # spatial average.
    vacuum_witness = minisuperspace["vacuum_expanding_witness"]
    witness_parameter_substitution = {
        minisuperspace["Mpl2"]: Mpl2,
        minisuperspace["Mc2"]: Mc2,
        minisuperspace["Lambda"]: Lambda,
    }
    witness_scale = sp.simplify(
        vacuum_witness["scale_factor"].subs(
            witness_parameter_substitution
        )
    )
    witness_clock = vacuum_witness["T"]
    witness_potential = sp.simplify(
        vacuum_witness["potential"].subs(
            witness_parameter_substitution
        )
    )
    witness_clock_velocity = sp.diff(witness_clock, mini_time)
    witness_potential_derivative = sp.simplify(
        sp.diff(witness_potential, mini_time) / witness_clock_velocity
    )
    witness_substitution = {
        **witness_parameter_substitution,
        minisuperspace["rho"]: 0,
        minisuperspace["pressure"]: 0,
        sp.diff(minisuperspace["V"], mini_clock): (
            witness_potential_derivative
        ),
        minisuperspace["V"]: witness_potential,
        sp.diff(mini_lapse, mini_time): 0,
        sp.diff(mini_scale, mini_time, 2): sp.diff(
            witness_scale, mini_time, 2
        ),
        sp.diff(mini_scale, mini_time): sp.diff(
            witness_scale, mini_time
        ),
        sp.diff(mini_clock, mini_time): witness_clock_velocity,
        mini_lapse: 1,
        mini_scale: witness_scale,
        mini_clock: witness_clock,
    }
    vacuum_witness_residuals = tuple(
        sp.factor(equation.subs(witness_substitution, simultaneous=True))
        for equation in (
            minisuperspace["friedmann_equation"],
            minisuperspace["cuscuton_equation"],
            minisuperspace["raychaudhuri_equation"],
        )
    )

    exact_bulk_densities = {
        "eh_cosmological": eh_cosmological_density,
        "lambda_s": lambda_s_density,
        "lambda_K": lambda_K_density,
        "cuscuton": cuscuton_density,
        "potential": potential_density,
    }
    linear_density = sp.factor(
        sum(
            series_coefficient(density, epsilon, 1)
            for density in exact_bulk_densities.values()
        )
    )
    finite_mode_linear_average = exact_real_mode_average(
        linear_density, theta
    )
    homogeneous_linear_density = sp.factor(
        linear_density.subs(k, 0).subs(sp.cos(theta), 1)
    )
    homogeneous_velocity_coefficient = sp.diff(
        homogeneous_linear_density, geometry["Psi_dot"]
    )
    tadpole_temporal_boundary = sp.factor(
        homogeneous_velocity_coefficient * geometry["Psi"]
    )
    tadpole_boundary_coefficient_dot = sp.factor(
        sp.diff(homogeneous_velocity_coefficient, scale)
        * geometry["H"]
        * scale
        + sp.diff(homogeneous_velocity_coefficient, geometry["H"])
        * H_dot
    )
    homogeneous_tadpole_bulk = sp.factor(
        homogeneous_linear_density
        - homogeneous_velocity_coefficient * geometry["Psi_dot"]
        - tadpole_boundary_coefficient_dot * geometry["Psi"]
    )
    homogeneous_tadpole_after_friedmann = sp.factor(
        homogeneous_tadpole_bulk.subs(friedmann_substitution)
    )
    homogeneous_tadpole_on_shell = sp.factor(
        homogeneous_tadpole_after_friedmann.subs(
            raychaudhuri_substitution
        )
    )

    quadratic_pieces = {
        "eh_cosmological": eh_cosmological_quadratic,
        "exponential": exponential_quadratic,
        "lambda_s": lambda_s_quadratic,
        "lambda_K": lambda_K_quadratic,
        "cuscuton": cuscuton_quadratic,
        "potential": potential_quadratic,
    }
    normalized_quadratic_pieces = {
        "eh_cosmological": normalized_eh_cosmological,
        "exponential": normalized_exponential,
        "lambda_s": normalized_lambda_s,
        "lambda_K": normalized_lambda_K,
        "cuscuton": normalized_cuscuton,
        "potential": normalized_potential,
    }
    raw_quadratic = sp.factor(sum(quadratic_pieces.values()))
    raw_normalized = sp.factor(
        (raw_quadratic / A).subs(k, scale * q)
    )

    # Remove only the EH Psi*Psi_dot term.  No temporal integration by parts
    # is made in the lambda_K sector, because doing so would change the
    # canonical momenta.  Derive dot(A)=3HA from A=M_Pl^2 a^3/2.
    A_dot = sp.factor(sp.diff(A, scale) * geometry["H"] * scale)
    psi_velocity_mixing_coefficient = sp.factor(
        sp.diff(raw_quadratic, geometry["Psi"], geometry["Psi_dot"])
    )
    psi_velocity_mixing = sp.factor(
        psi_velocity_mixing_coefficient
        * geometry["Psi"]
        * geometry["Psi_dot"]
    )
    quadratic_temporal_boundary = sp.factor(
        psi_velocity_mixing_coefficient * geometry["Psi"] ** 2 / 2
    )
    temporal_boundary_coefficient = sp.factor(
        psi_velocity_mixing_coefficient / 2
    )
    temporal_boundary_coefficient_dot = sp.factor(
        sp.diff(temporal_boundary_coefficient, scale)
        * geometry["H"]
        * scale
        + sp.diff(temporal_boundary_coefficient, geometry["H"])
        * H_dot
    )
    quadratic_bulk_remainder = sp.factor(
        -temporal_boundary_coefficient_dot * geometry["Psi"] ** 2
    )
    bulk_after_time_ibp = sp.factor(
        raw_quadratic
        - psi_velocity_mixing
        + quadratic_bulk_remainder
    )
    bulk_after_friedmann = sp.factor(
        bulk_after_time_ibp.subs(friedmann_substitution)
        .subs(k, scale * q)
    )
    on_shell_bulk = sp.factor(
        bulk_after_friedmann.subs(raychaudhuri_substitution)
    )

    # Independent Minkowski route: specialize every exact density before
    # taking its epsilon coefficient.  The exponential piece is added from
    # the exact primitive Hessian because its norm is nonanalytic at y=0.
    minkowski_substitution = {
        geometry["H"]: 0,
        lambda_s_bar: 0,
        lambda_K_bar: 0,
        Mc2: 0,
        potential: -Mpl2 * Lambda,
    }
    direct_minkowski_exact_density = sum(
        exact_bulk_densities.values()
    ).subs(minkowski_substitution, simultaneous=True)
    direct_minkowski_quadratic = sp.factor(
        exact_real_mode_average(
            series_coefficient(
                direct_minkowski_exact_density, epsilon, 2
            ),
            theta,
        )
        + exponential_quadratic.subs(
            minkowski_substitution, simultaneous=True
        )
    )
    direct_minkowski_q = sp.factor(
        direct_minkowski_quadratic.subs(k, scale * q)
    )
    flrw_simultaneous_limit = sp.factor(
        raw_quadratic.subs(
            minkowski_substitution, simultaneous=True
        ).subs(k, scale * q)
    )
    coefficient_variables = (
        geometry["Phi"],
        geometry["Psi"],
        geometry["B"],
        geometry["Psi_dot"],
        delta_lambda_s,
        delta_lambda_K,
    )
    direct_polynomial = sp.Poly(
        sp.expand(direct_minkowski_q), *coefficient_variables
    )
    limit_polynomial = sp.Poly(
        sp.expand(flrw_simultaneous_limit), *coefficient_variables
    )
    coefficient_keys = tuple(
        sorted(
            set(direct_polynomial.monoms())
            | set(limit_polynomial.monoms())
        )
    )
    coefficient_residuals = {
        monomial: sp.simplify(
            direct_polynomial.coeff_monomial(monomial)
            - limit_polynomial.coeff_monomial(monomial)
        )
        for monomial in coefficient_keys
    }

    # Independent provenance bridge: call the already committed Minkowski
    # ADM generator from the action gate, map its own symbols into this
    # module's convention, and compare coefficients with the FLRW limit.
    # This is logically separate from the specialization/expansion
    # commutation check above, whose two sides share this module's geometry.
    from cde_l4c_2delta_action_gate_2026 import (
        _derive_minkowski_adm_principal,
    )

    action_gate_y = sp.symbols("y_action_gate", positive=True)
    action_gate_correction = 2 * (
        (1 + action_gate_y) * sp.exp(-action_gate_y) - 1
    )
    action_gate_generator = _derive_minkowski_adm_principal(
        action_gate_correction, action_gate_y
    )
    action_gate_source_expression = action_gate_generator[
        "generated_zero_field_lagrangian"
    ]
    action_gate_symbol_map = {
        action_gate_generator["A"]: A,
        action_gate_generator["k"]: q,
        action_gate_generator["Phi"]: geometry["Phi"],
        action_gate_generator["Psi"]: geometry["Psi"],
        action_gate_generator["B"]: geometry["B"],
        action_gate_generator["lambda_s"]: delta_lambda_s,
        action_gate_generator["lambda_K"]: delta_lambda_K,
        action_gate_generator["Psi_dot"]: geometry["Psi_dot"],
    }
    action_gate_mapped_expression = sp.factor(
        action_gate_source_expression.subs(
            action_gate_symbol_map, simultaneous=True
        )
    )
    action_gate_polynomial = sp.Poly(
        sp.expand(action_gate_mapped_expression), *coefficient_variables
    )
    action_gate_coefficient_keys = tuple(
        sorted(
            set(action_gate_polynomial.monoms())
            | set(limit_polynomial.monoms())
        )
    )
    action_gate_coefficient_residuals = {
        monomial: sp.simplify(
            action_gate_polynomial.coeff_monomial(monomial)
            - limit_polynomial.coeff_monomial(monomial)
        )
        for monomial in action_gate_coefficient_keys
    }

    without_cuscuton_on_shell = sp.factor(
        (bulk_after_time_ibp - cuscuton_quadratic)
        .subs(friedmann_substitution)
        .subs(k, scale * q)
        .subs(raychaudhuri_substitution)
    )
    without_cuscuton_residual = sp.factor(
        without_cuscuton_on_shell - on_shell_bulk
    )

    return {
        "geometry_symbols": {
            name: geometry[name]
            for name in (
                "epsilon",
                "theta",
                "k",
                "scale_factor",
                "Phi",
                "Psi",
                "B",
                "H",
                "Psi_dot",
            )
        },
        "symbols": {
            "Mpl2": Mpl2,
            "Lambda": Lambda,
            "Mc2": Mc2,
            "V": potential,
            "H_dot": H_dot,
            "ell0": ell0,
            "lambda_s_bar": lambda_s_bar,
            "lambda_K_bar": lambda_K_bar,
            "delta_lambda_s": delta_lambda_s,
            "delta_lambda_K": delta_lambda_K,
        },
        "normalization": {
            "A": A,
            "A_dot": A_dot,
            "q": q,
            "physical_wave_number_substitution": {k: scale * q},
        },
        "quadratic": {
            "pieces": quadratic_pieces,
            "normalized_pieces": normalized_quadratic_pieces,
            "raw": raw_quadratic,
            "raw_normalized": raw_normalized,
        },
        "exact_clock_densities": {
            "cuscuton": cuscuton_density,
            "potential": potential_density,
        },
        "background": {
            "source_friedmann_equation": minisuperspace[
                "friedmann_equation"
            ],
            "source_cuscuton_equation": minisuperspace[
                "cuscuton_equation"
            ],
            "source_raychaudhuri_equation": minisuperspace[
                "raychaudhuri_equation"
            ],
            "friedmann_residual_before_solving": friedmann_residual,
            "raychaudhuri_residual_before_solving": raychaudhuri_residual,
            "friedmann_substitution": friedmann_substitution,
            "raychaudhuri_substitution": raychaudhuri_substitution,
            "friedmann_residual_after_solving": sp.simplify(
                friedmann_residual.subs(friedmann_substitution)
            ),
            "raychaudhuri_residual_after_solving": sp.simplify(
                raychaudhuri_residual.subs(raychaudhuri_substitution)
            ),
            "vacuum_witness": {
                "clock": witness_clock,
                "scale_factor": witness_scale,
                "potential": witness_potential,
                "substitution": witness_substitution,
            },
            "vacuum_witness_residuals": vacuum_witness_residuals,
        },
        "tadpoles": {
            "unaveraged_finite_mode_density": linear_density,
            "finite_mode_spatial_average": finite_mode_linear_average,
            "finite_mode_average_is_kinematic": True,
            "homogeneous_raw_density": homogeneous_linear_density,
            "temporal_boundary_primitive": tadpole_temporal_boundary,
            "homogeneous_bulk_before_background_equations": (
                homogeneous_tadpole_bulk
            ),
            "homogeneous_bulk_after_friedmann": (
                homogeneous_tadpole_after_friedmann
            ),
            "homogeneous_bulk_on_shell": homogeneous_tadpole_on_shell,
        },
        "time_ibp": {
            "psi_velocity_mixing": psi_velocity_mixing,
            "temporal_boundary_primitive": quadratic_temporal_boundary,
            "bulk_remainder": quadratic_bulk_remainder,
            "bulk_before_background_equations": bulk_after_time_ibp,
            "bulk_after_friedmann": bulk_after_friedmann,
            "on_shell_bulk": on_shell_bulk,
            "lambda_K_was_time_integrated_by_parts": False,
        },
        "minkowski_comparison": {
            "internal_specialization_expansion_commutation": {
                "specialization": minkowski_substitution,
                "direct_exact_density_before_expansion": (
                    direct_minkowski_exact_density
                ),
                "direct_specialization_before_expansion": (
                    direct_minkowski_q
                ),
                "flrw_simultaneous_limit": flrw_simultaneous_limit,
                "coefficient_variables": coefficient_variables,
                "coefficient_keys": coefficient_keys,
                "coefficient_residuals": coefficient_residuals,
            },
            "independent_action_gate_bridge": {
                "source_expression": action_gate_source_expression,
                "symbol_map": action_gate_symbol_map,
                "mapped_expression": action_gate_mapped_expression,
                "task2_minkowski_expression": flrw_simultaneous_limit,
                "coefficient_variables": coefficient_variables,
                "coefficient_keys": action_gate_coefficient_keys,
                "coefficient_residuals": (
                    action_gate_coefficient_residuals
                ),
            },
        },
        "mutation_controls": {
            "without_cuscuton": {
                "on_shell_bulk": without_cuscuton_on_shell,
                "on_shell_residual": without_cuscuton_residual,
                "identity_survives": without_cuscuton_residual == 0,
            },
        },
        "exact_multiplier_fields": {
            "lambda_s": lambda_s_field,
            "lambda_K": lambda_K_field,
        },
        "exact_multiplier_densities": {
            "lambda_s": lambda_s_density,
            "lambda_K": lambda_K_density,
        },
        "exponential": {
            "y": y,
            "amplitude": amplitude,
            "y_hat": y_hat,
            "primitive": exponential_primitive,
            "primitive_at_zero": primitive_at_zero,
            "primitive_slope_at_zero": primitive_slope_at_zero,
            "primitive_hessian_at_zero": primitive_hessian_at_zero,
            "primitive_remainder": primitive_remainder,
            "acceleration_squared": acceleration_squared,
            "y_squared": y_squared,
        },
        "scope": {
            "vacuum_witness": True,
            "matter_perturbations_invented": False,
        },
        "boundary_assumptions": {
            "spatial": (
                "one periodic nonzero real cosine mode; equivalently, "
                "falloff that kills the spatial surface term in the "
                "self-adjoint D2 integration"
            ),
            "temporal": (
                "the displayed total derivative is fixed or vanishes at "
                "the initial and final time slices"
            ),
            "lambda_K_time_integration_by_parts": False,
        },
    }


def derive_full_quadratic_action(shift_sign: int = -1) -> dict[str, Any]:
    """Return an isolated copy of the generated quadratic action data."""

    return deepcopy(_derive_full_quadratic_action_cached(shift_sign))


def _canonical_poisson_bracket(
    first: sp.Expr,
    second: sp.Expr,
    coordinates: tuple[sp.Symbol, ...],
    momenta: tuple[sp.Symbol, ...],
) -> sp.Expr:
    """Canonical Poisson bracket used by the full finite-k chain."""

    return sp.factor(
        sum(
            sp.diff(first, coordinate) * sp.diff(second, momentum)
            - sp.diff(first, momentum) * sp.diff(second, coordinate)
            for coordinate, momentum in zip(coordinates, momenta)
        )
    )


def _matrix_rank_witness(matrix: sp.MatrixBase) -> dict[str, Any]:
    """Find a nonzero minor whose size is the matrix's computed rank."""

    rank = matrix.rank()
    if rank == 0:
        empty = sp.zeros(0, 0)
        return {
            "size": 0,
            "rows": (),
            "columns": (),
            "matrix": empty,
            "determinant": sp.Integer(1),
        }

    columns = tuple(matrix.rref()[1])
    column_basis = matrix[:, columns]
    rows = tuple(column_basis.T.rref()[1])
    witness = matrix.extract(rows, columns)
    determinant = sp.factor(witness.det())
    if determinant == 0:
        raise RuntimeError("rank decomposition failed to produce a nonzero minor")
    return {
        "size": rank,
        "rows": rows,
        "columns": columns,
        "matrix": witness,
        "determinant": determinant,
    }


def _proportional_polynomial_residual(
    first: sp.Expr,
    second: sp.Expr,
    variables: tuple[sp.Symbol, ...],
) -> tuple[sp.Expr, sp.Expr]:
    """Derive a proportionality factor between two constraint polynomials."""

    first_poly = sp.Poly(sp.expand(first), *variables)
    second_poly = sp.Poly(sp.expand(second), *variables)
    monomials = tuple(
        sorted(set(first_poly.monoms()) | set(second_poly.monoms()))
    )
    for monomial in monomials:
        second_coefficient = second_poly.coeff_monomial(monomial)
        if second_coefficient != 0:
            ratio = sp.factor(
                first_poly.coeff_monomial(monomial) / second_coefficient
            )
            return ratio, sp.simplify(first - ratio * second)
    if first == 0 and second == 0:
        return sp.Integer(1), sp.Integer(0)
    raise ValueError("cannot compare against an identically zero constraint")


@lru_cache(maxsize=1)
def _derive_finite_k_dirac_chain_cached() -> dict[str, Any]:
    """Derive the complete time-dependent finite-k scalar Dirac chain.

    The starting point is Task 2's on-shell quadratic action.  The scalar
    spatial metric mode E is restored through the independently checked
    shear Sigma=B-a^2 dot(E) before any momentum is calculated.
    """

    task2 = _derive_full_quadratic_action_cached()
    task2_geometry = task2["geometry_symbols"]
    task2_symbols = task2["symbols"]

    Phi = task2_geometry["Phi"]
    Psi = task2_geometry["Psi"]
    B = task2_geometry["B"]
    H = task2_geometry["H"]
    Psi_dot = task2_geometry["Psi_dot"]
    scale = task2_geometry["scale_factor"]
    q = task2["normalization"]["q"]
    task2_A = task2["normalization"]["A"]
    lambda_s_bar = task2_symbols["lambda_s_bar"]
    lambda_K_bar = task2_symbols["lambda_K_bar"]
    delta_lambda_s = task2_symbols["delta_lambda_s"]
    delta_lambda_K = task2_symbols["delta_lambda_K"]

    A = sp.symbols("A", positive=True, nonzero=True)
    E = sp.symbols("E", real=True)
    Phi_dot, B_dot, E_dot = sp.symbols(
        "Phi_dot B_dot E_dot", real=True
    )
    delta_lambda_s_dot, delta_lambda_K_dot = sp.symbols(
        "delta_lambda_s_dot delta_lambda_K_dot", real=True
    )
    p_Phi, p_Psi, p_B, p_E, p_s, p_K = sp.symbols(
        "p_Phi p_Psi p_B p_E p_s p_K", real=True
    )
    H_dot, lambda_s_bar_dot, lambda_K_bar_dot = sp.symbols(
        "H_dot lambda_s_bar_dot lambda_K_bar_dot", real=True
    )

    coordinates = (
        Phi,
        Psi,
        B,
        E,
        delta_lambda_s,
        delta_lambda_K,
    )
    velocities = (
        Phi_dot,
        Psi_dot,
        B_dot,
        E_dot,
        delta_lambda_s_dot,
        delta_lambda_K_dot,
    )
    momenta = (p_Phi, p_Psi, p_B, p_E, p_s, p_K)
    phase_variables = coordinates + momenta

    Theta = Psi_dot + H * Phi
    Sigma = B - scale**2 * E_dot
    effective_lambda_s = delta_lambda_s + lambda_s_bar * Phi
    effective_lambda_K = delta_lambda_K + lambda_K_bar * Phi

    task2_on_shell_action = task2["time_ibp"]["on_shell_bulk"]
    task2_normalized_action = sp.factor(task2_on_shell_action / task2_A)
    gauge_fixed_action = sp.factor(A * task2_normalized_action)
    lagrangian = sp.factor(gauge_fixed_action.subs(B, Sigma))
    task2_provenance_residual = sp.simplify(
        gauge_fixed_action.subs(A, task2_A) - task2_on_shell_action
    )
    E_zero_gauge_action_residual = sp.simplify(
        lagrangian.subs(E_dot, 0) - gauge_fixed_action
    )
    spatial_diffeomorphism_identity = sp.simplify(
        sp.diff(lagrangian, E_dot)
        + scale**2 * sp.diff(lagrangian, B)
    )

    background_derivative_rules = {
        A: 3 * H * A,
        scale: H * scale,
        q: -H * q,
        H: H_dot,
        lambda_s_bar: lambda_s_bar_dot,
        lambda_K_bar: lambda_K_bar_dot,
    }

    def partial_time(expression: sp.Expr) -> sp.Expr:
        return sp.factor(
            sum(
                sp.diff(expression, background) * background_dot
                for background, background_dot in (
                    background_derivative_rules.items()
                )
            )
        )

    def constraint_rank(expressions: list[sp.Expr] | tuple[sp.Expr, ...]) -> int:
        if not expressions:
            return 0
        return sp.Matrix(expressions).jacobian(phase_variables).rank()

    def canonical_signature(expression: sp.Expr) -> dict[str, Any]:
        derived_momenta = tuple(
            sp.factor(sp.diff(expression, velocity))
            for velocity in velocities
        )
        velocity_hessian = sp.hessian(expression, velocities).applyfunc(
            sp.factor
        )
        velocity_hessian_rank = velocity_hessian.rank()
        velocity_hessian_nullspace = velocity_hessian.nullspace()

        regular_velocity_indices = tuple(velocity_hessian.rref()[1])
        regular_columns = velocity_hessian[:, regular_velocity_indices]
        regular_momentum_indices = tuple(regular_columns.T.rref()[1])
        momentum_equations = tuple(
            sp.Eq(momenta[index], derived_momenta[index])
            for index in regular_momentum_indices
        )
        regular_velocities = tuple(
            velocities[index] for index in regular_velocity_indices
        )
        velocity_solutions = sp.solve(
            momentum_equations,
            regular_velocities,
            dict=True,
            simplify=False,
        )
        if not velocity_solutions:
            raise RuntimeError("regular velocity block could not be inverted")
        velocity_solution = {
            velocity: sp.factor(solution)
            for velocity, solution in velocity_solutions[0].items()
        }

        primaries = tuple(
            sp.factor(
                sum(
                    null_vector[index]
                    * (momenta[index] - derived_momenta[index])
                    for index in range(len(coordinates))
                )
            )
            for null_vector in velocity_hessian_nullspace
        )
        legendre_expression = sp.factor(
            sum(
                momentum * velocity
                for momentum, velocity in zip(momenta, velocities)
            )
            - expression
        )
        legendre_after_regular_solution = sp.factor(
            legendre_expression.subs(velocity_solution)
        )
        null_velocity_substitution = {
            velocities[index]: 0
            for index in range(len(velocities))
            if index not in regular_velocity_indices
        }
        canonical_hamiltonian = sp.factor(
            legendre_after_regular_solution.subs(null_velocity_substitution)
        )
        null_velocity_primary_piece = sp.factor(
            legendre_after_regular_solution - canonical_hamiltonian
        )
        legendre_decomposition_residual = sp.simplify(
            legendre_after_regular_solution
            - canonical_hamiltonian
            - null_velocity_primary_piece
        )

        secondary_candidates = tuple(
            sp.factor(
                partial_time(primary)
                + _canonical_poisson_bracket(
                    primary,
                    canonical_hamiltonian,
                    coordinates,
                    momenta,
                )
            )
            for primary in primaries
        )
        constraints: list[sp.Expr] = []
        running_ranks: list[int] = []
        for candidate in primaries + secondary_candidates:
            if sp.simplify(candidate) == 0:
                continue
            old_rank = constraint_rank(constraints)
            proposed = constraints + [candidate]
            new_rank = constraint_rank(proposed)
            if new_rank > old_rank:
                constraints.append(candidate)
                running_ranks.append(new_rank)

        constraint_tuple = tuple(constraints)
        poisson_matrix = sp.Matrix(
            [
                [
                    _canonical_poisson_bracket(
                        first, second, coordinates, momenta
                    )
                    for second in constraint_tuple
                ]
                for first in constraint_tuple
            ]
        ).applyfunc(sp.factor)
        constraint_jacobian = sp.Matrix(constraint_tuple).jacobian(
            phase_variables
        )
        return {
            "lagrangian": expression,
            "derived_momenta": derived_momenta,
            "velocity_hessian": velocity_hessian,
            "velocity_hessian_rank": velocity_hessian_rank,
            "velocity_hessian_nullspace": velocity_hessian_nullspace,
            "regular_velocity_indices": regular_velocity_indices,
            "regular_momentum_indices": regular_momentum_indices,
            "velocity_solution": velocity_solution,
            "primaries": primaries,
            "legendre_expression": legendre_expression,
            "legendre_after_regular_solution": (
                legendre_after_regular_solution
            ),
            "null_velocity_primary_piece": null_velocity_primary_piece,
            "legendre_decomposition_residual": (
                legendre_decomposition_residual
            ),
            "canonical_hamiltonian": canonical_hamiltonian,
            "secondary_candidates": secondary_candidates,
            "constraints": constraint_tuple,
            "constraint_generation_ranks": tuple(running_ranks),
            "poisson_matrix": poisson_matrix,
            "poisson_determinant": sp.factor(poisson_matrix.det()),
            "poisson_rank": poisson_matrix.rank(),
            "constraint_jacobian": constraint_jacobian,
            "constraint_jacobian_rank": constraint_jacobian.rank(),
        }

    baseline = canonical_signature(lagrangian)
    primaries = baseline["primaries"]
    primary_multipliers = sp.symbols(
        f"u0:{len(primaries)}", real=True
    )
    total_hamiltonian = sp.factor(
        baseline["canonical_hamiltonian"]
        + sum(
            multiplier * primary
            for multiplier, primary in zip(primary_multipliers, primaries)
        )
    )

    # Use a declared elimination preference only to retain the surviving
    # canonical variables in readable form.  The number of solved variables
    # is determined by the generated constraints, not supplied in advance.
    elimination_preference = (
        p_Phi,
        p_B,
        p_s,
        p_K,
        p_E,
        Phi,
        delta_lambda_K,
        delta_lambda_s,
    )
    constraint_solutions = sp.solve(
        baseline["constraints"],
        elimination_preference,
        dict=True,
        simplify=False,
    )
    if not constraint_solutions:
        raise RuntimeError("finite-k constraint surface could not be solved")
    constraint_solution = {
        variable: sp.factor(value)
        for variable, value in constraint_solutions[0].items()
    }
    constraint_solution_residuals = tuple(
        sp.simplify(
            constraint.subs(constraint_solution, simultaneous=True)
        )
        for constraint in baseline["constraints"]
    )

    partial_time_terms = tuple(
        partial_time(constraint) for constraint in baseline["constraints"]
    )
    poisson_evolution_terms = tuple(
        _canonical_poisson_bracket(
            constraint, total_hamiltonian, coordinates, momenta
        )
        for constraint in baseline["constraints"]
    )
    total_time_derivatives = tuple(
        sp.factor(partial + poisson)
        for partial, poisson in zip(
            partial_time_terms, poisson_evolution_terms
        )
    )
    on_constraint_surface = tuple(
        sp.factor(
            equation.subs(constraint_solution, simultaneous=True)
        )
        for equation in total_time_derivatives
    )
    multiplier_coefficient_matrix = sp.Matrix(
        [
            [
                sp.diff(equation, multiplier)
                for multiplier in primary_multipliers
            ]
            for equation in on_constraint_surface
        ]
    ).applyfunc(sp.factor)
    zero_multiplier_substitution = {
        multiplier: 0 for multiplier in primary_multipliers
    }
    multiplier_rhs = sp.Matrix(
        [
            -equation.subs(zero_multiplier_substitution)
            for equation in on_constraint_surface
        ]
    ).applyfunc(sp.factor)
    multiplier_coefficient_rank = multiplier_coefficient_matrix.rank()
    augmented_rank = multiplier_coefficient_matrix.row_join(
        multiplier_rhs
    ).rank()
    multiplier_solutions = sp.solve(
        on_constraint_surface,
        primary_multipliers,
        dict=True,
        simplify=False,
    )
    multiplier_solution = (
        {
            multiplier: sp.factor(value)
            for multiplier, value in multiplier_solutions[0].items()
        }
        if multiplier_solutions
        else {}
    )
    closure_residuals = tuple(
        sp.simplify(equation.subs(multiplier_solution))
        for equation in on_constraint_surface
    )
    tertiary_candidates: list[sp.Expr] = []
    current_rank = baseline["constraint_jacobian_rank"]
    for residual in closure_residuals:
        if residual == 0 or residual.has(*primary_multipliers):
            continue
        proposed = baseline["constraints"] + tuple(tertiary_candidates) + (
            residual,
        )
        proposed_rank = constraint_rank(proposed)
        if proposed_rank > current_rank:
            tertiary_candidates.append(residual)
            current_rank = proposed_rank
    free_multipliers = tuple(
        multiplier
        for multiplier in primary_multipliers
        if multiplier not in multiplier_solution
    )
    multiplier_rank_witness = _matrix_rank_witness(
        multiplier_coefficient_matrix
    )

    poisson_matrix = baseline["poisson_matrix"]
    poisson_nullspace = poisson_matrix.nullspace()
    first_class_combinations = tuple(
        sp.factor(
            sum(
                vector[index] * baseline["constraints"][index]
                for index in range(len(baseline["constraints"]))
            )
        )
        for vector in poisson_nullspace
    )
    weak_first_class_brackets = sp.Matrix(
        [
            [
                sp.simplify(
                    _canonical_poisson_bracket(
                        combination, constraint, coordinates, momenta
                    ).subs(constraint_solution, simultaneous=True)
                )
                for constraint in baseline["constraints"]
            ]
            for combination in first_class_combinations
        ]
    )
    first_class_count = len(poisson_nullspace)
    second_class_count = baseline["poisson_rank"]
    phase_dimension = len(phase_variables)
    reduced_phase_dimension = (
        phase_dimension - 2 * first_class_count - second_class_count
    )
    configuration_dof = sp.Rational(reduced_phase_dimension, 2)
    poisson_rank_witness = _matrix_rank_witness(poisson_matrix)

    sample_symbol_pool = tuple(
        sorted(poisson_matrix.free_symbols, key=lambda symbol: symbol.name)
    )
    sampled_exact_ranks: list[int] = []
    sampled_numerical_ranks: list[int] = []
    sample_substitutions: list[dict[sp.Symbol, sp.Expr]] = []
    import numpy as np

    for sample_index in range(3):
        substitution: dict[sp.Symbol, sp.Expr] = {}
        for symbol_index, symbol in enumerate(sample_symbol_pool):
            numerator = 2 + sample_index + symbol_index
            denominator = 1 + ((sample_index + symbol_index) % 3)
            substitution[symbol] = sp.Rational(numerator, denominator)
        substitution[A] = sp.Rational(2 + sample_index, 1)
        substitution[scale] = sp.Rational(3 + sample_index, 2)
        substitution[q] = sp.Rational(4 + sample_index, 3)
        exact_sample = poisson_matrix.subs(substitution)
        sampled_exact_ranks.append(exact_sample.rank())
        numerical_sample = np.asarray(exact_sample.evalf(), dtype=float)
        sampled_numerical_ranks.append(
            int(np.linalg.matrix_rank(numerical_sample))
        )
        sample_substitutions.append(substitution)

    # Pull back the canonical and extended one-forms before choosing a gauge.
    free_phase_variables = tuple(
        variable
        for variable in phase_variables
        if variable not in constraint_solution
    )
    one_form_coefficients: dict[sp.Symbol, sp.Expr] = {}
    for free_variable in free_phase_variables:
        coefficient = sp.Integer(0)
        for coordinate, momentum in zip(coordinates, momenta):
            reduced_coordinate = coordinate.subs(
                constraint_solution, simultaneous=True
            )
            reduced_momentum = momentum.subs(
                constraint_solution, simultaneous=True
            )
            coefficient += reduced_momentum * sp.diff(
                reduced_coordinate, free_variable
            )
        one_form_coefficients[free_variable] = sp.simplify(coefficient)
    differential_symbols = {
        variable: sp.symbols(f"d_{variable.name}", real=True)
        for variable in free_phase_variables
    }
    pulled_spatial_one_form = sp.simplify(
        sum(
            one_form_coefficients[variable]
            * differential_symbols[variable]
            for variable in free_phase_variables
        )
    )
    reduced_hamiltonian = sp.factor(
        baseline["canonical_hamiltonian"].subs(
            constraint_solution, simultaneous=True
        )
    )
    dt = sp.symbols("dt", real=True)
    pulled_extended_one_form = sp.simplify(
        pulled_spatial_one_form - reduced_hamiltonian * dt
    )
    symplectic_matrix = sp.Matrix(
        [
            [
                sp.diff(one_form_coefficients[column], row)
                - sp.diff(one_form_coefficients[row], column)
                for column in free_phase_variables
            ]
            for row in free_phase_variables
        ]
    )
    symplectic_rank = symplectic_matrix.rank()
    quotient_symplectic_witness = _matrix_rank_witness(symplectic_matrix)

    # Discover the p_B -> C_B first-class chain and construct its Castellani
    # generator.  The generator is expressed in the generated constraints,
    # not counted as an extra constraint.
    primary_B_index = next(
        index
        for index, primary in enumerate(primaries)
        if sp.simplify(primary - p_B) == 0
    )
    C_B = baseline["secondary_candidates"][primary_B_index]
    eta, eta_dot = sp.symbols("eta eta_dot", real=True)
    spatial_generator = sp.factor(
        scale**2 * eta_dot * primaries[primary_B_index]
        - scale**2 * eta * C_B
    )
    generator_constraint_representation_residual = sp.simplify(
        spatial_generator
        - (
            scale**2 * eta_dot * primaries[primary_B_index]
            - scale**2 * eta * C_B
        )
    )
    coordinate_variations = {
        coordinate: _canonical_poisson_bracket(
            coordinate, spatial_generator, coordinates, momenta
        )
        for coordinate in coordinates
    }
    Sigma_variation = sp.simplify(
        coordinate_variations[B] - scale**2 * eta_dot
    )
    weak_generator_brackets = tuple(
        sp.simplify(
            _canonical_poisson_bracket(
                spatial_generator, constraint, coordinates, momenta
            ).subs(constraint_solution, simultaneous=True)
        )
        for constraint in baseline["constraints"]
    )

    E_dot_on_constraint_surface = sp.factor(
        baseline["velocity_solution"][E_dot].subs(
            constraint_solution, simultaneous=True
        )
    )
    B_solutions = sp.solve(
        sp.Eq(E_dot_on_constraint_surface, 0), B, dict=True
    )
    if not B_solutions:
        raise RuntimeError("E=0 gauge preservation did not determine the shift")
    B_solution = sp.factor(B_solutions[0][B])

    # Compare the gauge-fixed action and constraints to the pre-existing
    # gauge-fixed principal derivation.  Proportionality factors are obtained
    # from polynomial coefficients rather than supplied in advance.
    from cde_l4c_2delta_flrw_gate_2026 import _derive_principal_family

    existing = _derive_principal_family()
    existing_symbol_map = {
        existing["A"]: A,
        existing["q"]: q,
        existing["H"]: H,
        existing["lambda_s_bar"]: lambda_s_bar,
        existing["lambda_K_bar"]: lambda_K_bar,
    }
    for old, new in zip(
        existing["coordinates"],
        (Phi, Psi, B, delta_lambda_s, delta_lambda_K),
    ):
        existing_symbol_map[old] = new
    for old, new in zip(
        existing["momenta"],
        (p_Phi, p_Psi, p_B, p_s, p_K),
    ):
        existing_symbol_map[old] = new
    existing_mapped_lagrangian = sp.factor(
        existing["lagrangian"].subs(
            existing_symbol_map, simultaneous=True
        )
    )
    existing_mapped_constraints = tuple(
        sp.factor(
            constraint.subs(existing_symbol_map, simultaneous=True)
        )
        for constraint in existing["constraints"]
    )
    gauge_fixed_secondaries = list(baseline["secondary_candidates"])
    gauge_fixed_secondaries[primary_B_index] = sp.factor(B - B_solution)
    gauge_fixed_constraints = primaries + tuple(gauge_fixed_secondaries)
    proportionality_factors: list[sp.Expr] = []
    proportionality_residuals: list[sp.Expr] = []
    for generated, previous in zip(
        gauge_fixed_constraints, existing_mapped_constraints
    ):
        ratio, residual = _proportional_polynomial_residual(
            generated, previous, phase_variables
        )
        proportionality_factors.append(ratio)
        proportionality_residuals.append(residual)

    # Positive longitudinal background: change only the spatial Phi^2
    # coefficient, then repeat the complete momentum/constraint generation.
    lambda_parallel, y = sp.symbols(
        "lambda_parallel y", positive=True
    )
    positive_lagrangian = sp.factor(
        lagrangian - A * lambda_parallel * q**2 * Phi**2
    )
    positive_signature = canonical_signature(positive_lagrangian)
    positive_constraint_solutions = sp.solve(
        positive_signature["constraints"],
        elimination_preference,
        dict=True,
        simplify=False,
    )
    if not positive_constraint_solutions:
        raise RuntimeError("positive-gradient constraint surface not solved")
    positive_constraint_solution = {
        variable: sp.factor(value)
        for variable, value in positive_constraint_solutions[0].items()
    }
    positive_reduced_hamiltonian = sp.factor(
        positive_signature["canonical_hamiltonian"].subs(
            positive_constraint_solution, simultaneous=True
        )
    )
    omega_squared = sp.simplify(
        sp.diff(positive_reduced_hamiltonian, p_Psi, 2)
        * sp.diff(positive_reduced_hamiltonian, Psi, 2)
    )
    sound_speed_squared = sp.simplify(omega_squared / q**2)
    exact_lambda_parallel = sp.simplify(1 + (y - 1) * sp.exp(-y))
    exact_sound_speed_squared = sp.simplify(
        sound_speed_squared.subs(lambda_parallel, exact_lambda_parallel)
    )

    # Two adversarial mutations are regenerated through the same canonical
    # pipeline.  One removes a multiplier coupling; one changes a kinetic
    # coefficient while preserving dependence on Sigma.
    lambda_s_piece = sp.factor(
        A
        * task2["quadratic"]["normalized_pieces"]["lambda_s"]
    )
    deleted_lambda_s_lagrangian = sp.factor(lagrangian - lambda_s_piece)
    deleted_lambda_s_signature = canonical_signature(
        deleted_lambda_s_lagrangian
    )
    shear_theta_piece = sp.factor(2 * A * q**2 * Sigma * Theta)
    perturbed_shear_lagrangian = sp.factor(
        lagrangian + shear_theta_piece / 2
    )
    perturbed_shear_signature = canonical_signature(
        perturbed_shear_lagrangian
    )
    perturbed_spatial_diffeomorphism_identity = sp.simplify(
        sp.diff(perturbed_shear_lagrangian, E_dot)
        + scale**2 * sp.diff(perturbed_shear_lagrangian, B)
    )

    primary_rank = constraint_rank(primaries)
    final_rank = baseline["constraint_jacobian_rank"]
    preservation_iterations = (
        {
            "stage": "primaries",
            "constraint_count": len(primaries),
            "jacobian_rank": primary_rank,
            "new_independent_constraints": len(primaries),
        },
        {
            "stage": "secondaries",
            "constraint_count": len(baseline["constraints"]),
            "jacobian_rank": final_rank,
            "new_independent_constraints": (
                len(baseline["constraints"]) - len(primaries)
            ),
        },
        {
            "stage": "closure",
            "constraint_count": (
                len(baseline["constraints"]) + len(tertiary_candidates)
            ),
            "jacobian_rank": current_rank,
            "new_independent_constraints": len(tertiary_candidates),
        },
    )

    return {
        "symbols": {
            "A": A,
            "a": scale,
            "q": q,
            "H": H,
            "H_dot": H_dot,
            "Phi": Phi,
            "Psi": Psi,
            "B": B,
            "E": E,
            "delta_lambda_s": delta_lambda_s,
            "delta_lambda_K": delta_lambda_K,
            "lambda_s_bar": lambda_s_bar,
            "lambda_K_bar": lambda_K_bar,
            "lambda_s_bar_dot": lambda_s_bar_dot,
            "lambda_K_bar_dot": lambda_K_bar_dot,
            "Phi_dot": Phi_dot,
            "Psi_dot": Psi_dot,
            "B_dot": B_dot,
            "E_dot": E_dot,
            "delta_lambda_s_dot": delta_lambda_s_dot,
            "delta_lambda_K_dot": delta_lambda_K_dot,
            "p_Phi": p_Phi,
            "p_Psi": p_Psi,
            "p_B": p_B,
            "p_E": p_E,
            "p_s": p_s,
            "p_K": p_K,
        },
        "restoration": {
            "Theta": Theta,
            "Sigma": Sigma,
            "effective_lambda_s": effective_lambda_s,
            "effective_lambda_K": effective_lambda_K,
            "task2_on_shell_action": task2_on_shell_action,
            "task2_normalized_action": task2_normalized_action,
            "task2_gauge_fixed_action": gauge_fixed_action,
            "lagrangian": lagrangian,
            "task2_provenance_residual": task2_provenance_residual,
            "E_zero_gauge_action_residual": (
                E_zero_gauge_action_residual
            ),
            "spatial_diffeomorphism_identity": (
                spatial_diffeomorphism_identity
            ),
            "identity_checked_before_legendre": True,
        },
        "canonical": {
            "coordinates": coordinates,
            "velocities": velocities,
            "momenta": momenta,
            "phase_variables": phase_variables,
            "lagrangian": lagrangian,
            "derived_momenta": baseline["derived_momenta"],
            "velocity_hessian": baseline["velocity_hessian"],
            "velocity_hessian_rank": baseline["velocity_hessian_rank"],
            "velocity_hessian_nullspace": baseline[
                "velocity_hessian_nullspace"
            ],
            "regular_velocity_indices": baseline[
                "regular_velocity_indices"
            ],
            "regular_momentum_indices": baseline[
                "regular_momentum_indices"
            ],
            "velocity_solution": baseline["velocity_solution"],
            "primaries": primaries,
            "legendre_expression": baseline["legendre_expression"],
            "legendre_after_regular_solution": baseline[
                "legendre_after_regular_solution"
            ],
            "null_velocity_primary_piece": baseline[
                "null_velocity_primary_piece"
            ],
            "legendre_decomposition_residual": baseline[
                "legendre_decomposition_residual"
            ],
            "canonical_hamiltonian": baseline[
                "canonical_hamiltonian"
            ],
            "primary_multipliers": primary_multipliers,
            "total_hamiltonian": total_hamiltonian,
        },
        "dirac": {
            "secondary_candidates": baseline["secondary_candidates"],
            "constraints": baseline["constraints"],
            "constraint_generation_ranks": baseline[
                "constraint_generation_ranks"
            ],
            "constraint_solution": constraint_solution,
            "constraint_solution_residuals": (
                constraint_solution_residuals
            ),
            "constraint_jacobian": baseline["constraint_jacobian"],
            "constraint_jacobian_rank": baseline[
                "constraint_jacobian_rank"
            ],
            "poisson_matrix": poisson_matrix,
            "poisson_determinant": baseline["poisson_determinant"],
            "poisson_rank": baseline["poisson_rank"],
            "rank_witness_minor": poisson_rank_witness,
            "sample_substitutions": tuple(sample_substitutions),
            "sampled_exact_ranks": tuple(sampled_exact_ranks),
            "sampled_numerical_ranks": tuple(sampled_numerical_ranks),
            "declared_singular_surfaces": (A, scale, q),
        },
        "time_preservation": {
            "background_derivative_rules": background_derivative_rules,
            "partial_time_operator": partial_time,
            "partial_time_terms": partial_time_terms,
            "poisson_evolution_terms": poisson_evolution_terms,
            "total_time_derivatives": total_time_derivatives,
            "on_constraint_surface": on_constraint_surface,
            "multiplier_coefficient_matrix": (
                multiplier_coefficient_matrix
            ),
            "multiplier_rhs": multiplier_rhs,
            "multiplier_coefficient_rank": multiplier_coefficient_rank,
            "augmented_rank": augmented_rank,
            "multiplier_rank_witness_minor": multiplier_rank_witness,
            "multiplier_solution": multiplier_solution,
            "fixed_multipliers": tuple(multiplier_solution),
            "free_multipliers": free_multipliers,
            "closure_residuals": closure_residuals,
            "tertiary_candidates": tuple(tertiary_candidates),
            "no_tertiary_evidence": not tertiary_candidates
            and all(residual == 0 for residual in closure_residuals),
            "C_B": C_B,
            "C_B_preservation": total_time_derivatives[
                len(primaries) + primary_B_index
            ],
            "iterations": preservation_iterations,
        },
        "classification": {
            "poisson_nullspace": poisson_nullspace,
            "first_class_combinations": first_class_combinations,
            "weak_first_class_brackets": weak_first_class_brackets,
            "first_class_count": first_class_count,
            "second_class_count": second_class_count,
            "phase_dimension": phase_dimension,
            "reduced_phase_dimension": reduced_phase_dimension,
            "configuration_dof": configuration_dof,
        },
        "spatial_gauge": {
            "primary_B_index": primary_B_index,
            "C_B": C_B,
            "eta": eta,
            "eta_dot": eta_dot,
            "generator": spatial_generator,
            "generator_constraint_representation_residual": (
                generator_constraint_representation_residual
            ),
            "coordinate_variations": coordinate_variations,
            "Sigma_variation": Sigma_variation,
            "weak_generator_brackets": weak_generator_brackets,
            "E_zero_action_residual": E_zero_gauge_action_residual,
            "E_zero_preservation_equation": (
                E_dot_on_constraint_surface
            ),
            "B_solution": B_solution,
            "existing_gauge_fixed_comparison": {
                "source_lagrangian": existing["lagrangian"],
                "symbol_map": existing_symbol_map,
                "mapped_lagrangian": existing_mapped_lagrangian,
                "lagrangian_residual": sp.simplify(
                    gauge_fixed_action - existing_mapped_lagrangian
                ),
                "generated_constraints": gauge_fixed_constraints,
                "mapped_existing_constraints": (
                    existing_mapped_constraints
                ),
                "constraint_count_matches": (
                    len(gauge_fixed_constraints)
                    == len(existing_mapped_constraints)
                ),
                "proportionality_factors": tuple(
                    proportionality_factors
                ),
                "proportionality_residuals": tuple(
                    proportionality_residuals
                ),
            },
        },
        "reduction": {
            "free_phase_variables": free_phase_variables,
            "differentials": differential_symbols,
            "dt": dt,
            "one_form_coefficients": one_form_coefficients,
            "pulled_spatial_one_form": pulled_spatial_one_form,
            "reduced_hamiltonian": reduced_hamiltonian,
            "pulled_extended_one_form": pulled_extended_one_form,
            "symplectic_matrix": symplectic_matrix,
            "symplectic_rank": symplectic_rank,
            "quotient_symplectic_rows": quotient_symplectic_witness[
                "rows"
            ],
            "quotient_symplectic_columns": quotient_symplectic_witness[
                "columns"
            ],
            "quotient_symplectic_determinant": (
                quotient_symplectic_witness["determinant"]
            ),
        },
        "positive_gradient": {
            "y": y,
            "lambda_parallel": lambda_parallel,
            "exact_lambda_parallel": exact_lambda_parallel,
            "lagrangian": positive_lagrangian,
            "derived_momenta": positive_signature["derived_momenta"],
            "constraints": positive_signature["constraints"],
            "poisson_matrix": positive_signature["poisson_matrix"],
            "poisson_rank": positive_signature["poisson_rank"],
            "constraint_solution": positive_constraint_solution,
            "reduced_hamiltonian": positive_reduced_hamiltonian,
            "omega_squared": omega_squared,
            "sound_speed_squared": sound_speed_squared,
            "exact_sound_speed_squared": exact_sound_speed_squared,
        },
        "mutation_controls": {
            "without_lambda_s_coupling": {
                "lagrangian": deleted_lambda_s_lagrangian,
                "lagrangian_difference": sp.factor(
                    deleted_lambda_s_lagrangian - lagrangian
                ),
                "lambda_s_euler_derivative": sp.diff(
                    deleted_lambda_s_lagrangian, delta_lambda_s
                ),
                "constraints": deleted_lambda_s_signature["constraints"],
                "constraint_jacobian_rank": deleted_lambda_s_signature[
                    "constraint_jacobian_rank"
                ],
                "poisson_matrix": deleted_lambda_s_signature[
                    "poisson_matrix"
                ],
                "poisson_rank": deleted_lambda_s_signature[
                    "poisson_rank"
                ],
            },
            "perturbed_shear_theta_coefficient": {
                "lagrangian": perturbed_shear_lagrangian,
                "lagrangian_difference": sp.factor(
                    perturbed_shear_lagrangian - lagrangian
                ),
                "derived_momenta": perturbed_shear_signature[
                    "derived_momenta"
                ],
                "constraints": perturbed_shear_signature["constraints"],
                "poisson_matrix": perturbed_shear_signature[
                    "poisson_matrix"
                ],
                "poisson_rank": perturbed_shear_signature[
                    "poisson_rank"
                ],
                "spatial_diffeomorphism_identity": (
                    perturbed_spatial_diffeomorphism_identity
                ),
            },
        },
        "scope": {
            "finite_k_only": True,
            "full_time_dependent_quadratic_chain": True,
            "matter_perturbations_invented": False,
            "nonlinear_zero_gradient_rank_proved": False,
            "global_covariant_dof_theorem": False,
        },
    }


def derive_finite_k_dirac_chain() -> dict[str, Any]:
    """Return an isolated copy of the generated finite-k Dirac analysis."""

    return deepcopy(_derive_finite_k_dirac_chain_cached())


if __name__ == "__main__":
    geometry = derive_full_flrw_adm_geometry()
    print("exact FLRW ADM geometry constructed")
    print("R3 =", geometry["three_curvature"])
    print("K =", geometry["extrinsic_trace_direct"])
