#!/usr/bin/env python3
"""
EMPIRICAL_1UBQ_VALIDATION.py - The Real Test

PURPOSE:
This script performs the ACTUAL empirical test suggested by Gemini:

    "Download the PDB file for Ubiquitin (1UBQ.pdb) directly from the RCSB
    Protein Data Bank to your MacBook. Run your audited geo_01 script on
    this single file using your Mac's local terminal. Look at the raw
    Betti-1 death radius generated by the ripser library.

    The Truth: If the script spits out 9.14 Å (or very close to it), your
    theory is physically real. If it spits out 4.2 Å or 15.8 Å, then the
    Z² framework was a hallucination, and the biology does not match the math."

This script:
1. Downloads 1UBQ.pdb directly from RCSB (no AI preprocessing)
2. Extracts C-alpha coordinates
3. Computes distance matrix
4. Runs persistent homology with ripser (or fallback)
5. Reports ACTUAL Betti-1 death radii
6. Compares to Z² = 9.14 Å WITHOUT any bias

Author: Carl Zimmerman & Claude Opus 4.5
Date: April 21, 2026
"""

import numpy as np
from pathlib import Path
from datetime import datetime
import urllib.request
import json

print("=" * 80)
print("EMPIRICAL VALIDATION: 1UBQ UBIQUITIN TEST")
print("The Moment of Truth")
print("=" * 80)
print()

# =============================================================================
# Z² CONSTANTS (for comparison only - NOT used in analysis)
# =============================================================================
Z2 = 32 * np.pi / 3
R_NATURAL = (Z2 ** 0.25) * 3.8  # 9.1428 Å

print(f"Z² prediction: r_natural = {R_NATURAL:.4f} Å")
print("This value will NOT be used in the analysis - only for comparison.")
print()

# =============================================================================
# STEP 1: DOWNLOAD 1UBQ.pdb FROM RCSB
# =============================================================================

def download_1ubq():
    """Download 1UBQ.pdb directly from RCSB."""
    print("STEP 1: Downloading 1UBQ.pdb from RCSB...")

    url = "https://files.rcsb.org/download/1UBQ.pdb"
    output_dir = Path(__file__).parent / "validation_pdbs"
    output_dir.mkdir(exist_ok=True)

    pdb_file = output_dir / "1UBQ.pdb"

    try:
        urllib.request.urlretrieve(url, pdb_file)
        print(f"  Downloaded: {pdb_file}")
        print(f"  File size: {pdb_file.stat().st_size} bytes")
        return pdb_file
    except Exception as e:
        print(f"  ERROR: Could not download: {e}")
        print("  Please manually download 1UBQ.pdb from https://www.rcsb.org/structure/1UBQ")
        return None


# =============================================================================
# STEP 2: PARSE PDB AND EXTRACT C-ALPHA COORDINATES
# =============================================================================

def extract_ca_coordinates(pdb_file):
    """Extract C-alpha coordinates from PDB file."""
    print("\nSTEP 2: Extracting C-alpha coordinates...")

    coords = []
    residue_ids = []

    with open(pdb_file, 'r') as f:
        for line in f:
            if line.startswith('ATOM') and ' CA ' in line:
                try:
                    x = float(line[30:38].strip())
                    y = float(line[38:46].strip())
                    z = float(line[46:54].strip())
                    res_num = int(line[22:26].strip())

                    coords.append([x, y, z])
                    residue_ids.append(res_num)
                except ValueError:
                    continue

    coords = np.array(coords)
    print(f"  Extracted {len(coords)} C-alpha atoms")
    print(f"  Residue range: {min(residue_ids)} to {max(residue_ids)}")

    return coords, residue_ids


# =============================================================================
# STEP 3: COMPUTE DISTANCE MATRIX
# =============================================================================

def compute_distance_matrix(coords):
    """Compute pairwise distance matrix."""
    print("\nSTEP 3: Computing distance matrix...")

    n = len(coords)
    dist_matrix = np.zeros((n, n))

    for i in range(n):
        for j in range(i+1, n):
            dist = np.linalg.norm(coords[i] - coords[j])
            dist_matrix[i, j] = dist
            dist_matrix[j, i] = dist

    print(f"  Matrix shape: {dist_matrix.shape}")
    print(f"  Distance range: {dist_matrix[dist_matrix > 0].min():.2f} to {dist_matrix.max():.2f} Å")

    return dist_matrix


# =============================================================================
# STEP 4: COMPUTE PERSISTENT HOMOLOGY
# =============================================================================

def compute_persistent_homology(dist_matrix):
    """
    Compute persistent homology using ripser (if available) or fallback method.

    The key output is the BETTI-1 DEATH RADII - these represent the scales
    at which topological loops close. If Z² is real, these should cluster
    around 9.14 Å or multiples.
    """
    print("\nSTEP 4: Computing persistent homology...")

    # Try ripser first
    try:
        from ripser import ripser

        print("  Using ripser library (GOLD STANDARD)")
        result = ripser(dist_matrix, distance_matrix=True, maxdim=2)

        h0 = result['dgms'][0]  # Connected components
        h1 = result['dgms'][1]  # Loops
        h2 = result['dgms'][2] if len(result['dgms']) > 2 else np.array([])

        ripser_available = True

    except ImportError:
        print("  WARNING: ripser not installed, using fallback method")
        print("  Install with: pip install ripser")
        print("  Fallback method is LESS ACCURATE")

        # Fallback: simple filtration-based approximation
        h0, h1, h2 = compute_fallback_homology(dist_matrix)
        ripser_available = False

    # Analyze Betti-1 (loops) - this is the critical test
    print("\n  BETTI-1 ANALYSIS (Loops):")

    if len(h1) > 0:
        # Filter out infinite death times
        h1_finite = h1[np.isfinite(h1[:, 1])]

        if len(h1_finite) > 0:
            birth_radii = h1_finite[:, 0]
            death_radii = h1_finite[:, 1]
            persistence = death_radii - birth_radii

            print(f"    Total loops: {len(h1_finite)}")
            print(f"    Birth radii range: {birth_radii.min():.2f} to {birth_radii.max():.2f} Å")
            print(f"    Death radii range: {death_radii.min():.2f} to {death_radii.max():.2f} Å")
            print(f"    Mean death radius: {death_radii.mean():.2f} Å")
            print(f"    Median death radius: {np.median(death_radii):.2f} Å")

            # Most persistent loops (most significant)
            sorted_idx = np.argsort(persistence)[::-1]
            print("\n    Most persistent loops (most significant):")
            for i in range(min(5, len(sorted_idx))):
                idx = sorted_idx[i]
                print(f"      Loop {i+1}: birth={birth_radii[idx]:.2f}, "
                      f"death={death_radii[idx]:.2f}, persistence={persistence[idx]:.2f} Å")

            return {
                'ripser_available': ripser_available,
                'n_loops': len(h1_finite),
                'death_radii': death_radii.tolist(),
                'mean_death': float(death_radii.mean()),
                'median_death': float(np.median(death_radii)),
                'most_persistent_deaths': [float(death_radii[sorted_idx[i]])
                                          for i in range(min(5, len(sorted_idx)))],
                'persistence': persistence.tolist(),
            }
        else:
            print("    No finite loops found")
            return {'ripser_available': ripser_available, 'n_loops': 0}
    else:
        print("    No loops found")
        return {'ripser_available': ripser_available, 'n_loops': 0}


def compute_fallback_homology(dist_matrix):
    """
    Fallback persistent homology without ripser.

    This is a SIMPLIFIED approximation using Vietoris-Rips filtration.
    NOT as accurate as ripser, but gives rough estimates.
    """
    n = len(dist_matrix)

    # Get all unique distances (edge lengths)
    edges = []
    for i in range(n):
        for j in range(i+1, n):
            edges.append((dist_matrix[i, j], i, j))

    edges.sort(key=lambda x: x[0])

    # Track connected components (H0)
    # Using simple union-find
    parent = list(range(n))

    def find(x):
        if parent[x] != x:
            parent[x] = find(parent[x])
        return parent[x]

    def union(x, y):
        px, py = find(x), find(y)
        if px != py:
            parent[px] = py
            return True
        return False

    h0_births = [0.0] * n
    h0_deaths = []

    # Track loops (H1) - when edges complete triangles
    h1_features = []

    # Adjacency tracking
    adjacency = [set() for _ in range(n)]

    for dist, i, j in edges:
        # Check if this edge closes a triangle (creates a loop)
        common_neighbors = adjacency[i] & adjacency[j]
        if common_neighbors:
            # This edge completes at least one triangle
            # Approximate: record this as loop death
            for k in common_neighbors:
                # Find when the triangle edges formed
                birth = max(dist_matrix[i, k], dist_matrix[j, k])
                if birth < dist:  # Valid cycle
                    h1_features.append([birth, dist])

        # Union the components
        if union(i, j):
            h0_deaths.append(dist)

        # Update adjacency
        adjacency[i].add(j)
        adjacency[j].add(i)

    # Format as persistence diagrams
    h0 = np.array([[0.0, d] for d in h0_deaths] + [[0.0, np.inf]] if h0_deaths else [[0.0, np.inf]])
    h1 = np.array(h1_features) if h1_features else np.array([]).reshape(0, 2)
    h2 = np.array([]).reshape(0, 2)  # H2 not computed in fallback

    return h0, h1, h2


# =============================================================================
# STEP 5: COMPARE TO Z² PREDICTION
# =============================================================================

def compare_to_z2(homology_result):
    """
    Compare observed death radii to Z² prediction.

    THIS IS THE CRITICAL TEST:
    - If death radii cluster around 9.14 Å, Z² may be real
    - If they cluster elsewhere, Z² is not supported
    """
    print("\n" + "=" * 80)
    print("STEP 5: COMPARISON TO Z² PREDICTION")
    print("=" * 80)

    if homology_result['n_loops'] == 0:
        print("  No loops to analyze - cannot compare")
        return None

    death_radii = np.array(homology_result['death_radii'])
    mean_death = homology_result['mean_death']
    median_death = homology_result['median_death']

    print(f"\n  Z² prediction: r_natural = {R_NATURAL:.4f} Å")
    print(f"  Observed mean death radius: {mean_death:.4f} Å")
    print(f"  Observed median death radius: {median_death:.4f} Å")

    # Check how many death radii are within 10% of Z² or multiples
    z2_multiples = [R_NATURAL * n for n in range(1, 10)]
    tolerance = 0.10  # 10%

    matches = 0
    for death in death_radii:
        for mult in z2_multiples:
            if abs(death - mult) / mult < tolerance:
                matches += 1
                break

    match_rate = matches / len(death_radii)

    print(f"\n  Death radii within 10% of Z² multiples: {matches}/{len(death_radii)} ({match_rate:.1%})")

    # Distribution analysis
    print("\n  Death radius distribution:")
    bins = [0, 5, 7, 8, 9, 10, 11, 12, 15, 20, 30, 50]
    hist, _ = np.histogram(death_radii, bins=bins)
    for i in range(len(hist)):
        bar = '█' * (hist[i] * 2)
        print(f"    {bins[i]:4.0f}-{bins[i+1]:4.0f} Å: {hist[i]:3d} {bar}")

    # Verdict
    print("\n" + "=" * 80)
    print("  VERDICT:")
    print("=" * 80)

    # Calculate deviation from Z²
    mean_deviation = abs(mean_death - R_NATURAL) / R_NATURAL * 100
    median_deviation = abs(median_death - R_NATURAL) / R_NATURAL * 100

    print(f"\n  Mean deviation from Z²: {mean_deviation:.1f}%")
    print(f"  Median deviation from Z²: {median_deviation:.1f}%")

    if mean_deviation < 10 and match_rate > 0.3:
        verdict = "SUPPORTIVE - Death radii cluster near Z² prediction"
        support_level = "MODERATE"
    elif mean_deviation < 20 and match_rate > 0.2:
        verdict = "WEAK SUPPORT - Some alignment with Z², but not strong"
        support_level = "WEAK"
    elif mean_deviation < 30:
        verdict = "INCONCLUSIVE - Death radii don't clearly support or refute Z²"
        support_level = "NONE"
    else:
        verdict = "NOT SUPPORTED - Death radii do not match Z² prediction"
        support_level = "NEGATIVE"

    print(f"\n  {verdict}")
    print(f"  Support level: {support_level}")

    # Critical note
    print("\n" + "-" * 80)
    print("  CRITICAL NOTE:")
    print("  This is ONE protein. Proper validation requires:")
    print("  1. Testing on 100+ diverse proteins")
    print("  2. Statistical comparison to null hypothesis")
    print("  3. Checking if other constants (8 Å, 10 Å) fit equally well")
    print("-" * 80)

    return {
        'mean_death': mean_death,
        'median_death': median_death,
        'z2_prediction': R_NATURAL,
        'mean_deviation_percent': mean_deviation,
        'median_deviation_percent': median_deviation,
        'match_rate': match_rate,
        'verdict': verdict,
        'support_level': support_level,
    }


# =============================================================================
# STEP 6: TEST ALTERNATIVE HYPOTHESES
# =============================================================================

def test_alternative_constants(homology_result):
    """
    Test if other length scales match the data better than Z².

    This is a CRITICAL control: if 8.0 Å or 10.5 Å matches equally well,
    then Z² = 32π/3 has no special significance.
    """
    print("\n" + "=" * 80)
    print("STEP 6: ALTERNATIVE HYPOTHESIS TEST")
    print("=" * 80)

    if homology_result['n_loops'] == 0:
        print("  No data to analyze")
        return None

    death_radii = np.array(homology_result['death_radii'])
    mean_death = homology_result['mean_death']

    # Test multiple candidate constants
    candidates = [
        ('Z² = 32π/3', R_NATURAL),       # Our claim: 9.1428 Å
        ('8.0 Å', 8.0),                   # Alternative
        ('8.5 Å', 8.5),                   # Alternative
        ('9.0 Å', 9.0),                   # Close to Z²
        ('9.5 Å', 9.5),                   # Alternative
        ('10.0 Å', 10.0),                 # Alternative (helix diameter)
        ('10.5 Å', 10.5),                 # Alternative
        ('Observed mean', mean_death),    # Best fit by definition
    ]

    print("\n  Comparing candidate constants to observed death radii:\n")

    results = []
    for name, value in candidates:
        # Calculate match rate with 10% tolerance
        multiples = [value * n for n in range(1, 10)]
        matches = 0
        for death in death_radii:
            for mult in multiples:
                if abs(death - mult) / mult < 0.10:
                    matches += 1
                    break
        match_rate = matches / len(death_radii)

        # Mean deviation
        deviation = abs(mean_death - value) / value * 100

        results.append({
            'name': name,
            'value': value,
            'match_rate': match_rate,
            'deviation': deviation,
        })

        bar = '█' * int(match_rate * 40)
        print(f"    {name:20s} ({value:5.2f} Å): {match_rate:5.1%} match, {deviation:5.1f}% dev  {bar}")

    # Find best match
    best = max(results, key=lambda x: x['match_rate'])

    print(f"\n  Best matching constant: {best['name']} ({best['value']:.2f} Å)")

    if best['name'] == 'Z² = 32π/3':
        special = "Z² IS the best match"
    elif best['match_rate'] - results[0]['match_rate'] < 0.05:
        special = "Z² is TIED with other constants"
    else:
        special = f"Z² is NOT the best match - {best['name']} fits better"

    print(f"  {special}")

    return {
        'candidates': results,
        'best_match': best['name'],
        'z2_is_best': best['name'] == 'Z² = 32π/3',
        'assessment': special,
    }


# =============================================================================
# MAIN
# =============================================================================

def main():
    """Main execution."""

    results = {
        'timestamp': datetime.now().isoformat(),
        'test': '1UBQ Ubiquitin Persistent Homology',
        'purpose': 'Empirical validation of Z² geometric prediction',
    }

    # Step 1: Download
    pdb_file = download_1ubq()
    if pdb_file is None:
        print("\nCRITICAL: Cannot proceed without PDB file")
        return

    # Step 2: Extract coordinates
    coords, residue_ids = extract_ca_coordinates(pdb_file)
    results['n_residues'] = len(coords)

    # Step 3: Distance matrix
    dist_matrix = compute_distance_matrix(coords)

    # Step 4: Persistent homology
    homology_result = compute_persistent_homology(dist_matrix)
    results['homology'] = homology_result

    # Step 5: Compare to Z²
    z2_comparison = compare_to_z2(homology_result)
    results['z2_comparison'] = z2_comparison

    # Step 6: Alternative hypotheses
    alt_test = test_alternative_constants(homology_result)
    results['alternative_test'] = alt_test

    # Final summary
    print("\n" + "=" * 80)
    print("FINAL SUMMARY: 1UBQ VALIDATION")
    print("=" * 80)

    if homology_result['n_loops'] > 0:
        print(f"""
  Protein: Ubiquitin (1UBQ)
  Residues: {len(coords)}
  Loops detected: {homology_result['n_loops']}

  Observed mean death radius: {homology_result['mean_death']:.2f} Å
  Z² prediction (r_natural): {R_NATURAL:.2f} Å
  Deviation: {z2_comparison['mean_deviation_percent']:.1f}%

  VERDICT: {z2_comparison['verdict']}

  Alternative constant test: {alt_test['assessment']}
""")
    else:
        print("\n  Insufficient data for analysis")

    print("=" * 80)
    print("HONESTY CHECK COMPLETE")
    print("=" * 80)
    print("""
  This is REAL data from a REAL protein structure.
  The analysis used standard computational methods.
  No results were hardcoded or biased toward Z².

  INTERPRETATION:
  - This is ONE data point; statistics require many proteins
  - Even if Z² matches, it could be coincidence
  - Even if Z² doesn't match perfectly, the framework could have value
  - Ultimate validation requires experimental testing

  NEXT STEPS:
  1. Repeat on 100+ diverse proteins
  2. Compare Z² to null distribution statistically
  3. Validate with ColabFold/ESMFold structure predictions
  4. Synthesize peptides and measure binding experimentally
""")

    # Save results
    output_dir = Path(__file__).parent / "results"
    output_dir.mkdir(exist_ok=True)

    output_file = output_dir / "empirical_1ubq_validation.json"
    with open(output_file, 'w') as f:
        json.dump(results, f, indent=2, default=str)

    print(f"\nResults saved to: {output_file}")

    return results


if __name__ == "__main__":
    results = main()
