#!/usr/bin/env python3
"""
CFG155 -- independent referee of CFG130 (Door 5), ONE headline: for CFG44's point-mass target, Eddington's
isotropic f(E) is positive over the whole energy range.

Frozen criteria: ../CFG155_FROZEN_CRITERIA.md (its sha256 is printed first).  Written from CFG130's FROZEN_QUESTION.md
and README.md only; CFG130's scripts and outputs were not opened before the frozen runs of this file.

Units G = M_b = a0 = 1: r_M = 1, speeds in v_M = (G M_b a0)^(1/4), energies in v_M^2, f in M_b r_M^-3 v_M^-3.
Target: rho_c = 1/(4 pi x sqrt(1+x^2)), g_tot = sqrt(1+x^2)/x^2, Phi = asinh x - sqrt(1+x^2)/x (Phi -> -1/x at the centre).

Eddington (Binney & Tremaine 2008, sec. 4.3.1, recalled), E convention; Phi_max = +inf for the target:
  first form   f(E) = (1/(sqrt8 pi^2)) d/dE Int_E^Phimax (drho/dPhi) dPhi / sqrt(Phi - E)
  second form  f(E) = (1/(sqrt2 pi^2)) Int_0^tmax rho''(E + t^2) dt - (1/(sqrt8 pi^2)) rho'(Phimax)/sqrt(Phimax - E)
Three routes: A (second form, Gauss-Legendre in t), B (second form in x, QUADPACK with the (x - x_E)^(-1/2) weight),
C (first form: Route A's quadrature of drho/dPhi and a 5-point derivative in E).

Usage:   python3 cfg155_eddington_referee.py            main run
         MUTATE=1 python3 cfg155_eddington_referee.py   MUTATE: rho_c replaced by the cored tracer
                                                         rho_mut = 1/(4 pi sqrt(x^2 + 0.01) sqrt(1+x^2)), same potential
Outputs next to this file: cfg155_eddington_referee[_MUTATE].out and cfg155_eddington_referee[_MUTATE]_results.json.
Exit 0 only if H1 and every control pass.  kappa = 1/2 and Omega_c h^2 stay fitted; nothing here fits anything.
"""
import hashlib
import json
import math
import os
import sys
import time
import warnings

import mpmath as mp
import numpy as np
import sympy as sp
from scipy.integrate import IntegrationWarning, quad, solve_ivp

HERE = os.path.dirname(os.path.abspath(__file__))
SPEC = os.path.join(HERE, '..', 'CFG155_FROZEN_CRITERIA.md')
SPEC_REL = 'campaign_fresh_gravity/CFG155_FROZEN_CRITERIA.md'
MUTATE = os.environ.get('MUTATE', '0') == '1'
TAG = 'cfg155_eddington_referee' + ('_MUTATE' if MUTATE else '')
OUT_TXT = os.path.join(HERE, TAG + '.out')
OUT_JSON = os.path.join(HERE, TAG + '_results.json')

SQ2, PI = math.sqrt(2.0), math.pi
C2 = 1.0 / (SQ2 * PI ** 2)            # 1/(sqrt2 pi^2): second-form prefactor
C8 = 1.0 / (math.sqrt(8.0) * PI ** 2)  # 1/(sqrt8 pi^2): first-form prefactor and boundary term
GLX, GLW = np.polynomial.legendre.leggauss(64)
X_CORE = 0.1                           # MUTATE only (declared in the spec)
LOG = []
NWARN = {'quad': 0}


def log(s=''):
    print(s, flush=True)
    LOG.append(s)


# ----------------------------------------------------------------------------------------------------------------------
# profiles: declared by rho(x), g(x) and the closed-form Phi(x); dPhi/dx = g is checked by sympy; drho/dPhi = (drho/dx)/g,
# K = d(drho/dPhi)/dx = rho'' g and rho'' = K/g are generated by sympy (simplified before lambdify, so no cancelling sums).
# D(x, xe) = (Phi(x) - Phi(xe))/(x - xe) is written per potential without cancellation.
# ----------------------------------------------------------------------------------------------------------------------
X = sp.symbols('x', positive=True)


class Profile:
    def __init__(self, name, rho, g, phi, phi0, phimax, D_np, D_s):
        self.name = name
        self.rho_e, self.g_e, self.phi_e = rho, g, phi
        self.phi0, self.phimax = float(phi0), float(phimax)
        self.phi_ok = bool(sp.simplify(sp.diff(phi, X) - g) == 0)
        d1 = sp.simplify(sp.diff(rho, X) / g)
        K = sp.simplify(sp.diff(d1, X))
        r2 = sp.simplify(K / g)
        self.d1_e, self.K_e, self.r2_e = d1, K, r2
        self.d1_inf = sp.limit(d1, X, sp.oo)
        L = lambda e, m: sp.lambdify(X, e, modules=m)
        self.rho, self.g, self.phi = L(rho, 'numpy'), L(g, 'numpy'), L(phi, 'numpy')
        self.d1, self.K, self.r2 = L(d1, 'numpy'), L(K, 'numpy'), L(r2, 'numpy')
        self.K_s, self.phi_s = L(K, 'math'), L(phi, 'math')
        self.mpf = {k: L(e, 'mpmath') for k, e in (('d1', d1), ('K', K), ('r2', r2))}
        self.D, self.D_s = D_np, D_s


def D_tgt_np(x, xe):
    """(Phi(x)-Phi(xe))/(x-xe) for Phi = asinh x - sqrt(1+x^2)/x, via asinh a - asinh b = asinh(a sqrt(1+b^2) - b sqrt(1+a^2))
    and sqrt(1+1/x^2) - sqrt(1+1/xe^2) = -(x-xe)(x+xe)/(x^2 xe^2 (F+Fe))."""
    x = np.asarray(x, float)
    xe = np.asarray(xe, float)
    sx, se = np.sqrt(1 + x * x), np.sqrt(1 + xe * xe)
    den = x * se + xe * sx
    S = (x - xe) * (x + xe) / den
    Ss = np.where(S == 0, 1.0, S)
    ratio = np.where(S == 0, 1.0, np.arcsinh(Ss) / Ss)
    F, Fe = np.sqrt(1 + 1 / (x * x)), np.sqrt(1 + 1 / (xe * xe))
    return ratio * (x + xe) / den + (x + xe) / (x * x * xe * xe * (F + Fe))


def D_tgt_s(x, xe):
    sx, se = math.sqrt(1 + x * x), math.sqrt(1 + xe * xe)
    den = x * se + xe * sx
    S = (x - xe) * (x + xe) / den
    ratio = 1.0 if S == 0 else math.asinh(S) / S
    F, Fe = math.sqrt(1 + 1 / (x * x)), math.sqrt(1 + 1 / (xe * xe))
    return ratio * (x + xe) / den + (x + xe) / (x * x * xe * xe * (F + Fe))


def D_her_np(x, xe):
    return 1.0 / ((1 + np.asarray(x, float)) * (1 + np.asarray(xe, float)))


def D_her_s(x, xe):
    return 1.0 / ((1 + x) * (1 + xe))


def D_sis_np(x, xe):
    x = np.asarray(x, float)
    xe = np.asarray(xe, float)
    u = (x - xe) / xe
    us = np.where(u == 0, 1.0, u)
    return np.where(u == 0, 1.0 / xe, np.log1p(us) / (us * xe))


def D_sis_s(x, xe):
    u = (x - xe) / xe
    return 1.0 / xe if u == 0 else math.log1p(u) / (u * xe)


def build_profiles():
    sq = sp.sqrt(1 + X ** 2)
    tgt = Profile('target', 1 / (4 * sp.pi * X * sq), sq / X ** 2, sp.asinh(X) - sq / X, -np.inf, np.inf,
                  D_tgt_np, D_tgt_s)
    mut = Profile('mutate_cored', 1 / (4 * sp.pi * sp.sqrt(X ** 2 + sp.Rational(1, 100)) * sq), sq / X ** 2,
                  sp.asinh(X) - sq / X, -np.inf, np.inf, D_tgt_np, D_tgt_s)
    her = Profile('hernquist', 1 / (2 * sp.pi * X * (1 + X) ** 3), 1 / (1 + X) ** 2, -1 / (1 + X), -1.0, 0.0,
                  D_her_np, D_her_s)
    sis = Profile('sis', 1 / (4 * sp.pi * X ** 2), 1 / X, sp.log(X), -np.inf, np.inf, D_sis_np, D_sis_s)
    return tgt, mut, her, sis


# ----------------------------------------------------------------------------------------------------------------------
# numerics
# ----------------------------------------------------------------------------------------------------------------------
def invert(prof, phit, lo, hi, maxit=300):
    """x with Phi(x) = phit, by safeguarded Newton in s = ln x inside the bracket [lo, hi] (ln x)."""
    phit = np.asarray(phit, float)
    lo = np.array(np.broadcast_to(lo, phit.shape), float)
    hi = np.array(np.broadcast_to(hi, phit.shape), float)
    s = 0.5 * (lo + hi)
    with np.errstate(all='ignore'):
        for _ in range(maxit):
            xx = np.exp(s)
            F = prof.phi(xx) - phit
            pos = F > 0
            hi = np.where(pos, s, hi)
            lo = np.where(pos, lo, s)
            sn = s - F / (xx * prof.g(xx))
            bad = ~((sn >= lo) & (sn <= hi))
            sn = np.where(bad, 0.5 * (lo + hi), sn)
            done = np.all(np.abs(sn - s) <= 2e-15 * np.maximum(1.0, np.abs(s)))
            s = sn
            if done:
                break
    return np.exp(s)


def xmax_of(xe):
    return np.maximum(1e14, 1e8 * np.asarray(xe, float))


def seg_edges(xe, xtop, per_dec):
    n = np.maximum(1, np.ceil(per_dec * np.log10(xtop / xe) - 1e-9).astype(int))
    k = np.arange(n.max() + 1)
    xk = np.minimum(xe[:, None] * 10.0 ** (k[None, :] / per_dec), xtop[:, None])
    xk[:, 0] = xe
    return xk


def t_integral(prof, xe, which, xtop=None, cut=False, chunk=48):
    """Int_0^{t_top} F(E + t^2) dt, F = rho'' ('r2') or drho/dPhi ('d1'), E = Phi(xe), t_top = sqrt(Phi(x_top) - E).
    If not cut and Phi_max is finite, the last piece from x_top to Phi_max is added.  64-node Gauss-Legendre on segments
    ending at xe*10^(k/4); node potentials are formed as Phi_a + (t - t_a)(t + t_a), without cancellation."""
    xe = np.atleast_1d(np.asarray(xe, float))
    out = np.empty(len(xe))
    Ff = prof.r2 if which == 'r2' else prof.d1
    for i0 in range(0, len(xe), chunk):
        x0 = xe[i0:i0 + chunk]
        xt = xmax_of(x0) if xtop is None else np.array(np.broadcast_to(xtop, x0.shape), float)
        xk = seg_edges(x0, xt, 4)
        phik = prof.phi(xk)
        tk = np.sqrt(np.maximum((xk - x0[:, None]) * prof.D(xk, x0[:, None]), 0.0))
        xa, xb = xk[:, :-1], xk[:, 1:]
        ta, tb = tk[:, :-1], tk[:, 1:]
        tsum = ta + tb
        dt = np.where(tsum > 0, (xb - xa) * prof.D(xb, xa) / np.where(tsum > 0, tsum, 1.0), 0.0)
        toff = dt[..., None] * (1 + GLX) / 2
        tau = ta[..., None] + toff
        phin = phik[:, :-1, None] + toff * (tau + ta[..., None])
        lo = np.broadcast_to(np.log(xa)[..., None], tau.shape)
        hi = np.broadcast_to(np.log(xb)[..., None], tau.shape)
        xn = invert(prof, phin, lo, hi)
        val = np.sum(dt[..., None] * (GLW / 2) * Ff(xn), axis=(1, 2))
        if (not cut) and np.isfinite(prof.phimax):
            E = prof.phi(x0)
            pt = prof.phi(xt)
            t1 = np.sqrt((xt - x0) * prof.D(xt, x0))
            t2 = np.sqrt(prof.phimax - E)
            dtl = (prof.phimax - pt) / (t1 + t2)
            toffl = dtl[:, None] * (1 + GLX) / 2
            taul = t1[:, None] + toffl
            phinl = pt[:, None] + toffl * (taul + t1[:, None])
            xnl = invert(prof, phinl, np.broadcast_to(np.log(xt)[:, None], taul.shape),
                         np.full(taul.shape, math.log(1e300)))
            val = val + np.sum(dtl[:, None] * (GLW / 2) * Ff(xnl), axis=1)
        out[i0:i0 + chunk] = val
    return out


def bterm(prof, E):
    """Boundary term of the second form, -(1/(sqrt8 pi^2)) rho'(Phi_max)/sqrt(Phi_max - E); zero for Phi_max = +inf."""
    if not np.isfinite(prof.phimax):
        return np.zeros_like(np.asarray(E, float))
    return -C8 * float(prof.d1_inf) / np.sqrt(prof.phimax - np.asarray(E, float))


def route_A(prof, xe):
    xe = np.atleast_1d(np.asarray(xe, float))
    return C2 * t_integral(prof, xe, 'r2') + bterm(prof, prof.phi(xe))


def local_scale(prof, E):
    s = np.maximum(1.0, np.abs(E))
    s = np.minimum(s, E - prof.phi0)
    return np.minimum(s, prof.phimax - E)


def fd5(prof, xe, fun):
    """5-point central derivative in E of fun(x_E(E)), step 1e-3 s(E)."""
    xe = np.atleast_1d(np.asarray(xe, float))
    E = prof.phi(xe)
    h = 1e-3 * local_scale(prof, E)
    ls = np.log(xe)
    vals = {}
    for m in (-2, -1, 1, 2):
        xm = invert(prof, E + m * h, ls - 2.0, ls + 2.0)
        vals[m] = fun(xm)
    return (vals[-2] - 8 * vals[-1] + 8 * vals[1] - vals[2]) / (12 * h)


def route_C(prof, xe, xtop=None, cut=False):
    return C8 * fd5(prof, xe, lambda xm: 2.0 * t_integral(prof, xm, 'd1', xtop=xtop, cut=cut))


def route_B(prof, xe, absval=False, xtop=None):
    """Second form in x: f = (1/(2 sqrt2 pi^2)) Int_{xe}^{x_top} K(x) dx / sqrt(Phi(x) - E) (+ boundary term)."""
    xe = float(xe)
    xt = float(xmax_of(xe)) if xtop is None else float(xtop)
    Kf = (lambda x: abs(prof.K_s(x))) if absval else prof.K_s
    D = prof.D_s
    tot = 0.0
    with warnings.catch_warnings(record=True) as wl:
        warnings.simplefilter('always', IntegrationWarning)
        b1 = min(2.0 * xe, xt)
        v, _ = quad(lambda x: Kf(x) / math.sqrt(D(x, xe)), xe, b1, weight='alg', wvar=(-0.5, 0.0),
                    epsabs=0.0, epsrel=1e-11, limit=200)
        tot += v
        a = b1
        while a < xt:
            b = min(a * 10 ** 0.5, xt)
            v, _ = quad(lambda x: Kf(x) / math.sqrt((x - xe) * D(x, xe)), a, b, epsabs=0.0, epsrel=1e-11, limit=200)
            tot += v
            a = b
        NWARN['quad'] += sum(1 for w in wl if issubclass(w.category, IntegrationWarning))
    f = tot / (2.0 * SQ2 * PI ** 2)
    if xtop is None and np.isfinite(prof.phimax):
        f += float(bterm(prof, prof.phi_s(xe)))
    return f


def moments_from_f(prof, x, xcut=1e12):
    """rho = 8 sqrt2 pi Int f(Phi+s^2) s^2 ds and rho sigma^2 = (16 sqrt2 pi/3) Int f s^4 ds, f by Route A, 64-node
    Gauss-Legendre in s on half-decade segments of x up to xcut (Phi_max = +inf profiles only)."""
    n = int(np.ceil(2 * np.log10(xcut / x) - 1e-9))
    xk = np.minimum(x * 10.0 ** (np.arange(n + 1) / 2), xcut)
    xk[0] = x
    sk = np.sqrt(np.maximum((xk - x) * prof.D(xk, x), 0.0))
    xa, xb = xk[:-1], xk[1:]
    ds = (xb - xa) * prof.D(xb, xa) / (sk[:-1] + sk[1:])
    soff = ds[:, None] * (1 + GLX) / 2
    s = sk[:-1, None] + soff
    En = prof.phi(xa)[:, None] + soff * (s + sk[:-1, None])
    xEn = invert(prof, En, np.broadcast_to(np.log(xa)[:, None], s.shape), np.broadcast_to(np.log(xb)[:, None], s.shape))
    fn = route_A(prof, xEn.ravel()).reshape(xEn.shape)
    w = ds[:, None] * GLW / 2
    rho = 8 * SQ2 * PI * np.sum(w * fn * s ** 2)
    rs2 = 16 * SQ2 * PI / 3 * np.sum(w * fn * s ** 4)
    return rho, rs2


def f_hernquist(E):
    q2 = -E
    q = math.sqrt(q2)
    br = 3 * math.asin(q) + q * math.sqrt(1 - q2) * (1 - 2 * q2) * (8 * q2 * q2 - 8 * q2 - 3)
    return br / (8 * SQ2 * PI ** 3 * (1 + E) ** 2.5)


def f_kepler(E):
    return 1.0 / (8 * SQ2 * PI ** 3 * np.sqrt(-np.asarray(E, float)))


def f_iso(E):
    return np.exp(-2.0 - 2.0 * np.asarray(E, float)) / PI ** 2.5


def rel(a, b):
    return abs(a / b - 1.0)


def fnum(v):
    if isinstance(v, (bool, np.bool_)):
        return bool(v)
    if isinstance(v, (np.floating, float)):
        return float(v)
    if isinstance(v, (np.integer,)):
        return int(v)
    return v


# ----------------------------------------------------------------------------------------------------------------------
def main():
    T0 = time.time()
    sha = hashlib.sha256(open(SPEC, 'rb').read()).hexdigest()
    log('spec ' + SPEC_REL + ' sha256 = ' + sha)
    log('expected prefix edff8228 (commit c702dde54): ' + ('MATCH' if sha.startswith('edff8228') else 'MISMATCH'))
    log('CFG155 referee of CFG130 (Door 5): Eddington f(E) for the point-mass target.  mode = '
        + ('MUTATE (cored tracer, x_core = 0.1)' if MUTATE else 'main'))
    log('units G = M_b = a0 = 1 (r_M = 1); f in M_b r_M^-3 v_M^-3, v_M = (G M_b a0)^(1/4)')
    R = {'spec_sha256': sha, 'mode': 'MUTATE' if MUTATE else 'main', 'checks': {}, 'rows': {}}
    CH = R['checks']

    def check(name, ok, **kw):
        CH[name] = dict(passed=bool(ok), **{k: fnum(v) for k, v in kw.items()})
        return bool(ok)

    tgt, mut, her, sis = build_profiles()
    TR = mut if MUTATE else tgt
    log()
    log('== profiles (sympy; simplified before lambdify) ==')
    for p in (tgt, mut, her, sis):
        log(f'  {p.name:12s} dPhi/dx == g: {p.phi_ok};  drho/dPhi = {p.d1_e};  d2rho/dPhi2 = {p.r2_e};  '
            f'lim_(x->inf) drho/dPhi = {p.d1_inf}')
    prof_ok = all(p.phi_ok for p in (tgt, mut, her, sis))

    # N1 hygiene (diagnostic, not in the spec): numpy lambdified forms against 50-digit mpmath of the same expressions
    mp.mp.dps = 50
    xs = 10.0 ** np.linspace(-8, 8, 33)
    hyg = {}
    for p in (tgt, mut, her, sis):
        worst = 0.0
        for key, fnp in (('d1', p.d1), ('K', p.K), ('r2', p.r2)):
            for xv in xs:
                ref = p.mpf[key](mp.mpf(float(xv)))
                if abs(ref) < mp.mpf('1e-300'):
                    continue
                worst = max(worst, float(abs((mp.mpf(float(fnp(np.array([xv]))[0])) - ref) / ref)))
        hyg[p.name] = worst
    log('  N1 (diagnostic) max rel. error of the numpy forms vs 50-digit mpmath on x in [1e-8, 1e8]: '
        + ', '.join(f'{k} {v:.1e}' for k, v in hyg.items()))
    R['rows']['N1_lambdify_hygiene'] = hyg

    # ------------------------------------------------------------------ C5 closed forms (target)
    log()
    log('== C5 CONTROL: closed forms of the target ==')
    rho_t = 1 / (4 * sp.pi * X * sp.sqrt(1 + X ** 2))
    phi_t = sp.asinh(X) - sp.sqrt(1 + X ** 2) / X
    hand_d1 = -(1 + 2 * X ** 2) / (4 * sp.pi * (1 + X ** 2) ** 2)
    hand_r2 = X ** 5 / (sp.pi * (1 + X ** 2) ** sp.Rational(7, 2))
    s_d1 = sp.diff(rho_t, X) / sp.diff(phi_t, X)
    s_r2 = sp.diff(s_d1, X) / sp.diff(phi_t, X)
    sym1 = sp.simplify(s_d1 - hand_d1) == 0
    sym2 = sp.simplify(s_r2 - hand_r2) == 0
    sym3 = (sp.simplify(tgt.d1_e - hand_d1) == 0) and (sp.simplify(tgt.r2_e - hand_r2) == 0)
    log(f'  sympy: d(rho)/dPhi - hand = 0: {sym1};  d2(rho)/dPhi2 - hand = 0: {sym2};  profile forms == hand: {sym3}')
    hd1 = sp.lambdify(X, hand_d1, 'numpy')
    hr2 = sp.lambdify(X, hand_r2, 'numpy')
    q_piece = sp.lambdify(X, X ** 4 / (4 * sp.pi * (1 + X ** 2) ** 2), 'numpy')
    xs25 = 10.0 ** np.linspace(-2, 2, 25)
    e1 = e2 = 0.0
    for x0 in xs25:
        P0 = tgt.phi(x0)
        h = 1e-3 * max(1.0, abs(P0))
        xm = {m: invert(tgt, np.array([P0 + m * h]), math.log(x0) - 2, math.log(x0) + 2)[0] for m in (-2, -1, 1, 2)}
        dr = (tgt.rho(xm[-2]) - 8 * tgt.rho(xm[-1]) + 8 * tgt.rho(xm[1]) - tgt.rho(xm[2])) / (12 * h)
        dq = (q_piece(xm[-2]) - 8 * q_piece(xm[-1]) + 8 * q_piece(xm[1]) - q_piece(xm[2])) / (12 * h)
        e1 = max(e1, rel(dr, hd1(x0)))
        e2 = max(e2, rel(dq, hr2(x0)))
    log(f'  finite differences at 25 radii in [1e-2, 1e2]: max rel err d(rho)/dPhi {e1:.2e}, d2(rho)/dPhi2 {e2:.2e} (tol 1e-6)')
    C5 = check('C5_closed_forms', sym1 and sym2 and sym3 and e1 <= 1e-6 and e2 <= 1e-6 and prof_ok,
               sympy_d1=sym1, sympy_d2=sym2, profile_forms=sym3, fd_d1_maxrel=e1, fd_d2_maxrel=e2, tol=1e-6)
    log(f'  C5 {"PASS" if C5 else "FAIL"}')

    # ------------------------------------------------------------------ H1(a) sign of rho'' and the boundary
    log()
    log(f'== H1(a): sign of d2rho/dPhi2 for the tracer ({TR.name}) on 16001 points, x in [1e-8, 1e8] ==')
    xd = 10.0 ** np.linspace(-8, 8, 16001)
    r2d = TR.r2(xd)
    a_sym = bool(np.all(r2d > 0))
    a_hand = bool(np.all(hr2(xd) > 0)) if not MUTATE else None
    nneg = int(np.sum(r2d <= 0))
    log(f'  sympy form: min {r2d.min():.3e}, points <= 0: {nneg}' + (
        f';  hand form all > 0: {a_hand}' if not MUTATE else ''))
    if nneg:
        xneg = xd[r2d <= 0]
        log(f'  d2rho/dPhi2 <= 0 for x in [{xneg.min():.3e}, {xneg.max():.3e}]')
    d1_inf = TR.d1_inf
    d1_far = float(TR.d1(np.array([1e14]))[0])
    log(f'  lim_(Phi->+inf) drho/dPhi = {d1_inf} (sympy);  drho/dPhi at x = 1e14: {d1_far:.3e}  ->  boundary term 0')
    H1a = a_sym and (a_hand if not MUTATE else True) and (d1_inf == 0) and C5
    check('H1a_rho2_positive_no_boundary', H1a, n_nonpositive=nneg, min_rho2=float(r2d.min()), d1_inf=str(d1_inf),
          d1_at_1e14=d1_far)
    log(f'  H1(a) {"PASS" if H1a else "FAIL"}')

    # ------------------------------------------------------------------ the grid: Route B at all, A and C at every 10th
    log()
    log('== the grid: x_E = 10^(-6..6), 100 per decade (1201 energies); Route B at all, Routes A and C at every 10th ==')
    xg = 10.0 ** np.linspace(-6, 6, 1201)
    Eg = TR.phi(xg)
    t1 = time.time()
    fB = np.array([route_B(TR, x) for x in xg])
    Iab = np.array([route_B(TR, x, absval=True) for x in xg])
    log(f'  Route B done in {time.time() - t1:.1f} s; QUADPACK warnings so far: {NWARN["quad"]}')
    i10 = np.arange(0, 1201, 10)
    t1 = time.time()
    fA = route_A(TR, xg[i10])
    fC = route_C(TR, xg[i10])
    log(f'  Routes A and C done in {time.time() - t1:.1f} s')
    ratio = fB / Iab
    log('  x_E        E              f (Route B)     f/Int|integrand|   f/f_K or f/f_iso')
    for i in range(0, 1201, 100):
        norm = fB[i] / (f_kepler(Eg[i]) if xg[i] <= 1 else f_iso(Eg[i]))
        lab = 'f/f_K' if xg[i] <= 1 else 'f/f_iso'
        log(f'  {xg[i]:9.1e}  {Eg[i]:+.6e}  {fB[i]:+.6e}   {ratio[i]:+.8f}        {lab} = {norm:.8f}')

    # tail bound (method): (1/(2 sqrt2 pi^3)) / (2 xmax^2 sqrt(Phi(xmax) - E)) < 1e-10 f(E)
    xm_g = xmax_of(xg)
    tailb = 1.0 / (2 * SQ2 * PI ** 3) / (2 * xm_g ** 2 * np.sqrt((xm_g - xg) * TR.D(xm_g, xg)))
    tail_rel_f = float(np.max(tailb / np.abs(fB)))
    tail_rel_I = float(np.max(tailb / Iab))
    log(f'  dropped tail beyond x_max: max bound/|f| = {tail_rel_f:.2e}, max bound/Int|integrand| = {tail_rel_I:.2e} '
        f'(must be < 1e-10 of f)')

    # H1(b)
    pos_cert = ratio > 1e-6
    neg_cert = ratio < -1e-6
    win = (xg >= 1e-5 * (1 - 1e-9)) & (xg <= 1e5 * (1 + 1e-9))
    imin = int(np.argmin(fB))
    iminw = int(np.where(win)[0][np.argmin(fB[win])])
    H1b = bool(np.all(pos_cert)) and tail_rel_f < 1e-10
    log(f'  min f over the grid = {fB[imin]:.6e} at x_E = {xg[imin]:.3e} (E = {Eg[imin]:+.4f}); '
        f'over CFG130 README window [1e-5, 1e5]: {fB[iminw]:.6e} at x_E = {xg[iminw]:.3e}')
    log(f'  min f/Int|integrand| = {ratio.min():+.10f} at x_E = {xg[np.argmin(ratio)]:.3e};  energies with f > +1e-6 '
        f'Int|.|: {int(pos_cert.sum())}/1201;  with f < -1e-6 Int|.| (negative by CFG130 M1): {int(neg_cert.sum())}')
    if neg_cert.any():
        xn_ = xg[neg_cert]
        sign_ch = np.where(np.diff(np.sign(fB)) != 0)[0]
        log(f'  NEGATIVE f (certain) for x_E in [{xn_.min():.3e}, {xn_.max():.3e}] ({int(neg_cert.sum())} energies); '
            f'sign changes of f between grid points at x_E ~ ' + ', '.join(f'{xg[j]:.3e}' for j in sign_ch))
    check('H1b_f_positive_on_grid', H1b, min_f=fB[imin], x_at_min_f=xg[imin], min_f_readme_window=fB[iminw],
          x_at_min_f_window=xg[iminw], min_f_over_Iabs=float(ratio.min()), n_pos_certain=int(pos_cert.sum()),
          n_neg_certain=int(neg_cert.sum()), tail_bound_over_f=tail_rel_f, tail_bound_over_Iabs=tail_rel_I)
    log(f'  H1(b) {"PASS" if H1b else "FAIL"}')

    # H1(c)
    dA = np.abs(fA / fB[i10] - 1)
    dC = np.abs(fC / fB[i10] - 1)
    dAI = np.abs(fA - fB[i10]) / Iab[i10]
    dCI = np.abs(fC - fB[i10]) / Iab[i10]
    H1c = bool(dA.max() <= 1e-5 and dC.max() <= 1e-5)
    log(f'  H1(c): max |f_A/f_B - 1| = {dA.max():.2e}, max |f_C/f_B - 1| = {dC.max():.2e} (tol 1e-5);  '
        f'relative to Int|integrand|: {dAI.max():.2e}, {dCI.max():.2e}')
    check('H1c_routes_agree', H1c, max_rel_A=dA.max(), max_rel_C=dC.max(), max_A_over_Iabs=dAI.max(),
          max_C_over_Iabs=dCI.max(), tol=1e-5)
    log(f'  H1(c) {"PASS" if H1c else "FAIL"}')

    # Q1-Q3 (Q4 after C4)
    Q1 = not bool(np.any(fB < 0)) and not bool(neg_cert.any())
    Q2 = bool(ratio.min() >= 1 - 1e-10)
    k6, k5 = 0, 100
    q3v = [rel(fB[k6], f_kepler(Eg[k6])), rel(fB[k5], f_kepler(Eg[k5]))]
    Q3 = max(q3v) <= 1e-4
    log(f'  Q1 no f < 0: {Q1};  Q2 min f/Int|.| >= 1 - 1e-10: {Q2};  Q3 |f/f_K - 1| at x_E = 1e-6, 1e-5: '
        f'{q3v[0]:.2e}, {q3v[1]:.2e} (tol 1e-4): {Q3}')
    log(f'  E range check (convention): Phi(1e-5) = {tgt.phi(1e-5):+.6e}, Phi(1e5) = {tgt.phi(1e5):+.4f}, '
        f'Phi(1e-6) = {tgt.phi(1e-6):+.6e}, Phi(1e6) = {tgt.phi(1e6):+.4f}')
    check('Q1_no_negative_f', Q1)
    check('Q2_min_f_over_Iabs', Q2, value=float(ratio.min()))
    check('Q3_kepler_limit', Q3, at_1e_6=q3v[0], at_1e_5=q3v[1], tol=1e-4)

    # ------------------------------------------------------------------ C1 Hernquist
    log()
    log('== C1 CONTROL: Hernquist (G = M = a = 1), closed form of Hernquist (1990), q^2 = -E = 0.01 ... 0.99 ==')
    q2s = np.round(np.arange(1, 100) / 100.0, 2)
    Eh = -q2s
    xh = 1.0 / q2s - 1.0
    fH = np.array([f_hernquist(e) for e in Eh])
    fHB = np.array([route_B(her, x) for x in xh])
    eB = np.abs(fHB / fH - 1)
    j10 = np.arange(0, 99, 10)
    fHA = route_A(her, xh[j10])
    fHC = route_C(her, xh[j10])
    eA = np.abs(fHA / fH[j10] - 1)
    eC = np.abs(fHC / fH[j10] - 1)
    C1 = eB.max() <= 1e-6 and eA.max() <= 1e-5 and eC.max() <= 1e-5
    log(f'  Route B max rel err {eB.max():.2e} (tol 1e-6) at q^2 = {q2s[np.argmax(eB)]};  Routes A, C (10 energies) '
        f'{eA.max():.2e}, {eC.max():.2e} (tol 1e-5);  boundary term {float(bterm(her, np.array([-0.5]))[0]):.1e}')
    for j in (0, 49, 98):
        log(f'    q^2 = {q2s[j]:.2f}: f_closed = {fH[j]:.10e}, f_B = {fHB[j]:.10e}')
    check('C1_hernquist', C1, max_rel_B=eB.max(), max_rel_A=eA.max(), max_rel_C=eC.max(), tol_B=1e-6, tol_AC=1e-5)
    log(f'  C1 {"PASS" if C1 else "FAIL"}')

    log('== C1b CONTROL: the closed-form Hernquist f integrated back to rho ==')
    e1b = 0.0
    for x0 in (0.01, 0.1, 1.0, 10.0, 100.0):
        P0 = -1.0 / (1 + x0)
        smax = math.sqrt(-P0)
        v, _ = quad(lambda s: f_hernquist(P0 + s * s) * s * s, 0, smax, epsabs=0, epsrel=1e-12, limit=200)
        rho_rt = 8 * SQ2 * PI * v
        rho_ex = 1.0 / (2 * PI * x0 * (1 + x0) ** 3)
        e1b = max(e1b, rel(rho_rt, rho_ex))
        log(f'    x = {x0:6.2f}: rho(f) = {rho_rt:.10e}, rho = {rho_ex:.10e}, rel {rel(rho_rt, rho_ex):.1e}')
    C1b = e1b <= 1e-6
    check('C1b_hernquist_formula_roundtrip', C1b, max_rel=e1b, tol=1e-6)
    log(f'  C1b {"PASS" if C1b else "FAIL"} (max rel {e1b:.2e}, tol 1e-6)')

    # ------------------------------------------------------------------ C2 SIS
    log()
    log('== C2 CONTROL: singular isothermal sphere, Phi = ln x, Phi_max = +inf; Maxwellian e^(-2E)/(4 pi^(5/2)) ==')
    Es = np.linspace(-10, 10, 41)
    xs_ = np.exp(Es)
    fS = np.exp(-2 * Es) / (4 * PI ** 2.5)
    fSB = np.array([route_B(sis, x) for x in xs_])
    fSA = route_A(sis, xs_)
    fSC = route_C(sis, xs_)
    sB, sA, sC = (np.abs(v / fS - 1).max() for v in (fSB, fSA, fSC))
    C2ok = sB <= 1e-8 and sA <= 1e-6 and sC <= 1e-6
    log(f'  max rel err: Route B {sB:.2e} (tol 1e-8), Route A {sA:.2e}, Route C {sC:.2e} (tol 1e-6)')
    check('C2_sis_maxwellian', C2ok, max_rel_B=sB, max_rel_A=sA, max_rel_C=sC, tol_B=1e-8, tol_AC=1e-6)
    log(f'  C2 {"PASS" if C2ok else "FAIL"}')

    # ------------------------------------------------------------------ C3 target identities (no f)
    log()
    log('== C3 CONTROL: the target\'s own identities (no f) ==')
    xc = 10.0 ** np.linspace(-4, 4, 81)
    sol = solve_ivp(lambda s, w: [math.exp(2 * s) / (1 + w[0])], (math.log(1e-8), math.log(1e4)), [0.0],
                    method='DOP853', rtol=1e-12, atol=1e-14, t_eval=np.log(xc))
    g_ode = (1 + sol.y[0]) / xc ** 2
    gN = 1 / xc ** 2
    g_p2 = np.sqrt(gN ** 2 + gN)
    c3a = float(np.max(np.abs(g_ode / g_p2 - 1)))
    x25 = 10.0 ** np.linspace(-4, 4, 25)
    wfun = lambda x: x * x / (np.sqrt(1 + x * x) + 1)
    c3b = 0.0
    for x0 in x25:
        h = 1e-3 * x0
        dw = (wfun(x0 - 2 * h) - 8 * wfun(x0 - h) + 8 * wfun(x0 + h) - wfun(x0 + 2 * h)) / (12 * h)
        c3b = max(c3b, rel(dw / x0 ** 2, 4 * PI * float(tgt.rho(x0))))
    Cr = tgt.rho(x25) * x25 ** 3 * tgt.g(x25)
    c3c = float(np.max(np.abs(Cr * 4 * PI - 1)))
    c3d = 0.0
    for x0 in 10.0 ** np.arange(-4, 5):
        pts = [p for p in 10.0 ** np.arange(-4, 5) if p < x0]
        v, _ = quad(lambda x: x / math.sqrt(1 + x * x), 0, x0, points=pts or None, epsabs=0, epsrel=1e-13, limit=400)
        c3d = max(c3d, rel(v, x0 * x0 / (math.sqrt(1 + x0 * x0) + 1)))
    c3e = 0.0
    P1 = float(tgt.phi(1.0))
    for x0 in x25:
        lo_, hi_ = (1.0, x0) if x0 >= 1 else (x0, 1.0)
        pts = [p for p in 10.0 ** np.arange(-4, 5) if lo_ < p < hi_]
        v, _ = quad(lambda x: math.sqrt(1 + x * x) / x ** 2, lo_, hi_, points=pts or None, epsabs=0, epsrel=1e-13,
                    limit=400)
        v = v if x0 >= 1 else -v
        c3e = max(c3e, abs(float(tgt.phi(x0)) - (P1 + v)) / max(1.0, abs(float(tgt.phi(x0)))))
    Pf = lambda x: 1 / (8 * PI * x * x)
    c3f = float(np.max(np.abs(tgt.rho(x25) * x25 * tgt.g(x25) / 2 / Pf(x25) - 1)))
    c3g = 0.0
    for x0 in x25:
        h = 1e-3 * x0
        dP = (Pf(x0 - 2 * h) - 8 * Pf(x0 - h) + 8 * Pf(x0 + h) - Pf(x0 + 2 * h)) / (12 * h)
        c3g = max(c3g, rel(dP, -float(tgt.rho(x0) * tgt.g(x0))))
    log(f'  closure ODE vs P2 law: max rel {c3a:.1e} (tol 1e-8);  Poisson (cold part): {c3b:.1e} (tol 1e-7)')
    log(f'  C(r) = (a0/4pi) M_b: {c3c:.1e} (tol 1e-12);  M_c(<r) by quadrature: {c3d:.1e} (tol 1e-8)')
    log(f'  Phi closed form vs quadrature of g_tot from x = 1: {c3e:.1e} (tol 1e-10, scaled by max(1,|Phi|))')
    log(f'  hydrostatics: P = rho V_c^2/2: {c3f:.1e} (tol 1e-12);  dP/dr = -rho g: {c3g:.1e} (tol 1e-7);  '
        f'P(1e8)/P(1) = {Pf(1e8) / Pf(1.0):.1e}')
    C3 = c3a <= 1e-8 and c3b <= 1e-7 and c3c <= 1e-12 and c3d <= 1e-8 and c3e <= 1e-10 and c3f <= 1e-12 and c3g <= 1e-7
    check('C3_target_identities', C3, closure_ode=c3a, poisson=c3b, charge=c3c, cold_mass=c3d, phi_quadrature=c3e,
          P_equals_rho_Vc2_half=c3f, hydrostatic=c3g, beta_point_mass='0 for r > 0 (rho_b = 0 there)')
    log(f'  beta = -(1/2) dlnM_b/dlnr = 0 for r > 0 (point mass): a statement.   C3 {"PASS" if C3 else "FAIL"}')

    # ------------------------------------------------------------------ C4 identities through f
    log()
    log(f'== C4 CONTROL: identities through f ({TR.name}) at x = 1e-4 ... 1e4 ==')
    t1 = time.time()
    rt_err, sg_err = [], []
    for x0 in 10.0 ** np.arange(-4, 5):
        rho_f, rs2 = moments_from_f(TR, x0)
        rho_ref = float(TR.rho(x0))
        sig2 = rs2 / rho_f
        sig2_ref = math.sqrt(1 + x0 * x0) / (2 * x0)
        rt_err.append(rel(rho_f, rho_ref))
        sg_err.append(rel(sig2, sig2_ref))
        log(f'    x = {x0:7.0e}: rho(f)/rho - 1 = {rho_f / rho_ref - 1:+.2e};  sigma^2(f)/(V_c^2/2) - 1 = '
            f'{sig2 / sig2_ref - 1:+.2e}')
    iso_idx = [900, 1000, 1100, 1200]
    iso_err = [rel(fB[i], f_iso(Eg[i])) for i in iso_idx]
    log(f'  outer limit |f/f_iso - 1| at x_E = 1e3, 1e4, 1e5, 1e6: ' + ', '.join(f'{v:.1e}' for v in iso_err)
        + f' (tol 1e-4);  {time.time() - t1:.1f} s')
    c4rt, c4sg, c4iso = max(rt_err) <= 1e-5, max(sg_err) <= 1e-5, max(iso_err) <= 1e-4
    C4 = c4rt and c4sg and c4iso and Q3
    check('C4_identities_through_f', C4, roundtrip_maxrel=max(rt_err), sigma2_maxrel=max(sg_err),
          iso_limit_maxrel=max(iso_err), kepler_limit_Q3=Q3, tol_rt=1e-5, tol_sig=1e-5, tol_lim=1e-4)
    log(f'  round trip {c4rt}, sigma^2 = V_c^2/2 {c4sg}, isothermal limit {c4iso}, Kepler limit (Q3) {Q3}.   '
        f'C4 {"PASS" if C4 else "FAIL"}')
    Q4 = max(rt_err) <= 4e-4
    check('Q4_roundtrip_vs_4e-4', Q4, value=max(rt_err))
    log(f'  Q4 round trip <= 4e-4: {Q4} ({max(rt_err):.1e})')

    # ------------------------------------------------------------------ C6 both footings
    log()
    log('== C6 CONTROL: both footings in kpc, km/s, Msun (target) ==')
    rs = sp.symbols('r', positive=True)
    Gs, Ms, As = sp.symbols('G M a0', positive=True)
    rMs = sp.sqrt(Gs * Ms / As)
    rho_p = As / (4 * sp.pi * Gs * rs * sp.sqrt(1 + (rs / rMs) ** 2))
    g_p = sp.sqrt((Gs * Ms / rs ** 2) ** 2 + As * Gs * Ms / rs ** 2)
    phi_p = sp.sqrt(Gs * Ms * As) * (sp.asinh(rs / rMs) - sp.sqrt(1 + (rMs / rs) ** 2))
    phys_phi_ok = sp.simplify(sp.diff(phi_p, rs) - g_p) == 0
    K_p = sp.simplify(sp.diff(sp.simplify(sp.diff(rho_p, rs) / g_p), rs))
    log(f'  sympy: dPhi/dr == g_tot: {phys_phi_ok};  K = d(drho/dPhi)/dr = {K_p}')
    Gk = 4.30091727e-6
    kpc_m = 3.0856775814913673e19
    xs6 = [1e-3, 1e-1, 1.0, 10.0, 1e3]
    fB6 = [route_B(tgt, x) for x in xs6]
    c6 = 0.0
    for a0si in (9.3603e-11, 1.13e-10):
        a0k = a0si * kpc_m / 1e6
        for Mb in (1e9, 1e12):
            rM = math.sqrt(Gk * Mb / a0k)
            vM = (Gk * Mb * a0k) ** 0.25
            Kf = sp.lambdify(rs, K_p.subs({Gs: Gk, Ms: Mb, As: a0k}), 'math')
            Dp = lambda r, re: vM ** 2 / rM * D_tgt_s(r / rM, re / rM)
            for x0, fdim in zip(xs6, fB6):
                re = rM * x0
                rt = rM * float(xmax_of(x0))
                tot = 0.0
                with warnings.catch_warnings():
                    warnings.simplefilter('ignore', IntegrationWarning)
                    v, _ = quad(lambda r: Kf(r) / math.sqrt(Dp(r, re)), re, 2 * re, weight='alg', wvar=(-0.5, 0.0),
                                epsabs=0.0, epsrel=1e-11, limit=200)
                    tot += v
                    a = 2 * re
                    while a < rt:
                        b = min(a * 10 ** 0.5, rt)
                        v, _ = quad(lambda r: Kf(r) / math.sqrt((r - re) * Dp(r, re)), a, b, epsabs=0.0, epsrel=1e-11,
                                    limit=200)
                        tot += v
                        a = b
                fphys = tot / (2 * SQ2 * PI ** 2)
                c6 = max(c6, rel(fphys * rM ** 3 * vM ** 3 / Mb, fdim))
            log(f'    a0 = {a0si:.4e} m/s^2 = {a0k:.2f} (km/s)^2/kpc, M_b = {Mb:.0e}: r_M = {rM:.4f} kpc, '
                f'v_M = {vM:.3f} km/s')
    C6 = c6 <= 1e-8 and phys_phi_ok
    check('C6_both_footings', C6, max_rel=c6, tol=1e-8)
    log(f'  max |f_phys r_M^3 v_M^3 / M_b / f - 1| = {c6:.1e} (tol 1e-8).   C6 {"PASS" if C6 else "FAIL"}')

    # ------------------------------------------------------------------ reported rows
    log()
    log('== R1-R4 reported rows (no pass line) ==')
    inner = xg <= 1
    outer = xg >= 1
    rK = fB[inner] / f_kepler(Eg[inner])
    rI = fB[outer] / f_iso(Eg[outer])
    log(f'  R1: min f = {fB[imin]:.4e} at x_E = {xg[imin]:.2e};  f/f_K over x_E <= 1 in [{rK.min():.6f}, {rK.max():.6f}];'
        f'  f/f_iso over x_E >= 1 in [{rI.min():.6f}, {rI.max():.6f}]')
    R['rows']['R1'] = dict(min_f=fB[imin], x_at_min=xg[imin], fK_ratio_range=[rK.min(), rK.max()],
                           fiso_ratio_range=[rI.min(), rI.max()])
    if not MUTATE:
        t1 = time.time()
        fpA = fd5(TR, xg, lambda xm: route_A(TR, xm))
        dlnf = fpA / fB
        jm = int(np.argmax(dlnf))
        log(f'  R2: d ln f/dE max = {dlnf[jm]:+.4f} at x_E = {xg[jm]:.3e} (E = {Eg[jm]:+.4f});  at x_E = 1e5: '
            f'{dlnf[1100]:+.4f};  at x_E = 1e-5: {dlnf[100]:+.2e};  at x_E = 1e6: {dlnf[1200]:+.4f}  '
            f'(CFG130: +0.3 to -2.0; +-0.05: max {abs(dlnf[jm] - 0.3) <= 0.05}, end {abs(dlnf[1100] + 2.0) <= 0.05})'
            f'  [{time.time() - t1:.1f} s]')
        R['rows']['R2'] = dict(max_dlnf_dE=dlnf[jm], x_at_max=xg[jm], E_at_max=Eg[jm], at_1e5=dlnf[1100],
                               at_1e_5=dlnf[100], at_1e6=dlnf[1200], within_005_of_cfg130=bool(
                abs(dlnf[jm] - 0.3) <= 0.05 and abs(dlnf[1100] + 2.0) <= 0.05))
    else:
        log('  R2: not meaningful under MUTATE (f changes sign); skipped')
    r3 = {}
    for xe0 in (1e3, 1e4, 1e5):
        i = int(round((math.log10(xe0) + 6) * 100))
        for xo in (1e5, 1e6):
            key = f'xE={xe0:.0e},xout={xo:.0e}'
            if xo <= xe0:
                r3[key] = 'degenerate (x_out <= x_E)'
                continue
            fcutB = route_B(TR, xe0, xtop=xo)
            fcutC = float(route_C(TR, np.array([xe0]), xtop=xo, cut=True)[0])
            r3[key] = dict(second_form_cut=fcutB / fB[i] - 1, first_form_cut=fcutC / fB[i] - 1)
    log('  R3 (outer boundary; relative change of f):')
    for k, v in r3.items():
        log(f'    {k}: ' + (v if isinstance(v, str) else
                            f'second form cut {v["second_form_cut"]:+.3e};  first form cut {v["first_form_cut"]:+.3e}'))
    R['rows']['R3'] = r3
    R['rows']['R4_boundary'] = {p.name: str(p.d1_inf) for p in (tgt, mut, her, sis)}
    log('  R4: lim drho/dPhi at Phi_max: ' + ', '.join(f'{p.name} {p.d1_inf}' for p in (tgt, mut, her, sis))
        + '  -> every boundary term is zero')

    # ------------------------------------------------------------------ MUTATE specifics
    if MUTATE:
        log()
        log('== MUTATE specifics ==')
        rho0 = 1.0 / (4 * PI * X_CORE)
        deep = xg <= 1e-4 * (1 + 1e-9)
        fcore = -rho0 / (4 * SQ2 * PI ** 2) * (-Eg[deep]) ** -1.5
        dev = np.abs(fB[deep] / fcore - 1)
        asym_ok = dev.max() <= 0.05
        log(f'  deep asymptote f -> -rho0/(4 sqrt2 pi^2) (-E)^(-3/2), rho0 = {rho0:.6f}: max |f/f_asym - 1| over '
            f'x_E <= 1e-4 = {dev.max():.2e} (tol 0.05): {asym_ok};  at x_E = 1e-6: {dev[0]:.2e}, at 1e-4: {dev[-1]:.2e}')
        bites = bool(neg_cert.any())
        log(f'  MUTATE bites (H1(b) fails with certainty, f < -1e-6 Int|integrand|): {bites}')
        check('MUTATE_deep_asymptote', asym_ok, max_rel=dev.max(), tol=0.05)
        R['mutate_bites'] = bites

    # ------------------------------------------------------------------ summary
    H1 = H1a and H1b and H1c and Q1 and Q2 and Q3 and Q4
    CH['H1_headline'] = dict(passed=bool(H1), parts=dict(a=H1a, b=H1b, c=H1c, Q1=Q1, Q2=Q2, Q3=Q3, Q4=Q4))
    ctrl = dict(C1=C1, C1b=C1b, C2=C2ok, C3=C3, C4=C4, C5=C5, C6=C6)
    ok = H1 and all(ctrl.values())
    code = 0 if ok else 1
    log()
    log('== summary ==')
    log(f'  H1 [headline] f(E) > 0 for the {"MUTATED tracer" if MUTATE else "point-mass target"}: '
        f'{"PASS" if H1 else "FAIL"}  (a {H1a}, b {H1b}, c {H1c}, Q1 {Q1}, Q2 {Q2}, Q3 {Q3}, Q4 {Q4})')
    log('  controls: ' + ', '.join(f'{k} {"PASS" if v else "FAIL"}' for k, v in ctrl.items()))
    log(f'  QUADPACK IntegrationWarnings (Route B, all calls): {NWARN["quad"]}')
    if MUTATE:
        log(f'  MUTATE: {"bites (H1(b) fails with certainty)" if R.get("mutate_bites") else "DOES NOT BITE"}; '
            f'expected exit 1')
    log(f'  exit code {code};  run time {time.time() - T0:.1f} s')
    log('  kappa = 1/2 and Omega_c h^2 stay fitted. Nothing here says the data favour either model, or that the theory '
        'is closed.')
    R['exit_code'] = code
    R['runtime_s'] = time.time() - T0
    R['quad_warnings'] = NWARN['quad']
    R['grid'] = dict(x_E=xg.tolist(), E=Eg.tolist(), f_B=fB.tolist(), Int_abs=Iab.tolist(), idx_AC=i10.tolist(),
                     f_A=fA.tolist(), f_C=fC.tolist())
    with open(OUT_TXT, 'w') as fh:
        fh.write('\n'.join(LOG) + '\n')
    with open(OUT_JSON, 'w') as fh:
        json.dump(R, fh, indent=1, default=fnum)
    return code


if __name__ == '__main__':
    sys.exit(main())
