#!/usr/bin/env python3
"""IDEAS_100_generator.py -- one hundred further steps, generated with a novelty gate against the whole repository.

Each candidate is a record (title, distinctive terms, the statement Lean can certify, the computation or data, the
pre-registered kill gate).  The script (1) builds a lower-cased corpus from every tracked .md file and every lane
docstring (.py first 60 lines) in the repository, (2) scores each candidate by the fraction of its distinctive terms
ABSENT from the corpus and flags any candidate whose terms all already occur, (3) drops candidates that collide with
FIFTY_NEXT_STEPS.md, (4) ranks the survivors and writes IDEAS_100.md (the document) and IDEAS_100.json (the audit:
every term with its corpus hit count).  A candidate with novelty < 0.5 is excluded.  Run from the repository root:
    python3 fable_independent_2026/kappa_slot_2026/IDEAS_100_generator.py
The candidates themselves are authored; the script is the novelty audit and the formatter -- it does not invent physics.
"""
import os, re, json, subprocess, itertools
HERE = os.path.dirname(os.path.abspath(__file__)); REPO = os.path.dirname(os.path.dirname(HERE))

# ---------------------------------------------------------------- the corpus
def corpus():
    files = subprocess.run(["git", "ls-files", "*.md", "*.py"], cwd=REPO, capture_output=True, text=True).stdout.split()
    buf = []
    for f in files:
        p = os.path.join(REPO, f)
        try:
            if f.endswith(".md"): buf.append(open(p, errors="ignore").read().lower())
            else: buf.append("".join(open(p, errors="ignore").readlines()[:60]).lower())
        except Exception: pass
    return "\n".join(buf), len(files)
CORPUS, NFILES = corpus()
FIFTY = open(os.path.join(HERE, "FIFTY_NEXT_STEPS.md"), errors="ignore").read().lower()

# ---------------------------------------------------------------- the candidates
# (title, [distinctive terms], lean statement, computation/data, kill gate)
C = [
# A. the deep-MOND virial family and the sigma-to-v conversion (the twelve-decade line's hidden coefficient)
("Milgrom's deep-MOND virial theorem, certified, then applied to every pressure-supported channel", ["deep-mond virial theorem", "2/3 sqrt(g a0) m^{3/2}", "sigma_los^4 = (4/81)"],
 "Q = 2K = (2/3) sqrt(G a0) M^{3/2} for an isolated deep-MOND system (scale invariance + the field virial); isotropic: sigma_1D^2 = (2/9) v_inf^2, not v_inf^2/2",
 "recompute the dSph, ATLAS3D, GEMS, cluster and GC zero points of the 542-object line with the certified coefficient instead of v = sqrt(2) sigma; the factor (9/2 / 2)^2 = 5.06 in a0",
 "if the channel offsets 7.4x (dSph) and 12.2x (clusters) collapse to ~1.5x and ~2.4x the line's 'one scale' claim was a conversion artefact; if not, the deep virial fails"),
("The tracer-profile dependence of sigma in a log potential", ["sigma^2 = v_c^2/gamma_*", "tracer profile exponent", "sersic tracer in a log potential"],
 "for a tracer rho_* ~ r^{-gamma_*} with anisotropy beta in Phi = v_c^2 ln r: sigma_r^2 = v_c^2/(gamma_* - 2 beta) exactly",
 "per ATLAS3D galaxy use the measured Sersic n to get gamma_*(r) at R_e and convert sigma_e to v_c object by object",
 "the ATLAS3D channel's 2.02x offset and +1.30 internal slope must move toward 1.0 and 1.0; if they do not, the ETGs violate the log-potential reading"),
("Deep-MOND two-body force, certified, tested on galaxy pairs", ["two-body deep-mond force", "(m1+m2)^{3/2} - m1^{3/2} - m2^{3/2}", "galaxy pair timing"],
 "F = (2/3) sqrt(G a0) [(m1+m2)^{3/2} - m1^{3/2} - m2^{3/2}]/r for two deep-MOND masses (Milgrom 1994)",
 "relative velocities of isolated galaxy pairs (SDSS/ALFALFA pairs, HI masses) versus separation; the pair-timing mass",
 "the pair-inferred baryonic masses must match the photometric ones within 0.3 dex; a systematic 2x excess kills the isolated two-body law"),
("The central surface density relation from mu_2", ["central surface density relation", "csdr", "sigma_dyn(0) vs sigma_bar(0)"],
 "for a razor-thin disc the mu_2 central dynamical surface density is a certified function of the central baryonic one (the 1-D Poisson solution)",
 "SPARC's CSDR (Lelli 2016): compare mu_2, nu_RAR and simple predictions",
 "mu_2 worse than nu_RAR by Delta chi2 > 9"),
("The EFE detection of Chae et al. re-analysed with the framework's cap", ["chae 2020", "efe detection", "outer rotation curve decline vs g_ext"],
 "the spherical EFE closed form for mu_2 (the quasi-linear solution) gives the outer-curve decline as a certified function of g_ext/a0",
 "SPARC outer slopes versus the environmental g_ext catalogue; the framework's cap law versus AQUAL's EFE",
 "the cap predicts a sharper break than AQUAL; the data decide between them at 3 sigma or the cap is retired"),
("Milgrom's space-time scale invariance as a Lean-certified symmetry", ["space-time scale invariance", "(t, r) -> (lambda t, lambda r)", "deep-mond symmetry algebra"],
 "the deep-MOND equations are invariant under (t, r) -> (lambda t, lambda r); the conserved charges and the resulting virial identity",
 "derive every deep-regime scaling used in the repository from the one symmetry; list which committed 'laws' are its corollaries",
 "any committed deep-regime relation not a corollary of the symmetry is flagged as an independent postulate"),
# B. Milky Way and Gaia
("The Milky Way's outer Keplerian decline versus the 1/r force", ["ou 2024", "jiao 2023", "keplerian decline", "milky way rotation curve beyond 15 kpc"],
 "the mu_2 well with the EFE cap gives a certified v_c(r) for r > r_M given M_b and g_ext(MW)",
 "Gaia DR3 + APOGEE outer rotation curve (Ou et al. 2024; Jiao et al. 2023): fit the decline with the cap versus NFW",
 "a decline steeper than the capped 1/r prediction at 3 sigma kills the cap; a flat curve out to 25 kpc kills the Keplerian claim"),
("The stellar-halo break radius", ["stellar halo break", "deason 2011 break radius", "halo density break at 25 kpc"],
 "in a deep-MOND well a collisionless halo formed by mergers has a break at the apocentre pile-up radius, a certified function of C",
 "Gaia/SDSS halo density profiles (Deason; Xue) versus the predicted break radius",
 "break radius off by > 50% from the prediction"),
("The Gaia phase spiral as a kernel test", ["phase spiral", "antoja 2018", "vertical phase-space snail"],
 "the vertical frequency Omega_z(J_z) in the mu_2 slab at R0 is a certified closed form; the spiral's winding rate follows",
 "measure the winding of the DR3 phase spiral; compare mu_2, nu_RAR, Newton + halo",
 "the mu_2 winding rate excluded at 3 sigma"),
("Hyades tidal-tail asymmetry", ["hyades tidal tail", "kroupa 2022 asymmetry", "leading trailing tail ratio"],
 "the EFE-induced asymmetry of the tidal tails of an open cluster in the Galactic field is a certified function of g_ext/a0 and the orbit",
 "Gaia DR3 Hyades, Praesepe, Coma Ber tails: leading/trailing star counts",
 "measured asymmetry inconsistent with the prediction at 3 sigma (Newton predicts symmetry)"),
("Open-cluster dissolution times under Milgromian friction", ["open cluster dissolution", "milgromian dynamical friction on clusters", "cluster lifetime versus mass"],
 "the deep-regime friction timescale for a cluster on a circular Galactic orbit, certified",
 "the observed open-cluster age distribution (Kharchenko) versus the predicted dissolution law",
 "predicted lifetimes shorter than observed ages for > 20% of the sample"),
("Distant halo globular clusters as EFE probes", ["pal 14", "ngc 2419", "outer halo globular cluster dispersion"],
 "the internal dispersion of a GC at r > 50 kpc under the cap: sigma_pred(M, g_ext) certified",
 "Pal 14, Pal 4, NGC 2419, Eridanus dispersions (Baumgardt, Ibata)",
 "predictions outside 2 sigma for > 2 of 4"),
("The RAVE/Gaia escape-speed curve as a cap measurement", ["escape speed curve", "v_esc(r) gaia", "cap radius from escape speed"],
 "v_esc^2(r) = 2 C ln(r_cap/r) certified; r_cap is the only free quantity",
 "fit the DR3 escape-speed profile for r_cap; compare with the cap law's r_cap = r_M sqrt(a0/g_ext)",
 "fitted r_cap off by > 50% from the cap law"),
("Solar-neighbourhood vertical waves from a passing satellite under mu_2", ["vertical waves sagittarius passage", "bending mode response mu_2", "disc response to a perturber"],
 "the linear response of a mu_2 slab to an impulsive vertical perturbation, certified (the response kernel)",
 "compare the predicted bending-wave amplitude with the Gaia DR3 vertical velocity waves",
 "amplitude off by > 2x"),
("The Galactic centre's a0-crossing: does the nuclear star cluster sit on the RAR?", ["nuclear star cluster rar", "galactic centre acceleration at 100 pc", "nsc dynamics"],
 "at g >> a0 the framework is Newtonian; certify the residual mu_2 correction 1 - mu_2 at the NSC",
 "the NSC's dynamical mass (Feldmeier) versus its stellar mass",
 "any required dark mass at g/a0 > 100 kills the reading"),
# C. dwarfs, UDGs, pairs, rings
("The Walker-Penarrubia slope test on the phantom's inner profile", ["walker penarrubia", "two-population dwarf slopes", "inner phantom slope"],
 "for two stellar populations in the same mu_2 well the mass-slope estimator is a certified functional of the phantom's inner profile",
 "Fornax and Sculptor two-population data",
 "the inferred inner slope inconsistent with the phantom's core/cusp prediction at 3 sigma"),
("Dragonfly 44 versus DF2: the UDG dichotomy under the cap", ["dragonfly 44", "df44 dispersion", "udg dichotomy"],
 "sigma_pred(M_*, g_ext) for an isolated UDG (no cap) versus a cluster UDG (capped), certified",
 "DF44 (isolated-ish, sigma 33 km/s) versus DF2 (in NGC1052 field)",
 "either outside 2 sigma"),
("Mutual EFE in galaxy pairs", ["mutual external field", "pair efe", "rar offset in close pairs"],
 "two mu_2 wells in each other's field: the certified first-order correction to each rotation curve",
 "close SPARC/MaNGA pairs: RAR offset versus projected separation",
 "no offset where the correction predicts > 0.05 dex at 3 sigma"),
("Collisional ring galaxies' expansion velocities", ["cartwheel expansion velocity", "collisional ring", "ring propagation speed"],
 "the ring's radial expansion in a mu_2 disc is a certified function of the intruder mass ratio",
 "Cartwheel, Arp 147 expansion velocities from HI/Halpha",
 "prediction off by > 30%"),
("Tidal-tail lengths of interacting pairs", ["antennae tidal tail length", "tiret combes", "tail length mond"],
 "in the deep regime the tidal-tail length scales as C^{1/2} t (certified from the 1/r force)",
 "the Antennae, Mice, NGC 7252 tail lengths and ages",
 "predicted lengths off by > 50%"),
("Malin 1 and the giant LSB discs at extreme low acceleration", ["malin 1", "giant lsb disc", "extreme low acceleration rotation curve"],
 "the mu_2 rotation curve at g_bar << a0 is certified: v^4 = G M_b a0 to 1% beyond 3 r_M",
 "Malin 1, UGC 1382 extended HI curves",
 "a departure > 0.1 dex from the deep law at 3 sigma"),
("Compact-group crossing times and merger rates", ["hickson compact group", "crossing time merger", "compact group survival"],
 "Milgromian friction in a compact group: certified merger timescale versus group velocity dispersion",
 "Hickson catalogue: fraction of groups older than their friction time",
 "> 30% of groups should have merged: kill"),
("Dwarf irregulars' HI scale heights", ["hi scale height dwarf", "banerjee jog", "vertical hi structure irregulars"],
 "the vertical equilibrium of an HI layer in the mu_2 well: certified h_z(R)",
 "LITTLE THINGS / FIGGS HI scale heights",
 "predicted h_z off by > 2x"),
("The Fornax dSph's globular clusters' spatial distribution as a friction record", ["fornax gc radial distribution", "friction record", "gc sinking law"],
 "the predicted present-day radial distribution of GCs after 10 Gyr of Milgromian friction from a uniform start",
 "compare with the observed five-GC configuration",
 "the observed configuration has probability < 1% under the prediction"),
("Andromeda's satellites' velocity dispersions with M31's field as the cap", ["m31 satellites dispersion", "andromeda dwarfs efe", "m31 cap"],
 "sigma_pred for each M31 dSph with g_ext from M31's baryons, certified",
 "Collins et al. dispersions for 30 M31 dwarfs",
 "> 20% outside 2 sigma"),
# D. ellipticals, lensing
("SLACS Einstein radii versus sigma under the mu_2 well", ["slacs einstein radius", "einstein radius sigma relation", "strong lens fundamental plane"],
 "the Einstein radius of a Sersic mass in the mu_2 well with lensing = dynamics, certified",
 "SLACS/BELLS: theta_E versus sigma_ap",
 "residual scatter > 2x that of a free-halo fit"),
("Time-delay Hubble constant with the phantom potential", ["time-delay cosmography", "h0licow lens potential", "phantom in time delays"],
 "the Fermat potential of a lens with the framework's phantom (no free halo) is certified",
 "re-fit the seven TDCOSMO lenses with the phantom fixed by the lens's baryons",
 "inferred H0 outside [60, 80] or lens chi2 worse by > 25"),
("X-ray ellipticals on the RAR", ["x-ray isolated ellipticals", "humphrey hydrostatic ellipticals", "elliptical rar from x-ray"],
 "hydrostatic mass profile of hot gas in the mu_2 well, certified",
 "Chandra isolated ellipticals (NGC 720, NGC 4636, NGC 1521): acceleration relation",
 "> 0.2 dex off the RAR at 3 sigma"),
("Super-spirals on the BTFR", ["super spirals", "ogle 2019 super spiral", "btfr at 10^12 msun"],
 "the BTFR at the highest baryonic masses is certified to be kernel-blind",
 "Ogle et al. super spirals' HI/CO rotation versus stellar + gas mass",
 "systematic offset > 0.2 dex"),
("The fundamental plane's tilt from mu_2", ["fundamental plane tilt", "fp tilt from mond", "virial plane coefficient"],
 "the FP coefficients for a Sersic galaxy in the mu_2 well versus the Newtonian virial plane, certified",
 "ATLAS3D/SDSS fundamental plane",
 "predicted tilt excluded at 3 sigma"),
("Weak-lensing shear around isolated dwarfs at g << a0", ["dwarf galaxy-galaxy lensing", "lensing around dwarfs", "kids dwarfs esd"],
 "the ESD of a deep-MOND phantom around a 10^8 Msun galaxy, certified (the 1/R law)",
 "KiDS/DES stacked ESD around isolated dwarfs",
 "slope departure from 1/R at 3 sigma inside 100 kpc"),
("The lensing-dynamics ratio in clusters as a function of radius", ["lensing to dynamics ratio", "eta(r) in clusters", "slip in clusters"],
 "with lensing = dynamics the ratio M_lens/M_dyn = 1 at all radii is certified; the phantom adds nothing",
 "CLASH lensing versus X-COP hydrostatic (with the measured beta correction)",
 "ratio departing from 1 by > 20% at 3 sigma at any radius"),
# E. clusters, groups, SZ, cosmology
("The caustic mass versus the phantom", ["caustic mass", "diaferio caustic", "escape velocity profile clusters"],
 "the caustic amplitude for the phantom + dust profile, certified",
 "HeCS caustic masses versus hydrostatic",
 "caustic/hydrostatic ratio inconsistent with the two-phase prediction at 3 sigma"),
("Splashback radius versus the framework's turnaround", ["splashback radius", "more diemer splashback", "phantom splashback"],
 "the splashback feature position for infall onto the phantom well, certified from the 1/r force",
 "DES/SDSS splashback measurements",
 "position off by > 20%"),
("Cluster abundance under the framework's growth", ["cluster mass function", "sz cluster counts", "abundance versus growth"],
 "the halo mass function with the framework's growth factor, certified as a Press-Schechter integral",
 "Planck SZ counts, eRASS1 counts",
 "counts off by > 3 sigma at any mass bin"),
("CMB lensing amplitude with the fluid sector", ["a_l lensing amplitude", "cmb lensing fluid sector", "planck a_lens"],
 "the lensing potential power spectrum for a fluid dark sector with c_s^2 = sigma^2/c^2, certified in the linear regime",
 "Planck A_L and the ACT/SPT lensing spectra",
 "A_L off unity by > 3 sigma"),
("The neutrino-mass degeneracy of the fluid sector", ["sum m_nu degeneracy", "desi neutrino mass tension", "fluid mimics neutrinos"],
 "the direction in (sum m_nu, c_s^2) space along which the CMB+BAO likelihood is flat, certified as a Fisher identity",
 "DESI's sum m_nu < 0.07 eV: does the fluid sector relax or tighten it",
 "no direction exists: the fluid is not degenerate and must pass on its own"),
("Standard sirens as a completion test", ["standard siren distance ratio", "gw luminosity distance", "alpha_m friction"],
 "d_L(GW)/d_L(EM) = exp(-int alpha_M) for any completion; certified",
 "GW170817 + future sirens versus the surviving completion's alpha_M",
 "any surviving completion with alpha_M != 0 is killed at |ratio - 1| > 0.1"),
("The cluster gas-fraction–mass relation as a phantom probe", ["f_gas(m) relation", "gas fraction versus mass", "eckert f_gas"],
 "f_gas(M500) for baryons + phantom + dust with the committed pie, certified",
 "X-COP, HSC-XXL f_gas",
 "slope off by > 3 sigma"),
("The intracluster magnetic-field-free test: thermal versus non-thermal pressure with the phantom", ["non-thermal pressure fraction", "hydrostatic bias from turbulence", "phantom versus non-thermal"],
 "hydrostatic mass with a non-thermal fraction p_nt(r) and the phantom, certified",
 "X-COP non-thermal fractions versus the phantom's required share",
 "the phantom's share degenerate with p_nt at all radii: the sector is unobservable there (a kill of the test, recorded)"),
("Peculiar velocities of galaxies in the outskirts of clusters", ["infall velocity profile", "cluster outskirts infall", "turnaround velocity"],
 "the mean infall v(r) onto the phantom + dust well, certified from spherical collapse in the 1/r field",
 "HeCS/Coma outskirts kinematics",
 "infall amplitude off by > 30%"),
("Void galaxies' rotation curves", ["void galaxy rotation curve", "isolated void galaxies rar", "lowest g_ext environment"],
 "the RAR with g_ext -> 0 (no cap), certified",
 "VGS void galaxies' HI curves",
 "offset from the field RAR at 3 sigma"),
# F. formal theorems
("Ostrogradsky classification of acceleration-dependent Lagrangians", ["ostrogradsky degenerate hessian", "acceleration-dependent lagrangian classification", "ghost-free l(q, qdot, qddot)"],
 "which L(q, qdot, qddot) with degenerate Hessian are ghost-free (a finite classification theorem in Lean)",
 "enumerate the a0-scale members",
 "none give MOND inertia: MI closed by theorem, not by lensing alone"),
("The field-space-supported kernel theorem", ["field-space support", "nonlocal in field space", "kernel supported below a0"],
 "if the response kernel differs from delta only for |grad Phi| < a0 then PPN = GR to all orders where |grad Phi| > a0 (certified)",
 "compute the Cassini quadrupole for such a kernel",
 "quadrupole above the ceiling kills the class"),
("The Bargmann algebra with an acceleration generator", ["bargmann extension", "central charge a0", "jacobi identity acceleration generator"],
 "the extended algebra's Jacobi identities as a finite computation",
 "classify the representations",
 "no consistent extension: the central-charge route closed"),
("The minimal-surface functional forced by the RAR", ["minimal surface reading", "plateau functional equipotentials", "area functional gravity"],
 "the Euler-Lagrange equation of A[Phi] = int F(|grad Phi|/a0) and the F the RAR forces, certified",
 "solve for F from nu_RAR",
 "F not convex: the variational reading fails"),
("Finsler worldline action with an acceleration one-form", ["finsler metric worldline", "acceleration one-form", "finsler geodesic newtonian limit"],
 "the geodesic equation and its Newtonian limit, certified",
 "compute PPN gamma and beta",
 "gamma != 1 kills it"),
("Quasi-local mass with a de Sitter reference", ["brown-york with de sitter reference", "quasi-local mass floor", "komar mass a0 correction"],
 "the Newtonian limit of the Brown-York mass with the dS reference term, certified",
 "evaluate for a point mass",
 "the correction is a pure Lambda renormalisation: closed"),
("The Vlasov stationary-state family in a log potential", ["vlasov stationary states log potential", "f(e) family", "cold collapse reachable gamma"],
 "the isotropic f(E) with rho ~ r^{-gamma} in Phi = C ln r, and the energy bound on reachable gamma from cold collapse",
 "bounds what any N-body can show",
 "gamma = 2 not reachable from cold starts: the temperature is not dynamical by theorem"),
("The requirement matrix as a decidable statement", ["requirement matrix theorem", "thirteen gates consistency", "decidable admissibility"],
 "the thirteen gates as propositions; consistency for the coherent class, inconsistency for every local class (from the no-go theorems as hypotheses)",
 "one Lean file",
 "the coherent class also inconsistent: the programme closes by theorem"),
("The GDM closure of the isothermal phantom", ["generalised dark matter closure", "gdm c_s^2 c_vis^2", "phantom as gdm"],
 "(c_s^2, c_vis^2, w) of the isothermal phantom, certified",
 "CLASS/hi_class Planck fit",
 "Delta chi2 > 25"),
("The BAO sound-horizon shift from a fluid sector", ["sound horizon shift fluid", "r_s with c_s^2 sector", "bao shift closed form"],
 "delta r_s/r_s as a closed form in c_s^2, certified",
 "DESI + Planck",
 "|delta r_s/r_s| > 1%"),
("The ISW sign with the framework's nu(z)", ["isw sign", "isw cross-correlation framework", "potential decay nu(z)"],
 "the ISW kernel for the framework's potential evolution, certified",
 "Planck x galaxies ISW",
 "sign reversal"),
("The Lean dependency graph of the framework", ["lean dependency graph", "named axioms kappa kernel temperature", "one lean project"],
 "every rung's algebra in one project with the three postulates as named axioms",
 "build it",
 "any downstream theorem that imports no postulate is a genuine derivation: list them (expected: none beyond algebra)"),
("The falsifier scorers as Lean functions", ["scorer as lean function", "decision function certified", "verdict as computation"],
 "each registered decision rule as a total function on the data type",
 "implement DR4, tSZ, kink, XRISM scorers",
 "a scorer that cannot be written totally is under-specified: recorded"),
("The look-elsewhere enumeration completeness theorem", ["enumeration completeness", "natural constants alphabet", "in-band fraction prior"],
 "completeness of the expression enumeration for the alphabet at k <= 4",
 "publish the in-band fraction for kappa's band",
 "the prior every coefficient claim must beat"),
("Symbolic regression on the RAR residual field with an FDR gate", ["symbolic regression rar residuals", "fdr gate residual law", "atomos on sparc"],
 "the FDR control theorem for the search (Benjamini-Hochberg as a lemma)",
 "run the atomos engine on SPARC residuals versus (x, Sigma, g_ext, B/T, f_gas, size)",
 "FDR-dead is a valid outcome; a survivor is pre-registered before a second sample"),
# G. more empirical, cross-domain
("The Tully-Fisher of HI-rich ultra-diffuse galaxies", ["hi-rich udg btfr", "leisman udg tully fisher", "gas-rich udg rotation"],
 "the BTFR is composition-blind, certified",
 "Leisman/Mancera Pina HI UDGs (the claimed BTFR outliers)",
 "offset > 0.3 dex after inclination correction kills composition-blindness"),
("Counter-rotating gas discs' RAR", ["counter-rotating gas rar", "retrograde gas disc", "time-reversal rar test"],
 "time-reversal symmetry of the a0-scale dynamics, certified",
 "MaNGA counter-rotators",
 "systematic RAR offset between prograde and retrograde"),
("The RAR in polar-ring galaxies' two planes", ["polar ring two-plane rar", "ngc 4650a", "flattening in aqual"],
 "the non-spherical mu_2 solution's ratio v_polar/v_disc, certified numerically to 1e-3",
 "polar-ring sample",
 "ratio outside the measured band"),
("Bar pattern speeds as friction probes", ["bar pattern speed", "fast bars aguerri", "r = r_cr/r_bar"],
 "Milgromian friction on a bar in its own disc, certified scaling",
 "S4G/MaNGA bar pattern speeds",
 "slow bars (R > 1.4) in > 30% of the sample"),
("Warp onset in units of r_M", ["warp onset radius", "reshetnikov warps", "torque-free radius"],
 "the torque-free radius of a tilted outer disc in the mu_2 well, a pure number x_w",
 "HI warp onset radii / r_M",
 "no clustering at any x_w within 0.2 dex"),
("Lopsidedness growth versus x", ["lopsidedness m=1 growth", "whisp lopsided", "m = 1 amplitude versus acceleration"],
 "the m = 1 growth rate in the deep regime, certified scaling",
 "WHISP HI m = 1 amplitudes versus g_bar/a0",
 "no trend at 3 sigma"),
("The gravitational-redshift test of lensing = dynamics", ["gravitational redshift clusters", "wojtak 2011", "sadeh 2015 stacked redshift"],
 "lensing = dynamics implies the stacked gravitational redshift equals the lensing potential depth, certified",
 "SDSS/BOSS stacked cluster redshifts versus lensing Phi",
 "3 sigma mismatch"),
("High-z cluster T-M as an a0(z) probe", ["high-z cluster t-m", "a0(z) from clusters", "t-m zero point evolution"],
 "T ~ sqrt(M_b a0(z)): the zero point tracks sqrt(a0(z)), certified",
 "Chandra/XMM clusters 0.5 < z < 1.2",
 "evolution inconsistent with the flat law at 3 sigma"),
("Entropy profiles of the phantom", ["entropy profile k(r)", "ghirardini entropy", "k ~ r^{4/3} phantom"],
 "K = T/n^{2/3} ~ r^{4/3} in the deep regime, certified",
 "X-COP entropy profiles",
 "4/3 excluded at 3 sigma in the outskirts"),
("The Local Volume turnaround radius law", ["turnaround radius", "zero-velocity surface", "karachentsev local volume"],
 "r_0 where the 1/r attraction balances H^2 r, certified: r_0 ~ M_b^{1/2}",
 "Local Volume groups",
 "M^{1/3} (LCDM) preferred at 3 sigma"),
("The Local Group timing argument in the deep regime", ["timing argument deep regime", "m31-mw radial orbit 1/r", "elliptic-integral orbit"],
 "the radial two-body orbit with the 1/r force, certified closed form",
 "LG mass from the M31 approach",
 "implied M_b(LG) > 2x the census"),
("The LMC's friction and the Milky Way's reflex", ["lmc reflex motion", "petersen penarrubia", "lmc dynamical friction"],
 "friction on the LMC in the deep MW well, certified integral",
 "Gaia reflex velocity",
 "outside 2 sigma"),
("Hypervelocity stars' deceleration", ["hypervelocity star deceleration", "hvs speed-distance", "unbound star in mu_2 well"],
 "the deceleration profile of an unbound star, certified",
 "Gaia DR3 HVS",
 "3 sigma exclusion"),
("Stream widths and the deep-regime Jacobi radius", ["jacobi radius log potential", "pal 5 width", "gd-1 width"],
 "the tidal radius law in a log potential, certified",
 "Pal 5 and GD-1 widths",
 "off by > 50%"),
("Sagittarius plane precession", ["sagittarius precession", "orbital plane precession 1/r", "sgr bifurcation"],
 "the precession rate in a central 1/r well, certified (interior-only)",
 "observed Sgr precession",
 "wrong sign or 3 sigma"),
("PN kinematics in ellipticals under the cap", ["planetary nebulae ellipticals", "pn.s kinematics", "romanowsky pne"],
 "projected Jeans for a Sersic galaxy in the capped mu_2 well, certified",
 "PN.S sample",
 "3 sigma without a halo"),
("Crater II and Antlia II under the cap", ["crater ii", "antlia ii", "cap law dispersion prediction"],
 "sigma_pred(M_*, g_ext) closed form, certified",
 "measured 2.7 and 5.7 km/s",
 "either outside 2 sigma"),
("DF2/DF4 under the cap", ["ngc 1052-df2", "df4 dispersion", "no dark matter galaxies"],
 "the phantom vanishes at g_ext > a0 under the cap, certified",
 "8.5 and 4.2 km/s",
 "outside 2 sigma for both"),
("The tidal-dwarf BTFR", ["tidal dwarf galaxies btfr", "ngc 5291 tdg", "composition-blind btfr"],
 "composition-blindness certified",
 "Lelli 2015 TDGs on the 12-decade line",
 "> 0.3 dex offset"),
("Fornax GC inspiral times", ["fornax globular clusters inspiral", "fornax timing problem", "gc sinking"],
 "Milgromian friction inspiral time in a deep-MOND dSph, certified",
 "the five Fornax GCs",
 "any predicted sinking < 2 Gyr"),
("The satellite escape-velocity law", ["escape velocity law satellites", "v_esc with efe", "2c ln(r_cap/r)"],
 "v_esc^2 = 2C ln(r_cap/r), certified",
 "Deason escape-speed curve",
 "> 20 km/s mismatch at 2 R0"),
("Cluster T-M at groups' low-mass end with the two-temperature sector", ["two-temperature sector", "phantom and dust temperatures", "temperature ratio partition"],
 "Jeans equations for two components at T1, T2 in one well, certified",
 "X-COP partition at a fixed T1/T2",
 "required ratio varies > 30% across clusters"),
("Coherent-stiffening uniqueness", ["coherent stiffening uniqueness", "response kernel fixed by locality and c_t", "stiffening class theorem"],
 "the response kernel of a coherently stiffened tensor sector is fixed up to one function of |k|/k0 by the Newtonian limit and c_T = c",
 "derive the RAR's constraints on that function",
 "no function exists or the Hamiltonian is unbounded"),
("Weak lensing at the two-halo scale with the phantom fixed", ["two-halo amplitude free", "esd phantom fixed by rar", "brouwer 2021 refit"],
 "the ESD of a truncated phantom plus a correlated-neighbour term, certified",
 "KiDS-1000 ESD with only the two-halo amplitude free",
 "Delta chi2 > 25 versus the free-halo fit"),
("Growth rate with a k-dependent nu", ["growth with k-dependent nu", "fsigma8 coherent stiffening", "desi dr1 growth kernel"],
 "the linear growth equation with nu(k), certified",
 "DESI DR1 fsigma8(z)",
 "3 sigma at any z"),
("The a0-crossing dark fraction", ["dark fraction at a0 crossing", "nu(1) - 1", "m_dark(<r_m)/m_b measured"],
 "M_dark(<r_M)/M_b = nu(1) - 1 for any kernel, certified",
 "SPARC gas-dominated subsample",
 "outside every kernel's value by 3 sigma, or equal to 1.000"),
("The asymptotic correction to equipartition", ["asymptotic correction law", "m_ph/(m_b x) - 1 residual", "approach from below"],
 "the exact residual R(x) for mu_2 and its bound, certified",
 "extended-HI outer curves",
 "sign or rate wrong at 3 sigma"),
("The gamma-law of the dark profile", ["gamma-law dark profile", "sigma_r^2 = c/(gamma - 2 beta)", "jeans inversion of the phantom"],
 "sigma^2 = C/gamma and its anisotropic generalisation, certified",
 "SPARC Jeans inversion",
 "(gamma, beta) inconsistent with C/2 at 3 sigma"),
("The gas-only kappa", ["gas-only rar zero point", "upsilon cancels identically", "kappa from gas-dominated"],
 "Upsilon cancels identically for g_gas > 0.9 g_bar, certified",
 "fit a0 on the gas-dominated subsample",
 "kappa outside [0.35, 0.70]"),
("The vertical kernel test at R0", ["vertical jeans mu_2 slab", "k_z(z) closed form", "gaia dr3 vertical kinematics kernel"],
 "K_z(z) for the mu_2 slab, certified",
 "Gaia DR3 vertical kinematics at R0",
 "mu_2 worse than nu_RAR by Delta chi2 > 9"),
("The 21-cm bias scale independence", ["21-cm bias scale independence", "chime hi autopower", "r(k) = 1 bias"],
 "with R(k) = 1 the HI bias is scale-independent on k < 1 h/Mpc, certified",
 "CHIME/MeerKAT",
 "a cut where the warm face predicts one"),
("The bulk-flow enhancement", ["bulk flow enhancement nu", "cosmicflows-4 bulk flow", "2m++ prediction under nu"],
 "the bulk-flow functional with the nu factor, certified",
 "Cosmicflows-4 versus 2M++",
 "3 sigma above measured"),
("Three-merger offset clock", ["el gordo offset", "macs j0025 offset", "three mergers clock"],
 "phantom re-attachment at the light crossing versus the dust, certified",
 "El Gordo, MACS J0025, Bullet ages",
 "any offset persisting beyond the gas re-alignment"),
("Bar-halo decoupling in LSB discs", ["disc self-gravity fraction f_disc", "f_disc function of x", "bars in lsb discs s4g"],
 "f_disc = v_disc^2/v_c^2 is a function of x only in the deep regime, certified",
 "SPARC f_disc versus S4G bars",
 "no correlation at 3 sigma"),
("Group X-ray outskirts slopes", ["erass1 group outskirts", "surface-brightness slope outside r_m", "isothermal projected beta"],
 "Sigma ~ 1/b outside r_M for the phantom, certified",
 "eRASS1 groups",
 "slopes 3 sigma steeper"),
("Timing the Sagittarius stream's leading arm apocentre", ["sgr leading arm apocentre", "apocentre precession 1/r", "stream apocentre timing"],
 "apocentre precession per orbit in a central 1/r well, certified",
 "the observed Sgr apocentres",
 "3 sigma"),
("The Coma cluster's outskirts kinematics", ["coma outskirts kinematics", "coma infall region", "coma caustic profile"],
 "the caustic profile of the phantom + dust well, certified",
 "Coma redshift survey",
 "3 sigma"),
("The dwarf-galaxy pair timing (LMC-SMC)", ["lmc-smc binary orbit", "magellanic pair timing", "smc lmc bound orbit mond"],
 "the two-body deep-MOND orbit of the LMC-SMC pair, certified",
 "Gaia proper motions",
 "the pair unbound in the prediction while observed bound, or vice versa"),
("The Andromeda-Milky Way past encounter", ["m31 mw past encounter", "zhao 2013 past encounter", "flyby 10 gyr ago"],
 "the past radial orbit under the 1/r force, certified",
 "the implied encounter epoch versus the thick-disc age",
 "the encounter predicted inside the last 3 Gyr: killed by disc survival"),

# H. thirty more, domains the corpus lacks
("The dwarf-core test: the phantom's r^-2 cusp versus observed cores", ["cusp-core problem phantom", "things dwarfs inner slope", "phantom cusp in dwarfs"],
 "in a deep-MOND dwarf the equilibrium phantom is rho ~ r^-2 to the centre, steeper than NFW's r^-1; certified",
 "THINGS/LITTLE THINGS inner rotation curves: the inner dark slope",
 "cores (slope > -0.5) in > 50% of the sample kill the phantom-as-mass reading inside r_M"),
("Ellipticals' central dark fraction versus the phantom cusp", ["central dark fraction ifu", "atlas3d central dark matter", "phantom cusp ellipticals"],
 "the phantom's contribution inside R_e for a Sersic galaxy, certified",
 "ATLAS3D JAM central dark fractions (median 13%)",
 "predicted central fraction > 2x the JAM value"),
("Group-scale lensing with the phantom", ["gama group esd", "group-scale excess surface density", "lensing around groups"],
 "the ESD of a group's phantom + dust pie, certified",
 "GAMA/KiDS group lensing (Viola et al.)",
 "Delta chi2 > 25 versus the free-halo fit"),
("SLUGGS globular-cluster kinematics in the capped well", ["sluggs kinematics", "gc system dispersion profile", "ellipticals gc tracers"],
 "projected Jeans for GC tracers in the capped mu_2 well, certified",
 "SLUGGS dispersion profiles to 10 R_e",
 "3 sigma without a halo"),
("Fornax-cluster dwarfs under Fornax's field", ["fornax deep survey dwarfs", "fornax cluster dwarf dispersions", "cap in the fornax cluster"],
 "sigma_pred with g_ext from the Fornax cluster's baryons, certified",
 "FDS dwarf dispersions (Eftekhari et al.)",
 "> 20% outside 2 sigma"),
("Virgo dwarf ellipticals (SMAKCED) under Virgo's field", ["smakced virgo des", "virgo dwarf elliptical kinematics", "cap in virgo"],
 "sigma_pred with g_ext from Virgo, certified",
 "SMAKCED sample",
 "> 20% outside 2 sigma"),
("The cluster-scale RAR of Tian et al.", ["cluster rar tian 2020", "clash rar", "cluster acceleration relation offset"],
 "the two-phase sector's cluster RAR: g_obs(g_bar) with the committed pie, certified",
 "Tian et al. 2020 CLASH RAR (a0_cluster ~ 2e-9)",
 "the predicted cluster RAR offset from the galaxy RAR off by > 0.2 dex"),
("CMB spectral distortions from the fluid sector", ["mu distortion fluid sector", "y distortion dissipation", "pixie forecast framework"],
 "the dissipation of acoustic modes with the sector's c_s^2 adds a certified mu-distortion",
 "compare with FIRAS bounds and PIXIE forecasts",
 "mu above the FIRAS bound kills the c_s^2"),
("JWST early-galaxy abundance under the fluid sector's growth", ["jwst early galaxies abundance", "z > 10 halo mass function fluid", "early structure framework"],
 "the halo mass function at z = 10-15 with the framework's growth, certified as an integral",
 "JWST UV luminosity functions",
 "the framework under-produces bright early galaxies by > 3 sigma"),
("Disc scale-height law versus acceleration", ["disc scale height law", "h/r versus g_bar/a0", "edge-on thickness relation"],
 "the vertical equilibrium of a self-gravitating disc in the mu_2 well gives h/R as a certified function of x",
 "edge-on samples (Bizyaev; Comeron)",
 "no trend at 3 sigma where one is predicted"),
("M31's giant stellar stream orbit in the deep well", ["m31 giant stream", "andromeda giant stream orbit", "stream in the m31 well"],
 "the progenitor orbit in M31's mu_2 well, certified integration",
 "PAndAS stream kinematics",
 "no orbit fits within the measured velocities"),
("Kernel axiomatics: which axioms pin nu", ["kernel axiomatics", "monotone concave deep limit axioms", "one-parameter family of kernels"],
 "the set {monotone, Newtonian limit, deep limit, analyticity at 0, convexity of the transition} is either inconsistent or leaves an n-parameter family; certified",
 "enumerate the family; compare with mu_2 and nu_RAR",
 "the family is empty or contains no data-preferred member"),
("The Cassini quadrupole lower-bound theorem", ["quadrupole lower bound theorem", "minimum efe quadrupole", "variational bound on q2"],
 "for every monotone kernel with the deep limit the EFE quadrupole at eta = 2.5 exceeds Q_min; certify Q_min as a variational lower bound",
 "compare Q_min with the Park ceiling",
 "Q_min above the ceiling closes every modified-gravity kernel at once"),
("Energy conditions of the phantom's stress tensor", ["phantom null energy condition", "stress tensor of the isothermal phantom", "nec violation phantom"],
 "the isothermal phantom's T_mu_nu satisfies the NEC and WEC iff sigma^2 < c^2/3; certified",
 "evaluate for the committed sigma",
 "a violation anywhere in the well kills the fluid reading"),
("The heat-capacity sign of the phantom", ["heat capacity sign", "negative specific heat self-gravitating", "isothermal assumption consistency"],
 "a self-gravitating isothermal sphere has negative heat capacity; the isothermal equilibrium at T_b is thermodynamically unstable unless confined; certified",
 "compute the Antonov-type instability radius for the phantom at T_b",
 "the instability radius inside r_M kills the equilibrium reading"),
("Gauss-map charge conservation", ["gauss-map charge conservation", "flux-defined dark mass evolution", "charge without a current"],
 "a dark mass defined by the flux integral is conserved only if a local current exists; certified as a theorem about the continuity equation",
 "apply to the sourced-field ontology",
 "no current exists: the Gauss-map reading is static only"),
("XRISM turbulence versus the hydrostatic bias the phantom needs", ["xrism turbulence", "resolve line widths", "turbulent pressure fraction"],
 "the hydrostatic bias implied by a measured turbulent velocity, certified",
 "XRISM Resolve line widths in Perseus/Coma versus the phantom's required share",
 "the phantom's share degenerate with turbulence at all radii: the test is void (recorded)"),
("Radio-relic Mach numbers and merger speeds in the deep well", ["radio relic mach number", "merger shock speed", "relic mach versus infall"],
 "the infall speed onto the phantom + dust well, certified",
 "relic Mach numbers (van Weeren) versus predicted merger speeds",
 "predicted speeds off by > 30%"),
("Cluster weak-lensing outskirts convergence", ["convergence profile outskirts", "hsc cluster outskirts lensing", "kappa(theta) phantom"],
 "kappa(theta) of the phantom's 1/r^2 envelope, certified",
 "HSC cluster stacks beyond R200",
 "slope 3 sigma from the prediction"),
("Distance-updated SPARC RAR", ["updated distances sparc", "gaia-based distances rar", "distance revision rar scatter"],
 "the RAR's distance sensitivity as a certified propagation identity",
 "re-derive the RAR with the latest TRGB/Cepheid distances",
 "the scatter increases: the old distances were absorbing error"),
("False-kill and false-pass rates of every falsifier on mocks", ["false-kill rate", "mock calibration of falsifiers", "falsifier power on mocks"],
 "the decision rule's error rates as a certified function of the mock's noise model",
 "generate mocks for DR4, tSZ, kink, XRISM",
 "any falsifier with false-kill > 5% is re-registered before data"),
("A CI gate against literal-True checks", ["ci gate literal true", "check(true detector", "continuous integration for lanes"],
 "a static analysis that no check's condition is a constant, certified as a decidable syntactic property",
 "run over every lane; list offenders",
 "the count itself is the deliverable"),
("A tactic for the sqrt-pair algebra", ["sqrt-pair tactic", "gm/a0 algebra lemma", "mathlib tactic framework identities"],
 "one lemma sqrt(GM/a0) sqrt(GM a0) = GM plus a tactic that closes every rung identity",
 "refactor the 22 certificate files to import it",
 "any rung that does not reduce to the lemma is not algebra: list it"),
("Symplecticity of the N-body engine, certified", ["leapfrog symplecticity certified", "energy bound theorem integrator", "kdk error bound"],
 "the KDK leapfrog's symplecticity and its energy-error bound O(dt^2), certified",
 "apply to the G111 engine's dt",
 "a bound looser than the observed drift means the engine is not the one certified"),
("Lunar laser ranging as the second quadrupole bound", ["lunar laser ranging quadrupole", "llr efe bound", "blanchet novak llr"],
 "the EFE quadrupole's effect on the lunar orbit, certified",
 "compare with LLR precision",
 "LLR excludes the kernel independently of Cassini"),
("The LMC-SMC bound orbit", ["lmc smc bound orbit", "magellanic binary deep mond", "smc orbit around lmc"],
 "the two-body deep-MOND orbit, certified",
 "Gaia proper motions",
 "bound/unbound mismatch"),
("The Milky Way's satellite orbital energies under the cap", ["satellite orbital energies", "dwarf infall times cap", "gaia satellite orbits mond"],
 "orbital energies of the MW satellites in the capped well, certified",
 "Gaia proper motions of 40 satellites",
 "> 30% unbound in the prediction while observed bound"),
("The RAR of counter-rotating stellar discs", ["counter-rotating stellar discs", "two stellar discs rar", "ngc 4550"],
 "time-reversal symmetry certified",
 "NGC 4550-type systems",
 "systematic offset between the discs"),
("Planetary-nebula RAR in S0 galaxies", ["s0 galaxies pne rar", "lenticular kinematics rar", "pn.s s0"],
 "projected Jeans for an S0 in the capped well, certified",
 "PN.S S0 sample",
 "3 sigma without a halo"),
("Ultra-compact dwarfs' dynamics", ["ultra-compact dwarfs", "ucd dispersion", "ucd mass-to-light"],
 "at g >> a0 UCDs are Newtonian; the residual mu_2 correction, certified",
 "UCD dynamical M/L (Mieske)",
 "any required dark mass at g/a0 > 10 kills the reading"),
]

# ---------------------------------------------------------------- the novelty gate
def hits(term):
    t = term.lower(); return CORPUS.count(t)
rows = []
for i, (title, terms, lean, comp, kill) in enumerate(C):
    h = {t: hits(t) for t in terms}
    absent = sum(1 for v in h.values() if v == 0)
    novelty = absent / len(terms)
    in_fifty = any(t.lower() in FIFTY for t in terms)
    rows.append(dict(i=i, title=title, terms=h, novelty=round(novelty, 2), in_fifty=in_fifty, lean=lean, comp=comp, kill=kill))
survivors = [r for r in rows if r["novelty"] >= 0.5 and not r["in_fifty"]]
# deduplicate near-identical titles (keep first)
seen, uniq = set(), []
for r in survivors:
    k = re.sub(r"[^a-z]", "", r["title"].lower())[:24]
    if k in seen: continue
    seen.add(k); uniq.append(r)
uniq.sort(key=lambda r: (-r["novelty"], r["i"]))
top = uniq[:100]
print(f"corpus: {NFILES} files; candidates {len(C)}; novelty >= 0.5 and not in FIFTY: {len(survivors)}; unique: {len(uniq)}; emitted: {len(top)}")
print(f"rejected (overlap with the record or the fifty): {[r['title'][:50] for r in rows if r not in survivors]}")

# ---------------------------------------------------------------- the document
L = ["# IDEAS_100 — one hundred further steps, each novel to this record by keyword audit, each with a Lean-certifiable statement, a computation or dataset, and a kill gate",
     "", f"Generated by `IDEAS_100_generator.py` on the tracked corpus ({NFILES} .md/.py files; every distinctive term below was searched; a term's hit count is in IDEAS_100.json). "
     "A step is emitted only if at least half of its distinctive terms appear nowhere in the repository and none appears in FIFTY_NEXT_STEPS.md. "
     "The same rules as the fifty: Lean certifies the mathematics; the data or the computation decides; every step can fail; both a₀ footings; no literal-True checks; a FAIL is a finding.", ""]
for n, r in enumerate(top, 1):
    L.append(f"**{n}. {r['title']}** (novelty {r['novelty']:.2f})  ")
    L.append(f"Lean: {r['lean']}.  ")
    L.append(f"Compute/data: {r['comp']}.  ")
    L.append(f"Kill: {r['kill']}.")
    L.append("")
open(os.path.join(HERE, "IDEAS_100.md"), "w").write("\n".join(L))
json.dump(dict(n_files=NFILES, candidates=len(C), emitted=len(top), rows=rows), open(os.path.join(HERE, "IDEAS_100.json"), "w"), indent=1)
print("wrote IDEAS_100.md and IDEAS_100.json")
