"""Generate Axioms_all.lean: `#print axioms` for EVERY theorem declared in the seven certificate modules and in Bridges32pi.lean.
(The per-file #print lines cover the headline theorems; this audit covers all of them, so no theorem is left unchecked.)"""
import re, sys
mods = ["H1_bpst", "H2_s4_euler", "H3_horizon_area_lambda", "H4_graviton", "H5_freefall", "H6_nonembed", "H7_p09_reduction", "Bridges32pi"]
names = []
for m in mods:
    src = open(m + ".lean", encoding="utf-8").read()
    src = re.sub(r"/-.*?-/", "", src, flags=re.S)          # drop block comments / docstrings
    for line in src.splitlines():
        mm = re.match(r"\s*theorem\s+([A-Za-z0-9_'.]+)", line)
        if mm:
            names.append(mm.group(1))
assert len(names) == len(set(names)), "duplicate theorem names: " + str([n for n in names if names.count(n) > 1])
with open("Axioms_all.lean", "w", encoding="utf-8") as f:
    f.write("import Mathlib\n" + "".join("import %s\n" % m for m in mods) + "\n")
    f.write("-- generated by gen_axioms.py: one #print axioms per theorem of the eight modules\n")
    for n in names:
        f.write("#print axioms %s\n" % n)
print(len(names), "theorems")
