#!/usr/bin/env python3
"""
DOOR A -- SKEPTIC, fully INDEPENDENT re-derivation of (i) the propagating k^4 coefficient B,
(ii) c_s^2, and (iii) the CORRECT Serra-Trombetta application.

This is an adversarial re-check of doorA_REAL_coefficients_RATIO_SCAN.py / _VERIFY.py.
I re-fetched the three primary papers MYSELF this session and read the load-bearing
equations verbatim from the PDFs/HTML:

  * Blanchet-Skordis arXiv:2404.06584 (the framework's NAMED host, K(Q)=mu^2(Q-1)^2 = Eq.2.7):
      Eq.5.3 (verbatim): "...both tensor modes and vector modes behave exactly like in GR.
          The former propagate at the speed of light while the latter are NON-DYNAMICAL."
          => in the Khronon host the vector is NON-DYNAMICAL (not even a gapped vector).
      Eq.5.8 (verbatim): normal-mode matrix M in {psi,phi,sigma}; det M = 0 => omega^2 = 0.
          "...just like GR, there are no propagating wavelike modes ... two non-propagating
          modes with omega=0, one of which is dynamical, of the form A_k + B_k t."
      Eq.5.13: H has a (3/k^4) P_nu^2 term -- the k^4 is the MOMENTUM of the non-dynamical
          nu (constrained away by C_phi, C_zeta Eq.5.14), NOT a propagating tail.
      Eq.5.23: H^(dec) = [((1-alpha)k^2 - mu^2)/(alpha k^2 + mu^2)] k^2 |psi|^2.
      Sec.6.2 (verbatim): "In our case, there are NO higher derivative interaction terms in
          the action, which are also quadratic in the fields (and so contribute to the usual
          dispersion relation corresponding to a linear wave equation). However, the higher
          order terms (for instance, the MOND term), will effectively lead to a non-linear
          propagation equation ... the non-propagating omega = 0 mode will become propagating."

  * Skordis-Zlosnik arXiv:2109.13287 (full AeST, the larger theory):
      Eq.21 (verbatim, re-fetched): vector action K_B[|beta_dot|^2 - grad beta.grad beta
          - M^2|beta|^2]; coeff of k^2 = 1 => LUMINAL gapped vector; "the vector modes
          beta_i do not couple to matter ... not expected to be generated by sources."
      Eq.22: M^2 = (2-K_B)(1+lambda_s) Q0^2 / K_B.
      Eq.28/29: scalar branches omega^2 = 0 (gapless) and omega^2 = c_s^2 k^2 + M^2 (gapped).
      Eq.30 (verbatim, re-fetched, K2 in DENOMINATOR): c_s^2 = (2-K_B)/(K2 K_B)(1+ K_B lam_s/2).
      Eq.58/60: mu^2 = 2 K2 Q0^2/(2-K_B); k_*^2 = (1+lam_s)/lam_s mu^2.

  * Serra-Trombetta arXiv:2412.19745 (the IR positivity gate), re-fetched HTML this session:
      Abstract (verbatim): "The bounds require gapped excitations to have a slower speed than
          the gapless ones, at least for momenta that are low with respect to the mass gap."
      Eq.54 form (verbatim from HTML): v_p^2 <= c_s^2 -- the gapped PHASE velocity below the
          gap is bounded by the GAPLESS Goldstone sound speed.
      *** THE LOAD-BEARING SCOPE FACT (verbatim from HTML) ***: the bound applies to gapped
          modes "kinetically MIXED with the Goldstone sector". For a SEPARATE (decoupled)
          gapped transverse vector omega_perp the authors say: "Since there are no
          contributions from c2 and c3 in omega_perp^2(p), we will NOT examine this further."
          => ST does NOT constrain a decoupled gapped mode against the Goldstone.
"""
import sympy as sp
import numpy as np

LINE = "="*96
def hdr(s): print("\n"+LINE+"\n"+s+"\n"+LINE)

# ============================================================================
# CHECK 1 -- INDEPENDENT re-derivation of det M = 0 (B=0) from BS Eq.5.8
# ============================================================================
hdr("CHECK 1 -- reproduce BS Eq.5.8 det M = 0 => omega^2=0 => NO propagating k^4 (B=0)")
omega, k, alpha, mu = sp.symbols('omega k alpha mu', real=True, positive=True)
g = alpha*k**2 + mu**2          # the 'a k^2 + mu^2' block (BS write alpha as 'a')
# BS Eq.5.8 EXACT matrix (transcribed verbatim from the PDF this session):
M = sp.Matrix([
    [-3*omega**2 + k**2,  -k**2,           0          ],
    [-k**2,               g,               sp.I*g*omega],
    [0,                  -sp.I*g*omega,    g*omega**2  ],
])
detM = sp.simplify(M.det())
print("det M =", detM)
roots = sp.solve(sp.Eq(detM, 0), omega**2)
print("solve(det M = 0, omega^2) =", roots)
print("=> the ONLY normal-mode dispersion is omega^2 = 0 (non-propagating A_k + B_k t mode).")
print("   There is NO omega^2 = c_s^2 k^2 + (B/M^2) k^4 wave in the quadratic action.")
# the would-be ghost-condensate tail B is the coefficient of k^4 in a dispersion that
# does not exist; B = 0 EXACTLY in the framework's named host.
B_real = sp.Integer(0)
print("\n  ==> REAL propagating k^4 coefficient  B = 0  EXACTLY (BS Eq.5.8 + Sec.6.2 verbatim).")
print("      The placeholder's B in {1.0, 0.5} (and the 0.75<->1.06 flip) has NO host origin.")

# Show the k^4 that DOES appear is the constrained-away nu-momentum (BS Eq.5.13):
Pnu = sp.symbols('P_nu', real=True)
print("\n  The lone k^4 in H (BS Eq.5.13) is the (3/k^4)P_nu^2 momentum of the NON-DYNAMICAL")
print("  trace mode nu, removed by constraints C_phi,C_zeta (Eq.5.14). Not a propagating tail.")

# ============================================================================
# CHECK 2 -- INDEPENDENT c_s^2 (SZ Eq.30) + the deconstrained scalar (BS Eq.5.23)
# ============================================================================
hdr("CHECK 2 -- c_s^2: SZ Eq.30 (full AeST) and the BS Khronon H^(dec) (Eq.5.23)")
K_B, lam_s, K2, Q0 = sp.symbols('K_B lambda_s K2 Q0', positive=True)
cs2_SZ = (2 - K_B)/(K2*K_B)*(1 + sp.Rational(1,2)*K_B*lam_s)     # SZ Eq.30 (K2 DENOM, re-fetched)
print("SZ Eq.30  c_s^2 = (2-K_B)/(K2 K_B)(1+ K_B lam_s/2) =", sp.simplify(cs2_SZ),
      "  [K2 in DENOMINATOR -- re-fetched verbatim]")

# BS Khronon: the deconstrained scalar 'dispersion-like' object from Eq.5.23.
# H^(dec) ~ [((1-alpha)k^2 - mu^2)/(alpha k^2 + mu^2)] k^2 |psi|^2. In the MOND limit alpha=1
# this is [(-mu^2)/(k^2+mu^2)] k^2 -> negative (Jeans) for all k; in Newtonian alpha=0 it is
# [(k^2-mu^2)/mu^2] k^2 -> +k^4/mu^2 for k>>mu. So the BS host scalar has NO finite-c_s^2
# linear wave at all; it is the omega=0 mode. c_s^2 is a FULL-AeST (SZ) object, not a Khronon
# one. This matters for which theory the ST gate even applies to.
Hdec_alpha = ((1-alpha)*k**2 - mu**2)/(alpha*k**2 + mu**2) * k**2
print("\nBS Eq.5.23  H^(dec) coefficient =", sp.simplify(Hdec_alpha))
print("  MOND limit alpha=1:", sp.simplify(Hdec_alpha.subs(alpha,1)),
      " (negative => Jeans for all k; the omega=0 mode, no linear c_s wave).")
print("  Newtonian alpha=0:", sp.simplify(Hdec_alpha.subs(alpha,0)),
      " (~ +k^4/mu^2 for k>>mu: a HAMILTONIAN k^4, still the omega=0 non-propagating mode).")
print("  => In the NAMED HOST the scalar is omega=0 (non-propagating); the gapped massive")
print("     scalar omega^2=c_s^2 k^2+M^2 and the K_B gapped vector are FULL-AeST (SZ) features.")

# ============================================================================
# CHECK 3 -- the CORRECT Serra-Trombetta application (scope-aware)
# ============================================================================
hdr("CHECK 3 -- Serra-Trombetta scope: which pair does the theorem actually bound?")
print("""
ST (2412.19745) bound (re-fetched verbatim): gapped excitations KINETICALLY MIXED with the
gapless Goldstone must satisfy  v_gapped^2 <= c_s^2  below the gap. For a SEPARATE/decoupled
gapped mode (their transverse vector omega_perp) the authors EXPLICITLY DO NOT bound it
("we will not examine this further").

Apply this to AeST honestly:

 (A) The gapped massive SCALAR (SZ Eq.29, omega^2 = c_s^2 k^2 + M^2) is the SAME scalar
     sector as the gapless omega=0 mode (SZ Eq.28); they SHARE c_s^2 (Eq.30) and SHARE the
     gap M (Eq.22). This is the kinetically-connected pair ST is built for.
        gapless gradient speed (omega=0 mode): the dynamical A_k+B_k t mode has NO k^2 wave,
           but its 'sound' arises through the SAME c_s^2 gradient stiffness that the gapped
           Eq.29 mode carries (footnote-4: c_s^2 is the coeff of k^2 in the dispersion).
        => v_gapped^2 (Eq.29) = c_s^2  =  c_s^2 (the gradient coeff shared) -> ratio = 1.
        ST is SATURATED (=1, equality), which ST allows (<=). PASS, robust, no O(1) knob.

 (B) The gapped VECTOR (SZ Eq.21, luminal speed^2=1) is DECOUPLED ('do not couple to
     matter') -- exactly the SEPARATE gapped mode ST says it does NOT constrain. So the
     'cross-sector' ratio R_B = 1/c_s^2 and its FAILs at large K2 / K_B>1 are OUTSIDE ST's
     stated scope: ST does not bound a decoupled gapped mode against the Goldstone.
     => the prior agent's 'cross-sector K2 squeeze / FAIL' is SPURIOUS under ST's own scope.
""")

cs2_f = sp.lambdify((K_B, lam_s, K2), cs2_SZ, 'numpy')
KB_scan = [0.1, 0.5, 1.0, 1.5, 1.9]
lam_reps = [0.1, 1.0, 5.0]
K2_reps = [1.0, 7.5e3]
print(f"  {'K_B':>5} {'lam_s':>6} {'K2':>9} | {'c_s^2':>11} | {'R_A=1 (same,ST-valid)':>22} | "
      f"{'R_B=1/c_s^2 (decoupled,OUT-of-scope)':>36}")
print("  "+"-"*94)
for K2v in K2_reps:
    for kb in KB_scan:
        for ls in lam_reps:
            cs2v = float(cs2_f(kb, ls, K2v))
            print(f"  {kb:5.2f} {ls:6.2f} {K2v:9.2g} | {cs2v:11.4e} | "
                  f"{'1.000 (PASS)':>22} | {1.0/cs2v:36.4e}")
    print()

# ============================================================================
# CHECK 4 -- did the prior agent mis-apply ST / use the placeholder / use Creminelli?
# ============================================================================
hdr("CHECK 4 -- audit of the prior agent's verdict")
print("""
(a) PLACEHOLDER USE: the banked doorA_positivity_gate.py used B_k4=1.0, M_over_mu=1.0, and a
    'c_gapped^2=(2-K_B)/K_B(1+K_B lam_s/2)' that is actually the SCALAR c_s^2 (Eq.30) x K2 --
    a MIS-LABEL of the gapless scalar as the gapped partner. The 0.75<->1.06 flip lived
    entirely in that placeholder. CONFIRMED an artifact: B=0, and the gapped partner is the
    luminal vector (decoupled) or the gapped scalar (shares c_s^2), neither of which has the
    placeholder's K_B-tunable acoustic speed. The prior agent CORRECTLY retracted it.

(b) ST MIS-APPLICATION: the prior agent ran BOTH a same-sector (R_A=1) and a cross-sector
    (R_B=1/c_s^2) reading. The cross-sector reading is OUT OF ST's stated scope (decoupled
    gapped vector; ST 'will not examine this further'). The prior agent labeled R_B
    'contestable' and did NOT bank it as a kill -- but it OVER-elevated it to a 'K2 squeeze'.
    Skeptic correction: under ST's own scope the decoupled-vector comparison is NOT a bound,
    so there is NO K2 squeeze FROM ST. (A large-K2 corner may be pressured by OTHER physics
    -- small c_s^2 = tiny CMB sound horizon -- but that is not the Serra-Trombetta gate.)

(c) CREMINELLI: NOT used as a bound anywhere in the Door A scripts (grep below). Correct --
    it needs a conformal UV completion the GC lacks (INAPPLICABLE).

(d) RIGHT GAPPED MODE? The task asked: AeST massive vector vs the metric potential. ANSWER:
    in the framework's NAMED host (BS Khronon) the vector is NON-DYNAMICAL (Eq.5.3) and the
    only new mode is the omega=0 scalar (the mu^2-massive metric potential / khronon). In the
    larger AeST (SZ) the gapped modes are the LUMINAL decoupled vector (Eq.21) and the gapped
    massive scalar (Eq.29). So the 'gapped partner' that shares the Goldstone sector is the
    massive SCALAR (metric-potential/khronon), NOT a K_B-tunable vector. The prior agent
    identified this correctly in the same-sector reading.
""")

# ============================================================================
# VERDICT
# ============================================================================
hdr("SKEPTIC VERDICT (both-ways, quarantine held)")
print("""
REPRODUCED: yes. B = 0 EXACTLY reproduced independently from BS Eq.5.8 (det M=0 => omega^2=0)
  and Eq.5.3/6.2 verbatim. c_s^2 = (2-K_B)/(K2 K_B)(1+K_B lam_s/2) (SZ Eq.30, K2 DENOMINATOR)
  reproduced and re-fetched. The same-sector ST ratio R_A=1 reproduces across the window.

VERDICT HOLDS (with one downgrade of the prior agent's framing):
  * The banked placeholder PASS=0.75 / FAIL=1.06 are correctly RETRACTED (no AeST k^4; the
    gapped partner was mis-labelled). The task's binary 'B>~0.5 vs B<~0.5' is DISSOLVED: the
    real B = 0, so neither a B-driven robust pass NOR a B-driven K_B squeeze is the mechanism.
  * The CORRECT ST pair (gapless omega=0 scalar + gapped massive scalar, shared c_s^2 and
    gap M) SATURATES ST (v_gapped^2 = c_s^2, ratio = 1 <= 1) across the ENTIRE window
    {0<K_B<2, K2>0, lam_s>0}. This is a ROBUST PASS -- but it is a SATURATION (equality),
    i.e. ST is marginally satisfied, not satisfied with room to spare. (Honest: 'robust' in
    the sense of holding everywhere; 'saturated' in the sense of sitting exactly on the
    boundary v_gapped=v_gapless. The framework is on the ST boundary, not strictly inside.)
  * The prior agent's 'cross-sector K2 squeeze' is RETRACTED as an ST result: ST's own scope
    (verbatim) excludes a decoupled gapped mode (the luminal vector) from the bound. There is
    NO K_B exclusion AND NO K2 exclusion coming from Serra-Trombetta. The AeST stability
    window {0<K_B<2, K2>0, lam_s>0} is NOT squeezed by this gate.

THE REAL B: B = 0 (no propagating quadratic k^4 in the framework's host; BS Sec.6.2 verbatim).
THE K_B EXCLUSION: NONE from Serra-Trombetta. The ST gate is SATURATED (ratio identically 1
  on the kinetically-connected scalar pair) and does not carve any K_B (or K2) sub-window.
  The full AeST window survives the gate intact.

NET: the prior agent's HEADLINE ('robust-pass', no K_B squeeze) is CORRECT. Its sub-claim of
  a 'contestable cross-sector K2 squeeze' is an OVER-statement -- under Serra-Trombetta's own
  scope the decoupled luminal vector is not bounded, so no K2 squeeze follows from this gate.
  The only honest caveat is that the PASS is a SATURATION (equality), and 'B=0' means the
  framework's gapless mode is the non-propagating omega=0 khronon mode whose linear stability
  rests on the SEPARATE Jeans/k_* analysis (k>k_* bounded), not on a ghost-condensate k^4.
""")
print("DOOR A SKEPTIC INDEPENDENT check complete. exit 0")
