#!/usr/bin/env python3
"""
L35 -- is IC12's transition ghost GENERIC to switch-based constructions, or a property of ITS pressure?
=======================================================================================================
Lane L35 of `fable_independent_2026/CHARTER.md`.  The lead agent's directory
(`closure_2026/integrable_clock_construction_2026/`) is READ-ONLY to this lane: nothing there is imported,
executed or copied.  Every number below is rebuilt from the ACTIONS AS WRITTEN in IC5_ACTION.md,
IC10_LOCAL_CLOCK.md, IC11_CLOCK_PRESSURE.md, IC11_TRANSITION.md and IC12_COMBINED.md, transcribed by hand
into sympy here, differentiated here, and root-solved by a Newton iteration written here.  Comparison with
the lead's committed numbers happens only at the end of each control.

THE QUESTION the lead explicitly declined to answer.  IC12_COMBINED.md closes with:
    "No conclusion is claimed for all possible pressure functions or all other Hamiltonian redesigns."
Its result is that the combined action -- IC11's convex clock pressure PLUS IC11's spatial/tensor
correction -- fails the necessary positive scalar kinetic condition in its TRANSITION region (the plateau
eta = 1 is fine and is checked by its own algebraic pressure reduction; the failure lives where
0 < eta < 1).  So: is that failure generic to ANY smooth switch between the two regimes, or is it a
property of the particular pressure f(X) = (5/64)(2X)^16?

WHAT IS REBUILT (transcribed constants, IC4/IC5/IC8, m = h0 = 1, kappa = 6):
  ell = ln(9/5),  U(c) = (1-c)[ln^2(1-c) - 2 ln(1-c) + 2] - 2,  a0^2 = 27 e^{-1/2}/(8 ell^2),
  Lambda = 6 e^{-1/2} - a0^2 U(4/9),   w = (u-1) xi,  E = e^{(4-3u)xi},  J = e^{-2w-1/6},  S = (2-u) xi,
  h_base = -E rho^2/3 + e^{(3u-2)xi}[Lambda + a0^2 U(u^2)] - 3 e^{(3u-4)xi},
  delta_10 = -E rho^2 (1/J - 1)/3,   B = e^S f(S),   r = -rho E/3,
  h12 = h_base + eta(r) [delta_10 - B],
  eta(r) = E(1/4-d)/[E(1/4-d) + E(d-1/16)],  d = (r^2-1)^2,  E(t) = e^{-1/t} (t>0), 0 (t<=0),
  a_UV = E A/6 + h12,rhorho/4,   A = 1 + eta (1/J - 1).

THE STRUCTURE THIS LANE FINDS (derived symbolically in Part 2, not assumed).  With G = 1/J - 1 and
B = e^S f(S) (which, at fixed (xi,u), does NOT depend on rho):

        a_UV  =  -(E G r/3) eta'  -  (E G r^2/12 + B E^2/36) eta''  =  -(1/b) d/dr [ b(r)^2 eta'(r) ],
        b(r) =  E (G r^2 + B E/3)/12.

Three things follow immediately, and each is a check below:
  (i)   a_UV vanishes IDENTICALLY wherever eta is locally constant -- on BOTH plateaus.  The whole scalar
        UV kinetic coefficient of this reduction is generated by the switch's derivatives.  The plateaus
        are exactly MARGINAL, not positive: E A/6 cancels the -2EA/3 in h,rhorho/4 for every constant eta.
  (ii)  b^2 eta' vanishes at both ends of any transition, so its derivative cannot have one sign:
        integrating with the weight b gives  int b a_UV dr = -[b^2 eta']  = 0.  A quantity whose
        b-weighted integral vanishes, with b of one sign, MUST take negative values.
  (iii) at any interior point where eta'' = 0 -- and one must exist, since eta' vanishes at both ends and
        not in between -- a_UV = -(E G r/3) eta' EXACTLY, with NO dependence on the pressure whatsoever.

THE CHECKS (every one can fail; C* are controls that would catch MY OWN algebra being wrong).
  C1  the IC11 convex-pressure plateau state at S = .2 reproduces IC11_CLOCK_PRESSURE.md's row;
  C2  the IC12 continuation start (rho0, xi0, u0) reproduces IC12_COMBINED.md's quoted digits;
  C3  the 501-point continuation reproduces IC12's eta, physical H and a_UV table and its first negative step;
  C4  two independent routes to a_UV (symbolic Hessian vs the closed identity) agree; a finite-difference
      differentiation of the raw Hamiltonian agrees with the symbolic h,rhorho;
  C5  the machinery returns the KNOWN HEALTHY answer on the eta = 1 plateau (the algebraic pressure
      reduction: PX > 0, Q_clock > 0, 0 < cs^2 <= 1) and returns a_UV = 0 there;
  C6  it returns a_UV = 0 on the eta = 0 base as well, and for EVERY constant eta -- the marginality of (i);
  S1  the general a_UV formula for an ARBITRARY switch and an ARBITRARY pressure, derived symbolically;
  S2  the b-form a_UV = -(1/b)(b^2 eta')' , derived symbolically;
  S3  is the sign flip in IC12's own sample driven by the switch derivatives or by the background G?
  T1  the weighted-integral identity int b a_UV dr = 0, numerically, for a menu of switches;
  T2  the inflection identity a_UV = -(E G r/3) eta' at eta'' = 0, PRESSURE-INDEPENDENT;
  T3  is the ghost generic: 7 switches x 9 pressures (including sign-changing and adversarially optimal B);
  T4  does ANY pressure function cure the FULL transition;
  R1  the curing inequality for the SLIVER the lead's run actually samples, and whether it is satisfiable;
  R2  an EXPLICIT f meeting it, re-solved and re-tested end to end (this is the positive outcome available);
  R3  the structural tension: convexity wants f = a(2X)^n with n > 1, which makes B decay exactly where the
      inequality needs it to grow;
  P1  where the ghost region is for a real Solar System and a real galaxy, and how thick;
  P2  the instability rate there;
  P3  the a0 calibration of the model's own h0 unit, BOTH footings;
  V1  the verdict: is the transition ghost generic.

HONESTY.  A PASS on R2 would be a direct, usable contribution to the lead's IC13/IC14 effort and is the
most valuable positive outcome available in this lane; a PASS on T4 would overturn the lead's negative.
Neither is assumed.  L8 of this lane verified the lead's IC10 metric sector as exactly Einstein with a
separately counted healthy clock, so this lane confirms as readily as it contradicts.
"""
import sys
import math
import sympy as sp
import mpmath as mp

mp.mp.dps = 60
FAILS = []


def check(name, ok, detail=""):
    print(f"  [{'PASS' if ok else 'FAIL'}] {name}" + (f"   ({detail})" if detail else ""), flush=True)
    if not ok:
        FAILS.append(name)


def rel(a, b):
    a, b = mp.mpf(a), mp.mpf(b)
    return abs(a - b) / max(abs(b), mp.mpf(1))


LINE = "=" * 122
print(LINE)
print("L35 -- is IC12's transition ghost generic to switch-based constructions, or a property of its pressure?")
print(LINE, flush=True)

# ----------------------------------------------------------------------------------------------------
# PART 0.  Independent transcription of the action's homogeneous density and of the switch.
# ----------------------------------------------------------------------------------------------------
print("\nPART 0 -- independent transcription (sympy), from the markdown actions only\n" + "-" * 122)

rho, xi, u, aP, nP = sp.symbols("rho xi u aP nP", real=True)
ell = sp.log(sp.Rational(9, 5))
Ufun = lambda c: (1 - c) * (sp.log(1 - c) ** 2 - 2 * sp.log(1 - c) + 2) - 2
a02 = 27 * sp.exp(-sp.Rational(1, 2)) / (8 * ell ** 2)
Lam = 6 * sp.exp(-sp.Rational(1, 2)) - a02 * Ufun(sp.Rational(4, 9))
wS = (u - 1) * xi
Esym = sp.exp((4 - 3 * u) * xi)
Jsym = sp.exp(-2 * wS - sp.Rational(1, 6))
Ssym_of = (2 - u) * xi
base_sym = (-Esym * rho ** 2 / 3 + sp.exp((3 * u - 2) * xi) * (Lam + a02 * Ufun(u ** 2))
            - 3 * sp.exp((3 * u - 4) * xi))
d10_sym = -Esym * rho ** 2 * (1 / Jsym - 1) / 3
# f(X) = aP (2X)^nP with X = e^{-2S}/2  =>  f = aP e^{-2 nP S},  B = e^S f = aP e^{(1-2nP)S}.
Bsym = aP * sp.exp((1 - 2 * nP) * Ssym_of)
delta_sym = d10_sym - Bsym
r_sym = -rho * Esym / 3

VARS = (rho, xi, u)
_pack = []
for expr in (base_sym, delta_sym, r_sym):
    _pack.append(expr)
    _pack += [sp.diff(expr, v) for v in VARS]
    _pack += list(sp.hessian(expr, VARS))
_pack += [Esym, Jsym, Bsym, Ssym_of]
EVAL = sp.lambdify((rho, xi, u, aP, nP), sp.Matrix(_pack), "mpmath", cse=True)
RAW = sp.lambdify((rho, xi, u, aP, nP), (base_sym, delta_sym, r_sym), "mpmath", cse=True)
A_IC12, N_IC12 = mp.mpf(5) / 64, mp.mpf(16)
print(f"  a0^2 = {mp.nstr(mp.mpf(str(sp.N(a02, 40))), 20)}   Lambda = {mp.nstr(mp.mpf(str(sp.N(Lam, 40))), 20)}"
      f"   (m = h0 = 1, kappa = 6)")
print(f"  IC12's pressure in this parameterisation: f = a (2X)^n with a = 5/64, n = 16, so B = (5/64) e^(-31 S)")


def eta_jets(r):
    """(eta, eta', eta'') for the IC5 activation, derived here from E(t) = exp(-1/t)."""
    r = mp.mpf(r)
    d = (r * r - 1) ** 2
    if d <= mp.mpf(1) / 16:
        return mp.mpf(1), mp.mpf(0), mp.mpf(0)
    if d >= mp.mpf(1) / 4:
        return mp.mpf(0), mp.mpf(0), mp.mpf(0)
    left, right = mp.mpf(1) / 4 - d, d - mp.mpf(1) / 16
    L = 1 / left - 1 / right                      # eta = 1/(1+e^L)
    Ld = 1 / left ** 2 + 1 / right ** 2
    Ldd = 2 / left ** 3 - 2 / right ** 3
    dr = 4 * r * (r * r - 1)
    drr = 12 * r * r - 4
    L1 = Ld * dr
    L2 = Ldd * dr ** 2 + Ld * drr
    t = mp.exp(-abs(L))
    if L > 0:
        e, cm = t / (1 + t), 1 / (1 + t)
    else:
        e, cm = 1 / (1 + t), t / (1 + t)
    prod = t / (1 + t) ** 2                       # = eta (1-eta), cancellation-free
    return e, -prod * L1, prod * ((cm - e) * L1 * L1 - L2)


def jets(point, a=A_IC12, n=N_IC12):
    """h12, its gradient and Hessian in (rho,xi,u), with both switch jets."""
    r0, x0, u0 = (mp.mpf(v) for v in point)
    d = EVAL(r0, x0, u0, a, n)
    out = []
    for off in (0, 13, 26):
        out.append((d[off], mp.matrix(d[off + 1:off + 4]),
                    mp.matrix([[d[off + 4 + 3 * i + j] for j in range(3)] for i in range(3)])))
    (h0, g0, H0), (dl, gd, Hd), (rr, gr, Hr) = out
    e, e1, e2 = eta_jets(rr)
    h = h0 + e * dl
    grad = g0 + e * gd + e1 * dl * gr
    Hess = H0 + e * Hd + e1 * (gr * gd.T + gd * gr.T + dl * Hr) + e2 * dl * gr * gr.T
    E, J, B, Sv = d[39], d[40], d[41], d[42]
    G = 1 / J - 1
    A = 1 + e * G
    aUV_direct = E * A / 6 + Hess[0, 0] / 4
    aUV_ident = -E * G * (4 * rr * e1 + rr ** 2 * e2) / 12 - B * E ** 2 * e2 / 36
    bcoef = E * (G * rr ** 2 + B * E / 3) / 12
    aUV_bform = -(E * G * rr / 3) * e1 - bcoef * e2
    return dict(point=[r0, x0, u0], h=h, grad=grad, hess=Hess, M=Hess[1:3, 1:3], eta=e, eta1=e1, eta2=e2,
                r=rr, E=E, J=J, G=G, B=B, S=Sv, A=A, delta=dl,
                aUV=aUV_direct, aUV_ident=aUV_ident, aUV_bform=aUV_bform, b=bcoef)


def newton_root(rhov, seed, a=A_IC12, n=N_IC12, tol=mp.mpf(10) ** -45, itmax=60):
    """My own damped Newton on the auxiliary constraint h,xi = h,u = 0."""
    x, uu = mp.mpf(seed[0]), mp.mpf(seed[1])
    for _ in range(itmax):
        bg = jets([rhov, x, uu], a, n)
        F = mp.matrix([bg["grad"][1], bg["grad"][2]])
        if mp.norm(F) < tol:
            break
        step = mp.lu_solve(bg["M"], F)
        x, uu = x - step[0], uu - step[1]
        if mp.norm(step) < tol:
            break
    if not 0 < uu < 1:
        raise ValueError("root left the 0 < u < 1 chart")
    return jets([rhov, x, uu], a, n)


# --- the eta = 1 plateau: the algebraic pressure reduction (IC10 + IC11's f), rebuilt ------------------
Ssym, wsym = sp.symbols("S w", real=True)
Xt = sp.exp(-2 * Ssym) / 2
u_of = (Ssym + 2 * wsym) / (Ssym + wsym)
P_expr = -sp.exp(4 * wsym) * (Lam + a02 * Ufun(u_of ** 2)) + 6 * sp.exp(2 * wsym) * Xt + aP * (2 * Xt) ** nP
PEVAL = sp.lambdify((Ssym, wsym, aP, nP), sp.Matrix([P_expr, sp.diff(P_expr, wsym), sp.diff(P_expr, Ssym),
                                                     sp.diff(P_expr, wsym, 2), sp.diff(P_expr, Ssym, wsym),
                                                     sp.diff(P_expr, Ssym, 2)]), "mpmath", cse=True)


def plateau_state(S, a=A_IC12, n=N_IC12):
    """IC11's convex-pressure plateau state.  f_w = 0, so the w root is the IC10 one."""
    S = mp.mpf(S)
    w = mp.mpf(-S) / 4
    for _ in range(80):                                   # my own Newton on P_w = 0
        _, Pw, _, Pww, _, _ = PEVAL(S, w, mp.mpf(0), mp.mpf(1))
        if abs(Pw) < mp.mpf(10) ** -50:
            break
        w = w - Pw / Pww
    P, Pw, PS, Pww, PSw, PSS = PEVAL(S, w, a, n)
    X, mstar = mp.exp(-2 * S) / 2, mp.exp(-mp.mpf(1) / 6)
    eff = PSS - PSw ** 2 / Pww
    PX, Q, Qbare = -PS / (2 * X), (eff + PS) / (2 * X), (PSS + PS) / (2 * X)
    energy = -PS - P
    H = mp.sqrt(energy / (3 * mstar)) if energy > 0 else mp.nan
    wSd = -PSw / Pww
    cs2 = PX / Q
    physH = mp.exp(-w) * H * (1 + 3 * cs2 * wSd)
    J = mp.exp(-2 * w - mp.mpf(1) / 6)
    rr = mp.exp(S) * J * H
    Asch = Pww - PSw ** 2 / (PSS + PS)
    inside = bool(mp.mpf(3) / 4 <= rr * rr <= mp.mpf(5) / 4)
    healthy = bool(PX > 0 and Q >= PX and energy > 0 and physH > 0 and Asch != 0 and Qbare != 0)
    return dict(S=S, w=w, u=(S + 2 * w) / (S + w), PX=PX, Q=Q, cs2=cs2, energy=energy, H=H, physH=physH,
                r=rr, inside=inside, healthy=healthy, admissible=inside and healthy, constraint=Pw)


# ----------------------------------------------------------------------------------------------------
# PART 1.  CONTROLS -- reproduce the lead's negative before generalising anything.
# ----------------------------------------------------------------------------------------------------
print("\nPART 1 -- CONTROLS: reproduce IC11's plateau and IC12's transition failure, independently\n" + "-" * 122)

st = plateau_state("0.2")
print(f"  IC11 convex-pressure plateau, S = 0.2 (mine | IC11_CLOCK_PRESSURE.md):")
for key, lead, lab in ((st["PX"], "1.554712", "PX"), (st["Q"], "6.033178", "Q_clock"),
                       (st["cs2"], ".257694", "cs^2"), (st["energy"], "2.253969", "rho"),
                       (st["physH"], ".813796", "H_physical"), (st["r"], "1.098455", "r")):
    print(f"    {lab:12s} {mp.nstr(key, 12):>16s} | {lead:>10s}")
c1 = all(rel(v, mp.mpf(l)) < mp.mpf("2e-6") for v, l in
         ((st["PX"], "1.554712"), (st["Q"], "6.033178"), (st["cs2"], ".257694"),
          (st["energy"], "2.253969"), (st["physH"], ".813796"), (st["r"], "1.098455")))
check("C1 [control] my rebuilt IC11 convex-pressure plateau at S = .2 reproduces the lead's six quoted numbers",
      c1, "all six agree to the 6-7 digits IC11 quotes")

rho0 = -3 * mp.exp(-mp.mpf(1) / 6) * st["H"]
xi0, u0 = st["S"] + st["w"], st["u"]
lead0 = (mp.mpf("-2.39245296036635527032033"), mp.mpf("0.139901151226159201400473"),
         mp.mpf("0.570419197789965663436675"))
print(f"  IC12 continuation start:  rho0 = {mp.nstr(rho0, 24)}   xi0 = {mp.nstr(xi0, 24)}   u0 = {mp.nstr(u0, 24)}")
print(f"  IC12_COMBINED.md quotes:  rho0 = {mp.nstr(lead0[0], 24)}   xi0 = {mp.nstr(lead0[1], 24)}   "
      f"u0 = {mp.nstr(lead0[2], 24)}")
c2 = max(rel(rho0, lead0[0]), rel(xi0, lead0[1]), rel(u0, lead0[2])) < mp.mpf("1e-20")
check("C2 [control] the continuation start (rho0, xi0, u0) reproduces IC12's quoted 21-24 digits",
      c2, f"max relative difference {mp.nstr(max(rel(rho0, lead0[0]), rel(xi0, lead0[1]), rel(u0, lead0[2])), 4)}")

print("\n  running the 501-point continuation rho = rho0 + n/1000 (my Newton, seeded from the previous root) ...",
      flush=True)
STATES = []
seed = [xi0, u0]
for step in range(501):
    bg = newton_root(rho0 + mp.mpf(step) / 1000, seed)
    seed = [bg["point"][1], bg["point"][2]]
    bg["step"] = step
    # physical expansion, from the preservation equations rho' = -3h/2, (lnV)' = 3 h,rho/2
    hh, gg, HH = bg["h"], bg["grad"], bg["hess"]
    rhodot, logVdot = -3 * hh / 2, 3 * gg[0] / 2
    qdot = -(bg["M"] ** -1) * (HH[1:3, 0] * rhodot + logVdot * gg[1:3, :])
    wdot = (bg["point"][2] - 1) * qdot[0] + bg["point"][1] * qdot[1]
    bg["physH"] = mp.exp(-bg["point"][1]) * (gg[0] / 2 + wdot)
    bg["rhodot"], bg["logVdot"] = rhodot, logVdot
    STATES.append(bg)

LEAD_TABLE = {0: ("1", "0.813795908489", None),
              200: ("0.998768085276", "0.843722075154", "0.0575680682531"),
              205: ("0.998141100037", "0.859713094253", "0.0191790702739"),
              210: ("0.997729876650", "0.865891322917", "-0.0447954514623"),
              220: ("0.997264003171", "0.869581325452", "-0.202971957824"),
              500: ("0.995746896086", "0.855926309976", "-7.04063964151")}
print(f"    {'n':>4s} {'eta (mine)':>18s} {'eta (IC12)':>16s} {'H_phys (mine)':>18s} {'H (IC12)':>16s}"
      f" {'a_UV (mine)':>18s} {'a_UV (IC12)':>18s}")
c3ok = True
for n_, (le, lh, la) in LEAD_TABLE.items():
    bg = STATES[n_]
    print(f"    {n_:>4d} {mp.nstr(bg['eta'], 12):>18s} {le:>16s} {mp.nstr(bg['physH'], 12):>18s} {lh:>16s}"
          f" {mp.nstr(bg['aUV'], 12):>18s} {la if la else '0 (eta=1)':>18s}")
    c3ok &= rel(bg["eta"], mp.mpf(le)) < mp.mpf("1e-10") and rel(bg["physH"], mp.mpf(lh)) < mp.mpf("1e-10")
    if la:
        c3ok &= rel(bg["aUV"], mp.mpf(la)) < mp.mpf("1e-9")
    else:
        c3ok &= abs(bg["aUV"]) < mp.mpf("1e-40")
first_neg = next((b["step"] for b in STATES if b["aUV"] < -mp.mpf("1e-30")), None)
maxeig = max(max(mp.eigsy(b["M"], eigvals_only=True)) for b in STATES)
print(f"    first step with a_UV < -1e-30: mine {first_neg}, IC12 says 207."
      f"   largest eigenvalue of M over the sample: mine {mp.nstr(maxeig, 12)}, IC12 says -3.52681974136")
check("C3 [control] the independent rebuild reproduces IC12's transition table AND the sign of its Hessian",
      c3ok and first_neg == 207 and rel(maxeig, mp.mpf("-3.52681974136")) < mp.mpf("1e-10"),
      "eta, physical H, a_UV, the first negative step (207) and max eig M all reproduce")

dmax = max(abs(b["aUV"] - b["aUV_ident"]) for b in STATES)
dmax2 = max(abs(b["aUV"] - b["aUV_bform"]) for b in STATES)
fd = []
for n_ in (210, 300, 450):
    bg = STATES[n_]
    _, x_, u_ = bg["point"]
    f_raw = lambda z: (lambda t: t[0] + eta_jets(t[2])[0] * t[1])(RAW(z, x_, u_, A_IC12, N_IC12))
    fd.append(abs(mp.diff(f_raw, bg["point"][0], 2) - bg["hess"][0, 0]))
print(f"    |a_UV(Hessian) - a_UV(identity)| <= {mp.nstr(dmax, 6)};  |a_UV - b-form| <= {mp.nstr(dmax2, 6)};"
      f"  |h,rhorho(symbolic) - finite difference| <= {mp.nstr(max(fd), 6)}")
check("C4 [control] three independent routes to the same coefficient agree (symbolic Hessian, closed identity, b-form)"
      " and a finite-difference derivative of the RAW Hamiltonian confirms h,rhorho",
      dmax < mp.mpf("1e-45") and dmax2 < mp.mpf("1e-45") and max(fd) < mp.mpf("1e-25"),
      "the identity IC12 states is confirmed, not assumed")

# C4b -- the finite-wavenumber Schur complement, so the UV limit is not the only thing tested
def eta_complement(r):
    """1 - eta, cancellation-free next to the eta = 1 boundary."""
    d = (r * r - 1) ** 2
    if d <= mp.mpf(1) / 16:
        return mp.mpf(0)
    if d >= mp.mpf(1) / 4:
        return mp.mpf(1)
    L = 1 / (mp.mpf(1) / 4 - d) - 1 / (d - mp.mpf(1) / 16)
    t = mp.exp(-abs(L))
    return 1 / (1 + t) if L > 0 else t / (1 + t)


def spatial_block(bg):
    """IC11_TRANSITION's W and the corrected G11 = -2(1-eta) e^{u xi}[W + eta(1+tr W^2) I], transcribed here."""
    rv, x_, u_ = bg["point"]
    T = -mp.mpf(27) / 16 + 54 / (5 * mp.log(mp.mpf(9) / 5))
    al, dd = 81 / (8 * T * T), -9 / (8 * T)
    be = 2 * dd - mp.mpf(1) / 3 - 3 * al / 4
    ga = mp.mpf(1) / 16 + 9 * al / 64 - 3 * dd / 4
    a02n = 27 * mp.exp(-mp.mpf(1) / 2) / (8 * mp.log(mp.mpf(9) / 5) ** 2)
    p = mp.exp(-3 * (u_ - 1) * x_) * rv
    W = (mp.matrix([[0, u_ * x_], [u_ * x_, x_ * x_]])
         + 3 * p * p / (8 * a02n * mp.log(mp.mpf(9) / 5) ** 2) * mp.matrix([[al, be / 2], [be / 2, ga]]))
    trW2 = W[0, 0] ** 2 + 2 * W[0, 1] ** 2 + W[1, 1] ** 2
    W11 = W + bg["eta"] * (1 + trW2) * mp.eye(2)
    return W, -2 * eta_complement(bg["r"]) * mp.exp(u_ * x_) * W11


bg220 = STATES[220]
_, G11 = spatial_block(bg220)
print(f"    finite-wavenumber Schur complement at n = 220 (IC11's corrected spatial block, transcribed here):")
schur = {}
for k2 in ("1e8", "1e12", "1e16"):
    Q11 = bg220["M"] + mp.mpf(k2) * G11
    v = bg220["aUV"] - (bg220["hess"][0, 1:3] * (Q11 ** -1) * bg220["hess"][1:3, 0])[0] / 4
    schur[k2] = v
    print(f"      k^2 = {k2:>6s}:  a_UV - (h_rhoq/2) Q11^-1 (h_qrho/2) = {mp.nstr(v, 12)}")
print(f"      k^2 -> infinity:  a_UV = {mp.nstr(bg220['aUV'], 12)}")
check("C4b [control] the negative sign is not an artefact of the strict k -> infinity limit: the finite-wavenumber "
      "momentum Schur complement is negative too and converges to a_UV as k grows, reproducing IC12's k^2 = 1e16 check",
      all(v < 0 for v in schur.values()) and abs(schur["1e16"] - bg220["aUV"]) < abs(schur["1e8"] - bg220["aUV"]),
      f"negative at all three wavenumbers; |difference from the UV limit| falls from "
      f"{mp.nstr(abs(schur['1e8'] - bg220['aUV']), 4)} to {mp.nstr(abs(schur['1e16'] - bg220['aUV']), 4)}")

st0 = STATES[0]
check("C5 [control] on the eta = 1 plateau the machinery returns the KNOWN HEALTHY answer -- the algebraic pressure "
      "reduction is positive -- while the transition reduction returns exactly 0 there",
      st["PX"] > 0 and st["Q"] > 0 and 0 < st["cs2"] <= 1 and abs(st0["aUV"]) < mp.mpf("1e-50") and st0["eta"] == 1,
      f"PX = {mp.nstr(st['PX'], 8)} > 0, Q_clock = {mp.nstr(st['Q'], 8)} > 0, cs^2 = {mp.nstr(st['cs2'], 8)}, "
      f"a_UV = {mp.nstr(st0['aUV'], 4)}")

# eta = 0 base and arbitrary CONSTANT eta: marginality
x_, u_ = STATES[220]["point"][1], STATES[220]["point"][2]
Ev = mp.exp((4 - 3 * u_) * x_)
r_zero = mp.sqrt(mp.mpf(8) / 5)                       # r^2 = 1.6 > 3/2  =>  eta = 0
rho_zero = -3 * r_zero / Ev
bg0 = jets([rho_zero, x_, u_])
const_marginal = []
for e_const in ("0", "0.25", "0.5", "0.75", "1"):
    ec = mp.mpf(e_const)
    d = EVAL(STATES[220]["point"][0], x_, u_, A_IC12, N_IC12)
    Hrr = d[4] + ec * d[17]                            # h,rhorho at frozen eta (no switch jets)
    A_c = 1 + ec * (1 / d[40] - 1)
    const_marginal.append(abs(d[39] * A_c / 6 + Hrr / 4))
print(f"    eta = 0 base (r^2 = 1.6): eta = {mp.nstr(bg0['eta'], 4)}, A = {mp.nstr(bg0['A'], 8)}, "
      f"a_UV = {mp.nstr(bg0['aUV'], 4)};  frozen-eta marginality max |a_UV| = {mp.nstr(max(const_marginal), 4)}")
check("C6 [control] a_UV = 0 identically for EVERY locally constant eta -- both plateaus are exactly MARGINAL, so the "
      "entire coefficient is generated by the switch's derivatives",
      abs(bg0["aUV"]) < mp.mpf("1e-50") and max(const_marginal) < mp.mpf("1e-45") and bg0["eta"] == 0,
      "E A/6 cancels the -2EA/3 inside h,rhorho/4 for any constant eta; nothing is left but eta' and eta''")

# ----------------------------------------------------------------------------------------------------
# PART 2.  STRUCTURE -- derive the general coefficient for an arbitrary switch and an arbitrary pressure.
# ----------------------------------------------------------------------------------------------------
print("\nPART 2 -- STRUCTURE: the coefficient for an ARBITRARY switch and an ARBITRARY pressure\n" + "-" * 122)

Eg, Gg, Bg, rg = sp.symbols("E_g G_g B_g r_g", positive=True)
rho_g = sp.Symbol("rho_g", real=True)
eta_g = sp.Function("eta")
r_of_rho = -rho_g * Eg / 3
h_gen = (-Eg * rho_g ** 2 / 3 + sp.Symbol("V0")                       # h_base: kinetic + rho-independent
         + eta_g(r_of_rho) * (-Eg * rho_g ** 2 * Gg / 3 - Bg))        # eta (delta_10 - B)
A_gen = 1 + eta_g(r_of_rho) * Gg
aUV_gen = sp.simplify(Eg * A_gen / 6 + sp.diff(h_gen, rho_g, 2) / 4)
target = (-Eg * Gg * rg * sp.Derivative(eta_g(rg), rg) / 3
          - (Eg * Gg * rg ** 2 / 12 + Bg * Eg ** 2 / 36) * sp.Derivative(eta_g(rg), (rg, 2)))
diff_S1 = sp.simplify(aUV_gen.subs(rho_g, -3 * rg / Eg).doit() - target.doit())
print(f"  derived   a_UV = {sp.simplify(aUV_gen.subs(rho_g, -3*rg/Eg)).doit()}")
check("S1 [structure] for an arbitrary C^2 switch and an arbitrary rho-independent pressure B, the reduced scalar UV "
      "kinetic coefficient is exactly  -(E G r/3) eta' - (E G r^2/12 + B E^2/36) eta''",
      sp.simplify(diff_S1) == 0, "derived symbolically here; IC12's stated identity is a special case")

b_gen = Eg * (Gg * rg ** 2 + Bg * Eg / 3) / 12
bform = -sp.diff(b_gen ** 2 * sp.Derivative(eta_g(rg), rg), rg) / b_gen
diff_S2 = sp.simplify(sp.expand(bform.doit() - target.doit()))
print(f"  and equals  -(1/b) d/dr [ b^2 eta' ]   with  b(r) = E (G r^2 + B E/3)/12")
check("S2 [structure] that coefficient is an exact total derivative in disguise: a_UV = -(1/b) d/dr[b^2 eta'], "
      "b = E(G r^2 + B E/3)/12",
      sp.simplify(diff_S2) == 0, "this is the whole theorem: b^2 eta' vanishes at BOTH ends of any transition")

# S3: in IC12's own sample, what flips the sign?
print("\n  what actually flips the sign in IC12's own 501 samples:")
print(f"    {'n':>4s} {'G = 1/J - 1':>18s} {'d(r^4 eta1)/dr /r^2':>20s} {'clock term':>16s} {'pressure term':>16s} "
      f"{'a_UV':>16s}")
for n_ in (200, 205, 207, 210, 220, 500):
    b_ = STATES[n_]
    SW = 4 * b_["r"] * b_["eta1"] + b_["r"] ** 2 * b_["eta2"]
    t_clock = -b_["E"] * b_["G"] * SW / 12
    t_press = -b_["B"] * b_["E"] ** 2 * b_["eta2"] / 36
    print(f"    {n_:>4d} {mp.nstr(b_['G'], 10):>18s} {mp.nstr(SW, 10):>20s} {mp.nstr(t_clock, 10):>16s} "
          f"{mp.nstr(t_press, 10):>16s} {mp.nstr(b_['aUV'], 10):>16s}")
G_flip = next((b["step"] for b in STATES if b["G"] < 0), None)
TRANS = [b for b in STATES if b["eta"] < 1]
SW_signs = set(mp.sign(4 * b["r"] * b["eta1"] + b["r"] ** 2 * b["eta2"]) for b in TRANS)
press_frac = max(abs(-b["B"] * b["E"] ** 2 * b["eta2"] / 36) / max(abs(b["aUV"]), mp.mpf("1e-40"))
                 for b in TRANS)
geo = next(b["step"] for b in STATES if b["r"] ** 2 > mp.mpf(5) / 4)
print(f"    the geometric switch boundary r^2 = 5/4 is crossed at n = {geo}; 1 - eta first exceeds 60-digit precision "
      f"at n = {TRANS[0]['step']}.")
print(f"    Over those {len(TRANS)} resolved transition samples the switch factor (4 r eta' + r^2 eta'') keeps ONE "
      f"sign (signs seen: {sorted(float(sg) for sg in SW_signs)}),")
print(f"    G = 1/J - 1 crosses zero at n = {G_flip}, a_UV crosses zero at n = {first_neg}, and the pressure's own "
      f"contribution never exceeds {mp.nstr(100*press_frac, 4)}% of a_UV.")
check("S3 [structure] in IC12's own sample the sign flip is NOT a change in the switch derivatives: the switch factor "
      "keeps one sign over every transition sample and the flip tracks G = 1/J - 1 crossing zero",
      G_flip is not None and G_flip == first_neg and SW_signs == {mp.mpf(-1)},
      f"G < 0 from n = {G_flip}, a_UV < 0 from the same n = {first_neg}; the switch factor is negative at all "
      f"{len(TRANS)} transition samples, so it cannot be what changed")

# ----------------------------------------------------------------------------------------------------
# PART 3.  THE THEOREM -- is the ghost generic to any switch and any pressure?
# ----------------------------------------------------------------------------------------------------
print("\nPART 3 -- THEOREM: any smooth interpolation, any pressure\n" + "-" * 122)

R_LO = (mp.sqrt(mp.mpf(1) / 2), mp.sqrt(mp.mpf(3) / 4))      # lower branch: eta 0 -> 1
R_HI = (mp.sqrt(mp.mpf(5) / 4), mp.sqrt(mp.mpf(3) / 2))      # upper branch: eta 1 -> 0


def make_switch(kind, r1, r2, rising):
    """A menu of smooth interpolations, each with eta' = 0 at BOTH ends."""
    span = r2 - r1
    if kind == "IC5 mollifier":
        f = lambda r: eta_jets(r)[0]
    else:
        def shape(t):
            t = min(max(t, mp.mpf(0)), mp.mpf(1))
            if kind == "smoothstep":
                return 3 * t ** 2 - 2 * t ** 3
            if kind == "smootherstep":
                return 6 * t ** 5 - 15 * t ** 4 + 10 * t ** 3
            if kind == "raised cosine":
                return (1 - mp.cos(mp.pi * t)) / 2
            if kind == "skewed (t^3 warp)":
                s = t ** 3
                return 3 * s ** 2 - 2 * s ** 3
            if kind == "wiggly":
                return (6 * t ** 5 - 15 * t ** 4 + 10 * t ** 3) + mp.mpf("0.3") * mp.sin(4 * mp.pi * t) * (t * (1 - t)) ** 2
            if kind == "two-stage":                   # deliberately flat in the middle
                return (6 * t ** 5 - 15 * t ** 4 + 10 * t ** 3) if t > mp.mpf("0.5") else \
                       mp.mpf("0.5") * (6 * (2 * t) ** 5 - 15 * (2 * t) ** 4 + 10 * (2 * t) ** 3) / 1
            raise ValueError(kind)
        f = lambda r: shape((r - r1) / span) if rising else 1 - shape((r - r1) / span)
    if kind == "IC5 mollifier":
        return lambda r: eta_jets(r)
    return lambda r: (f(r), mp.diff(f, r), mp.diff(f, r, 2))


def aUV_of(r, E, G, B, sw):
    e, e1, e2 = sw(r)
    return -(E * G * r / 3) * e1 - (E * G * r ** 2 / 12 + B * E ** 2 / 36) * e2


def b_of(r, E, G, B):
    return E * (G * r ** 2 + B * E / 3) / 12


bgc = STATES[220]
Ec, Gc = bgc["E"], bgc["G"]
print(f"  fixing the background scalars at IC12's own n = 220 sample:  E = {mp.nstr(Ec, 10)}, "
      f"G = 1/J - 1 = {mp.nstr(Gc, 10)}  (B is then a FREE positive function of the pressure)")

# T1 -- the weighted-integral identity, numerically
worst_int = mp.mpf(0)
for kind in ("IC5 mollifier", "smootherstep", "wiggly"):
    for (r1, r2), rising in ((R_HI, False), (R_LO, True)):
        sw = make_switch(kind, r1, r2, rising)
        for Bv in (mp.mpf(0), mp.mpf("1e-3"), mp.mpf(1)):
            I = mp.quad(lambda r: b_of(r, Ec, Gc, Bv) * aUV_of(r, Ec, Gc, Bv, sw), [r1, (r1 + r2) / 2, r2])
            sc = mp.quad(lambda r: abs(b_of(r, Ec, Gc, Bv) * aUV_of(r, Ec, Gc, Bv, sw)), [r1, (r1 + r2) / 2, r2])
            worst_int = max(worst_int, abs(I) / max(sc, mp.mpf("1e-60")))
print(f"  weighted integral  int_r1^r2 b(r) a_UV(r) dr  vanishes to a relative {mp.nstr(worst_int, 6)} "
      f"over 18 switch x pressure combinations")
check("T1 [theorem] the b-weighted integral of a_UV over ANY complete transition is exactly zero -- so where b has one "
      "sign, a_UV cannot",
      worst_int < mp.mpf("1e-20"), "the boundary term is -[b^2 eta'], and eta' vanishes at both ends by construction")

# T2 -- the inflection identity: pressure-independent
def inflection(sw, r1, r2):
    """Bracketed bisection for an interior eta'' = 0 with eta' != 0 there."""
    grid = [r1 + (r2 - r1) * mp.mpf(i) / 300 for i in range(1, 300)]
    vals = [sw(x)[2] for x in grid]
    best = None
    for i in range(len(grid) - 1):
        if vals[i] == 0 or vals[i] * vals[i + 1] < 0:
            lo, hi = grid[i], grid[i + 1]
            for _ in range(200):
                mid = (lo + hi) / 2
                if sw(lo)[2] * sw(mid)[2] <= 0:
                    hi = mid
                else:
                    lo = mid
            rr = (lo + hi) / 2
            if best is None or abs(sw(rr)[1]) > abs(sw(best)[1]):
                best = rr
    return best


print("\n  the pressure-independent point: wherever eta'' = 0, a_UV = -(E G r/3) eta' with NO B in it")
print(f"    {'switch':>22s} {'branch':>8s} {'sign G':>7s} {'r* (eta2=0)':>14s} {'eta1(r*)':>14s} "
      f"{'a_UV(r*), B=0':>16s} {'a_UV(r*), B=1e6':>17s}")
t2ok = True
t2neg = {mp.mpf(1): 0, mp.mpf(-1): 0}
for kind in ("IC5 mollifier", "smootherstep", "raised cosine"):
    for (r1, r2), rising, lab in ((R_HI, False, "upper"), (R_LO, True, "lower")):
        sw = make_switch(kind, r1, r2, rising)
        rstar = inflection(sw, r1, r2)
        if rstar is None:
            print(f"    {kind:>22s} {lab:>8s}  no interior eta'' = 0 found")
            t2ok = False
            continue
        e1 = sw(rstar)[1]
        for sgn in (mp.mpf(1), mp.mpf(-1)):
            Gs = sgn * abs(Gc)
            v0 = aUV_of(rstar, Ec, Gs, mp.mpf(0), sw)
            v1 = aUV_of(rstar, Ec, Gs, mp.mpf("1e6"), sw)
            print(f"    {kind:>22s} {lab:>8s} {('+' if sgn > 0 else '-'):>7s} {mp.nstr(rstar, 8):>14s} "
                  f"{mp.nstr(e1, 6):>14s} {mp.nstr(v0, 6):>16s} {mp.nstr(v1, 6):>17s}")
            t2ok &= abs(v1 - v0) < mp.mpf("1e-12") * max(abs(v0), mp.mpf(1))
            t2ok &= rel(v0, -(Ec * Gs * rstar / 3) * e1) < mp.mpf("1e-12")
            if v0 < 0:
                t2neg[sgn] += 1
print(f"    for EACH sign of G at least one branch has a pressure-blind NEGATIVE inflection value "
      f"(G > 0: {t2neg[mp.mpf(1)]} of 3 switches on the lower branch; G < 0: {t2neg[mp.mpf(-1)]} of 3 on the upper)")
check("T2 [theorem] at the switch's inflection point a_UV is INDEPENDENT of the pressure (B multiplies eta'' = 0): its "
      "sign is fixed by sign(G eta') alone, so for EITHER sign of G one of the two branches is negative there",
      t2ok and t2neg[mp.mpf(1)] >= 3 and t2neg[mp.mpf(-1)] >= 3,
      "raising B by 1e6 leaves a_UV(r*) unchanged to 12 digits; G > 0 kills the rising branch, G < 0 the falling one")

# T3 -- generic sweep
print("\n  the sweep: 7 switches x 9 pressures (both signs, 12 decades, and the b-zero-tuned value)")
B_zero_tuned = -3 * Gc * ((R_HI[0] + R_HI[1]) / 2) ** 2 / Ec     # makes b vanish inside the upper branch
B_MENU = [mp.mpf(0), STATES[220]["B"], mp.mpf("1e-4"), mp.mpf("1e-2"), B_zero_tuned, mp.mpf(1), mp.mpf("1e3"),
          mp.mpf("1e6"), -mp.mpf("1e-2")]
SW_MENU = ["IC5 mollifier", "smoothstep", "smootherstep", "raised cosine", "skewed (t^3 warp)", "wiggly", "two-stage"]
worst_min = -mp.inf
n_combo = n_ghost = 0
for kind in SW_MENU:
    for (r1, r2), rising, lab in ((R_HI, False, "upper"), (R_LO, True, "lower")):
        sw = make_switch(kind, r1, r2, rising)
        grid = [r1 + (r2 - r1) * mp.mpf(i) / 400 for i in range(1, 400)]
        for Bv in B_MENU:
            vals = [aUV_of(rr, Ec, Gc, Bv, sw) for rr in grid]
            mn = min(vals)
            n_combo += 1
            n_ghost += 1 if mn < 0 else 0
            worst_min = max(worst_min, mn)
print(f"    {n_ghost}/{n_combo} switch x pressure combinations have a_UV < 0 somewhere in the transition; "
      f"the LEAST negative minimum over all of them is {mp.nstr(worst_min, 6)}")
check("T3 [theorem] the ghost is generic: every one of the 126 switch x pressure combinations tested has a_UV < 0 "
      "somewhere inside the transition",
      n_ghost == n_combo and worst_min < 0, "including B = 0, B tuned so that b changes sign, B = 1e6 and B < 0")

# T4 -- can ANY pressure function cure the full transition?  Adversarially optimal B(r).
print("\n  the adversarial test: let B(r) be a FREE function of r, chosen pointwise to maximise a_UV -- more freedom")
print("  than any f(X) has, since B = e^S f(S) is one function of the SAME background scalars that fix E and G")
t4rows = []
for kind in ("IC5 mollifier", "smootherstep", "raised cosine", "wiggly"):
    for (r1, r2), rising, lab in ((R_HI, False, "upper"), (R_LO, True, "lower")):
        sw = make_switch(kind, r1, r2, rising)
        rstar = inflection(sw, r1, r2)
        for sgn in (mp.mpf(1), mp.mpf(-1)):
            Gs = sgn * abs(Gc)
            v = aUV_of(rstar, Ec, Gs, mp.mpf("1e9"), sw) if rstar is not None else None
            t4rows.append((kind, lab, float(sgn), v))
by_sign = {}
for kind, lab, sgn, v in t4rows:
    by_sign.setdefault((kind, sgn), []).append(v)
killed = sum(1 for k, vals in by_sign.items() if any(v is not None and v < 0 for v in vals))
print(f"    for every (switch, sign of G) pair tested, at least one branch is negative at the pressure-blind point:"
      f" {killed} of {len(by_sign)} pairs")
check("T4 [theorem] NO pressure function cures the full transition: for either sign of G one branch is negative at the "
      "pressure-blind inflection point, and on any branch the weighted-integral identity independently forbids a "
      "one-signed a_UV",
      killed == len(by_sign),
      f"{killed}/{len(by_sign)} (switch, sign G) pairs are killed at a point where B cannot act at all")

print("""
  THE THEOREM, hypotheses stated exactly.
    Setting.  h = h_base + eta(r)[delta_10 - B] with h_base = -E rho^2/3 + (rho-independent), delta_10 =
      -E rho^2 G/3, r = -rho E/3, and the trace kinetic factor A = 1 + eta G.  E > 0 and G, B depend only on
      (xi, u) -- NOT on rho -- for any pressure of the form f(Xtilde), since Xtilde is fixed by (xi, u).  The
      reduced scalar UV kinetic coefficient is a_UV = E A/6 + h,rhorho/4.
    Lemma (S1, S2, derived not assumed).  a_UV = -(1/b) d/dr[b(r)^2 eta'(r)],  b = E(G r^2 + B E/3)/12.
    THEOREM.  Fix (xi, u) with G != 0.  Let eta be C^2 and non-constant on a transition interval [r1, r2] with
      eta'(r1) = eta'(r2) = 0.  Then a_UV < 0 on a subset of positive measure of (r1, r2), for EVERY B in R.
    Proof.  b is a quadratic in r with at most one positive root r0.  Put beta = r0 if r0 lies in (r1, r2),
      else beta = r2.  On (r1, beta) b has one strict sign, and integrating the Lemma against the weight b,
      int_{r1}^{beta} b a_UV dr = -[b^2 eta']_{r1}^{beta} = 0, because eta'(r1) = 0 and either b(beta) = 0 or
      eta'(r2) = 0.  If a_UV >= 0 there, then b a_UV has one sign and integrates to zero, so a_UV = 0 on
      (r1, beta), hence b^2 eta' is constant = its value 0 at r1, hence eta is constant there; repeating on
      (beta, r2) (where eta'(beta) = 0 by continuity) makes eta constant on all of [r1, r2].  Contradiction. []
    COROLLARY (pressure-blind).  At any interior r* with eta''(r*) = 0 -- one exists, since eta' vanishes at
      both ends and not in between -- a_UV(r*) = -(E G r*/3) eta'(r*), which contains no B at all.  The IC5
      switch has a RISING branch (r^2 in (1/2, 3/4)) and a FALLING branch (r^2 in (5/4, 3/2)) with opposite
      sign(eta'), while sign(G) is a single number at fixed (xi, u); so one of the two branches is ghostly
      whatever f is chosen.
    ALONG A TRAJECTORY, where E, G, B vary with r, the same conclusion follows with the weight
      mu = exp(int a/b)/b, since mu b = exp(int a/b) > 0 kills the boundary term and sign(mu) = sign(b); the
      extra hypothesis needed is that b does not vanish on an open subinterval.  R2b tests exactly this case
      numerically, on the model's own solved trajectories.
    WHAT IS NOT CLAIMED.  Nothing about Hamiltonian redesigns that break the Lemma's setting -- in particular
      a correction whose second rho-derivative does NOT cancel the E A/6 term, so that the plateaus stop being
      marginal.  That is the door this lane leaves open, and it is where IC13/IC14 should push.""")

# ----------------------------------------------------------------------------------------------------
# PART 4.  THE SLIVER -- what a pressure CAN do, and whether an explicit f achieves it.
# ----------------------------------------------------------------------------------------------------
print("\nPART 4 -- what a pressure CAN do: the sliver the lead's run actually samples\n" + "-" * 122)
print("  Near the eta = 1 edge, eta' and eta'' are both exponentially small but eta'' dominates (the mollifier leaves")
print("  the plateau with zero slope), so a_UV -> -b eta'' and sign(a_UV) = sign(b).  The lead's 501 samples never")
print("  leave that sliver (eta stays above 0.9957).  There the curing condition is one inequality, b > 0, i.e.")
print("        G r^2 + B E/3 > 0,      G = 1/J - 1 = e^{2w+1/6} - 1,   B = e^S f(S),")
print("  and it can be met in TWO ways, which is the practical content of this lane:")
print("    ROUTE A (background, free):  G > 0  <=>  2w + 1/6 > 0  <=>  (1-u) xi < 1/12.  No pressure needed at all.")
print("    ROUTE B (pressure, costly):  where G < 0,  e^S f(S) > 3 |G| r^2 / E.")
need = [(b_["step"], 3 * abs(b_["G"]) * b_["r"] ** 2 / b_["E"], b_["B"]) for b_ in STATES[1:] if b_["G"] < 0]
thr_max = max(x[1] for x in need)
have = need[-1][2]
print(f"    IC12's run takes NEITHER: its (1-u) xi crosses 1/12 at n = {first_neg}, and from there Route B would need")
print(f"    B between {mp.nstr(min(x[1] for x in need), 6)} and {mp.nstr(thr_max, 6)} while its f supplies "
      f"{mp.nstr(have, 6)} -- short by {mp.nstr(thr_max/have, 6)}x.")
sign_ok = all((b_["b"] > 0) == (b_["aUV"] > 0) for b_ in STATES[1:] if abs(b_["aUV"]) > mp.mpf("1e-12"))
check("R1 [cure] in the sampled sliver the sign of a_UV is exactly the sign of b, so the curing condition is the "
      "explicit inequality  G r^2 + e^S f(S) E/3 > 0",
      sign_ok, f"holds at every sample; on Route B, IC12's f falls short by {mp.nstr(thr_max/have, 4)}x")

wfac = lambda b_: (1 - b_["point"][2]) * b_["point"][1]
n_cross = next(b["step"] for b in STATES if wfac(b) > mp.mpf(1) / 12)
gap = abs(wfac(STATES[n_cross]) - mp.mpf(1) / 12)
print(f"    the geometric form of Route A, checked: (1-u) xi = 1/12 exactly where the ghost starts -- at n = "
      f"{n_cross - 1} it is {mp.nstr(wfac(STATES[n_cross-1]), 12)}, at n = {n_cross} it is "
      f"{mp.nstr(wfac(STATES[n_cross]), 12)}, and 1/12 = {mp.nstr(mp.mpf(1)/12, 12)}")
check("R1b [cure] the ghost onset in IC12's own run is EXACTLY the crossing of the geometric condition "
      "(1-u) xi = 1/12, not anything about its pressure",
      n_cross == first_neg and gap < mp.mpf("1e-4"),
      f"the a_UV sign change (n = {first_neg}) and the (1-u)xi = 1/12 crossing (n = {n_cross}) are the same step")

print("\n  R2: exhibit an explicit f that MEETS the inequality, re-solve the roots with it, and re-run the test.")
print("  Each candidate f gets its OWN admissible plateau window (IC11 chose S = .2 for its own f by exactly this")
print("  predicate: 3/4 <= r^2 <= 5/4 with PX > 0, Q_clock > 0, 0 < cs^2 <= 1, rho > 0, H_physical > 0), so no")
print("  candidate is judged on IC11's window.  The continuation then starts at the middle of that window.")
ZERO = mp.mpf("1e-25")


def plateau_window(a, n, dps=30):
    """The admissible eta = 1 plateau interval in S for f = a (2X)^n, by IC11's own predicate."""
    old = mp.mp.dps
    mp.mp.dps = dps
    good = []
    try:
        for i in range(1, 121):
            S = mp.mpf(i) / 200                                    # S in .005 .. .6
            try:
                stt = plateau_state(S, a, n)
            except Exception:
                continue
            if stt["admissible"]:
                good.append(S)
    finally:
        mp.mp.dps = old
    return good


def run_family(a, n, S0, steps=800, dps=40):
    """Continuation from an admissible plateau point for f = a (2X)^n, drho = .001 as IC12 uses."""
    old = mp.mp.dps
    mp.mp.dps = dps
    try:
        stt = plateau_state(S0, a, n)
        r0 = -3 * mp.exp(-mp.mpf(1) / 6) * stt["H"]
        sd = [stt["S"] + stt["w"], stt["u"]]
        tr = []                                     # transition samples only (0 < eta < 1)
        mn_b, mn_G, ghost_at, last, note = mp.inf, mp.inf, None, mp.mpf(0), ""
        for k in range(steps):
            try:
                bg = newton_root(r0 + mp.mpf(k) / 1000, sd, a, n, tol=mp.mpf(10) ** -30, itmax=80)
            except Exception:
                note = f"root lost at drho = {k/1000:.3f}"
                break
            sd = [bg["point"][1], bg["point"][2]]
            last = mp.mpf(k) / 1000
            mn_b, mn_G = min(mn_b, bg["b"]), min(mn_G, bg["G"])
            if 0 < bg["eta"] < 1:
                tr.append((last, bg))
                if bg["aUV"] < -ZERO and ghost_at is None:
                    ghost_at = (float(last), bg["eta"])
        mn_a = min((b["aUV"] for _, b in tr), default=mp.inf)
        mn_e = min((b["eta"] for _, b in tr), default=mp.mpf(1))
        n_neg = sum(1 for _, b in tr if b["aUV"] < -ZERO)
        return dict(note=note, mn_a=mn_a, mn_b=mn_b, mn_e=mn_e, mn_G=mn_G, ghost_at=ghost_at, reach=last,
                    n_tr=len(tr), n_neg=n_neg)
    finally:
        mp.mp.dps = old


R2_TRIED = [(A_IC12, N_IC12), (mp.mpf(1), N_IC12), (mp.mpf("5e-2"), mp.mpf(4)), (mp.mpf("3e-1"), mp.mpf(4)),
            (mp.mpf("2e-1"), mp.mpf(2)), (mp.mpf("1e-1"), mp.mpf("1.5")), (mp.mpf("3e-1"), mp.mpf("1.05")),
            (mp.mpf("1e-1"), mp.mpf("0.25")), (mp.mpf(1), mp.mpf("0.25"))]
print(f"    {'f = a (2X)^n':>18s} {'admissible S':>16s} {'start':>7s} {'min b':>11s} {'min G':>11s} "
      f"{'eta reached':>13s} {'min a_UV':>12s} {'ghosty':>8s} {'ends':>22s}")
R2_RES = []
for a, n in R2_TRIED:
    win = plateau_window(a, n)
    lab = f"{mp.nstr(a, 4)} (2X)^{mp.nstr(n, 4)}"
    if not win:
        print(f"    {lab:>18s} {'NONE':>16s}   (no admissible eta = 1 plateau for this f)")
        R2_RES.append((a, n, None, None))
        continue
    S0 = win[len(win) // 2]
    res = run_family(a, n, S0)
    R2_RES.append((a, n, win, res))
    fmt = lambda k: (mp.nstr(res[k], 6) if res.get(k) not in (None, mp.inf) else "-")
    ends = res["note"] if res["note"] else "ran to drho = {:.3f}".format(float(res["reach"]))
    counts = "{}/{}".format(res["n_neg"], res["n_tr"])
    print(f"    {lab:>18s} {('[' + mp.nstr(win[0], 3) + ',' + mp.nstr(win[-1], 3) + ']'):>16s} {mp.nstr(S0, 4):>7s} "
          f"{fmt('mn_b'):>11s} {fmt('mn_G'):>11s} {fmt('mn_e'):>13s} {fmt('mn_a'):>12s} "
          f"{counts:>8s} {ends:>22s}")
n_tr_ic12 = len(TRANS)
n_neg_ic12 = sum(1 for b in TRANS if b["aUV"] < -ZERO)
cured = [(a, n, r) for a, n, w, r in R2_RES if r is not None and r["n_neg"] == 0 and r["n_tr"] > 50]
print(f"    apples to apples: IC12's own f is ghostly at {n_neg_ic12} of its {n_tr_ic12} transition samples "
      f"(healthy for the first {n_tr_ic12 - n_neg_ic12}); the convex families above with min b > 0 are ghostly at NONE")
print("    of theirs -- but each of those continuations ENDS IN A FOLD (the Newton iterate leaves the real chart),")
print("    the same kind of termination L20 found on IC10's backward branch.  A lost root is not a proof that no root")
print("    exists, exactly as IC12 says of its own solver.  And note WHICH route they take: all three have min G > 0,")
print("    so they satisfy b > 0 on Route A (the background never crosses (1-u)xi = 1/12) and the pressure's own")
print("    B E/3 is the minor term.  The pressure earns its place by MOVING THE TRAJECTORY, not by outweighing G.")
check("R2 [cure] an EXPLICIT admissible f exists whose continuation keeps a_UV > 0 at EVERY transition sample it "
      "solves, where IC12's own f goes negative after 125 of them",
      len(cured) > 0,
      ("; ".join(f"f = {mp.nstr(a,4)}(2X)^{mp.nstr(n,4)}: {r['n_tr']} transition samples, 0 ghostly, min a_UV = "
                 f"{mp.nstr(r['mn_a'],4)} > 0, min b = {mp.nstr(r['mn_b'],4)} > 0" for a, n, r in cured))
      if cured else f"none of the {len(R2_TRIED)} tried families keeps a_UV > 0 through the transition it reaches")

deep = [(a, n, r) for a, n, w, r in R2_RES if r is not None and r["mn_e"] < mp.mpf("1e-2")]
print("\n  R2b: the tried pressures whose solution goes DEEP into the transition (eta down to 1e-2 or below) -- and what")
print("  happens to them, which is the theorem's prediction tested inside the model rather than on a menu")
for a, n, r in deep:
    print(f"    f = {mp.nstr(a,4)}(2X)^{mp.nstr(n,4)}: {r['n_tr']} transition samples down to eta = "
          f"{mp.nstr(r['mn_e'], 6)}; a_UV POSITIVE at first, NEGATIVE at {r['n_neg']} of them, first at eta = "
          f"{mp.nstr(r['ghost_at'][1], 6)}, minimum {mp.nstr(r['mn_a'], 6)}")
check("R2b [cure] the theorem is realised inside the model itself: EVERY tried pressure whose solution goes deep "
      "into the transition is healthy at first and ghostly later, as the b-weighted integral identity requires",
      len(deep) > 0 and all(r["n_neg"] > 0 and r["mn_a"] < -ZERO for _, _, r in deep),
      "; ".join(f"{r['n_neg']}/{r['n_tr']} negative, min a_UV = {mp.nstr(r['mn_a'], 4)}" for _, _, r in deep))

print("\n  R3: the structural reason the two requirements pull apart.  With f = a (2X)^n and X = e^{-2S}/2,")
print("      B = e^S f = a e^{(1-2n)S}.  IC11 needs n > 1 for the convex pressure to fix the plateau cone; but S")
print("      GROWS along the transition, so B DECAYS by e^{(1-2n) dS} exactly where the inequality needs it to grow.")
S_start, S_end = STATES[0]["S"], STATES[500]["S"]
dS = S_end - S_start
print(f"    S runs {mp.nstr(S_start, 8)} -> {mp.nstr(S_end, 8)} over the continuation (dS = {mp.nstr(dS, 6)}), so")
print(f"    {'n':>8s} {'B(end)/B(start)':>18s} {'convex plateau (n>1)?':>24s}")
r3rows = []
for n in ("16", "4", "2", "1.05", "0.5", "0.25"):
    nn = mp.mpf(n)
    ratio = mp.exp((1 - 2 * nn) * dS)
    r3rows.append((nn, ratio))
    print(f"    {n:>8s} {mp.nstr(ratio, 8):>18s} {('yes' if nn > 1 else 'NO'):>24s}")
tension = all(ratio < 1 for nn, ratio in r3rows if nn > mp.mpf("0.5"))
check("R3 [cure] the convexity requirement (n > 1) and the curing inequality pull in opposite directions: every n > 1/2 "
      "makes B DECAY through the transition, while the threshold 3|G|r^2/E rises",
      tension, "B(end)/B(start) = e^{(1-2n)dS} < 1 for every n > 1/2; only a CONCAVE pressure (n < 1/2) grows")

# ----------------------------------------------------------------------------------------------------
# PART 5.  PRICING -- where is the ghost region physically, and how fast does it grow?
# ----------------------------------------------------------------------------------------------------
print("\nPART 5 -- pricing the ghost: where it is for a real Solar System and a real galaxy, and its rate\n" + "-" * 122)
print("  r = -N p/(3 m h0) is the trace of the METRIC MOMENTUM in units of h0 -- the local expansion trace, not a")
print("  radius.  eta = 1 for r^2 in [3/4, 5/4] (cosmological), eta = 0 for r^2 <= 1/2 and r^2 >= 3/2 (static).  So:")
print("    * a STATIC system has p = 0 identically, hence r = 0, hence eta = 0 on a whole neighbourhood, with every")
print("      first jet vanishing (IC5's static plateau).  The Solar System and a virialised disc carry NO ghost.")
print("    * the ghost region is where the local expansion trace passes between 0.707 and 0.866 of its cosmological")
print("      value: the boundary between the Hubble flow and the collapsed region -- the TURNAROUND shell.")
e_stat, e1_stat, e2_stat = eta_jets(mp.mpf(0))
check("P1 [physics] the Solar System and the galactic disc are exactly ghost-free: p = 0 gives r = 0 and eta = 0 with "
      "all jets vanishing, so a_UV = 0 there and the static sector is untouched",
      e_stat == 0 and e1_stat == 0 and e2_stat == 0,
      "the ghost cannot be placed in the disc; it is a shell at the edge of the collapsed region")

# spherical-infall localisation of the shell (stated assumptions)
H0_SI = 0.674 * 100e3 / 3.0857e22
Om = 0.315
Gnewt = 6.674e-11
MSUN = 1.989e30
Mpc = 3.0857e22
rho_c = 3 * H0_SI ** 2 / (8 * math.pi * Gnewt)
rho_m = Om * rho_c
fgrow = Om ** 0.55
print(f"\n  spherical infall, stated: theta/(3H) = 1 - f delta/3 with f = Om^0.55 = {fgrow:.3f}; delta(<r) from the")
print(f"  enclosed mass.  rho_m = {rho_m:.3e} kg/m^3 (H0 = 67.4, Om = 0.315).  Both a0 footings enter only through")
print(f"  the h0 calibration below -- the shell location is a RATIO statement and is footing-independent.")
print(f"    {'system':>22s} {'M (Msun)':>12s} {'outer edge (Mpc)':>18s} {'inner edge (Mpc)':>18s} {'thickness (Mpc)':>17s}")
SHELL = {}
for label, Mm in (("Solar System (static)", 1.0), ("Milky Way", 1.5e12), ("galaxy cluster", 1.0e15)):
    if Mm < 1e6:
        print(f"    {label:>22s} {'-':>12s} {'no shell: p = 0, eta = 0 identically':>55s}")
        continue
    edges = []
    for ratio in (mp.mpf(0.866025403784), mp.mpf(0.707106781187)):
        delta = 3 * (1 - float(ratio)) / fgrow
        rr = (Mm * MSUN / ((4 * math.pi / 3) * rho_m * (1 + delta))) ** (1 / 3) / Mpc
        edges.append(rr)
    SHELL[label] = edges
    print(f"    {label:>22s} {Mm:>12.2e} {edges[0]:>18.3f} {edges[1]:>18.3f} {edges[0]-edges[1]:>17.3f}")
mw = SHELL["Milky Way"]
check("P2 [physics] the ghost shell of a real galaxy sits at the turnaround scale, NOT in the disc: "
      f"{mw[1]:.2f}-{mw[0]:.2f} Mpc for the Milky Way ({mw[0]-mw[1]:.2f} Mpc thick), "
      f"{SHELL['galaxy cluster'][1]:.1f}-{SHELL['galaxy cluster'][0]:.1f} Mpc for a cluster",
      mw[1] > 0.1 and mw[0] < 10, "spherical-infall estimate with the assumptions printed above; "
      "every bound system carries one such shell")

lam = (mw[0] - mw[1]) * Mpc
c_light = 2.99792458e8
Gamma_slow = 2 * math.pi * c_light / lam
print(f"\n  rate.  a_UV < 0 is a WRONG-SIGN KINETIC coefficient, so the growth rate is not bounded by the background:")
print(f"  omega^2 = -(gradient/|a_UV|) k^2 gives Gamma = c_eff k, growing linearly in k up to the EFT cutoff.")
print(f"  Taking c_eff ~ c (the reduced scalar's gradient coefficient is O(1) in the same units), the SLOWEST mode")
print(f"  that fits in the Milky Way's shell (lambda = {(mw[0]-mw[1]):.2f} Mpc) already grows at")
print(f"  Gamma = {Gamma_slow:.3e} s^-1, an e-folding time of {1/Gamma_slow/3.156e7:.3e} yr = {1/Gamma_slow/3.156e7/1e6:.4f} Myr;")
print(f"  every shorter mode is faster without bound.  |a_UV| itself reaches {mp.nstr(abs(STATES[500]['aUV']), 6)} in")
print(f"  units of the model's own h0^2 by the end of the lead's run -- an O(1) wrong-sign coefficient, not a whisker.")
print(f"  EXTERNAL BENCHMARK, not computed here: a Lorentz-violating ghost coupled to gravity decays the vacuum into")
print(f"  ghost + ordinary pairs; the diffuse gamma-ray background forces its cutoff below ~3 MeV (Cline, Jeon &")
print(f"  Moore 2004).  That is the standard price of a ghost in a finite region, and it is not softened by the")
print(f"  region being finite: the shell is spatially extended and permanent.")
check("P3 [physics] the ghost is not benign in its shell: the slowest mode that fits grows in "
      f"{1/Gamma_slow/3.156e7/1e6:.3f} Myr, and the rate is UNBOUNDED in k (cut off only by the EFT cutoff)",
      Gamma_slow > 0 and 1 / Gamma_slow / 3.156e7 < 1e8,
      "a negative kinetic coefficient is a UV problem; a finite region does not regulate it")

# a0 calibration, both footings
print("\n  a0 calibration of the model's own rate unit h0 (both footings), stated conversions:")
print("    the model fixes a0^2 = 27 e^{-1/2}/(8 ell^2) and Lambda = 6 e^{-1/2} - a0^2 U(4/9) in units m = h0 = 1,")
print("    kappa = 6 h0^2.  a0 is a RATE there (it sits beside Lambda), so a0_phys = c * a0_model * h0 and")
print("    3 H_Lambda^2 = Lambda gives H_Lambda = sqrt(Lambda/3) h0.  Hence a0_phys/(c H_Lambda) is a pure number")
print("    the model PREDICTS, independent of h0.")
a0_model = mp.sqrt(mp.mpf(str(sp.N(a02, 40))))
Lam_model = mp.mpf(str(sp.N(Lam, 40)))
HL_model = mp.sqrt(Lam_model / 3)
ratio_model = a0_model / HL_model
H_L_phys = 2.184e-18 * math.sqrt(1 - Om)
print(f"    {'footing':>28s} {'a0 (m/s^2)':>14s} {'h0 (s^-1)':>14s} {'h0/H0':>10s} {'a0/(c H_Lambda) obs':>22s} "
      f"{'model':>10s} {'ratio':>9s}")
foot_rows = []
for lab, a0v in (("canonical 9.3619e-11", 9.3619e-11), ("alternative 1.1279e-10", 1.1279e-10)):
    h0_phys = a0v / (c_light * float(ratio_model) * float(HL_model)) * float(HL_model)
    h0_phys = a0v / (c_light * float(a0_model))
    obs_ratio = a0v / (c_light * H_L_phys)
    foot_rows.append((lab, a0v, h0_phys, obs_ratio))
    print(f"    {lab:>28s} {a0v:>14.4e} {h0_phys:>14.4e} {h0_phys/2.184e-18:>10.4f} {obs_ratio:>22.4f} "
          f"{float(ratio_model):>10.4f} {float(ratio_model)/obs_ratio:>9.2f}")
mism = [float(ratio_model) / r[3] for r in foot_rows]
check("P4 [physics] the model's own a0-Lambda proportionality is off the observed value by 10-13x on BOTH footings, so "
      "its 'r ~ 1' plateau cannot be identified with today's expansion without that factor",
      all(m > 1 for m in mism), f"model a0/(c H_Lambda) = {float(ratio_model):.3f} vs observed "
      f"{foot_rows[0][3]:.3f} / {foot_rows[1][3]:.3f}  ->  {mism[0]:.1f}x / {mism[1]:.1f}x; IC10 already flags the "
      "a0-Lambda proportionality as INPUT, and this is its size")

# how much of the run is ghostly
lnV = mp.mpf(0)
wtot = mp.mpf(0)
efolds_ghost = None
for i in range(1, len(STATES)):
    p, q = STATES[i - 1], STATES[i]
    drho = q["point"][0] - p["point"][0]
    lnV += drho * (p["logVdot"] / p["rhodot"] + q["logVdot"] / q["rhodot"]) / 2
    wp = (p["point"][2] - 1) * p["point"][1]
    wq = (q["point"][2] - 1) * q["point"][1]
    if q["step"] == first_neg:
        efolds_ghost = (lnV, wq - (STATES[0]["point"][2] - 1) * STATES[0]["point"][1])
lnV_end = lnV
w_end = (STATES[-1]["point"][2] - 1) * STATES[-1]["point"][1]
w_start = (STATES[0]["point"][2] - 1) * STATES[0]["point"][1]
print(f"\n  duration: the lead's run spans {mp.nstr(lnV_end/3, 8)} barred e-folds "
      f"({mp.nstr(lnV_end/3 + w_end - w_start, 8)} physical); the ghost starts at "
      f"{mp.nstr(efolds_ghost[0]/3, 8)} barred e-folds in and the run ENDS still inside it, with eta only down to "
      f"{mp.nstr(STATES[-1]['eta'], 10)}.")

# ----------------------------------------------------------------------------------------------------
# PART 6.  VERDICT
# ----------------------------------------------------------------------------------------------------
print("\nPART 6 -- verdict\n" + "-" * 122)
generic = (sp.simplify(diff_S1) == 0 and sp.simplify(diff_S2) == 0 and n_ghost == n_combo and t2ok
           and worst_int < mp.mpf("1e-20"))
check("V1 [verdict] the transition ghost is GENERIC to switch-based constructions -- it follows from the switch's "
      "derivatives and the exact marginality of both plateaus, and NO pressure function removes it",
      generic, "a_UV = -(1/b)(b^2 eta')' with b^2 eta' vanishing at both ends; plus the pressure-blind inflection point")

print("\n" + LINE)
print("  Polarity, stated so the summary line cannot be misread: each check asserts a STATEMENT, and PASS means the")
print("  statement is true.  V1 passing is a NEGATIVE result for the construction, and C1-C6 passing means the lead's")
print("  own negative reproduces.  R2 passing is the one positive outcome in this lane.")
print(f"L35: {len(FAILS)} FAIL(S)" if FAILS else "L35: ALL CHECKS PASS")
for n_ in FAILS:
    print(f"    FAIL: {n_.split(':')[0]}")
cl = SHELL["galaxy cluster"]
print(f"""
  THREE SENTENCES.  IC12's transition failure reproduces exactly on an independent rebuild -- eta, physical H, a_UV,
  the first negative step n = 207 and max eig M all to the digits it quotes -- and it is not a property of its
  pressure: because both plateaus are exactly MARGINAL in this reduction, the entire scalar UV kinetic coefficient is
  a_UV = -(1/b) d/dr[b(r)^2 eta'(r)] with b = E(G r^2 + B E/3)/12, b^2 eta' vanishes at BOTH ends of any smooth
  interpolation, and at the switch's inflection point a_UV = -(E G r/3) eta' contains no pressure at all -- so no
  f cures the full transition, and the ghost is GENERIC.  The pressure does have real power in the sliver the lead's
  run samples, where the condition is the explicit inequality e^S f(S) > 3 |G| r^2/E, and an explicit admissible
  f = 0.05 (2X)^4 meets it and keeps a_UV > 0 at every transition sample its continuation solves, where IC12's own f
  turns negative after 125 -- that is the usable handout to IC13/IC14, but it is a deferral, confirmed by every tried
  pressure whose solution goes deep into the transition: each is healthy at first and ghostly later, as the
  identity demands.
  Priced honestly: the ghost is not in the Solar System or the disc (p = 0 gives eta = 0 with every jet vanishing,
  so the static sector is untouched) but in a turnaround shell around every bound system -- {mw[1]:.2f}-{mw[0]:.2f} Mpc for the
  Milky Way, {cl[1]:.1f}-{cl[0]:.1f} Mpc for a cluster -- where a wrong-sign kinetic coefficient of order unity grows at a rate
  unbounded in k, the slowest mode that fits already e-folding in {1/Gamma_slow/3.156e7/1e6:.2f} Myr.""")
print(LINE)
sys.exit(1 if FAILS else 0)
