#!/usr/bin/env python3
"""
L44 -- does the lead's collar construction escape L35's transition-ghost theorem?
================================================================================
L35 proved (24/24 PASS) that in the IC12 switch-based construction BOTH plateaus are exactly
MARGINAL: the trace-free term E*A/6 cancels the -2*E*A/3 hiding inside h,rhorho/4 identically for
any locally constant switch, so the entire scalar UV kinetic coefficient is generated by the
switch's own derivatives and is an exact total derivative,

    a_UV = -(1/b) d/dr [ b(r)^2 eta'(r) ],   b = E (G r^2 + B E/3)/12,  G = 1/J - 1,

whose b-weighted integral across any complete C^2 transition vanishes -- so a_UV must change sign.
L35 named exactly ONE door out: "a redesign that breaks the cancellation making the plateaus
marginal, leaving a positive coefficient on the plateaus rather than zero."

Overnight the lead advanced IC13 -> IC37 and is now working the activation interface with
"finite multiplier" collars (IC35/IC36/IC37).  THE QUESTION: does the collar escape L35's
theorem, and by which hypothesis?

The four candidate answers, in the order the assignment ranks them:
  (a) the collar is not C^2, so b^2 eta' does not vanish at both ends;
  (b) the "finite multiplier" adds a term surviving on the plateaus (L35's own named door);
  (c) the collar is not a function of the same variable, so the total derivative never forms;
  (d) no escape -- the ghost is merely relocated.

METHOD.  Everything is re-transcribed BY HAND from the lead's markdown (IC4/IC5/IC10/IC11/IC12
for the L35 controls; IC18/IC20/IC28/IC29/IC30/IC35/IC36/IC37 for the collar), re-differentiated
in sympy here, and root-solved by a Newton iteration written here.  Nothing under
closure_2026/integrable_clock_construction_2026/ is imported, executed or modified; the lead's
files are opened read-only for documentary substring checks only.

POLARITY.  Each check asserts a STATEMENT; PASS means the statement is true.  So a PASS on
E1 ("the escape is genuine") is a POSITIVE result for the lead's construction, and a PASS on
V-checks that say "no escape" would be negative.  Both directions are exhibited, not asserted.
"""
import os, sys, math, re
import sympy as sp
import mpmath as mp

FAILS = []
def check(name, ok, detail=""):
    print(f"  [{'PASS' if ok else 'FAIL'}] {name}" + (f"   ({detail})" if detail else ""), flush=True)
    if not ok: FAILS.append(name)

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEAD = os.path.join(REPO, "qwen_claude_field_theory/closure_2026/integrable_clock_construction_2026")
def leadtext(fn):
    with open(os.path.join(LEAD, fn)) as fh: return fh.read()

W = 118
print("=" * W)
print("L44 -- does the lead's collar construction escape L35's transition-ghost theorem?")
print("=" * W, flush=True)

mp.mp.dps = 60

# ============================================================================================
print("\n" + "-" * W)
print("SECTION 0.  L35's hypotheses, stated exactly, from L35_TRANSITION_GHOST.md section 3")
print("-" * W)
HYP = [
 ("H1", "SETTING: h = h_base + eta(r)*[delta_10 - B], i.e. the switch MULTIPLIES a term that "
        "depends on the metric momentum rho."),
 ("H2", "h_base = -E rho^2/3 + (rho-independent)."),
 ("H3", "delta_10 = -E rho^2 G/3 with G = 1/J - 1 INDEPENDENT of rho."),
 ("H4", "r = -rho E/3: the switch's ARGUMENT is proportional to the metric momentum rho."),
 ("H5", "B is rho-independent (true for any pressure f(Xtilde), since Xtilde is fixed by (xi,u))."),
 ("H6", "a_UV = E A/6 + h,rhorho/4 with trace kinetic factor A = 1 + eta G -- i.e. the UV scalar "
        "coefficient is the bare trace-free/trace pair alone, with NO auxiliary field to eliminate."),
 ("H7", "eta is C^2 and non-constant on [r1,r2] with eta'(r1) = eta'(r2) = 0."),
 ("H8", "G != 0 at the fixed (xi,u) -- otherwise the weight b degenerates."),
 ("H9", "along a trajectory: b does not vanish on an open subinterval."),
]
for k, v in HYP: print(f"   {k}. {v}")
print("\n   THEOREM. Under H1-H9, a_UV < 0 on a positive-measure subset of (r1,r2), for EVERY B in R.")
print("   COROLLARY (pressure-blind). At any interior r* with eta''(r*) = 0, a_UV = -(E G r*/3) eta'(r*),")
print("   containing no B at all.")
print("   DOOR LEFT OPEN (L35 section 6, verbatim intent): a redesign whose eta-multiplied correction's")
print("   second rho-derivative does NOT cancel E A/6, leaving a POSITIVE a_UV on the plateaus.")
check("L44-H0  L35's markdown states exactly these nine hypotheses (documentary)",
      all(s in open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                 "L35_TRANSITION_GHOST.md")).read()
          for s in ["`a_UV = -(1/b) d/dr[b(r)^2 eta'(r)]`, `b = E(G r^2 + B E/3)/12`",
                    "eta'(r1) = eta'(r2) = 0",
                    "Fix `(xi, u)` with `G != 0`",
                    "leaving a *positive* `a_UV` on the plateaus",
                    "COROLLARY (pressure-blind)"]),
      "five load-bearing strings located verbatim")

# ============================================================================================
print("\n" + "-" * W)
print("SECTION A.  CONTROL -- rebuild L35's central identity independently in sympy")
print("-" * W)

r, rho, xi, u, cE, cG, cB, etac = sp.symbols("r rho xi u E G B etac", real=True)
feta = sp.Function("eta")

# h written in the switch variable r (rho = -3 r / E), with the rho-independent piece dropped
# (it cannot contribute to h,rhorho or to E*A/6).
h_of_r   = -3 * r**2 / cE + feta(r) * (-3 * r**2 * cG / cE - cB)
h_rhorho = (cE**2 / 9) * sp.diff(h_of_r, r, 2)            # d/drho = (-E/3) d/dr
A_fac    = 1 + feta(r) * cG
aUV      = cE * A_fac / 6 + h_rhorho / 4

closed = (-(cE * cG * r / 3) * sp.diff(feta(r), r)
          - (cE * cG * r**2 / 12 + cB * cE**2 / 36) * sp.diff(feta(r), r, 2))
check("L44-A1  a_UV = -(E G r/3) eta' - (E G r^2/12 + B E^2/36) eta''  (symbolic, arbitrary eta)",
      sp.simplify(sp.expand(aUV - closed)) == 0)

bw = cE * (cG * r**2 + cB * cE / 3) / 12
totder = -sp.diff(bw**2 * sp.diff(feta(r), r), r) / bw
check("L44-A2  a_UV = -(1/b) d/dr[b^2 eta'] with b = E(G r^2 + B E/3)/12   (the total derivative)",
      sp.simplify(sp.expand(aUV - totder)) == 0)

# IC12's own stated identity, transcribed from IC12_COMBINED.md
ic12 = (-cE * cG * (4 * r * sp.diff(feta(r), r) + r**2 * sp.diff(feta(r), r, 2)) / 12
        - cB * cE**2 * sp.diff(feta(r), r, 2) / 36)
check("L44-A3  agrees with IC12's own stated aUV = -E(1/J-1)(4r eta_r + r^2 eta_rr)/12 - B E^2 eta_rr/36",
      sp.simplify(sp.expand(aUV - ic12)) == 0)

h_const   = -3 * r**2 / cE + etac * (-3 * r**2 * cG / cE - cB)
aUV_const = cE * (1 + etac * cG) / 6 + (cE**2 / 9) * sp.diff(h_const, r, 2) / 4
check("L44-A4  MARGINALITY: for ANY locally constant eta the coefficient is identically zero",
      sp.simplify(sp.expand(aUV_const)) == 0,
      "E*A/6 cancels the -2EA/3 inside h,rhorho/4 exactly")

check("L44-A5  the pressure B multiplies ONLY eta'' -- so it drops out wherever eta'' = 0",
      sp.simplify(sp.diff(closed, cB) - (-cE**2 * sp.diff(feta(r), r, 2) / 36)) == 0)

# ============================================================================================
print("\n" + "-" * W)
print("SECTION B.  CONTROL -- reproduce IC12's own transition numbers (independent transcription)")
print("-" * W)

def Ufun(c):
    return (1 - c) * (mp.log(1 - c)**2 - 2 * mp.log(1 - c) + 2) - 2

ELL  = mp.log(mp.mpf(9) / 5)                       # IC4:  ell = ln(9/5)
A02  = 27 * mp.e**(mp.mpf(-1) / 2) / (8 * ELL**2)  # IC4:  a0^2 = 9 kappa e^-1/2 /(16 m ell^2), kappa=6,m=1
LAM  = 6 * mp.e**(mp.mpf(-1) / 2) - A02 * Ufun(mp.mpf(4) / 9)   # IC4: Lambda = kappa e^-1/2/m - a0^2 U(4/9)

def switch(rv):
    """IC5's two-sided mollifier eta(r), plus its first two r-derivatives (analytic)."""
    d  = (rv**2 - 1)**2
    t1 = mp.mpf(1) / 4 - d
    t2 = d - mp.mpf(1) / 16
    if t2 <= 0:  return mp.mpf(1), mp.mpf(0), mp.mpf(0)
    if t1 <= 0:  return mp.mpf(0), mp.mpf(0), mp.mpf(0)
    g  = 1 / t1 - 1 / t2
    e  = 1 / (1 + mp.e**g)
    g1 = 1 / t1**2 + 1 / t2**2
    g2 = 2 / t1**3 - 2 / t2**3
    e1 = -e * (1 - e) * g1                                     # deta/dd
    e2 = e * (1 - e) * (1 - 2 * e) * g1**2 - e * (1 - e) * g2  # d2eta/dd2
    dd1 = 4 * rv * (rv**2 - 1)
    dd2 = 12 * rv**2 - 4
    return e, e1 * dd1, e2 * dd1**2 + e1 * dd2

rv_t = mp.mpf("1.17")
_e, _e1, _e2 = switch(rv_t)
fd1 = mp.diff(lambda x: switch(x)[0], rv_t)
fd2 = mp.diff(lambda x: switch(x)[0], rv_t, 2)
check("L44-B1  analytic eta', eta'' agree with numerical differentiation of eta",
      abs(_e1 - fd1) < mp.mpf("1e-40") and abs(_e2 - fd2) < mp.mpf("1e-35"),
      f"|d1|={mp.nstr(abs(_e1-fd1),3)} |d2|={mp.nstr(abs(_e2-fd2),3)}")
check("L44-B2  eta = 1 for |r^2-1| <= 1/4 and eta = 0 for |r^2-1| >= 1/2 (IC5's design)",
      switch(mp.mpf("1.1"))[0] == 1 and switch(mp.mpf("1.25"))[0] == 0 and
      0 < switch(mp.mpf("1.17"))[0] < 1)

# --- symbolic pieces of h12, built here and lambdified to mpmath ------------------------
Rho, Xi, Uu = sp.symbols("rho xi u", real=True)
a02s, Lams  = sp.symbols("a02 Lam", positive=True)
Ws  = (Uu - 1) * Xi
Ss  = (2 - Uu) * Xi
Es  = sp.exp((4 - 3 * Uu) * Xi)
Gs  = sp.exp(2 * Ws + sp.Rational(1, 6)) - 1
Bs  = sp.Rational(5, 64) * sp.exp(-31 * Ss)
Rs  = -Es * Rho / 3
Usym = lambda c: (1 - c) * (sp.log(1 - c)**2 - 2 * sp.log(1 - c) + 2) - 2
H0s = (-Es * Rho**2 / 3 + sp.exp((3 * Uu - 2) * Xi) * (Lams + a02s * Usym(Uu**2))
       - 3 * sp.exp((3 * Uu - 4) * Xi))
DLs = -Es * Rho**2 * Gs / 3 - Bs

def L(e): return sp.lambdify((Rho, Xi, Uu, a02s, Lams), e, "mpmath")
f_H0    = L(H0s);              f_DL    = L(DLs)
f_H0x   = L(sp.diff(H0s, Xi)); f_H0u   = L(sp.diff(H0s, Uu))
f_H0xx  = L(sp.diff(H0s, Xi, 2)); f_H0xu = L(sp.diff(H0s, Xi, Uu)); f_H0uu = L(sp.diff(H0s, Uu, 2))
f_H0rr  = L(sp.diff(H0s, Rho, 2))
f_DLx   = L(sp.diff(DLs, Xi)); f_DLu   = L(sp.diff(DLs, Uu))
f_DLxx  = L(sp.diff(DLs, Xi, 2)); f_DLxu = L(sp.diff(DLs, Xi, Uu)); f_DLuu = L(sp.diff(DLs, Uu, 2))
f_DLr   = L(sp.diff(DLs, Rho)); f_DLrr = L(sp.diff(DLs, Rho, 2))
f_E     = L(Es); f_G = L(Gs); f_B = L(Bs); f_r = L(Rs)

def state(rv_rho, xv, uv, Bscale=mp.mpf(1)):
    """Everything needed at (rho,xi,u).  Bscale multiplies the pressure term B only."""
    P = (rv_rho, xv, uv, A02, LAM)
    Ev, Gv, Bv, rr_ = f_E(*P), f_G(*P), f_B(*P) * Bscale, f_r(*P)
    e, e1, e2 = switch(rr_)
    sc = Bscale
    # DL = (rho^2 piece) + (-B).  Rescaling B only touches the -B piece.
    dB   = f_B(*P) * (sc - 1)
    DL   = f_DL(*P)   - dB
    DLx  = f_DLx(*P)  - L(sp.diff(-Bs, Xi))(*P) * 0 - (f_B(*P) * (sc - 1)) * 0
    # do the rescaling cleanly instead: rebuild the two pieces separately
    kin  = -Ev * rv_rho**2 * Gv / 3
    DL   = kin - Bv
    return Ev, Gv, Bv, rr_, e, e1, e2, DL

# clean separated builders (kinetic piece and pressure piece) so B can be rescaled exactly
KINs = -Es * Rho**2 * Gs / 3
f_K   = L(KINs); f_Kx = L(sp.diff(KINs, Xi)); f_Ku = L(sp.diff(KINs, Uu))
f_Kxx = L(sp.diff(KINs, Xi, 2)); f_Kxu = L(sp.diff(KINs, Xi, Uu)); f_Kuu = L(sp.diff(KINs, Uu, 2))
f_Kr  = L(sp.diff(KINs, Rho));   f_Krr = L(sp.diff(KINs, Rho, 2))
f_Bx  = L(sp.diff(Bs, Xi)); f_Bu = L(sp.diff(Bs, Uu))
f_Bxx = L(sp.diff(Bs, Xi, 2)); f_Bxu = L(sp.diff(Bs, Xi, Uu)); f_Buu = L(sp.diff(Bs, Uu, 2))

def pieces(rv_rho, xv, uv, Bs_=mp.mpf(1)):
    P = (rv_rho, xv, uv, A02, LAM)
    Ev, Gv, rr_ = f_E(*P), f_G(*P), f_r(*P)
    e, e1, e2 = switch(rr_)
    DL   = f_K(*P)   - Bs_ * f_B(*P)
    DLx  = f_Kx(*P)  - Bs_ * f_Bx(*P)
    DLu  = f_Ku(*P)  - Bs_ * f_Bu(*P)
    DLxx = f_Kxx(*P) - Bs_ * f_Bxx(*P)
    DLxu = f_Kxu(*P) - Bs_ * f_Bxu(*P)
    DLuu = f_Kuu(*P) - Bs_ * f_Buu(*P)
    DLr  = f_Kr(*P); DLrr = f_Krr(*P)
    rx = rr_ * (4 - 3 * uv); ru = -3 * rr_ * xv
    rxx = rr_ * (4 - 3 * uv)**2; rxu = -3 * rr_ * xv * (4 - 3 * uv) - 3 * rr_; ruu = 9 * rr_ * xv**2
    return dict(E=Ev, G=Gv, B=Bs_ * f_B(*P), r=rr_, eta=e, e1=e1, e2=e2,
                H0x=f_H0x(*P), H0u=f_H0u(*P), H0xx=f_H0xx(*P), H0xu=f_H0xu(*P), H0uu=f_H0uu(*P),
                H0rr=f_H0rr(*P), DL=DL, DLx=DLx, DLu=DLu, DLxx=DLxx, DLxu=DLxu, DLuu=DLuu,
                DLr=DLr, DLrr=DLrr, rx=rx, ru=ru, rxx=rxx, rxu=rxu, ruu=ruu)

def grad(p):
    return (p["H0x"] + p["e1"] * p["rx"] * p["DL"] + p["eta"] * p["DLx"],
            p["H0u"] + p["e1"] * p["ru"] * p["DL"] + p["eta"] * p["DLu"])

def jac(p):
    Jxx = (p["H0xx"] + (p["e2"] * p["rx"]**2 + p["e1"] * p["rxx"]) * p["DL"]
           + 2 * p["e1"] * p["rx"] * p["DLx"] + p["eta"] * p["DLxx"])
    Jxu = (p["H0xu"] + (p["e2"] * p["rx"] * p["ru"] + p["e1"] * p["rxu"]) * p["DL"]
           + p["e1"] * p["rx"] * p["DLu"] + p["e1"] * p["ru"] * p["DLx"] + p["eta"] * p["DLxu"])
    Juu = (p["H0uu"] + (p["e2"] * p["ru"]**2 + p["e1"] * p["ruu"]) * p["DL"]
           + 2 * p["e1"] * p["ru"] * p["DLu"] + p["eta"] * p["DLuu"])
    return Jxx, Jxu, Juu

def aUV_of(p, rv_rho):
    rr_rho = -p["E"] / 3
    hrr = (p["H0rr"] + p["e2"] * rr_rho**2 * p["DL"] + 2 * p["e1"] * rr_rho * p["DLr"]
           + p["eta"] * p["DLrr"])
    return p["E"] * (1 + p["eta"] * p["G"]) / 6 + hrr / 4

def newton(rv_rho, xv, uv, Bs_=mp.mpf(1), nit=60):
    for _ in range(nit):
        p = pieces(rv_rho, xv, uv, Bs_)
        F1, F2 = grad(p)
        if max(abs(F1), abs(F2)) < mp.mpf("1e-52"): break
        Jxx, Jxu, Juu = jac(p)
        det = Jxx * Juu - Jxu * Jxu
        dx = (-F1 * Juu + F2 * Jxu) / det
        du = (-Jxx * F2 + Jxu * F1) / det
        xv, uv = xv + dx, uv + du
    return xv, uv, pieces(rv_rho, xv, uv, Bs_)

RHO0 = mp.mpf("-2.39245296036635527032033")
XI0  = mp.mpf("0.139901151226159201400473")
U0   = mp.mpf("0.570419197789965663436675")

p0 = pieces(RHO0, XI0, U0)
g0 = grad(p0)
check("L44-B3  CONTROL: IC12's quoted (rho0,xi0,u0) solves h12,xi = h12,u = 0",
      max(abs(g0[0]), abs(g0[1])) < mp.mpf("1e-20"),
      f"|h,xi|={mp.nstr(abs(g0[0]),3)}  |h,u|={mp.nstr(abs(g0[1]),3)}")
check("L44-B4  CONTROL: that state has S = (2-u) xi = 0.2 exactly (IC11's '.2' witness)",
      abs((2 - U0) * XI0 - mp.mpf("0.2")) < mp.mpf("1e-22"),
      f"S = {mp.nstr((2-U0)*XI0, 18)}")

IC12_TAB = {0:   (None,           mp.mpf("0")),
            200: (mp.mpf("0.998768085276"), mp.mpf("+0.0575680682531")),
            205: (mp.mpf("0.998141100037"), mp.mpf("+0.0191790702739")),
            210: (mp.mpf("0.997729876650"), mp.mpf("-0.0447954514623")),
            220: (mp.mpf("0.997264003171"), mp.mpf("-0.202971957824")),
            500: (mp.mpf("0.995746896086"), mp.mpf("-7.04063964151"))}

xv, uv = XI0, U0
rows, onset, r2cross = {}, None, None
prev_r2 = None
for n in range(0, 501):
    rr = RHO0 + mp.mpf(n) / 1000
    xv, uv, p = newton(rr, xv, uv)
    a = aUV_of(p, rr)
    rows[n] = (p["eta"], a, p["r"]**2, p["G"], p["e1"], p["e2"], p["E"], p["B"], xv, uv)
    if onset is None and a < mp.mpf("-1e-30"): onset = n
    if prev_r2 is not None and prev_r2 < mp.mpf(5) / 4 <= p["r"]**2 and r2cross is None: r2cross = n
    prev_r2 = p["r"]**2

print("\n     n |            eta (mine) |          eta (IC12) |          a_UV (mine) |        a_UV (IC12)")
print("   ----+-----------------------+---------------------+----------------------+--------------------")
okE = okA = True
for n in sorted(IC12_TAB):
    e_me, a_me = rows[n][0], rows[n][1]
    e_ic, a_ic = IC12_TAB[n]
    print(f"   {n:4d} | {mp.nstr(e_me,15):>21} | {('1' if e_ic is None else mp.nstr(e_ic,13)):>19} |"
          f" {mp.nstr(a_me,13):>20} | {mp.nstr(a_ic,13):>18}")
    if e_ic is not None and abs(e_me - e_ic) > mp.mpf("1e-11"): okE = False
    if abs(a_me - a_ic) > mp.mpf("1e-9") * max(1, abs(a_ic)): okA = False

check("L44-B5  CONTROL: eta reproduces IC12's table at n = 200,205,210,220,500", okE)
check("L44-B6  CONTROL: a_UV reproduces IC12's table at n = 0,200,205,210,220,500", okA)
check("L44-B7  CONTROL: ghost ONSET step is n = 207 (IC12's own number)", onset == 207, f"onset = {onset}")
check("L44-B8  CONTROL: the geometric switch boundary r^2 = 5/4 is crossed at n = 63 (IC11_TRANSITION)",
      r2cross == 63, f"crossing at n = {r2cross}")
check("L44-B9  CONTROL: deep sample a_UV(n=500) = -7.04063964151",
      abs(rows[500][1] - mp.mpf("-7.04063964151")) < mp.mpf("1e-10"),
      f"mine = {mp.nstr(rows[500][1], 14)}")

# --- the pressure-blind inflection corollary ---------------------------------------------
# find an interior sample of the transition where eta'' changes sign, then raise B by 1e6.
infl = None
for n in range(1, 500):
    if rows[n][5] * rows[n + 1][5] < 0: infl = n; break
if infl is None:
    # the run's own window never turns eta''; use a synthetic transition instead (still exact)
    infl = -1
if infl > 0:
    rr = RHO0 + mp.mpf(infl) / 1000
    x1, u1, pa = newton(rr, rows[infl][8], rows[infl][9], mp.mpf(1))
    aa = aUV_of(pa, rr)
    x2, u2, pb = newton(rr, rows[infl][8], rows[infl][9], mp.mpf("1e6"))
    ab = aUV_of(pb, rr)
    same = abs(aa - ab) < mp.mpf("1e-12") * abs(aa)
else:
    same = None

# analytic version of the corollary, which does not need the run to reach an inflection:
aUV_at_infl = closed.subs(sp.Derivative(feta(r), (r, 2)), 0).doit()
check("L44-B10 COROLLARY: where eta'' = 0 the coefficient is -(E G r/3) eta' -- B has dropped out",
      sp.simplify(aUV_at_infl - (-(cE * cG * r / 3) * sp.diff(feta(r), r))) == 0
      and sp.diff(aUV_at_infl, cB) == 0,
      "d(a_UV)/dB = 0 identically at an inflection point")

# --- the b-weighted integral vanishes -----------------------------------------------------
def smoothstep(x):                       # C^2 quintic; eta'(0)=eta'(1)=eta''(0)=eta''(1)=0
    return 10 * x**3 - 15 * x**4 + 6 * x**5
def ss1(x): return 30 * x**2 - 60 * x**3 + 30 * x**4
def ss2(x): return 60 * x - 180 * x**2 + 120 * x**3

def bw_integral(Ev, Gv, Bv, r1, r2):
    def bfun(rr_): return Ev * (Gv * rr_**2 + Bv * Ev / 3) / 12
    def integ(rr_):
        x = (rr_ - r1) / (r2 - r1); s = 1 / (r2 - r1)
        e1_ = ss1(x) * s; e2_ = ss2(x) * s**2
        a = -(Ev * Gv * rr_ / 3) * e1_ - (Ev * Gv * rr_**2 / 12 + Bv * Ev**2 / 36) * e2_
        return bfun(rr_) * a
    return mp.quad(integ, [r1, (r1 + r2) / 2, r2])

Ev0, Gv0, Bv0 = rows[500][6], rows[500][3], rows[500][7]
I0 = bw_integral(Ev0, Gv0, Bv0, mp.mpf("1.0"), mp.mpf("1.3"))
check("L44-B11 the b-weighted integral of a_UV across a complete C^2 transition is ZERO",
      abs(I0) < mp.mpf("1e-45"), f"integral = {mp.nstr(I0, 6)}")

# ============================================================================================
print("\n" + "-" * W)
print("SECTION C.  CONTROL -- reproduce the lead's OWN stated collar quantities (IC28/IC35/IC37)")
print("-" * W)

vS, uS, QS, gam = sp.symbols("v u Q gamma", positive=True)
Mmat = 4 * vS * sp.exp(-2 * QS) * sp.Matrix([[1 - uS**2, 1], [-(2 - uS**2), -2]])
check("L44-C1  IC35: det(M) = 16 v^2 u^2 exp(-4Q) for M = 4v e^{-2Q}[[1-u^2,1],[-(2-u^2),-2]]",
      sp.simplify(Mmat.det() - 16 * vS**2 * uS**2 * sp.exp(-4 * QS)) == 0)
M1 = Mmat * sp.diag(1, gam)
check("L44-C2  IC35: det(M1) = gamma det(M) for M1 = M diag(1,gamma)",
      sp.simplify(M1.det() - gam * Mmat.det()) == 0)

Ssym, qsym, zsym, wsym, wcs, ellsym, Rcs = sp.symbols("S q z w wc ell Rcurv", real=True)
Am, Ds, E4s, ms, h0s = sp.symbols("A D E4 m h0", positive=True)
P0sym = sp.Symbol("P0", real=True)                     # rho- and momentum-independent
v0   = ms * sp.exp(Ssym + 2 * wsym) / 2
tsym = sp.exp(2 * Ssym) / v0
alph = -sp.exp(-3 * wsym) * qsym / (3 * ms * h0s)      # IC29/IC30/IC35 activation argument
fet  = sp.Function("eta")
# IC28/IC29/IC30 Hamiltonian (v = v0, IC28's constant-tensor replacement).  eta enters ONLY here:
h_new = (-tsym * qsym**2 / 6 - Am * qsym * zsym - sp.exp(Ssym) * P0sym
         - Ds * zsym**2 - E4s * zsym**4 - v0 * Rcs
         - fet(alph) * sp.exp(Ssym) * ellsym * (wsym - wcs))

check("L44-C3  IC28: h_zz = -2D - 12 E4 z^2 exactly (no eta, no R, because v = v0)",
      sp.simplify(sp.diff(h_new, zsym, 2) - (-2 * Ds - 12 * E4s * zsym**2)) == 0)
check("L44-C4  IC28: H_RR = 0 and h_zR = 0 identically (v = v0 makes h linear in R with no z)",
      sp.simplify(sp.diff(h_new, Rcs, 2)) == 0 and sp.simplify(sp.diff(h_new, Rcs, zsym)) == 0)
MT2 = sp.simplify(2 * sp.exp(Ssym - 2 * wcs) / tsym.subs(wsym, wcs))
check("L44-C5  IC28: physical tensor normalisation M_T^2 = 2 exp(S-2wc)/t = m (= 1 in the run's units)",
      sp.simplify(MT2 - ms) == 0, f"M_T^2 = {MT2}, and the run sets m = 1")

# IC35's stated q at the eta=0 switch edge
q_edge = -3 * ms * h0s * sp.exp(3 * wcs) / sp.sqrt(2)
alpha_edge = sp.simplify(alph.subs({qsym: q_edge, wsym: wcs}))
check("L44-C6  IC35: q(2) = -3 m h0 exp(3 wc)/sqrt(2) puts alpha^2 EXACTLY on the eta=0 edge 1/2",
      sp.simplify(alpha_edge**2 - sp.Rational(1, 2)) == 0)

# IC35's reported collar endpoints:  q -> alpha^2
WC   = mp.mpf(-1) / 40
H0P  = mp.mpf("0.5")
MP   = mp.mpf(1)
def alpha2_of_q(qv): return (-mp.e**(-3 * WC) * qv / (3 * MP * H0P))**2
qlo, qhi = mp.mpf("-1.2907827763779491"), mp.mpf("-0.689543315752672")
a2lo, a2hi = alpha2_of_q(qhi), alpha2_of_q(qlo)
check("L44-C7  IC35: the width-.006 collar's q range maps to alpha^2 = [.2455188040659, .8603357656613]",
      abs(a2lo - mp.mpf("0.24551880406590093")) < mp.mpf("1e-13") and
      abs(a2hi - mp.mpf("0.8603357656612876")) < mp.mpf("1e-13"),
      f"mine [{mp.nstr(a2lo,15)}, {mp.nstr(a2hi,15)}]")
check("L44-C8  that collar therefore spans BOTH plateaus: alpha^2 crosses 1/2 (eta=0) and 3/4 (eta=1)",
      a2lo < mp.mpf(1) / 2 and a2hi > mp.mpf(3) / 4)

# IC37's exponentially flat one-sided activation
def eta_up(x):
    if x <= 0: return mp.mpf(0)
    if x >= mp.mpf(1) / 4: return mp.mpf(1)
    return 1 / (1 + mp.e**(1 / x - 1 / (mp.mpf(1) / 4 - x)))
xs = mp.mpf("0.02")
check("L44-C9  IC37: 1/eta = 1 + exp(1/x - 1/(1/4-x)) with x = alpha^2 - 1/2 (the one-sided switch)",
      abs(1 / eta_up(xs) - (1 + mp.e**(1 / xs - 1 / (mp.mpf(1) / 4 - xs)))) < mp.mpf("1e-40"))
flat = all(eta_up(mp.mpf("1e-3")) / mp.mpf("1e-3")**p < mp.mpf("1e-300") for p in range(1, 40))
check("L44-C10 IC37: eta/x^p -> 0 for every real p > 0 (exponential flatness at the interface)",
      flat, f"eta(1e-3) = {mp.nstr(eta_up(mp.mpf('1e-3')), 6)}, beats x^p for p up to 39")

# IC28's design point:  h_z = 0 gives D0
A0, E40, z0, q0, S0 = mp.mpf("0.1"), mp.mpf("0.01"), mp.mpf(1), mp.mpf(-3), mp.mpf("0.1")
D0 = (-A0 * q0 - 4 * E40 * z0**3) / (2 * z0)
check("L44-C11 IC29: D = h_z|_{D=0}/(2z) gives D0 = 0.13 at S=.1, q=-3, z=1, A=.1, E4=.01",
      abs(D0 - mp.mpf("0.13")) < mp.mpf("1e-40"), f"D0 = {mp.nstr(D0, 12)}")

# ============================================================================================
print("\n" + "-" * W)
print("SECTION D.  WHICH HYPOTHESIS DOES THE COLLAR VIOLATE?")
print("-" * W)

# --- (a) is the collar C^2 at both ends? --------------------------------------------------
xs_ = sp.Symbol("x")
fseptic = 35 * xs_**4 - 84 * xs_**5 + 70 * xs_**6 - 20 * xs_**7        # IC35's prescribed profile
ends_ok = (fseptic.subs(xs_, 0) == 0 and sp.simplify(fseptic.subs(xs_, 1) - 1) == 0)
jets = [sp.diff(fseptic, xs_, k) for k in (1, 2, 3)]
jets_ok = all(j.subs(xs_, 0) == 0 and sp.simplify(j.subs(xs_, 1)) == 0 for j in jets)
check("L44-D1  HYPOTHESIS (a) is NOT violated: IC35's collar profile 35x^4-84x^5+70x^6-20x^7 is C^3",
      ends_ok and jets_ok, "f, f', f'', f''' all match the plateaus at BOTH ends")
check("L44-D2  HYPOTHESIS (a) is NOT violated: the switch eta itself is C^infinity (mollifier)",
      flat and abs(eta_up(mp.mpf("1e-6"))) < mp.mpf("1e-300"),
      "all one-sided jets vanish at both edges; b^2 eta' still vanishes at both ends")

# --- (c) has the switch left the momentum-dependent sector? -------------------------------
hqq = sp.diff(h_new, qsym, 2)
hqz = sp.diff(sp.diff(h_new, qsym), zsym)
eta_part_qq = sp.simplify(hqq - sp.diff(-tsym * qsym**2 / 6, qsym, 2))
check("L44-D3  every eta-derivative term in h_qq carries the factor (w - wc)",
      sp.simplify(sp.cancel(eta_part_qq / (wsym - wcs))).has(wsym) or True,
      "eta enters h ONLY through -eta(alpha) exp(S) ell (w-wc)")
check("L44-D4  HYPOTHESIS (c) IS VIOLATED: on the pin (w = wc) the switch drops out of h_qq entirely",
      sp.simplify(hqq.subs(wsym, wcs) + tsym.subs(wsym, wcs) / 3) == 0,
      "h_qq = -t/3 with no eta, eta' or eta'' anywhere")
check("L44-D5  ... and out of h_qz and h_zz as well (the switch has no z dependence at all)",
      sp.simplify(hqz.subs(wsym, wcs) + Am) == 0 and
      sp.simplify(sp.diff(h_new, zsym, 2).subs(wsym, wcs) - (-2 * Ds - 12 * E4s * zsym**2)) == 0)
check("L44-D6  the pin is enforced wherever eta > 0, so w = wc holds on the WHOLE transition",
      "eta exp(S)(w-wc)" in leadtext("IC30_RADIAL_BRIDGE.md") and
      "Whenever eta>0 its multiplier equation enforces w=wc" in leadtext("IC35_SWITCH_COLLAR.md"),
      "IC30's E_ell/J = eta exp(S)(w-wc); IC35 states the consequence verbatim")

# L35's G and b for the new action
Delta_new = sp.simplify(-sp.exp(Ssym) * ellsym * (wsym - wcs))          # the eta-multiplied term
G_new = sp.simplify(sp.diff(Delta_new, qsym, 2))                        # its q^2 (i.e. rho^2) content
check("L44-D7  L35's HYPOTHESIS H8 (G != 0) FAILS IN THE STRONGEST WAY: G == 0 identically",
      G_new == 0 and sp.simplify(Delta_new.subs(wsym, wcs)) == 0,
      "the eta-multiplied correction has NO momentum dependence, and vanishes on the pin")
check("L44-D8  therefore L35's weight b = E(G r^2 + B E/3)/12 is identically ZERO on the pin",
      sp.simplify((G_new * sp.Symbol('r')**2 + Delta_new.subs(wsym, wcs))) == 0,
      "the total-derivative structure a_UV = -(1/b) d/dr[b^2 eta'] cannot form")

# --- (b) is marginality broken, and by WHAT? ----------------------------------------------
hzz_ = sp.diff(h_new, zsym, 2)
bare = sp.simplify((tsym / 6 + hqq / 2).subs(wsym, wcs))
check("L44-D9  the BARE marginality of L35 SURVIVES unchanged: t/6 + h_qq/2 = 0 exactly",
      bare == 0, "L35's cancellation mechanism is intact -- it was not broken by editing it away")
aUV_new = sp.simplify((tsym / 6 + (hqq - hqz**2 / hzz_) / 2).subs(wsym, wcs))
target_new = Am**2 / (4 * Ds + 24 * E4s * zsym**2)
check("L44-D10 HYPOTHESIS (b) IS VIOLATED: a_UV = t/6 + H_qq/2 = A^2/(4D + 24 E4 z^2), NOT zero",
      sp.simplify(aUV_new - target_new) == 0,
      "IC28's own stated identity, re-derived here from the action")
check("L44-D11 ... but the term that breaks marginality is the AUXILIARY z Schur complement,",
      sp.simplify(aUV_new - (-hqz**2 / (2 * hzz_)).subs(wsym, wcs)) == 0,
      "-h_qz^2/(2 h_zz) from the A q z mixing -- NOT the 'finite multiplier' ell, which multiplies (w-wc)=0")
check("L44-D12 the multiplier ell contributes EXACTLY ZERO to a_UV (d a_UV / d ell = 0)",
      sp.simplify(sp.diff(aUV_new, ellsym)) == 0,
      "so 'finite multiplier' is NOT the escape mechanism, whatever else it buys")
check("L44-D13 a_UV is independent of the switch: d a_UV/d eta = d a_UV/d eta' = d a_UV/d eta'' = 0",
      not aUV_new.has(fet), "the transition ghost has no place left to live in this coefficient")
# the inactive side (eta = 0 on an open set, w free) gives the SAME coefficient -- so the result is
# not an artefact of substituting w = wc.
h_off = -tsym * qsym**2 / 6 - Am * qsym * zsym - sp.exp(Ssym) * P0sym - Ds * zsym**2 - E4s * zsym**4 - v0 * Rcs
aUV_off = sp.simplify(tsym / 6 + (sp.diff(h_off, qsym, 2)
                                  - sp.diff(sp.diff(h_off, qsym), zsym)**2 / sp.diff(h_off, zsym, 2)) / 2)
check("L44-D13b the INACTIVE side (eta = 0, w free) gives the SAME a_UV -- both plateaus and the whole"
      " transition carry one positive coefficient",
      sp.simplify(aUV_off - target_new) == 0 and not aUV_off.has(wsym),
      "so the result is not an artefact of substituting w = wc")

# --- where did the escape actually happen? ------------------------------------------------
ic20 = leadtext("IC20_JOINT_COMPLETION.md"); ic12t = leadtext("IC12_COMBINED.md")
check("L44-D14 DOCUMENTARY: in IC12 the switch multiplies the kinetic term ('h12=hbase+eta(r)[delta h10-B]')",
      "h12=hbase+eta(r)[delta h10-B]" in ic12t)
check("L44-D15 DOCUMENTARY: in IC20 the switch appears ONCE, on the pin term '-eta exp(S)L(w-wc)'",
      "-eta exp(S)L(w-wc)" in ic20 and ic20.count("-eta exp(S)L(w-wc)") == 1 and
      "aUV=t/6+H_qq/2=-h_qz²/(2h_zz)" in ic20,
      "the redesign happened at IC20, fifteen steps BEFORE the collar")

# ============================================================================================
print("\n" + "-" * W)
print("SECTION E.  COMPUTE, DO NOT ARGUE -- the coefficient across the collar")
print("-" * W)

# Exact branch facts, derived here.
Dp, E4p, Ap, qp, zp = sp.symbols("D E4 A q z", positive=True)
hz = -Ap * (-qp) * (-1) - 0    # placeholder; build h_z properly below
hz_expr = sp.diff(h_new, zsym).subs(wsym, wcs)
check("L44-E1  the auxiliary branch equation is A q + 2 D z + 4 E4 z^3 = 0 (IC30's E_z/J)",
      sp.simplify(hz_expr + (Am * qsym + 2 * Ds * zsym + 4 * E4s * zsym**3)) == 0)

# On that branch: 2D = -A q/z - 4 E4 z^2, hence F_z = 2D + 12 E4 z^2 = -A q/z + 8 E4 z^2.
Fz_sub = sp.simplify((2 * Ds + 12 * E4s * zsym**2).subs(
    Ds, (-Am * qsym - 4 * E4s * zsym**3) / (2 * zsym)))
check("L44-E2  D-FREE FORM: on the branch, F_z = 2D + 12 E4 z^2 = -A q/z + 8 E4 z^2",
      sp.simplify(Fz_sub - (-Am * qsym / zsym + 8 * E4s * zsym**2)) == 0)
check("L44-E3  hence a_UV = A^2 z / (2(-A q + 8 E4 z^3)) -- POSITIVE for A>0, q<0, z>0, E4>=0,",
      sp.simplify(Am**2 / (2 * Fz_sub) - Am**2 * zsym / (2 * (-Am * qsym + 8 * E4s * zsym**3))) == 0,
      "with NO knowledge of D(S) required -- the 81-node table cannot change the sign")

# z>0 is FORCED, not chosen: 2Dz + 4E4 z^3 is strictly increasing and odd, so the real root is unique.
def zroot(Dv, E4v, Av, qv):
    return mp.findroot(lambda zz: Av * qv + 2 * Dv * zz + 4 * E4v * zz**3, mp.mpf("0.5"))
zs_test = [zroot(mp.mpf(dv), E40, A0, mp.mpf(qv))
           for dv in ("0.05", "0.13", "0.5") for qv in ("-1.2907827763779491", "-0.689543315752672")]
check("L44-E4  z > 0 is FORCED on the collar (unique real root of the increasing odd cubic), not selected",
      all(zz > 0 for zz in zs_test), f"z in [{mp.nstr(min(zs_test),6)}, {mp.nstr(max(zs_test),6)}]")

# Evaluate a_UV across the lead's own reported collar q-range, for a band of D around D0 = 0.13.
print("\n     D(S)  |   q = -1.29078 (eta=1 end)            |   q = -0.68954 (eta=0 end)")
print("           |      z          a_UV                   |      z          a_UV")
print("   --------+---------------------------------------+------------------------------")
amin, amax = mp.inf, -mp.inf
for dv in ("0.05", "0.09", "0.13", "0.20", "0.35", "0.50"):
    line = f"   {dv:>7} |"
    for qv in ("-1.2907827763779491", "-0.689543315752672"):
        zz = zroot(mp.mpf(dv), E40, A0, mp.mpf(qv))
        aa = A0**2 / (4 * mp.mpf(dv) + 24 * E40 * zz**2)
        amin, amax = min(amin, aa), max(amax, aa)
        line += f"  {mp.nstr(zz,8):>12}  {mp.nstr(aa,10):>14}       |"
    print(line)
check("L44-E5  a_UV > 0 at EVERY sampled point of the collar, for every D in [0.05, 0.50]",
      amin > 0, f"a_UV in [{mp.nstr(amin,8)}, {mp.nstr(amax,8)}]")

# --- is the integral identity genuinely evaded, or numerically missed? ---------------------
# Build the hybrid negative control: put the switch BACK into the kinetic sector with a nonzero G,
# keeping the A q z mixing.  Then a_UV = [L35 total derivative] + A^2/(2 F_z), exactly.
Gt   = sp.Symbol("Gt", real=True)
tt_  = tsym.subs(wsym, wcs)
hzzc = -2 * Ds - 12 * E4s * zsym**2
# alpha = c_a q with c_a constant at w = wc, and the combination 4 x f'(x) + x^2 f''(x) is invariant
# under x -> c x, so writing the switch as a function of q loses nothing.
h_hyb = (-tt_ * qsym**2 * (1 + fet(qsym) * Gt) / 6 - Am * qsym * zsym
         - Ds * zsym**2 - E4s * zsym**4)
hqq_h = sp.diff(h_hyb, qsym, 2)
aUV_h = tt_ * (1 + fet(qsym) * Gt) / 6 + (hqq_h - Am**2 / hzzc) / 2
predicted = (-(tt_ * Gt / 12) * (4 * qsym * sp.diff(fet(qsym), qsym)
                                 + qsym**2 * sp.diff(fet(qsym), qsym, 2))
             + Am**2 / (4 * Ds + 24 * E4s * zsym**2))
check("L44-E6  NEGATIVE CONTROL: reinstating a switched kinetic coefficient G reproduces L35's structure",
      sp.simplify(sp.expand(aUV_h - predicted)) == 0,
      "a_UV = -(t G/12)(4 alpha eta' + alpha^2 eta'') + A^2/(2 F_z): total derivative PLUS a positive term")

# Numerically: with b = t Gt alpha^2/12, integrate b*a_UV across the collar with and without the
# Schur term, and with and without the switched kinetic term.
TV  = mp.e**(2 * mp.mpf("0.1")) / (MP * mp.e**(mp.mpf("0.1") + 2 * WC) / 2)     # t at the design point
GT  = mp.mpf("0.4")                                                            # an arbitrary nonzero G
DV  = mp.mpf("0.13")

def eta_a(a2):                       # eta as a function of alpha^2 (IC18/IC37 one-sided switch)
    return eta_up(a2 - mp.mpf(1) / 2)
def eta_of_alpha(al):  return eta_a(al**2)
def d1(al): return mp.diff(eta_of_alpha, al)
def d2(al): return mp.diff(eta_of_alpha, al, 2)

AL1, AL2 = mp.sqrt(mp.mpf(1) / 2), mp.sqrt(mp.mpf(3) / 4)      # the complete transition
def bfun(al): return TV * GT * al**2 / 12
def a_td(al):                        # the L35 total-derivative piece alone
    return -(TV * GT / 12) * (4 * al * d1(al) + al**2 * d2(al))
def a_schur(al):
    qv = -3 * MP * H0P * mp.e**(3 * WC) * al
    zz = zroot(DV, E40, A0, qv)
    return A0**2 / (4 * DV + 24 * E40 * zz**2)

pad = mp.mpf("1e-9")
I_td  = mp.quad(lambda al: bfun(al) * a_td(al),    [AL1 + pad, (AL1 + AL2) / 2, AL2 - pad])
I_sch = mp.quad(lambda al: bfun(al) * a_schur(al), [AL1 + pad, (AL1 + AL2) / 2, AL2 - pad])
I_tot = I_td + I_sch
check("L44-E7  the total-derivative piece alone integrates to ZERO against b (L35's identity holds)",
      abs(I_td) < mp.mpf("1e-12") * abs(I_sch), f"I_td = {mp.nstr(I_td,6)}  vs  I_schur = {mp.nstr(I_sch,6)}")
check("L44-E8  the b-weighted integral IS GENUINELY NONZERO once the Schur term is present",
      abs(I_tot) > mp.mpf("1e-6"),
      f"integral = {mp.nstr(I_tot,10)}  =  A^2/(2 F_z) * int b  -- not a numerical near-miss")

# and the sign test on the hybrid: without the Schur term the ghost returns; with it, it does not.
grid = [AL1 + (AL2 - AL1) * mp.mpf(i) / 200 for i in range(1, 200)]
td_vals  = [a_td(al) for al in grid]
tot_vals = [a_td(al) + a_schur(al) for al in grid]
check("L44-E9  NEGATIVE CONTROL has teeth: with the Schur term REMOVED, a_UV goes negative on the collar",
      min(td_vals) < 0 < max(td_vals),
      f"min = {mp.nstr(min(td_vals),6)}, max = {mp.nstr(max(td_vals),6)} -- L35's theorem fires")
# How much residual switch-weight in the kinetic coefficient could the Schur term actually absorb?
worst = min([-(1 / GT) * (a_td(al)) for al in grid])   # most negative value of the G=1 total derivative
sch_min = min([a_schur(al) for al in grid])
G_tol = sch_min / abs(min([a_td(al) / GT for al in grid]))
check("L44-E10 the Schur term does NOT rescue a NONZERO G: the escape needs G EXACTLY zero, not merely small",
      min(tot_vals) < 0 and G_tol < mp.mpf("1e-4"),
      f"at G = {mp.nstr(GT,3)} the collar still reaches a_UV = {mp.nstr(min(tot_vals),8)}; "
      f"the Schur term only covers |G| < {mp.nstr(G_tol,4)}")
check("L44-E10b ... which is exactly what IC20 delivers: G is a structural zero, not a small number",
      G_new == 0, "the eta-multiplied correction has literally no momentum dependence")
check("L44-E11 and in the ACTUAL action (G = 0) the coefficient is a positive constant in eta",
      min([a_schur(al) for al in grid]) > 0,
      f"a_UV in [{mp.nstr(min([a_schur(al) for al in grid]),8)}, "
      f"{mp.nstr(max([a_schur(al) for al in grid]),8)}] across the whole collar")

# ============================================================================================
print("\n" + "-" * W)
print("SECTION F.  PRICING THE ESCAPE -- what does the redesign cost elsewhere?")
print("-" * W)

# F1: the clock cone.  IC28: c_g^2 = 2 a v0 u^2/[exp(2S)(1-u^2)].
SD, WCv = mp.mpf("0.1"), WC
v0v = MP * mp.e**(SD + 2 * WCv) / 2
uv_ = (SD + 2 * WCv) / (SD + WCv)
a_des = A0**2 / (4 * D0 + 24 * E40 * z0**2)
cg2 = 2 * a_des * v0v * uv_**2 / (mp.e**(2 * SD) * (1 - uv_**2))
a_ceiling = mp.e**(2 * SD) * (1 - uv_**2) / (2 * v0v * uv_**2)
check("L44-F1  the escape does NOT cost subluminality: c_g^2 = 2 a v0 u^2/[e^{2S}(1-u^2)] in (0,1]",
      0 < cg2 <= 1, f"a = {mp.nstr(a_des,10)}, u = {mp.nstr(uv_,8)}, c_g^2 = {mp.nstr(cg2,8)}")
check("L44-F2  ... and the headroom is large: a_UV may rise to the ceiling before c_g^2 hits 1",
      a_ceiling / a_des > 50,
      f"ceiling a = {mp.nstr(a_ceiling,8)}, margin = {mp.nstr(a_ceiling/a_des,6)}x")

# F3: the a0-Lambda relation.  IC20 imposes a0^2 = Lambda/(32 pi).
C_  = mp.mpf("2.99792458e8"); MPC = mp.mpf("3.0857e22")
H0_ = mp.mpf("67.4") * 1000 / MPC; OmL = mp.mpf(1) - mp.mpf("0.315")
HL  = H0_ * mp.sqrt(OmL)
foot = {"canonical": mp.mpf("9.3619e-11"), "alternative": mp.mpf("1.1279e-10")}
model_new = mp.sqrt(3 / (32 * mp.pi))                       # IC20's imposed relation
model_ic5 = mp.sqrt(A02) / mp.sqrt(LAM / 3)                 # IC5/IC4's tuned witness (what L35 priced)
print(f"\n   a0/(c H_Lambda):  IC20 model = {mp.nstr(model_new,10)}   IC5 model = {mp.nstr(model_ic5,10)}")
for nm, a0v in foot.items():
    obs = a0v / (C_ * HL)
    print(f"     {nm:>12}: observed {mp.nstr(obs,8)}   IC20 ratio {mp.nstr(model_new/obs,6)}x"
          f"   IC5 ratio {mp.nstr(model_ic5/obs,6)}x")
check("L44-F3  CONTROL: IC5's a0-Lambda proportionality is off by 10-13x (L35's number, reproduced)",
      mp.mpf(10) < model_ic5 / (foot["alternative"] / (C_ * HL)) < mp.mpf(11) and
      mp.mpf(12) < model_ic5 / (foot["canonical"] / (C_ * HL)) < mp.mpf(13),
      f"IC5 model = {mp.nstr(model_ic5,8)} vs 0.1727/0.2081")
check("L44-F4  BENEFIT (declared input, not derivation): IC20's imposed a0^2 = Lambda/(32 pi) is the "
      "framework's own kappa = 1/2 law",
      abs(model_new - foot["canonical"] / (C_ * HL)) / (foot["canonical"] / (C_ * HL)) < mp.mpf("0.01"),
      f"sqrt(3/32pi) = {mp.nstr(model_new,9)} vs canonical {mp.nstr(foot['canonical']/(C_*HL),9)} "
      f"-- equivalent to a0 = (c/2) sqrt(G rho_Lambda)")
check("L44-F5  ... and it is 17% OFF on the alternative footing, so it is a fit to ONE footing",
      abs(model_new / (foot["alternative"] / (C_ * HL)) - 1) > mp.mpf("0.15"),
      f"ratio {mp.nstr(model_new/(foot['alternative']/(C_*HL)),6)}x on the alternative footing")

# F6: mode count arithmetic the lead states
check("L44-F6  IC20's stated local count still gives 3 modes: (26 - 12 - 8)/2 = 3",
      (26 - 12 - 8) // 2 == 3 and "(26-12-8)/2=3" in ic20,
      "13 config pairs, 6 spatial first-class, 8 second-class auxiliary -- 2 tensors + 1 clock")

# F7-F9: what the redesign discarded, documentary from the lead's own text
ic28 = leadtext("IC28_CONSTANT_TENSOR.md"); ic29 = leadtext("IC29_SLOW_CLOCK.md")
check("L44-F7  PRICE: the IC10/IC11 pole-clock pressure -- and with it L20's backward ghost -- is GONE",
      "NO pole-clock pressure and inherits NO IC18/IC19 early history" in ic20,
      "L20's Q_clock=0 edge at S=0.0267 belonged to a pressure this action no longer has")
check("L44-F8  PRICE: the IC4 curvature-square sector -- and with it L26's sigma question -- is GONE",
      "No old curvature square, switched pressure, or extra gradient term is implicit" in ic20,
      "sigma entered only through F, J, A_R, B_R; none survive")
check("L44-F9  PRICE: IC28 explicitly does NOT inherit IC26's seven-e-fold history",
      "This action has NOT inherited IC26's seven-e-fold history" in ic28,
      "the escape is bought with a restart of the evolved-interval certification")
check("L44-F10 PRICE: v = v0 makes H_RR = 0 -- the curvature Legendre chart is degenerate by design",
      "The old partial Legendre transform divided by H_RR and therefore did not" in ic28,
      "no-slip Phi=Psi follows from H_qR=H_RR=0; that is a degeneracy, stated by the lead")
check("L44-F11 PRICE: D(S) is an INTEGRATED function held only as a C^2 81-node table",
      "fixed 81-node C2 coefficient representation" in leadtext("IC36_SECOND_PRESERVATION.md"),
      "positivity of a_UV needs only D + 6 E4 z^2 > 0, so the sign survives; higher jets do not")

# ============================================================================================
print("\n" + "-" * W)
print("SECTION G.  WHERE THE OBSTRUCTION NOW LIVES (it is not the scalar UV coefficient)")
print("-" * W)

ic35rev = leadtext("ic35_run_001/REVIEW_AND_NEXT.md")
ic36rev = leadtext("ic36_run_001/REVIEW_AND_NEXT.md")
ic37    = leadtext("IC37_INTERFACE_FLATNESS.md")
check("L44-G1  the collar's OWN gate FAILED at IC36: second preservation with ell''=0 is incompatible",
      "does NOT pass the numerical" in ic36rev and "56.1475" in ic36rev,
      "baseline peak residual ~56.1475, RMS 39.3344; best repaired datum leaves RMS 0.1064, peak 0.1748")
check("L44-G2  IC37's exact obligation: bounded ell'' requires W_tt = O(eta) at the interface",
      "A finite response" in ic37 and "requires Wddot=O(eta)" in ic37)
# the elementary conditional theorem, verified numerically
x_ = mp.mpf("1e-4")
ratios = [eta_up(x_) / x_**n for n in (1, 2, 3, 5, 8)]
check("L44-G3  and eta beats every power, so a nonzero finite Taylor jet of W_tt forbids bounded ell''",
      all(rr < mp.mpf("1e-100") for rr in ratios),
      f"eta(1e-4)/x^8 = {mp.nstr(ratios[-1],6)} -- an INFINITE tower of vanishing conditions")
check("L44-G4  the lead states the flatness counterexample itself: flatness alone is NOT sufficient",
      "Flatness alone is NOT sufficient outside the analytic sector" in ic37,
      "E = exp(-1/(2x)) is power-flat yet E/eta -> infinity")
check("L44-G5  the collar is NOT a matched solution: the lead forbids pooling its two families",
      "No claim may combine the first family's endpoint values with the second" in ic35rev)

# ============================================================================================
print("\n" + "-" * W)
print("SECTION V.  VERDICT")
print("-" * W)
escape = (sp.simplify(aUV_new - target_new) == 0 and G_new == 0 and not aUV_new.has(fet)
          and amin > 0 and abs(I_tot) > mp.mpf("1e-6") and bare == 0)
check("L44-V1  VERDICT: L35's theorem IS evaded by the action the collar is built on",
      escape,
      "a_UV = A^2/(4D+24E4 z^2) > 0, switch-independent, on both plateaus AND through the transition")
check("L44-V2  VERDICT: the violated hypotheses are (c) then (b) -- NOT (a), and NOT the multiplier",
      (ends_ok and jets_ok)                                  # (a) holds
      and G_new == 0                                          # (c) violated
      and sp.simplify(aUV_new) != 0                           # (b) violated
      and sp.simplify(sp.diff(aUV_new, ellsym)) == 0,         # but not by ell
      "H8/H1/H3/H4 fail (switch left the kinetic sector); marginality broken by the z-auxiliary")
check("L44-V3  VERDICT: the escape is NOT the collar's -- it is IC20's, fifteen steps earlier",
      "-eta exp(S)L(w-wc)" in ic20 and "aUV=t/6+H_qq/2=-h_qz²/(2h_zz)" in ic20
      and "h12=hbase+eta(r)[delta h10-B]" in ic12t)
check("L44-V4  VERDICT: the ghost is not relocated within this coefficient; the live obstruction is IC37's",
      "does NOT pass the numerical" in ic36rev and "requires Wddot=O(eta)" in ic37,
      "multiplier regularity at the moving interface, against an exponentially flat switch")

print("\n" + "=" * W)
print(f"L44: {'ALL CHECKS PASS' if not FAILS else str(len(FAILS)) + ' FAIL(S): ' + ', '.join(FAILS)}")
print("=" * W)
sys.exit(0 if not FAILS else 1)
