from pathlib import Path
import json,hashlib
O=Path(__file__).resolve().parent;R=O.parents[2]
base=json.loads((O/'forecast_manifest.json').read_text())
for p in sorted(O.glob('corrected_statistic_results*.json')):
 if '_manifest' in p.stem: continue
 x=json.loads(p.read_text());assert x['status']=='complete' and x['controls']['newton_velocity_equals_frozen']
 for name,h in x['input_hashes'].items():assert hashlib.sha256((R/name).read_bytes()).hexdigest()==h
 m=dict(base);m.update(claim_id='HR01-DR4-'+p.stem,command=['python3',str(O/('mc_convergence_audit.py' if '_model1p5m' in p.stem else 'corrected_statistic_audit.py'))],mathematics={'assertion_tested':'Correct observed speed-cut definition and compute joint bootstrap/Fisher information with overlapping anchors and profiled calibration.','coefficient_domain':'IEEE-754 binary64','conventions':'Natural logarithms of medians, full 9x9 covariance from paired whole-system resampling, finite independent model covariance, local velocity scaling kappa before noise.','inputs':[dict(path=k,sha256=v) for k,v in x['input_hashes'].items()],'bounds':x['settings'],'non_claims':x['limitations']},randomness={'used':True,'generator':'NumPy default_rng (PCG64)','seed':{'model':x['settings']['model_seed'],'mock':x['settings']['mock_seed'],'bootstrap':'literal base seeds plus case index and optional seed offset in source'}},run={'started_at':x['started_utc'],'runtime_seconds':x['runtime_seconds'],'exit_status':0},outputs=[dict(path=str(p.relative_to(R)),sha256=hashlib.sha256(p.read_bytes()).hexdigest())],checks=['Newtonian velocities equal frozen gamma=1 construction within 1e-14.','Joint covariance positive definite; full inversion without rank truncation.','Xi-independent prediction-path mutation has zero information.','Profiling calibration cannot increase information.','Separate cap counts and exact intersection-versus-symmetric differences reported.','All recorded input hashes still match.'],result='Six prospective covariance/calibration Fisher forecasts complete; observable cap correction zero in this clean sample; nuisance profile degrades near-floor precision.',residual_risks=x['limitations']+['Proposed audit settings are not frozen.','Version-1 provenance; source/result hashes supplement its weak schema.'])
 (O/(p.stem+'_manifest.json')).write_text(json.dumps(m,indent=2))
