from pathlib import Path
import json,hashlib,sys,platform,datetime,subprocess,time
import numpy as np,scipy
O=Path(__file__).resolve().parent;R=O.parents[2]
def h(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def output(p):return dict(path=str(p.relative_to(R)),sha256=h(p))
def stamp(t):return datetime.datetime.fromtimestamp(t,datetime.timezone.utc).isoformat()
start=time.time();p=subprocess.run([sys.executable,str(O/'forecast_audit.py')],stdout=subprocess.DEVNULL);elapsed=time.time()-start
manifest={'schema_version':1,'claim_id':'HR01-DR4-XR22-FISHER-ALGEBRA','repository':{'commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip(),'dirty':True},'command':[sys.executable,str(O/'forecast_audit.py')],'environment':{'software':[f'Python {platform.python_version()}',f'NumPy {np.__version__}',f'SciPy {scipy.__version__}'],'hardware':platform.platform()},'mathematics':{'assertion_tested':'Reconstruct saved seven-bin Fisher information; quantify loss on profiling one common amplitude and a hypothetical rank-one covariance.','coefficient_domain':'IEEE-754 binary64','conventions':'Fixed saved ratio and bootstrap errors; d/d ln xi by adjacent saved knots; no new solver or population simulation.','inputs':[output(R/'real_research/cross_thread_review_2026_09_26/XR22_prereg_statistic_results.json'),output(O/'forecast_audit.py')],'bounds':{'footings':['canonical','alt'],'xi_min':'footing floor','xi_max_pc':.1,'next_derivative_knot_max_pc':.15,'projected_bins_kAU':[2,3,5,7,10,15,20,30],'N':30000},'non_claims':['No self-consistent orbit or contamination modelling.','No calibrated confidence interval or detection forecast with nuisances.','The 2-percent correlated covariance is a sensitivity scenario, not the frozen gamma allowance.']},'randomness':{'used':False,'generator':'none; reads stored seeded bootstrap results','seed':None},'run':{'started_at':stamp(start),'runtime_seconds':elapsed,'exit_status':p.returncode},'outputs':[output(O/'forecast_audit_results.json')],'checks':['All reconstructed source Fisher values agree within 1e-10 relative/absolute tolerance.','Common-amplitude profiling cannot add information.','xi-independent mutation has zero Fisher information.'],'result':'Conditional algebraic forecast reproduced for 12 stored neighboring-knot pairs; floor fixed-calibration sigma .204595/.158483, free-amplitude .333840/.263921.','residual_risks':['Uses existing force/prediction tables; not independent end-to-end force reproduction.','Finite-difference/local-Fisher and stored bootstrap approximation.','Version-1 manifest; raw run records supplement source hashes and resource settings.']}
(O/'forecast_manifest.json').write_text(json.dumps(manifest,indent=2))
records=json.loads((O/'bounded_records.json').read_text())
for i,row in enumerate(records[:2]):
 mut=row['mutate']; suffix='_MUTATE' if mut else '';log=O/('xr31_mutate.log' if mut else 'xr31_main.log');t=log.stat().st_birthtime
 m=dict(manifest);m.update(claim_id='HR01-DR4-XR31'+suffix,command=[sys.executable,str(O/'mirror/real_research/cross_thread_review_2026_09_26/XR31_k04_f6_stability.py')],mathematics={'assertion_tested':'Slaved four-form kernel fold, longitudinal instability, and named mutation-control failure.','coefficient_domain':'binary64 plus sympy symbolic and mpmath 40-digit routes','conventions':'Fixed flux Routh reduction, k04 Z_four-form/beta^2=8; tied-alt additional diagnostic distinguished from ordinary alt.','inputs':[output(R/'real_research/cross_thread_review_2026_09_26/XR31_k04_f6_stability.py')],'bounds':{'full_script':True,'MUTATE':int(mut),'runs':'all original checks and original grid'},'non_claims':['No nonlinear endpoint or stable exterior derived.','Dynamical rate conditional on the chain-root kinetic form.','Not a theorem excluding all four-form theories.']},run={'started_at':stamp(t),'runtime_seconds':row['seconds'],'exit_status':row['rc'],'start_time_provenance':'Log creation (filesystem birth time), opened immediately before subprocess launch.'},outputs=[output(log),output(O/'mirror/real_research/cross_thread_review_2026_09_26'/('XR31_k04_f6_stability_results'+suffix+'.json'))],checks=['Every main/mutation check verdict matches original.','Main fold discrepancy <=6.4e-12.','Mutation fails fold-requiring checks rather than crashing.'],result='Expected failure control reproduced.' if mut else 'Slaved instability and corrective numeric results reproduced within solver tolerances.',residual_risks=['Retains declared original finite ranges and kinetic-form assumptions.','Historical input hashes before this bounded launch not recorded; source code copied and current input hashes provided separately.','Version-1 manifest has weaker resource/input provenance than a bounded-runner v2 record.'])
 (O/('xr31'+suffix.lower()+'_manifest.json')).write_text(json.dumps(m,indent=2))
