import Mathlib

/-!
# CFG332 -- Lean certificate of the decisive scalars (outer-halo globulars, three routes)
Generated by cfg332_lean_gen.py from cfg332_globulars_results.json; inputs rounded OUTWARD to 1e-4.
CERTIFIED: rational interval inequalities on those inputs (norm_num). NOT CERTIFIED: the chi^2/Fisher statistics,
the QUMOND solve, or any physics; this checks the arithmetic of the claims as stated. Zero sorry.
-/

/-- Route 1(a) owned/Newtonian, Ups 1.6: sigma_N/sigma_obs for NGC 2419 lies in [0.979, 0.9811] -/
theorem r1a_ratio_NGC2419 : (979/1000 : ℚ) ≤ (46757/10000 : ℚ) / (4771/1000 : ℚ) ∧ (23379/5000 : ℚ) / (47709/10000 : ℚ) ≤ (9811/10000 : ℚ) := by norm_num

/-- Route 1(a) owned/Newtonian, Ups 1.6: sigma_N/sigma_obs for Pal 3 lies in [0.4359, 0.438] -/
theorem r1a_ratio_Pal3 : (4359/10000 : ℚ) ≤ (1857/2500 : ℚ) / (17/10 : ℚ) ∧ (7429/10000 : ℚ) / (17/10 : ℚ) ≤ (219/500 : ℚ) := by norm_num

/-- Route 1(a): Pal 3 needs a Newtonian M/L_V = 1.6 (sigma_obs/sigma_N)^2 above the SPS ceiling 2.2 (by > 3x) -/
theorem r1a_pal3_needs_ups_above_sps : (16/10 : ℚ) * ((17/10 : ℚ) / (7429/10000 : ℚ))^2 > 3 * (22/10 : ℚ) := by norm_num

/-- Route 1(a) owned/Newtonian, Ups 1.6: sigma_N/sigma_obs for Pal 4 lies in [1.133, 1.1351] -/
theorem r1a_ratio_Pal4 : (1133/1000 : ℚ) ≤ (9979/10000 : ℚ) / (22/25 : ℚ) ∧ (499/500 : ℚ) / (22/25 : ℚ) ≤ (11351/10000 : ℚ) := by norm_num

/-- Route 1(a) owned/Newtonian, Ups 1.6: sigma_N/sigma_obs for Pal 14 lies in [0.8442, 0.8463] -/
theorem r1a_ratio_Pal14 : (4221/5000 : ℚ) ≤ (3/5 : ℚ) / (71/100 : ℚ) ∧ (6001/10000 : ℚ) / (71/100 : ℚ) ≤ (8463/10000 : ℚ) := by norm_num

/-- Route 1(b-B) vs (b-EFE), canonical, NGC 2419: isolated boost >= algebraic EFE boost -/
theorem r1b_iso_ge_efe_canonical_NGC2419 : (8267/5000 : ℚ) ≥ (16479/10000 : ℚ) := by norm_num

/-- Route 1(b-B) vs (b-EFE), canonical, Pal 3: isolated boost >= algebraic EFE boost -/
theorem r1b_iso_ge_efe_canonical_Pal3 : (73603/10000 : ℚ) ≥ (15579/2500 : ℚ) := by norm_num

/-- Route 1(b-B) vs (b-EFE), canonical, Pal 4: isolated boost >= algebraic EFE boost -/
theorem r1b_iso_ge_efe_canonical_Pal4 : (6303/1250 : ℚ) ≥ (47043/10000 : ℚ) := by norm_num

/-- Route 1(b-B) vs (b-EFE), canonical, Pal 14: isolated boost >= algebraic EFE boost -/
theorem r1b_iso_ge_efe_canonical_Pal14 : (52163/5000 : ℚ) ≥ (15923/2500 : ℚ) := by norm_num

/-- Route 1(b-B) vs (b-EFE), alt, NGC 2419: isolated boost >= algebraic EFE boost -/
theorem r1b_iso_ge_efe_alt_NGC2419 : (1753/1000 : ℚ) ≥ (17469/10000 : ℚ) := by norm_num

/-- Route 1(b-B) vs (b-EFE), alt, Pal 3: isolated boost >= algebraic EFE boost -/
theorem r1b_iso_ge_efe_alt_Pal3 : (16071/2000 : ℚ) ≥ (16987/2500 : ℚ) := by norm_num

/-- Route 1(b-B) vs (b-EFE), alt, Pal 4: isolated boost >= algebraic EFE boost -/
theorem r1b_iso_ge_efe_alt_Pal4 : (13719/2500 : ℚ) ≥ (25579/5000 : ℚ) := by norm_num

/-- Route 1(b-B) vs (b-EFE), alt, Pal 14: isolated boost >= algebraic EFE boost -/
theorem r1b_iso_ge_efe_alt_Pal14 : (114119/10000 : ℚ) ≥ (69461/10000 : ℚ) := by norm_num

/-- Route 2 branch K: Pal 4's MF-depleted stellar M/L (0.604) is more than twice what the law needs (0.264, canonical) -/
theorem r2_K_exceeds_required_Pal4 : (1207/2000 : ℚ) > 2 * (529/2000 : ℚ) := by norm_num

/-- Route 2 branch K: Pal 14's MF-depleted stellar M/L (0.875) is more than twice what the law needs (0.352, canonical) -/
theorem r2_K_exceeds_required_Pal14 : (4373/5000 : ℚ) > 2 * (3517/10000 : ℚ) := by norm_num

/-- Route 3, canonical, Pal 14: full-QUMOND boost >= algebraic-EFE boost, so sigma_num/sigma_alg >= 1 (computed 1.0109) -/
theorem r3_num_ge_alg_canonical_Pal14 : (16273/2500 : ℚ) / (15923/2500 : ℚ) ≥ 1 := by norm_num

/-- Route 3, canonical, Pal 3: full-QUMOND boost >= algebraic-EFE boost, so sigma_num/sigma_alg >= 1 (computed 1.0621) -/
theorem r3_num_ge_alg_canonical_Pal3 : (7029/1000 : ℚ) / (15579/2500 : ℚ) ≥ 1 := by norm_num

/-- Route 3, canonical, Pal 4: full-QUMOND boost >= algebraic-EFE boost, so sigma_num/sigma_alg >= 1 (computed 1.0273) -/
theorem r3_num_ge_alg_canonical_Pal4 : (24821/5000 : ℚ) / (47043/10000 : ℚ) ≥ 1 := by norm_num

/-- Route 3, canonical: the full EFE trims Pal 14's isolated boost by at most 0.3771 -/
theorem r3_pal14_trim_bound_canonical : 1 - (16273/2500 : ℚ) / (104327/10000 : ℚ) ≤ (3771/10000 : ℚ) := by norm_num

/-- Route 3, alt, Pal 14: full-QUMOND boost >= algebraic-EFE boost, so sigma_num/sigma_alg >= 1 (computed 1.0110) -/
theorem r3_num_ge_alg_alt_Pal14 : (71001/10000 : ℚ) / (69461/10000 : ℚ) ≥ 1 := by norm_num

/-- Route 3, alt, Pal 3: full-QUMOND boost >= algebraic-EFE boost, so sigma_num/sigma_alg >= 1 (computed 1.0625) -/
theorem r3_num_ge_alg_alt_Pal3 : (76713/10000 : ℚ) / (16987/2500 : ℚ) ≥ 1 := by norm_num

/-- Route 3, alt, Pal 4: full-QUMOND boost >= algebraic-EFE boost, so sigma_num/sigma_alg >= 1 (computed 1.0276) -/
theorem r3_num_ge_alg_alt_Pal4 : (10803/2000 : ℚ) / (25579/5000 : ℚ) ≥ 1 := by norm_num

/-- Route 3, alt: the full EFE trims Pal 14's isolated boost by at most 0.3789 -/
theorem r3_pal14_trim_bound_alt : 1 - (71001/10000 : ℚ) / (2853/250 : ℚ) ≤ (3789/10000 : ℚ) := by norm_num

/-- Decision: route1_a_owned T = 2.834 / 2.834 sigma, both > 2 => not MATCH -/
theorem dec_route1_a_owned_not_match : (28339/10000 : ℚ) > 2 ∧ (28339/10000 : ℚ) > 2 := by norm_num

/-- Decision: route1_b_EFE_h93 T = 4.132 / 4.455 sigma, both > 2 => not MATCH -/
theorem dec_route1_b_EFE_h93_not_match : (41317/10000 : ℚ) > 2 ∧ (44553/10000 : ℚ) > 2 := by norm_num

/-- Decision: route1_b_B_isolated T = 5.071 / 5.406 sigma, both > 2 => not MATCH -/
theorem dec_route1_b_B_isolated_not_match : (5071/1000 : ℚ) > 2 ∧ (6757/1250 : ℚ) > 2 := by norm_num

/-- Decision: route2_S T = 2.549 / 2.835 sigma, both > 2 => not MATCH -/
theorem dec_route2_S_not_match : (5097/2000 : ℚ) > 2 ∧ (28353/10000 : ℚ) > 2 := by norm_num

/-- Decision: route2_K T = 2.166 / 2.401 sigma, both > 2 => not MATCH -/
theorem dec_route2_K_not_match : (2707/1250 : ℚ) > 2 ∧ (6003/2500 : ℚ) > 2 := by norm_num

/-- Decision: route3_qumond T = 4.282 / 4.618 sigma, both > 2 => not MATCH -/
theorem dec_route3_qumond_not_match : (42821/10000 : ℚ) > 2 ∧ (46179/10000 : ℚ) > 2 := by norm_num

-- theorem count: 29
