#!/usr/bin/env python3
"""
oxDNA Setup for Z² Delivery Matrix (DNA Tetrahedron)
Generates the topology and configuration files for a 30nm DNA tetrahedron.
"""

import numpy as np
import os

def generate_oxdna_files(output_dir="oxdna_sim"):
    os.makedirs(output_dir, exist_ok=True)
    
    # 1. Generate a simplified topology (.top)
    # A regular tetrahedron has 4 vertices and 6 edges.
    # Each edge is 88 bp (30nm). 
    # For this setup script, we generate a template for a single 6-helix bundle strut.
    
    top_file = os.path.join(output_dir, "tetrahedron.top")
    with open(top_file, "w") as f:
        f.write("7249 1450\n") # Scaffold bases, Staple bases (approx)
        # Detailed base-by-base topology generation would be thousands of lines.
        # We write a simplified header to verify the pipeline logic.
        f.write("# Generated by Z2 Delivery Matrix Blueprint\n")
        f.write("# Scaffold: M13mp18\n")
        f.write("# Edges: 6 x 6HB (88bp each)\n")
        
    # 2. Generate a simplified configuration (.conf)
    conf_file = os.path.join(output_dir, "tetrahedron.conf")
    with open(conf_file, "w") as f:
        f.write("t = 0\n")
        f.write("b = 100 100 100\n") # Box size 100x100x100 (oxDNA units)
        f.write("E = 0 0 0\n") # Energy
        # Placeholder for atomic positions
        f.write("# Atomic positions and orientations follow...\n")
        
    # 3. Generate the input file
    input_file = os.path.join(output_dir, "input")
    with open(input_file, "w") as f:
        f.write("""# oxDNA2 Molecular Dynamics Configuration for Toehold Unzipping
backend = CUDA
backend_precision = mixed
interaction_type = DNA2

T = 300K
salt_concentration = 0.5
dt = 0.005
steps = 10000000

thermostat = john
newtonian_steps = 103

trajectory_file = trajectory.dat
info_file = energy.dat
print_energy_every = 10000
print_conf_interval = 10000

topology = tetrahedron.top
conf_file = tetrahedron.conf

external_forces = 1
external_forces_file = external_forces.conf
""")

    # 4. Generate external_forces.conf
    forces_file = os.path.join(output_dir, "external_forces.conf")
    with open(forces_file, "w") as f:
        f.write("""{
    "type": "mutual_trap",
    "particle": 1450,
    "ref_particle": 320,
    "stiff": 1.0,
    "r0": 0.5,
    "rate": 0.0001
}
""")

    print(f"[+] oxDNA simulation files generated in {output_dir}")
    print(f"    - {top_file}")
    print(f"    - {conf_file}")
    print(f"    - {input_file}")
    print(f"    - {forces_file}")

if __name__ == "__main__":
    generate_oxdna_files()
