#!/usr/bin/env python3
"""PRICE the single-metric 'Metric-Bundle-MMG' proposal.

Variables (ADM):  phi_N = ln N  (log lapse),  q = (1/6) ln det(gamma_ij)  (log spatial-volume/conformal).
Weak field (longitudinal/Newtonian gauge):  phi_N = Phi/c^2 ,  q = -Psi/c^2.
  sigma = phi_N - q = (Phi + Psi)/c^2      <- MOND is a constraint on this
  chi   = phi_N + q = (Phi - Psi)/c^2      <- NO-SLIP demands chi = 0 (Phi = Psi)

Decisive question: is chi=0 GENERATED by the Dirac constraint chain, or IMPOSED BY HAND?
We check the three load-bearing algebraic facts with sympy:

 (A) chi=0 is a LAPSE-FIXING (slicing) condition  N = (det gamma)^{-1/6}  -- i.e. it fixes the lapse
     as a local function of the spatial metric => it selects a foliation. Also: neither sigma nor chi is
     the 4D-covariant volume scalar ln|det g4| = 2 phi_N + 6 q, so BOTH are foliation-dependent combos.

 (B) DC-013 slip-lock: a diff-invariant single metric locks Psi/Phi = eta = (4L+m)/(8L+m).
     eta=1 (Phi=Psi) <=> L=0 (NO MOND enhancement). Massless limit eta(m=0)=1/2 = known f(R) gamma.

 (C) OVERDETERMINATION: the diff-invariant dynamics give Psi = eta*Phi with eta!=1 whenever L>0;
     chi=0 demands Psi=Phi. Simultaneous => (eta-1)Phi=0 => Phi=0 (trivial) unless L=0.
     So chi=0 is NOT a consequence of the diff-invariant chain -- it clashes with it (except trivially).

 (D) Constraint-count / second-class demotion (minisuperspace bracket): N is an ADM Lagrange multiplier;
     the Dirac chain from its primary constraint p_N~0 generates the Hamiltonian constraint H (=> the (1,-2)
     slip-lock of DC-013), NOT chi=0. Adding chi=0 as a lapse-fixing condition has {chi,H}!=0 => (chi,H)
     second class => H demoted from first class => refoliation (time-diffeo) invariance LOST => preferred frame.
"""
import sympy as sp

print("="*78)
print("(A) chi=0 as a LAPSE-FIXING / SLICING condition, and (non)covariance of sigma,chi")
print("="*78)
N, detg = sp.symbols('N detg', positive=True)           # detg = det(gamma_ij)
phi_N   = sp.log(N)
q       = sp.Rational(1,6)*sp.log(detg)
sigma   = phi_N - q
chi     = phi_N + q

# solve chi=0 for the lapse N
Nsol = sp.solve(sp.Eq(chi, 0), N)
print("phi_N = ln N ,  q = (1/6) ln det(gamma)")
print("chi = phi_N + q = 0   =>   N =", Nsol, "  i.e.  N = (det gamma)^(-1/6)")
print("  -> chi=0 fixes the LAPSE as a local function of the spatial metric = a slicing/foliation condition.")

# covariant 4-volume scalar:  -det(g4) = N^2 det(gamma)  => ln|det g4| = 2 phi_N + 6 q
# express the coeff vectors in the (phi_N, q) basis
def coeffs(expr):
    return (sp.simplify(sp.diff(expr, sp.log(N))*0 + expr.coeff(phi_N)) if False else None)
# do it explicitly with independent symbols to read off coefficients
a, b = sp.symbols('a b')                 # a<->phi_N , b<->q
covariant = 2*a + 6*b                    # ln|det g4|
sig_v     = 1*a - 1*b                    # sigma
chi_v     = 1*a + 1*b                    # chi
print("\n4D covariant volume scalar  ln|det g4| = 2*phi_N + 6*q   -> coeff vector (phi_N,q) = (2,6) ~ (1,3)")
print("sigma  -> (1,-1) ;  chi -> (1,1)")
for name, vec in [("sigma", (1,-1)), ("chi", (1,1))]:
    lam = sp.symbols('lam')
    sols = sp.solve([sp.Eq(vec[0], lam*1), sp.Eq(vec[1], lam*3)], lam, dict=True)
    print(f"  is {name} proportional to the covariant (1,3)?  solve -> {sols}  (empty => NOT covariant)")
print("  -> sigma and chi are BOTH foliation-dependent (built from the lapse); only (1,3)=phi_N+3q is a 4-scalar.")

print()
print("="*78)
print("(B) DC-013 slip-lock:  eta = Psi/Phi = (4L+m)/(8L+m)")
print("="*78)
L, m, Phi, Psi = sp.symbols('L m Phi Psi', real=True)
eta = (4*L + m)/(8*L + m)
print("eta =", eta)
print("eta at m=0 (massless, long-range) =", sp.simplify(eta.subs(m,0)), "  = known f(R) PPN gamma = 1/2  [check]")
print("eta at L=0 (no scalar coupling)   =", sp.simplify(eta.subs(L,0)), "  = 1 = GR (Phi=Psi)")
solL = sp.solve(sp.Eq(eta, 1), L)
print("solve eta = 1 (i.e. chi=0, Phi=Psi) for L  =>  L =", solL, "  (ONLY the no-MOND point)")
print("  -> Phi=Psi is possible only when the MOND/enhancement coupling L=0. Any L>0 (real MOND) => eta<1 => Phi!=Psi.")

print()
print("="*78)
print("(C) OVERDETERMINATION of the linearized (Phi,Psi) system")
print("="*78)
# diff-invariant dynamics (DC-013):  Psi = eta*Phi.   no-slip constraint chi=0:  Psi = Phi.
eq_dyn  = sp.Eq(Psi, eta*Phi)     # what the Dirac/diff chain gives
eq_slip = sp.Eq(Psi, Phi)         # what chi=0 demands
sol = sp.solve([eq_dyn, eq_slip], [Psi, Phi], dict=True)
print("dyn (DC-013): Psi = eta*Phi ;   slip (chi=0): Psi = Phi")
print("simultaneous solution:", sol)
# reduce to condition on Phi
combined = sp.simplify((eta - 1)*Phi)
print("subtracting: (eta-1)*Phi = 0  ->", combined, " = 0")
print("  => Phi = 0 (trivial) UNLESS eta=1 UNLESS L=0. So for real MOND (L>0) the only common solution is Phi=Psi=0.")
print("  => chi=0 is INCOMPATIBLE with the diff-invariant chain except trivially => it is NOT generated by it.")

print()
print("="*78)
print("(D) minisuperspace Dirac check: does preserving H generate chi, or is chi second-class WITH H?")
print("="*78)
# Toy homogeneous slice: config vars n=phi_N (lapse, MULTIPLIER) and s=q (dynamical, has momentum p).
# Diff-invariant single metric => a Hamiltonian constraint of the form H = f(p,s) with N a free multiplier;
# its preservation under evolution is what the ADM chain enforces (=> the (1,-2) locking at linear order).
# chi = n + s.  As an ADDED lapse-fixing condition we test {chi, H}.
n, s, p = sp.symbols('phi_N q p', real=True)          # n = lapse multiplier, (s,p) canonical pair
# generic Hamiltonian constraint (kinetic in p, plus potential); the key is only that H depends on p.
al, be = sp.symbols('alpha beta', positive=True)
H = al*p**2 + be*s          # representative first-class Hamiltonian-constraint density (depends on p)
chi_conf = n + s
# canonical Poisson bracket on the (s,p) pair (n is a multiplier: {n, anything canonical}=0)
def PB(F, G):
    return sp.diff(F, s)*sp.diff(G, p) - sp.diff(F, p)*sp.diff(G, s)
br = sp.simplify(PB(chi_conf, H))
print("H (representative diff-invariant Ham. constraint) =", H)
print("chi = phi_N + q ;   {chi, H} =", br, "  (nonzero as soon as H depends on the momentum p)")
print("  -> {chi,H} != 0  => (chi, H) are SECOND CLASS => H can no longer be a first-class generator of")
print("     time-reparametrization (refoliation) => that gauge symmetry is REMOVED => preferred foliation.")
print("  -> Equivalently: the Dirac chain of the multiplier N generates H (the (1,-2) slip-lock), NOT chi;")
print("     chi=0 is an EXTRA lapse-fixing condition imposed BY HAND.")

print()
print("="*78)
print("VERDICT")
print("="*78)
print("chi=0 is IMPOSED BY HAND, not generated by the diff-invariant Dirac chain (which instead yields the")
print("DC-013 (1,-2) slip-lock with eta!=1, i.e. Phi!=Psi for any MOND coupling L>0). Two readings:")
print("  * chi=0 as a GAUGE (lapse-fixing) condition: legal in a diff-invariant theory, but the slip Phi-Psi")
print("    is gauge-INVARIANT (Bardeen), so it stays at the DC-013 value !=0 -> no-slip NOT enforced, MOND")
print("    lensing still fails.")
print("  * chi=0 as a PHYSICAL constraint: {chi,H}!=0 makes H second-class, breaks refoliation invariance =>")
print("    PREFERRED-FRAME / khronometric / MMG theory. A vector/khronon must supply the off-ray anisotropy")
print("    that pushes eta back to 1 -- exactly TeVeS/AeST/MMG constrained-MOND.")
print("=> Metric-Bundle-MMG COLLAPSES onto the preferred-frame MMG constrained-MOND chassis (sigma carries the")
print("   constrained-MOND Poisson eq; chi=0 is the khronon-enforced no-slip). No new escape from DC-013.")
