import ChainCert.Chain
import ChainCert.Fluid
import ChainCert.PointMass
import ChainCert.Profile
import ChainCert.Cusp
import ChainCert.Gauss
import ChainCert.Separation
import ChainCert.Exchange
import ChainCert.Footing
import ChainCert.Ownership
import ChainCert.Theory
import ChainCert.A0Numeric
import ChainCert.DoorEleven
import ChainCert.Action
import ChainCert.Dimension
import ChainCert.FluidLink

/-! `lake build ChainCert.Axioms` prints the axioms of every theorem in the library; every line must show only
    [propext, Classical.choice, Quot.sound] (checked by `verify_chain.sh`). -/

#print axioms C1_exponent_matrix_det
#print axioms C1_a0_form_unique
#print axioms C1_a0_form_iff
#print axioms C2_nuBeta_one
#print axioms C2_nuBeta_mul_sqrt
#print axioms C2_nuBeta_deep
#print axioms C2_deep_mond_flat_speed
#print axioms C2_btfr_from_vacuum
#print axioms C3_conservation
#print axioms C3_max_rule_monotone
#print axioms C4_rival_exceeds_flat
#print axioms C4_rival_strictMono
#print axioms C4_E_at_two_point_five
#print axioms C4_flat_iff_rho_const
#print axioms C5_kappa_free
#print axioms nuMono_aux
#print axioms nuMono_deep
#print axioms nuMono_btfr_from_vacuum
#print axioms ChainPremises.a0_pos
#print axioms ChainPremises.a0_flat
#print axioms ChainPremises.btfr_limit
#print axioms ChainPremises.btfr_limit_redshift_independent
#print axioms zero_point_linear_in_kappa
#print axioms rhoFluid_hasDeriv
#print axioms fluid_pressure
#print axioms fluid_pressure_bounds
#print axioms cap_a0_tie
#print axioms cap_a0_eq
#print axioms ChainB.sx_sq
#print axioms ChainB.sx_pos
#print axioms ChainB.sx_hasDeriv
#print axioms ChainB.Mc_hasDerivAt
#print axioms ChainB.rhoC_eq_dMc
#print axioms ChainB.target_ODE
#print axioms ChainB.total_u_sq
#print axioms ChainB.gtot_eq_P2
#print axioms ChainB.charge_identity
#print axioms ChainB.hydrostatic
#print axioms ChainB.dispersion_half_vc_sq
#print axioms ChainB.rhoC_hasDeriv
#print axioms ChainB.Pfun_logderiv
#print axioms ChainB.rhoC_logderiv
#print axioms ChainB.GammaEff_eq
#print axioms ChainB.GammaX_eq
#print axioms ChainB.GammaX_bounds
#print axioms ChainB.GammaX_eq_two_iff
#print axioms ChainB.GammaX_strictAntiOn
#print axioms ChainB.GammaX_tendsto_zero
#print axioms ChainB.GammaX_tendsto_atTop
#print axioms ChainB.no_single_polytrope
#print axioms ChainB.GammaEff_tendsto_zero
#print axioms ChainB.GammaEff_tendsto_atTop
#print axioms ChainC.identity_P
#print axioms ChainC.hydrostatic_general
#print axioms ChainC.charge_nonneg
#print axioms ChainC.rhoC_nonneg
#print axioms ChainC.Pext_tendsto_zero
#print axioms ChainC.pressure_unique
#print axioms ChainC.pressure_nonneg
#print axioms ChainC.pressure_pos
#print axioms ChainC.dispersion_ratio
#print axioms ChainC.target_iff_ode
#print axioms ChainC.ode_hasDerivAt
#print axioms ChainC.w_eq
#print axioms ChainC.gtot_pointMass
#print axioms ChainC.pointMass_target
#print axioms ChainC.Pext_pointMass
#print axioms ChainC.pointMass_config
#print axioms ChainC.pointMass_decay
#print axioms ChainC.pointMass_pressure_pos
#print axioms ChainC.pointMass_hydrostatic
#print axioms ChainC.pointMass_ode
#print axioms ChainC.isothermal_config
#print axioms ChainC.exp_profile_identity_P
#print axioms ChainC.exp_profile_decay
#print axioms Cusp.m_zero
#print axioms Cusp.m_hasDerivAt
#print axioms Cusp.le_of_deriv_nonneg
#print axioms Cusp.m_strictMonoOn
#print axioms Cusp.m_pos
#print axioms Cusp.m_upper
#print axioms Cusp.m_lower
#print axioms Cusp.m_elastic
#print axioms Cusp.m_div_sq_antitoneOn
#print axioms Cusp.m_ratio_tendsto
#print axioms Cusp.nfw_small_r_form1
#print axioms Cusp.nfw_small_r_K
#print axioms Cusp.nfw_rho_s_form
#print axioms Cusp.nfw_small_r_rho_s
#print axioms Cusp.Kfam_identity
#print axioms Cusp.Kfam_ratio
#print axioms Cusp.leading_exponent
#print axioms Cusp.Kfam_bracket
#print axioms Cusp.log_lo
#print axioms Cusp.log_hi
#print axioms Cusp.exp2_le
#print axioms Cusp.exp3_le
#print axioms Cusp.exp3_ge
#print axioms Cusp.exp_4log2
#print axioms Cusp.m5_ge
#print axioms Cusp.m20_le
#print axioms Cusp.m_ratio_range
#print axioms Cusp.Kfam_bracket_range
#print axioms Cusp.c_at_1e9
#print axioms Cusp.R_at_1e9
#print axioms Cusp.t_bounds
#print axioms Cusp.u_bounds
#print axioms Cusp.c_at_1e8
#print axioms Cusp.c_at_1e10
#print axioms Cusp.c1_bounds
#print axioms Cusp.c2_bounds
#print axioms Cusp.m_c1_lo
#print axioms Cusp.m_c1_hi
#print axioms Cusp.m_c2_hi
#print axioms Cusp.m_c2_lo
#print axioms Cusp.debris_corollary
#print axioms Cusp.range_witness
#print axioms gateA_off
#print axioms gateA_on
#print axioms gauss_dyn_mass
#print axioms gauss_off_mass
#print axioms gauss_flux_deriv
#print axioms gauss_psi_momentum_zero
#print axioms gauss_second_source
#print axioms sep_strictMono
#print axioms sep_lt_cap
#print axioms sep_tendsto_cap
#print axioms sep_solve
#print axioms sep_solve_unique
#print axioms sep_no_solution
#print axioms sep_zero_floor
#print axioms exch_beta_pos
#print axioms exch_speed_gt_one
#print axioms exch_speed_eq_iff
#print axioms exch_bare_speed_lt
#print axioms exch_symbol_charpoly
#print axioms exch_symbol_eigen_iff
#print axioms exch_symbol_roots_distinct
#print axioms exch_static_theta
#print axioms exch_static_reaction
#print axioms exch_reaction_via_delta
#print axioms exch_reaction_ne_rled
#print axioms exch_reaction_neg_of_delta_lt_one
#print axioms exch_static_delta_fbb
#print axioms exch_delta_mul_fbb
#print axioms exch_open_delta_zero
#print axioms exch_fbb_gt_one
#print axioms exch_fbb_large
#print axioms exch_not_both_small
#print axioms exch_beta_eq_epsc_lamt
#print axioms exch_freal_split
#print axioms exch_freal_open
#print axioms exch_freal_lt_one
#print axioms exch_retardation_iff
#print axioms exch_sigma_strictMono
#print axioms exch_sigma_bounds
#print axioms exch_sigma_pointmass
#print axioms exch_sigma_pointmass_strictAnti
#print axioms exch_shell_integral
#print axioms exch_hyd_reaction
#print axioms exch_hyd_reaction_per_mass
#print axioms footing_Z_factor
#print axioms footing_kappaM_iff
#print axioms footing_ratio_sq
#print axioms foot_lam0
#print axioms foot_lam1
#print axioms foot_bounds
#print axioms foot_strictMono
#print axioms foot_kappa_cancels
#print axioms foot_lambda_of_rise
#print axioms foot_rise_of_lambda
#print axioms foot_lambda_of_Omeff
#print axioms Ownership.owned_internal_newton
#print axioms Ownership.top_internal_law
#print axioms Ownership.owned_boost_one
#print axioms Ownership.wideBinary_gammaHat_one
#print axioms Ownership.top_boost_gt_one_nuMono
#print axioms Ownership.top_boost_gt_one_P2
#print axioms Ownership.ownership_distinguishes
#print axioms Ownership.ownership_not_field_local
#print axioms Ownership.noEFE_continuousLinear
#print axioms Ownership.noEFE_linear_R3
#print axioms Ownership.noEFE_linear_real
#print axioms Ownership.noEFE_linear_ray
#print axioms Ownership.nonlinear_not_efeFree_real
#print axioms Ownership.nonlinear_not_efeFree
#print axioms Ownership.deep_not_efeFreeRay
#print axioms Ownership.deep_kernel_ne_one
#print axioms Ownership.law_not_efeFreeRay
#print axioms Ownership.nuMono_law_has_EFE
#print axioms Ownership.P2_law_has_EFE
#print axioms Ownership.P2_sqrt_law_has_EFE
#print axioms Ownership.vecLaw_not_efeFree
#print axioms Ownership.vecLaw_R3_not_efeFree
#print axioms CandidateB.a0_eq
#print axioms CandidateB.a0_flat
#print axioms CandidateB.btfr
#print axioms CandidateB.rival_separates
#print axioms CandidateB.a0_numeric
#print axioms CandidateB.owned_boost_one
#print axioms CandidateB.gammaHat_one
#print axioms CandidateB.merged_law_has_EFE
#print axioms CandidateB.merged_vecLaw_has_EFE
#print axioms CandidateB.ownership_nonlocal
#print axioms CandidateB.cold_budget
#print axioms CandidateB.cold_edge_mass
#print axioms CandidateB.cold_edge_monotone
#print axioms CandidateB.predictions
#print axioms CandidateB.nonempty_fin2
#print axioms A0Numeric.a0_of_rhoLambda
#print axioms A0Numeric.a0num_interval
#print axioms A0Numeric.a0_interval
#print axioms A0Numeric.a0_point
#print axioms DoorEleven.boosted_flux
#print axioms DoorEleven.vacuum_no_flux
#print axioms DoorEleven.flux_zero_iff
#print axioms DoorEleven.vacuum_boost_invariant
#print axioms DoorEleven.eta4_mul_self
#print axioms DoorEleven.vacuum_momentum_density_zero
#print axioms AqualAction.aqual_momentum
#print axioms AqualAction.gauss_form
#print axioms AqualAction.AqualMu.mu_pos
#print axioms AqualAction.AqualMu.inv_spec
#print axioms AqualAction.AqualMu.inv_pos
#print axioms AqualAction.AqualMu.inv_mul_mu
#print axioms AqualAction.AqualMu.inv_unique
#print axioms AqualAction.AqualMu.nu_mul
#print axioms AqualAction.AqualMu.mu_mul_nu
#print axioms AqualAction.AqualMu.kernel_of_gauss
#print axioms AqualAction.AqualMu.gauss_of_kernel
#print axioms AqualAction.AqualMu.gauss_iff_kernel
#print axioms AqualAction.AqualMu.spherical_kernel
#print axioms AqualAction.AqualMu.inv_tendsto_zero
#print axioms AqualAction.AqualMu.nu_deep
#print axioms AqualAction.onto_of_regimes
#print axioms AqualAction.muP2_mul
#print axioms AqualAction.muP2_to_nuP2
#print axioms AqualAction.nuP2_to_muP2
#print axioms AqualAction.muP2_iff
#print axioms AqualAction.P2_gauss_iff_kernel
#print axioms AqualAction.muP2_deep
#print axioms AqualAction.muP2_newton
#print axioms AqualAction.muP2_onto_from_regimes
#print axioms AqualAction.nuP2_of_action
#print axioms AqualAction.nuP2_of_action_nuBeta
#print axioms AqualAction.P2_deep_from_action
#print axioms CandidateB_Action.kernel_deep
#print axioms CandidateB_Action.predictions
#print axioms CandidateB_Action.top_solves_gauss
#print axioms CandidateB_Action.top_unique_gauss
#print axioms CandidateB_Action.top_from_field_equation
#print axioms CandidateB_Action.kernel_P2
#print axioms CandidateB_Action.nonempty_fin2
#print axioms Dimension.C1_in_framework
#print axioms Dimension.length_GMc_iff
#print axioms Dimension.length_GMc_mass_exp
#print axioms Dimension.no_sqrtM_length_GMc
#print axioms Dimension.velocity_GMc_iff
#print axioms Dimension.no_quarterM_velocity_GMc
#print axioms Dimension.massExp_mono
#print axioms Dimension.basis_decomp
#print axioms Dimension.GcSpan_iff
#print axioms Dimension.sqrtM_length_iff
#print axioms Dimension.acc_from_GcX_iff
#print axioms Dimension.sqrtM_length_iff_acc
#print axioms Dimension.sqrtM_length_acc
#print axioms Dimension.acc_unique
#print axioms Dimension.acc_c_family
#print axioms Dimension.hbar_admissible
#print axioms Dimension.hbar_not_acc_c
#print axioms Dimension.not_only_accelerations
#print axioms Dimension.force_not_admissible
#print axioms Dimension.rho_length
#print axioms Dimension.quarterM_velocity_iff
#print axioms Dimension.quarterM_velocity_acc
#print axioms FluidLink.link_general
#print axioms FluidLink.link_general_iff
#print axioms FluidLink.link_units
#print axioms FluidLink.link_sq
#print axioms FluidLink.link_flat
#print axioms CandidateB.fluid_cap_a0
