#!/usr/bin/env python3
"""
DYNAMIC STRATEGY GENERATOR
==========================

The brain of HermesFlow v2.0 - dynamically generates search strategies
for ANY research topic by reasoning about the domain, not pattern matching.

This replaces hardcoded SYNONYMS and DOMAIN_KEYWORDS with dynamic
LLM-guided strategy generation.

The key insight: Instead of encoding what we know about tornados or
hurricanes, we ASK the model what it knows about ANY topic and let
it guide the search.

Architecture:
    1. TopicAnalyzer    - Deeply understand the research goal
    2. StrategyPlanner  - Generate search strategies dynamically
    3. AdaptiveExplorer - Learn and adjust during exploration
    4. OutcomeTracker   - Remember what works for future searches

Author: Carl Zimmerman
Date: May 5, 2026
"""

import os
import json
import subprocess
from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass, field, asdict
from datetime import datetime
from pathlib import Path

LEGOMENA_MODEL = os.environ.get("LEGOMENA_MODEL", "legomena-moe")


@dataclass
class TopicProfile:
    """
    Dynamic understanding of a research topic.

    Generated by asking Legomena, not hardcoded.
    """
    topic: str
    domain: str

    # Dynamically discovered - not hardcoded
    key_terms: List[str] = field(default_factory=list)
    synonyms: Dict[str, List[str]] = field(default_factory=dict)
    authoritative_sources: List[Dict] = field(default_factory=list)
    expected_formats: List[str] = field(default_factory=list)
    target_quantities: List[str] = field(default_factory=list)
    known_values: Dict[str, float] = field(default_factory=dict)
    z2_predictions: Dict[str, str] = field(default_factory=dict)

    # Learning from exploration
    successful_queries: List[str] = field(default_factory=list)
    failed_queries: List[str] = field(default_factory=list)
    productive_portals: List[str] = field(default_factory=list)
    dead_end_portals: List[str] = field(default_factory=list)

    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class SearchStrategy:
    """A planned search approach with reasoning."""
    query: str
    rationale: str
    expected_sources: List[str]
    fallback_queries: List[str]
    validation_criteria: List[str]
    priority: int = 1


class TopicAnalyzer:
    """
    Phase 1: Deeply understand the research topic.

    Instead of hardcoded knowledge, ASK the model:
    - What are the key terms?
    - What sources have this data?
    - What formats should we expect?
    - What does Z² predict here?
    """

    def __init__(self, verbose: bool = True):
        self.verbose = verbose

    def _log(self, msg: str):
        if self.verbose:
            print(f"[TopicAnalyzer] {msg}")

    def _ask_legomena(self, prompt: str) -> str:
        """Query the local Legomena model."""
        try:
            result = subprocess.run(
                ["ollama", "run", LEGOMENA_MODEL],
                input=prompt,
                capture_output=True,
                text=True,
                timeout=60
            )
            return result.stdout.strip() if result.returncode == 0 else ""
        except Exception as e:
            self._log(f"Legomena error: {e}")
            return ""

    def analyze(self, topic: str, domain: str,
                z2_context: str = None) -> TopicProfile:
        """
        Generate a complete TopicProfile by reasoning about the topic.

        This is the KEY difference from static approach:
        We ASK what matters, not look it up in a dictionary.
        """
        self._log(f"Analyzing topic: {topic}")
        self._log(f"Domain: {domain}")

        profile = TopicProfile(topic=topic, domain=domain)

        # Step 1: Extract key terms and synonyms
        self._log("Step 1: Extracting key terms...")
        terms_response = self._ask_legomena(f"""
I'm researching: "{topic}"
Domain: {domain}

List the 5-10 most important technical terms for this research.
For each term, list 2-3 synonyms or closely related terms.

Format your response EXACTLY as:
TERM: [term]
SYNONYMS: [syn1], [syn2], [syn3]

Example:
TERM: hurricane
SYNONYMS: cyclone, tropical storm, typhoon
""")

        profile.key_terms, profile.synonyms = self._parse_terms(terms_response)
        self._log(f"  Found {len(profile.key_terms)} key terms")

        # Step 2: Identify authoritative sources
        self._log("Step 2: Identifying data sources...")
        sources_response = self._ask_legomena(f"""
For research on "{topic}" in {domain}:

What are the 3-5 most authoritative data sources?
For each, provide:
1. Organization name
2. Database/portal name
3. URL pattern (if known)
4. Data format (CSV, FITS, NetCDF, JSON, etc.)
5. Why it's authoritative

Format as:
SOURCE: [name]
ORG: [organization]
URL: [url or pattern]
FORMAT: [format]
WHY: [reason]
""")

        profile.authoritative_sources = self._parse_sources(sources_response)
        profile.expected_formats = list(set(
            s.get('format', 'CSV') for s in profile.authoritative_sources
        ))
        self._log(f"  Found {len(profile.authoritative_sources)} sources")

        # Step 3: Identify target quantities
        self._log("Step 3: Identifying measurable quantities...")
        quantities_response = self._ask_legomena(f"""
For research on "{topic}" in {domain}:

What specific quantities or measurements should I look for in the data?
List 5-10 measurable values that would be in a dataset about this topic.

Format as one per line:
- [quantity name]: [description]
""")

        profile.target_quantities = self._parse_quantities(quantities_response)
        self._log(f"  Found {len(profile.target_quantities)} quantities")

        # Step 4: Z² predictions (if context provided)
        if z2_context:
            self._log("Step 4: Computing Z² predictions...")
            z2_response = self._ask_legomena(f"""
Z² Framework context:
{z2_context}

For the topic "{topic}" in {domain}:

What specific predictions does Z² make?
What measured values should match Z² constants?

Format as:
PREDICTION: [what Z² predicts]
FORMULA: [the formula]
EXPECTED_VALUE: [numerical value]
MEASURED_QUANTITY: [what to look for in data]
""")

            profile.z2_predictions = self._parse_z2(z2_response)
            self._log(f"  Found {len(profile.z2_predictions)} Z² predictions")

        return profile

    def _parse_terms(self, response: str) -> Tuple[List[str], Dict[str, List[str]]]:
        """Parse term/synonym response."""
        terms = []
        synonyms = {}

        current_term = None
        for line in response.split('\n'):
            line = line.strip()
            if line.startswith('TERM:'):
                current_term = line.replace('TERM:', '').strip()
                terms.append(current_term)
            elif line.startswith('SYNONYMS:') and current_term:
                syns = [s.strip() for s in line.replace('SYNONYMS:', '').split(',')]
                synonyms[current_term] = syns

        return terms, synonyms

    def _parse_sources(self, response: str) -> List[Dict]:
        """Parse sources response."""
        sources = []
        current = {}

        for line in response.split('\n'):
            line = line.strip()
            if line.startswith('SOURCE:'):
                if current:
                    sources.append(current)
                current = {'name': line.replace('SOURCE:', '').strip()}
            elif line.startswith('ORG:'):
                current['org'] = line.replace('ORG:', '').strip()
            elif line.startswith('URL:'):
                current['url'] = line.replace('URL:', '').strip()
            elif line.startswith('FORMAT:'):
                current['format'] = line.replace('FORMAT:', '').strip()
            elif line.startswith('WHY:'):
                current['why'] = line.replace('WHY:', '').strip()

        if current:
            sources.append(current)

        return sources

    def _parse_quantities(self, response: str) -> List[str]:
        """Parse quantities response."""
        quantities = []
        for line in response.split('\n'):
            line = line.strip()
            if line.startswith('- '):
                # Extract just the quantity name before the colon
                qty = line[2:].split(':')[0].strip()
                if qty:
                    quantities.append(qty)
        return quantities

    def _parse_z2(self, response: str) -> Dict[str, str]:
        """Parse Z² predictions."""
        predictions = {}
        current_pred = None

        for line in response.split('\n'):
            line = line.strip()
            if line.startswith('PREDICTION:'):
                current_pred = line.replace('PREDICTION:', '').strip()
            elif line.startswith('EXPECTED_VALUE:') and current_pred:
                predictions[current_pred] = line.replace('EXPECTED_VALUE:', '').strip()

        return predictions


class StrategyPlanner:
    """
    Phase 2: Generate search strategies dynamically.

    Instead of fixed queries, REASON about what queries would work
    for THIS specific topic.
    """

    def __init__(self, verbose: bool = True):
        self.verbose = verbose

    def _log(self, msg: str):
        if self.verbose:
            print(f"[StrategyPlanner] {msg}")

    def _ask_legomena(self, prompt: str) -> str:
        try:
            result = subprocess.run(
                ["ollama", "run", LEGOMENA_MODEL],
                input=prompt,
                capture_output=True,
                text=True,
                timeout=60
            )
            return result.stdout.strip() if result.returncode == 0 else ""
        except:
            return ""

    def plan(self, profile: TopicProfile) -> List[SearchStrategy]:
        """
        Generate ranked search strategies based on topic understanding.
        """
        self._log(f"Planning search for: {profile.topic}")

        # Build context from profile
        sources_str = "\n".join([
            f"- {s.get('name', 'Unknown')}: {s.get('url', 'URL unknown')}"
            for s in profile.authoritative_sources[:5]
        ])

        terms_str = ", ".join(profile.key_terms[:10])
        quantities_str = ", ".join(profile.target_quantities[:5])

        response = self._ask_legomena(f"""
I need to find downloadable data for research on:
Topic: {profile.topic}
Domain: {profile.domain}

Key terms: {terms_str}
Target quantities: {quantities_str}

Known authoritative sources:
{sources_str}

Generate 5 search queries ranked by likelihood of finding ACTUAL DATA FILES.
For each query, explain:
1. Why this query should work
2. What data format to expect
3. What to do if it fails

Format EXACTLY as:
QUERY 1: [search query]
RATIONALE: [why this should work]
FORMAT: [expected format]
FALLBACK: [what to try if this fails]

QUERY 2: ...
""")

        strategies = self._parse_strategies(response, profile)
        self._log(f"Generated {len(strategies)} search strategies")

        return strategies

    def _parse_strategies(self, response: str, profile: TopicProfile) -> List[SearchStrategy]:
        """Parse strategy response into SearchStrategy objects."""
        strategies = []
        current = {}
        priority = 0

        for line in response.split('\n'):
            line = line.strip()
            if line.startswith('QUERY'):
                if current.get('query'):
                    strategies.append(SearchStrategy(
                        query=current.get('query', ''),
                        rationale=current.get('rationale', ''),
                        expected_sources=[s.get('url', '') for s in profile.authoritative_sources],
                        fallback_queries=[current.get('fallback', '')],
                        validation_criteria=profile.target_quantities[:3],
                        priority=priority
                    ))
                priority += 1
                # Extract query after the colon
                current = {'query': line.split(':', 1)[1].strip() if ':' in line else ''}
            elif line.startswith('RATIONALE:'):
                current['rationale'] = line.replace('RATIONALE:', '').strip()
            elif line.startswith('FALLBACK:'):
                current['fallback'] = line.replace('FALLBACK:', '').strip()

        # Don't forget the last one
        if current.get('query'):
            strategies.append(SearchStrategy(
                query=current.get('query', ''),
                rationale=current.get('rationale', ''),
                expected_sources=[s.get('url', '') for s in profile.authoritative_sources],
                fallback_queries=[current.get('fallback', '')],
                validation_criteria=profile.target_quantities[:3],
                priority=priority
            ))

        return strategies


class DynamicValidator:
    """
    Phase 3: Validate discovered data dynamically.

    Instead of hardcoded keyword matching, ASK if the data matches
    what we're looking for.
    """

    def __init__(self, verbose: bool = True):
        self.verbose = verbose

    def _log(self, msg: str):
        if self.verbose:
            print(f"[DynamicValidator] {msg}")

    def _ask_legomena(self, prompt: str) -> str:
        try:
            result = subprocess.run(
                ["ollama", "run", LEGOMENA_MODEL],
                input=prompt,
                capture_output=True,
                text=True,
                timeout=30
            )
            return result.stdout.strip() if result.returncode == 0 else ""
        except:
            return ""

    def validate(self, data_summary: str, profile: TopicProfile) -> Tuple[bool, str, Dict]:
        """
        Dynamically validate if data matches what we're researching.

        Returns: (is_valid, reason, extracted_info)
        """
        self._log("Validating discovered data against topic profile...")

        response = self._ask_legomena(f"""
I'm researching: {profile.topic}
Domain: {profile.domain}
Looking for quantities: {', '.join(profile.target_quantities[:5])}

I found this data:
{data_summary}

Questions:
1. Does this data relate to my research topic? (YES/NO)
2. Which of my target quantities are present? (list them)
3. What columns contain the relevant measurements?
4. Is this the primary data or derived/secondary?
5. Confidence level? (HIGH/MEDIUM/LOW)

Format response as:
RELEVANT: [YES/NO]
QUANTITIES_FOUND: [list]
KEY_COLUMNS: [list]
DATA_TYPE: [primary/derived]
CONFIDENCE: [HIGH/MEDIUM/LOW]
REASONING: [brief explanation]
""")

        return self._parse_validation(response)

    def _parse_validation(self, response: str) -> Tuple[bool, str, Dict]:
        """Parse validation response."""
        is_valid = False
        reason = ""
        info = {}

        for line in response.split('\n'):
            line = line.strip()
            if line.startswith('RELEVANT:'):
                is_valid = 'YES' in line.upper()
            elif line.startswith('QUANTITIES_FOUND:'):
                info['quantities'] = line.replace('QUANTITIES_FOUND:', '').strip()
            elif line.startswith('KEY_COLUMNS:'):
                info['columns'] = line.replace('KEY_COLUMNS:', '').strip()
            elif line.startswith('CONFIDENCE:'):
                info['confidence'] = line.replace('CONFIDENCE:', '').strip()
            elif line.startswith('REASONING:'):
                reason = line.replace('REASONING:', '').strip()

        return is_valid, reason, info


class OutcomeTracker:
    """
    Phase 4: Learn from successes and failures.

    Store what works so future searches on similar topics benefit.
    """

    def __init__(self, storage_path: Path = None):
        self.storage_path = storage_path or Path(__file__).parent / "learned_strategies.json"
        self.outcomes = self._load()

    def _load(self) -> Dict:
        if self.storage_path.exists():
            with open(self.storage_path) as f:
                return json.load(f)
        return {"successes": [], "failures": [], "domain_patterns": {}}

    def _save(self):
        with open(self.storage_path, 'w') as f:
            json.dump(self.outcomes, f, indent=2)

    def record_success(self, profile: TopicProfile, strategy: SearchStrategy,
                       url: str, data_summary: str):
        """Record a successful discovery for future learning."""
        self.outcomes["successes"].append({
            "domain": profile.domain,
            "topic_keywords": profile.key_terms[:5],
            "query": strategy.query,
            "url": url,
            "timestamp": datetime.now().isoformat()
        })

        # Update domain patterns
        if profile.domain not in self.outcomes["domain_patterns"]:
            self.outcomes["domain_patterns"][profile.domain] = {
                "successful_sources": [],
                "successful_query_patterns": []
            }

        patterns = self.outcomes["domain_patterns"][profile.domain]

        # Extract URL pattern
        from urllib.parse import urlparse
        parsed = urlparse(url)
        source = f"{parsed.scheme}://{parsed.netloc}"
        if source not in patterns["successful_sources"]:
            patterns["successful_sources"].append(source)

        self._save()

    def record_failure(self, profile: TopicProfile, strategy: SearchStrategy,
                       reason: str):
        """Record a failed attempt for learning."""
        self.outcomes["failures"].append({
            "domain": profile.domain,
            "topic_keywords": profile.key_terms[:5],
            "query": strategy.query,
            "reason": reason,
            "timestamp": datetime.now().isoformat()
        })
        self._save()

    def get_domain_hints(self, domain: str) -> Dict:
        """Get learned patterns for a domain."""
        return self.outcomes["domain_patterns"].get(domain, {})


# =============================================================================
# INTEGRATED DYNAMIC EXPLORER
# =============================================================================

class DynamicHermesExplorer:
    """
    The next-generation HermesFlow that reasons instead of pattern-matches.

    Flow:
    1. Analyze topic → Generate TopicProfile
    2. Plan search → Generate SearchStrategies
    3. Execute with validation → DynamicValidator
    4. Learn from outcomes → OutcomeTracker
    """

    def __init__(self, verbose: bool = True, z2_context: str = None):
        self.verbose = verbose
        self.z2_context = z2_context or self._default_z2_context()

        self.analyzer = TopicAnalyzer(verbose)
        self.planner = StrategyPlanner(verbose)
        self.validator = DynamicValidator(verbose)
        self.tracker = OutcomeTracker()

    def _default_z2_context(self) -> str:
        """Default Z² framework context for predictions."""
        import math
        Z2 = 32 * math.pi / 3
        Z = math.sqrt(Z2)
        PHI = (1 + math.sqrt(5)) / 2

        return f"""
Z² = 32π/3 = {Z2:.6f}
Z = √(Z²) = {Z:.6f}
φ = (1+√5)/2 = {PHI:.6f}

Key predictions:
- Coefficients of variation often ≈ Z or Z²/10
- Ratios between quantities often ≈ φ or 1/φ
- Scale transitions occur at Z² boundaries
"""

    def _log(self, msg: str):
        if self.verbose:
            print(f"[DynamicHermes] {msg}")

    def explore(self, topic: str, domain: str) -> Dict:
        """
        Full dynamic exploration for any topic.

        This is the main entry point - give it ANY topic and it will:
        1. Figure out what to search for
        2. Generate search strategies
        3. Execute and validate
        4. Learn from outcomes
        """
        self._log(f"=" * 60)
        self._log(f"DYNAMIC EXPLORATION: {topic}")
        self._log(f"Domain: {domain}")
        self._log(f"=" * 60)

        # Phase 1: Understand the topic
        self._log("\n--- Phase 1: Topic Analysis ---")
        profile = self.analyzer.analyze(topic, domain, self.z2_context)

        self._log(f"Key terms: {profile.key_terms}")
        self._log(f"Sources: {[s.get('name') for s in profile.authoritative_sources]}")
        self._log(f"Quantities: {profile.target_quantities}")

        # Check for learned hints
        hints = self.tracker.get_domain_hints(domain)
        if hints.get("successful_sources"):
            self._log(f"Learned sources for {domain}: {hints['successful_sources']}")
            # Could boost these in search

        # Phase 2: Plan search strategies
        self._log("\n--- Phase 2: Strategy Planning ---")
        strategies = self.planner.plan(profile)

        for i, s in enumerate(strategies[:3]):
            self._log(f"Strategy {i+1}: {s.query[:50]}...")
            self._log(f"  Rationale: {s.rationale[:50]}...")

        # Phase 3: Execute (would integrate with actual HermesExplorer)
        self._log("\n--- Phase 3: Execution ---")
        self._log("(Would execute search strategies here)")

        # Return the dynamic profile and strategies for integration
        return {
            "profile": asdict(profile),
            "strategies": [asdict(s) for s in strategies],
            "domain_hints": hints
        }


# =============================================================================
# DEMO
# =============================================================================

if __name__ == "__main__":
    print("=" * 70)
    print("DYNAMIC STRATEGY GENERATOR DEMO")
    print("=" * 70)
    print()

    # Test with a completely new topic - NOT hardcoded
    explorer = DynamicHermesExplorer(verbose=True)

    # This should work for ANY topic without hardcoding
    result = explorer.explore(
        topic="Solar neutrino flux measurements from SNO and Super-Kamiokande",
        domain="particle_physics"
    )

    print("\n" + "=" * 70)
    print("RESULT SUMMARY")
    print("=" * 70)
    print(f"Key terms discovered: {result['profile']['key_terms']}")
    print(f"Sources identified: {len(result['profile']['authoritative_sources'])}")
    print(f"Quantities to measure: {result['profile']['target_quantities']}")
    print(f"Search strategies generated: {len(result['strategies'])}")
