#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
CFG321 -- verification of the frozen FAIL trigger (reported; it does NOT change the frozen verdict).

The main run's frozen rule fired one FAIL signature: "1-D eps 1e-3: Lyapunov exponent grows with resolution at both
steps" (lambda = 0.0124, 0.0414, 0.0663 at N = 63, 127, 255).  The rule was written to catch Hadamard-type growth that
survives the nonlinearity.  This script checks, from the main run's saved work arrays (../_external_data/cfg321_work/,
regenerated by the main script), whether the trigger has the properties such growth would have:
  V1 the fitted lambda against the band's linear growth rates (Hadamard growth would be O(k) ~ 1 in slow units, rising
     with the grid's k_max);
  V2 lambda's trend with resolution in every set and its sensitivity to the fit window (frozen window 1e-4 <= D <= 1e-1;
     alternatives: 1e-4 <= D <= 1e-2, and the fixed time window [T/2, T]);
  V3 linearity in delta over the WHOLE run: D(1e-3)/D(1e-5) at every output (100 = linear response; an order-one response
     to infinitesimal data would push it toward 1);
  V4 the maximum amplification max_t D_1e-5(t)/1e-5 against resolution.
No threshold here is a verdict: CFG321's frozen verdict stands as computed by cfg321_zero_field_nonlinear.py.

Run from the repository root (after the main script):
    python3 campaign_fresh_gravity/CFG321_zero_field_nonlinear/cfg321_verify_fail.py
"""
import os, sys, json, math
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
EXT = os.path.join(os.path.dirname(REPO), "_external_data", "cfg321_work")
OUT = {"lane": "CFG321-verify", "checks": {}, "numbers": {}}
CH = []


def P(*a):
    print(*a, flush=True)


def check(name, measured, ok):
    CH.append((name, bool(ok)))
    OUT["checks"][name] = {"ok": bool(ok), "measured": str(measured)}
    P(f"  [{'PASS' if ok else 'FAIL'}] {name}\n         measured: {measured}")


def load(dim, n, eps, delta):
    z = np.load(os.path.join(EXT, f"cfg321_nu_mono_d{dim}_n{n}_eps{eps:.0e}_delta{delta:.0e}.npz"))
    return z["snap_t"], z["snap_w"]


def D_of(wa, wb):
    return np.array([np.linalg.norm(a - b) / np.linalg.norm(a) for a, b in zip(wa, wb)])


def fit(t, D, sel):
    if sel.sum() < 8:
        return None, None, int(sel.sum())
    c = np.polyfit(t[sel], np.log(D[sel]), 1)
    pred = np.polyval(c, t[sel]); y = np.log(D[sel])
    r2 = 1 - np.sum((y - pred) ** 2) / np.sum((y - y.mean()) ** 2)
    return float(c[0]), float(r2), int(sel.sum())


P(__doc__.split("Run from")[0].strip())
main = json.load(open(os.path.join(HERE, "cfg321_zero_field_nonlinear_results.json")))
rates = [r_[4] for r_ in main["numbers"].get("C_LIN", []) if r_[3] == "growth"]
P(f"\n  band growth rates measured in C-LIN (slow units, background yhat = 1e-4): {[round(x_, 3) for x_ in rates]}")
sets = [(1, 1e-2, (63, 127, 255), 80.0), (1, 1e-3, (63, 127, 255), 80.0), (2, 1e-2, (15, 21, 29), 60.0)]
rows = {}
lam_max = 0.0
for dim, eps, Ns, T in sets:
    P(f"\n  --- {dim}-D eps {eps:.0e} ---")
    for n in Ns:
        t, wb = load(dim, n, eps, 0.0)
        _, w3 = load(dim, n, eps, 1e-3)
        _, w5 = load(dim, n, eps, 1e-5)
        D3, D5 = D_of(wb, w3), D_of(wb, w5)
        f_frozen = fit(t, D5, (D5 >= 1e-4) & (D5 <= 1e-1))
        f_alt = fit(t, D5, (D5 >= 1e-4) & (D5 <= 1e-2))
        f_win = fit(t, D5, t >= T / 2)
        ratio = D3 / D5
        rows[f"{dim}D_eps{eps:.0e}_N{n}"] = {"frozen": f_frozen, "alt": f_alt, "window": f_win,
                                            "ratio_min": float(ratio[1:].min()), "ratio_max": float(ratio[1:].max()),
                                            "Amax": float(D5.max() / 1e-5), "D5_T": float(D5[-1])}
        for f_ in (f_frozen, f_alt, f_win):
            if f_[0] is not None:
                lam_max = max(lam_max, f_[0])
        P(f"    N = {n}: lambda frozen {f_frozen[0] if f_frozen[0] is None else round(f_frozen[0], 4)} (R^2 "
          f"{f_frozen[1] if f_frozen[1] is None else round(f_frozen[1], 2)}, {f_frozen[2]} pts); D<=1e-2: "
          f"{f_alt[0] if f_alt[0] is None else round(f_alt[0], 4)}; window [T/2,T]: {round(f_win[0], 4)} (R^2 {round(f_win[1], 2)}); "
          f"D(1e-3)/D(1e-5) over the run in [{ratio[1:].min():.1f}, {ratio[1:].max():.1f}]; max amplification "
          f"{D5.max() / 1e-5:.1f}; D_1e-5(T) = {D5[-1]:.2e}")
OUT["numbers"]["rows"] = rows

check("V1 every fitted separation exponent is far below the band's linear growth rates (< 0.1 x the smallest measured "
      "rate): the trigger is a slow late-time drift, not O(k) growth",
      f"max lambda over all fits {lam_max:.4f}; smallest band rate {min(rates):.3f}", lam_max < 0.1 * min(rates))
tr = {}
for dim, eps, Ns, T in sets:
    lf = [rows[f"{dim}D_eps{eps:.0e}_N{n}"]["frozen"][0] for n in Ns]
    lw = [rows[f"{dim}D_eps{eps:.0e}_N{n}"]["window"][0] for n in Ns]
    tr[f"{dim}D_eps{eps:.0e}"] = (lf, lw)
up = [k_ for k_, (lf, lw) in tr.items() if all(x_ is not None for x_ in lf) and lf[0] < lf[1] < lf[2]]
upw = [k_ for k_, (lf, lw) in tr.items() if lw[0] < lw[1] < lw[2]]
check("V2 (reported) the rise of lambda with resolution is not common to the sets: the frozen-window lambda rises "
      "monotonically in fewer than all three sets",
      f"rising (frozen window): {up}; rising (fixed window [T/2,T]): {upw}; values {tr}", len(up) < 3)
rat_ok = all(30 <= v_["ratio_min"] and v_["ratio_max"] <= 300 for v_ in rows.values())
check("V3 the response stays linear in delta over the whole run at every resolution (D(1e-3)/D(1e-5) in [30, 300] at "
      "every output): no order-one response to infinitesimal data",
      "; ".join(f"{k_}: [{v_['ratio_min']:.1f}, {v_['ratio_max']:.1f}]" for k_, v_ in rows.items()), rat_ok)
amp = {f"{dim}D_eps{eps:.0e}": [rows[f"{dim}D_eps{eps:.0e}_N{n}"]["Amax"] for n in Ns] for dim, eps, Ns, T in sets}
grow = [k_ for k_, a_ in amp.items() if a_[1] / a_[0] > 2 and a_[2] / a_[1] > 2]
check("V4 the maximum amplification over the run does not double with each resolution step in any set",
      f"{ {k_: [round(x_, 1) for x_ in a_] for k_, a_ in amp.items()} }; doubling sets: {grow}", not grow)
n_ok = sum(1 for c_ in CH if c_[1])
P(f"\n  {n_ok}/{len(CH)} checks pass (verification only; the frozen verdict of the main script stands: {main['verdict']})")
OUT["frozen_verdict"] = main["verdict"]
json.dump(OUT, open(os.path.join(HERE, "cfg321_verify_fail_results.json"), "w"), indent=1)
