#!/usr/bin/env python3
"""
g04h -- can the framework's causal MOND boost regenerate the matter power spectrum from a thermal-relic cutoff?
================================================================================================================
The relic completion (g04f/g04g, corrected by the N_eff argument) puts the dark matter in a ~28 eV thermal species whose free
streaming erases linear power below a half-mode scale of ~35 h^-1 Mpc.  In this cosmology structure below cluster scales must be
regenerated by MOND's late growth.  The framework's own linear-regime dynamics (g03s (i), g03t D5): the MOND scalar is driven by
the source with inertia 1/c_*^2, c_*^2 = 0.42 c^2/|K_2|, so a mode's scalar force builds up as
        g_psi/g_N = 0.9 (c_* k_phys t)^2,   k_phys = k/a,
until it saturates at the static MOND value, g_psi/g_N -> nu(y) - 1 with y = g_N/a0 and nu the carrier kernel.  For a suppressed
mode g_N is tiny, so the saturated boost is huge: the smaller the residual amplitude, the larger the boost -- the mechanism by
which a cutoff spectrum can be refilled, and at the same time the reason nuHDM cosmologies over-produce massive structure.

Per mode: d^2 delta/dlna^2 + (2 + dlnH/dlna) d delta/dlna = (3/2) Omega_m(a) [1 + B] delta,   B = min[0.9 (c_* k t/a)^2, nu(y) - 1],
g_N = 4 pi G rhobar delta a/k (the mode's rms field, delta = Delta(k)), from z = 50 with Delta_i = Delta_LCDM(k, z=50) T_relic(k).
Reference: LambdaCDM (Eisenstein-Hu no-wiggle transfer, n_s = 0.965, sigma_8 = 0.81); relic: T(k) = [1 + (alpha k)^{2 nu}]^{-5/nu},
nu = 1.12, alpha = 0.049 (m/keV)^-1.11 (Omega_x/0.25)^0.11 (h/0.7)^1.22 h^-1 Mpc (Viel et al. 2005; extrapolated to 28 eV).
Output: R(k) = Delta^2_framework(k, 0)/Delta^2_LCDM(k, 0) and sigma_8 for |K_2| in {1e5, 2.5e5, 1e6, 2.7e6, 1e7, 1e8}.
Checks that can fail:
  P1 [control]   with the boost off, R(k) = T^2(k) and sigma_8 falls to < 0.3 (the relic cutoff alone destroys small-scale structure);
  P2 [target]    some |K_2| gives R(k) within 0.3 dex rms of unity over k = 0.1-1 h/Mpc AND sigma_8 within 20% of 0.81;
  P3 [reported]  the k-range that saturates at the static MOND value and the amplitude it saturates to (the 'a0 floor');
  P4 [reported]  R(k) at k = 0.05, 0.1, 0.2, 0.5, 1, 2 h/Mpc for each |K_2|, and the sigma_8 of each.
Caveats: per-mode linear treatment with a saturated boost (no mode coupling, no nonlinear collapse); the boost formula is the
matter-era analytic solution of g03s; the relic and the baryons are one fluid with the relic's transfer function (the baryons had no
dark wells to fall into before z = 50); both footings of a0 are run.
"""
import numpy as np, math, json, sys, time
from scipy.integrate import solve_ivp
FAILS = []
def check(name, ok, detail=""):
    print(f"  [{'PASS' if ok else 'FAIL'}] {name}" + (f"   ({detail})" if detail else ""), flush=True)
    if not ok: FAILS.append(name)
T0 = time.time()
G = 6.674e-11; c = 2.998e8; Mpc = 3.0857e22; h = 0.674; H0 = h*100e3/Mpc; Om, OL, Ob, Od = 0.315, 0.685, 0.049, 0.266; ns = 0.965; sig8_target = 0.81
rho_c = 3*H0**2/(8*math.pi*G); A0 = {"canonical": 9.3619e-11, "alt": 1.1279e-10}
def H(a): return H0*math.sqrt(Om*a**-3 + OL)
def dlnH_dlna(a): return -1.5*Om*a**-3/(Om*a**-3 + OL)
def t_of(a):
    aa = np.linspace(1e-6, a, 4000); return float(np.trapz(1/(aa*H(aa) if False else aa*np.sqrt(Om*aa**-3 + OL)*H0), aa))
TT_A = np.geomspace(1e-4, 1.0, 3000); TT_T = np.array([t_of(a_) for a_ in TT_A])
def t_a(a): return float(np.interp(a, TT_A, TT_T))
def D_lcdm(a):
    aa = np.linspace(1e-4, a, 20000); E = np.sqrt(Om*aa**-3 + OL); return 2.5*Om*np.sqrt(Om*a**-3 + OL)*np.trapz(1/(aa*E)**3, aa)
# ---- Eisenstein-Hu no-wiggle transfer (k in h/Mpc) ----
om_h2 = Om*h**2; ob_h2 = Ob*h**2; s_eh = 44.5*math.log(9.83/om_h2)/math.sqrt(1 + 10*ob_h2**0.75); aG = 1 - 0.328*math.log(431*om_h2)*Ob/Om + 0.38*math.log(22.3*om_h2)*(Ob/Om)**2
def T_eh(kh):
    Gam = Om*h*(aG + (1 - aG)/(1 + (0.43*kh*h*s_eh)**4)); q = kh/Gam; L = np.log(2*math.e + 1.8*q); C = 14.2 + 731/(1 + 62.5*q); return L/(L + C*q**2)
def Delta2_lcdm(kh, A): return A*kh**(ns + 3)*T_eh(kh)**2                                                  # dimensionless power today, A fixed by sigma_8
def sigma8_of(kh, D2):
    x = kh*8.0; W = 3*(np.sin(x) - x*np.cos(x))/x**3; return math.sqrt(np.trapz(D2*W**2/kh, kh))
KH = np.geomspace(0.005, 5.0, 300); A_norm = 1.0; A_norm = (sig8_target/sigma8_of(KH, Delta2_lcdm(KH, 1.0)))**2
print(f"    LambdaCDM reference normalised: sigma_8 = {sigma8_of(KH, Delta2_lcdm(KH, A_norm)):.3f}; D(1)/D(1/51) = {D_lcdm(1.0)/D_lcdm(1/51):.2f}", flush=True)
# ---- relic transfer ----
def T_relic(kh, m_eV):
    alpha = 0.049*(m_eV/1000)**-1.11*(Od/0.25)**0.11*(h/0.7)**1.22; nu = 1.12; return (1 + (alpha*kh)**(2*nu))**(-5/nu)
for m_eV in (28.0, 11.4):
    alpha = 0.049*(m_eV/1000)**-1.11*(Od/0.25)**0.11*(h/0.7)**1.22; khm = (2**(nu_ := 1/4.46) - 1)**(1/2.24)/alpha
    print(f"    relic m = {m_eV} eV: alpha = {alpha:.2f} h^-1 Mpc, half-mode k = {khm:.3f} h/Mpc (lambda_hm = {2*math.pi/khm:.0f} h^-1 Mpc)", flush=True)
# ---- carrier kernel ----
YT = np.logspace(-6, 3, 4000); YN = YT*(1 - np.exp(-YT))
def nu_of(y): yt = np.interp(y, YN, YT); return np.where(yt <= 1, yt/np.maximum(y, 1e-300), 1 + (1/math.e)/np.maximum(y, 1e-300))
# ---- per-mode growth with the causal, saturating boost ----
def grow(kh, delta_i, K2abs, a0, ai=1/51, boost=True):
    kk = kh*h/Mpc; cstar = math.sqrt(0.42/K2abs)*c; sat_flag = [False]; sat_amp = [None]
    def rhs(lna, y):
        a = math.exp(lna); d, dp = y; B = 0.0
        if boost:
            gN = 4*math.pi*G*Om*rho_c/a**3*abs(d)*a/kk; ycar = gN/a0; nusat = float(nu_of(np.array([ycar]))[0]) - 1
            Bcaus = 0.9*(cstar*kk/a*t_a(a))**2; B = min(Bcaus, nusat)
            if B >= 0.999*nusat and not sat_flag[0]: sat_flag[0] = True; sat_amp[0] = (a, abs(d))
        Oma = Om*a**-3/(Om*a**-3 + OL)
        return [dp, -(2 + dlnH_dlna(a))*dp + 1.5*Oma*(1 + B)*d]
    sol = solve_ivp(rhs, [math.log(ai), 0.0], [delta_i, delta_i], method='LSODA', rtol=1e-7, atol=1e-30, max_step=0.02)
    return sol.y[0, -1], sat_flag[0], sat_amp[0]
DLi = D_lcdm(1.0)/D_lcdm(1/51); ks = np.array([0.05, 0.1, 0.2, 0.5, 1.0, 2.0]); KGRID = np.geomspace(0.01, 3.0, 40)
RES = {}
for foot, a0 in A0.items():
    for m_eV in (28.0,):
        Ti = T_relic(KGRID, m_eV); D2_L = Delta2_lcdm(KGRID, A_norm); Delta_i = np.sqrt(D2_L)*Ti/DLi
        # control
        R_ctrl = np.array([(grow(kh, di, 1e6, a0, boost=False)[0]/(di*DLi))**2*Ti[j]**2 for j, (kh, di) in enumerate(zip(KGRID, Delta_i))])
        D2_ctrl = D2_L*R_ctrl; s8_ctrl = sigma8_of(KGRID, D2_ctrl)
        print(f"    {foot}, m = {m_eV} eV: boost OFF: R(k) at {ks.tolist()} = {np.round(np.interp(ks, KGRID, R_ctrl), 3).tolist()}, sigma_8 = {s8_ctrl:.3f}", flush=True)
        if foot == "canonical": check("P1 [control] with the boost off R(k) = T^2(k) (within 5% at every k) and sigma_8 < 0.6", np.all(np.abs(R_ctrl/Ti**2 - 1) < 0.05) and s8_ctrl < 0.6, f"max |R/T^2 - 1| = {np.max(np.abs(R_ctrl/Ti**2 - 1)):.3f}, sigma_8 = {s8_ctrl:.3f}")
        for K2abs in (1e5, 2.5e5, 1e6, 2.7e6, 1e7, 1e8):
            out = [grow(kh, di, K2abs, a0) for kh, di in zip(KGRID, Delta_i)]
            R = np.array([(o[0]/(di*DLi))**2*Ti[j]**2 for j, (o, di) in enumerate(zip(out, Delta_i))]); D2 = D2_L*R; s8 = sigma8_of(KGRID, D2)
            sel = (KGRID >= 0.1) & (KGRID <= 1.0); rms = float(np.sqrt(np.mean(np.log10(np.maximum(R[sel], 1e-30))**2)))
            ksat = [KGRID[j] for j, o in enumerate(out) if o[1]]; samp = [o[2] for o in out if o[1]]
            RES[(foot, K2abs)] = (R, s8, rms, ksat, samp)
            print(f"    {foot} |K_2| = {K2abs:.1e} (c_* = {math.sqrt(0.42/K2abs)*c/1e3:.0f} km/s): R(k) at {ks.tolist()} = {['%.2e' % v for v in np.interp(ks, KGRID, R)]}; sigma_8 = {s8:.3f}; rms log R (0.1-1) = {rms:.2f} dex; saturated modes: k >= {min(ksat) if ksat else float('nan'):.3f} h/Mpc" + (f", first saturation at a = {samp[0][0]:.2f}, Delta = {samp[0][1]:.2e}" if samp else ""), flush=True)
ok = {key: (v[2] < 0.3 and abs(v[1]/sig8_target - 1) < 0.2) for key, v in RES.items()}
check("P2 [target] some |K_2| gives R(k) within 0.3 dex rms of unity over 0.1-1 h/Mpc and sigma_8 within 20% of 0.81 (canonical footing)", any(ok[key] for key in ok if key[0] == "canonical"), json.dumps({f"{key[1]:.1e}": [round(v[2], 2), round(v[1], 3)] for key, v in RES.items() if key[0] == "canonical"}))
check("P2b [target, alt] the same at the alt footing", any(ok[key] for key in ok if key[0] == "alt"), json.dumps({f"{key[1]:.1e}": [round(v[2], 2), round(v[1], 3)] for key, v in RES.items() if key[0] == "alt"}))
print(f"\n  caveats: per-mode linear growth with a saturating boost (no mode coupling or collapse; nuHDM's top-down fragmentation is not modelled); the causal build-up is g03s's matter-era formula with k/a; the saturation uses the mode's rms field; one fluid with the relic's transfer function; z_i = 50.  total {time.time()-T0:.0f}s")
print(f"\nRESULT: {len(FAILS)} FAIL" + (f" -> {FAILS}" if FAILS else ""))
sys.exit(1 if FAILS else 0)
