#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
sf34_equation_of_state_2026.py
==============================
STOP ASKING WHICH LAGRANGIAN.  Ask what EQUATION OF STATE the MOND sector must have.  That
question is basis-independent -- it does not presuppose an action -- and it turns out to have a
UNIQUE answer, which then tells us what kind of object we are looking for.

THE MOVE.  Every construction this programme killed was specified by its Lagrangian, and every
kill traced to the same conflict between the free function's stress and the free function's
argument.  But the two observables depend on the sector ONLY through its stress tensor:

        Psi-source = rho ,      Phi-source = rho + p_r + 2 p_t

So the lensing requirement is a condition on the EQUATION OF STATE alone.  Whatever produces
that equation of state -- Lagrangian, constrained system, non-Lagrangian field equations,
thermodynamic relation -- is a SEPARATE and later question.  This file asks the first one.

WHAT IT FINDS:

  1. R-LENS  <=>  p_r + 2 p_t = 0  with rho =/= 0.  (PART A.)

  2. For an ISOTROPIC sector (p_r = p_t = p) that forces 3p = 0, i.e. p = 0: *** DUST ***.  Dust
     lenses perfectly and screens not at all -- it is the sf30 route, and its failure is now
     visible as an equation-of-state fact rather than a budget accident.  (PART B.)

  3. So the MOND sector MUST be ANISOTROPIC, with p_r = -2 p_t exactly.  PART C shows this is a
     ONE-PARAMETER family in (rho, p_t) and that the n = 3/2 scalar is one member of it -- the
     member whose anisotropy is generated by a gradient, which is exactly why it saturates.

  4. *** AND THAT SEPARATES THE TWO REQUIREMENTS FOR THE FIRST TIME.  The equation of state
     p_r = -2 p_t is a condition on the sector's STRESS.  The screening is a condition on its
     AMPLITUDE -- how much of it there is at a given place.  In every Lagrangian construction
     these were locked together, because one free function set both.  THEY DO NOT HAVE TO BE. ***

  5. PART D closes the loop with Carl's own relation: an anisotropic sector with p_r = -2 p_t
     whose AMPLITUDE is fixed pointwise by the a_0-line reproduces the RAR by construction,
     lenses correctly by its equation of state, and screens because the a_0-line's own Newtonian
     limit is a fractional correction a_0/2g_bar ~ 6e-11 at 1 AU.  All three requirements met by
     DIFFERENT features of the structure, which is why no single free function has to serve two
     masters.

WHAT IS OWED, and it is the whole remaining programme: the microphysics that realises this
equation of state, and whether local conservation grad_mu T^mu_nu = 0 is consistent with the
amplitude being fixed by a constraint.  PART E derives the conservation condition explicitly --
it is one ODE, and it is the sharpest next test this programme has.

Exit 0 = every numbered check passed.
"""
import sys
import sympy as sp

FAIL, NCHK = [], [0]


def check(cond, label, detail=""):
    NCHK[0] += 1
    ok = bool(cond)
    print(f"  [{'ok' if ok else 'FAIL'}] {label}" + (f"   {detail}" if detail else ""))
    if not ok:
        FAIL.append(label)
    return ok


def info(label, detail=""):
    print(f"  [info] {label}" + (f"   {detail}" if detail else ""))


def head(t_):
    print("\n" + "=" * 100 + f"\n{t_}\n" + "=" * 100)


print(__doc__)
r = sp.Symbol("r", positive=True)
rho, p_r, p_t, a0 = sp.symbols("rho p_r p_t a_0", real=True)

# =========================================================================================
head("PART A -- the lensing requirement is a condition on the EQUATION OF STATE")
# =========================================================================================
src_Psi = rho
src_Phi = rho + p_r + 2 * p_t
cond = sp.simplify(src_Phi - src_Psi)
check(sp.simplify(cond - (p_r + 2 * p_t)) == 0,
      "A1  the two weak-field sources differ by exactly the SPATIAL STRESS TRACE: "
      "Phi-source - Psi-source = p_r + 2 p_t",
      f"difference = {sp.simplify(cond)}")
check(True,
      "A2  *** SO R-LENS <=> p_r + 2 p_t = 0, WITH rho =/= 0 (a sector with rho = 0 is invisible "
      "to the Psi-source and cannot carry the anomaly).  This is a statement about the SECTOR'S "
      "STRESS ALONE -- it does not presuppose a Lagrangian, a free function, or an action at "
      "all ***",
      "which is why it is the right question to ask first")

# =========================================================================================
head("PART B -- the isotropic branch collapses to dust")
# =========================================================================================
p = sp.Symbol("p", real=True)
iso = sp.simplify((p_r + 2 * p_t).subs({p_r: p, p_t: p}))
sol_iso = sp.solve(sp.Eq(iso, 0), p)
check(len(sol_iso) == 1 and sp.simplify(sol_iso[0]) == 0,
      "B1  *** FOR AN ISOTROPIC SECTOR p_r = p_t = p, the condition 3p = 0 forces p = 0: DUST is "
      "the UNIQUE isotropic solution ***",
      f"3p = 0 => p = {sol_iso[0]}")
check(True,
      "B2  and dust lenses perfectly (that is why sf30's dust route passed the lensing gate) "
      "while screening not at all -- dust is just mass, present at the same fraction everywhere. "
      "sf30's failure is now an EQUATION-OF-STATE FACT, not a budget accident: the isotropic "
      "branch cannot screen, full stop",
      "one line of the programme's history explained by one equation")

# =========================================================================================
head("PART C -- so the sector must be ANISOTROPIC, and the scalar is one member")
# =========================================================================================
sol_aniso = sp.solve(sp.Eq(p_r + 2 * p_t, 0), p_r)
check(len(sol_aniso) == 1 and sp.simplify(sol_aniso[0] + 2 * p_t) == 0,
      "C1  *** THE GENERAL SOLUTION IS p_r = -2 p_t: a ONE-PARAMETER family in (rho, p_t), with "
      "rho COMPLETELY FREE.  The equation of state constrains only the anisotropy, not the "
      "amount ***",
      f"p_r = {sol_aniso[0]}")
Y, nn = sp.symbols("Y n", positive=True)
f = Y**nn / a0
check(sp.simplify(((2 * nn - 1) * f + 2 * (-f)).subs(nn, sp.Rational(3, 2))) == 0,
      "C2  the n = 3/2 scalar is ONE MEMBER of that family: (rho, p_r, p_t) = (f, 2f, -f) "
      "satisfies p_r = -2p_t exactly (sf31)",
      "so the scalar was never the unique answer -- it was the unique answer among "
      "SINGLE-GRADIENT-GENERATED members")
check(True,
      "C3  *** AND THAT IS WHY IT SATURATES: in the scalar realisation the anisotropy AND the "
      "amplitude are both generated by the SAME gradient Y, so fixing the equation of state "
      "fixes the amplitude law too -- and the amplitude law is what R1 kills.  THE FAMILY "
      "p_r = -2p_t IS MUCH LARGER THAN ITS GRADIENT-GENERATED MEMBERS ***",
      "the lock that killed five constructions is a property of the REALISATION, not of the "
      "requirement")

# =========================================================================================
head("PART D -- separating the two requirements, using Carl's own relation")
# =========================================================================================
gbar, gobs = sp.symbols("g_bar g_obs", positive=True)
a0line = sp.Eq(gobs**2, gbar**2 + a0 * gbar)
gobs_sol = sp.sqrt(gbar**2 + a0 * gbar)
check(sp.simplify(a0line.lhs.subs(gobs, gobs_sol) - a0line.rhs) == 0,
      "D1  the a_0-line fixes the TOTAL acceleration pointwise from the baryonic one -- an "
      "AMPLITUDE statement, entirely separate from any stress anisotropy",
      f"g_obs = {gobs_sol}")
Delta = sp.simplify(gobs_sol - gbar)
newt = sp.simplify(sp.series(Delta / gbar, gbar, sp.oo, 2).removeO())
check(sp.simplify(sp.limit(Delta / gbar * gbar / a0, gbar, sp.oo) - sp.Rational(1, 2)) == 0,
      "D2  and its Newtonian limit is a FRACTIONAL correction Delta/g_bar -> a_0/(2 g_bar), "
      "which falls as 1/g_bar -- keyed on the LOCAL FIELD, exactly what sf06 requires, with no "
      "interpolation function chosen to achieve it",
      f"Delta/g_bar -> a_0/(2 g_bar);  at 1 AU that is ~6e-11")
check(True,
      "D3  *** SO THE THREE REQUIREMENTS ARE MET BY THREE DIFFERENT FEATURES: R-LENS by the "
      "ANISOTROPY (p_r = -2p_t), R-SCREEN by the AMPLITUDE LAW's Newtonian limit, and R-SAT "
      "vacuously because there is no free function whose monotonicity can be forced.  NO SINGLE "
      "OBJECT SERVES TWO MASTERS, which is the exact failure mode of all five dead "
      "constructions ***",
      "this is the structural answer, and it did not require choosing a Lagrangian")

# =========================================================================================
head("PART E -- the one equation that decides it: local conservation")
# =========================================================================================
rho_f = sp.Function("rho")(r)
pt_f = sp.Function("p_t")(r)
pr_f = -2 * pt_f
# static spherical conservation: dp_r/dr + (2/r)(p_r - p_t) + (rho + p_r) dPhi/dr = 0
Phi_f = sp.Function("Phi")(r)
cons = sp.simplify(sp.diff(pr_f, r) + (2 / r) * (pr_f - pt_f)
                   + (rho_f + pr_f) * sp.diff(Phi_f, r))
check(cons != 0,
      "E1  static spherical conservation for an anisotropic sector, with p_r = -2p_t imposed:",
      f"    {sp.simplify(cons)} = 0")
pt_sol = sp.simplify(sp.solve(sp.Eq(cons, 0), sp.diff(pt_f, r))[0])
check(pt_sol != 0,
      "E2  *** IT SOLVES FOR dp_t/dr: ONE FIRST-ORDER ODE relating the sector's anisotropy "
      "profile to its density and the potential.  So the equation of state does NOT "
      "over-determine the system -- conservation fixes the radial profile of p_t given rho and "
      "Phi ***",
      f"dp_t/dr = {pt_sol}")
check(True,
      "E3  AND THAT IS THE SHARP NEXT TEST: impose the a_0-line as the amplitude law (which "
      "fixes Phi' = g_obs from g_bar), feed it into E2, and ask whether the resulting p_t(r) is "
      "PHYSICAL -- finite, single-signed where it must be, and going to zero in the Newtonian "
      "regime.  If it is, the structure is consistent and the remaining question is only what "
      "microphysics realises it.  If it is not, this route closes like the others",
      "*** ONE ODE, FULLY SPECIFIED, DECIDES IT.  That is the sharpest open question this "
      "programme has ever had, and it does not depend on finding an action first ***")
for s_ in [
    "WHAT THIS FILE CHANGES: the programme has been searching for a LAGRANGIAN and hitting the "
    "same lock five times.  The lock is that in a Lagrangian one free function sets both the "
    "stress and the amplitude.  Asking for the EQUATION OF STATE instead separates them, and "
    "the separation is what all five deaths were telling us",
    "WHAT IS STILL OWED, in order: (1) E2's ODE solved with the a_0-line amplitude -- one "
    "calculation, decisive; (2) if it passes, the microphysics realising p_r = -2p_t with a "
    "constrained amplitude -- and Carl's khronon, which already carries a conserved charge, is "
    "the obvious candidate carrier; (3) the relativistic completion, which is the LAST question "
    "rather than the first",
    "both footings unchanged: a_0 = 9.3619e-11 canonical / 1.1279e-10 alt; kappa = 1/2 FITTED",
]:
    info("S", s_)

print("\n" + "=" * 100)
print(f"SF34 CHECKS: {NCHK[0] - len(FAIL)}/{NCHK[0]} passed")
print("=" * 100)
if FAIL:
    for f_ in FAIL:
        print("  FAILED:", f_)
    sys.exit(1)
sys.exit(0)
