#!/usr/bin/env python3
"""
Final pass: (1) symbolic verification of the two soft-branch limits
     c_s^2 (k->inf, Ab=0) = K1 (2-K_B) / (a^2 (3 K1 K_B + K2 Qb (K_B+2)))   [the K_B window]
     omega^2 (k->0,  Ab=0) = -(1/3)(k/a)^2 + K_B k^4/(72 pi G K1 Qb a^4) + ...  [the k^4 term]
(2) numeric branch structure at PHYSICAL trace-level charge (Omega_dust ~ 1e-6), all K_B cases.
"""
import sympy as sp
import numpy as np
import functools, time
print = functools.partial(print, flush=True)
t0 = time.time()
def check(cond, label):
    print(("  [PASS] " if cond else "  [FAIL] ") + label)

k   = sp.Symbol('k', positive=True)
G   = sp.Symbol('G', positive=True)
Lam = sp.Symbol('Lam', real=True)
KB  = sp.Symbol('K_B', real=True)
Ab  = sp.Symbol('A_b', real=True)
ub  = sp.Symbol('u_b', real=True)
K0, K1, K2 = sp.symbols('K0 K1 K2', real=True)
A0cp = sp.Symbol('A0cp', positive=True)
p0, s0, x0, a0v = sp.symbols('p0 s0 x0 a0v', real=True)
s1, x1, a1v, p1 = sp.symbols('s1 x1 a1v p1', real=True)
Hh  = sp.Symbol('H', real=True)
av  = sp.Symbol('a_v', positive=True)
Qbs = sp.Symbol('Qb', real=True)
FRIEDMANN = [(Lam, 3*Hh**2 - 8*sp.pi*G*(Qbs*K1 - K0))]

L2s = sp.sympify(open('L2s_checkpoint.txt').read())
cP  = sp.expand(sp.diff(L2s, p0)); AP = sp.expand(sp.diff(cP, p0)/2); cP0 = sp.expand(cP.subs(p0, 0))
Lred_num = sp.expand((4*AP*L2s.subs(p0, 0) - cP0**2).subs(FRIEDMANN))
vels = [s1, x1, a1v]; flds = [s0, x0, a0v]

w = sp.Symbol('omega')
acc = sp.symbols('s2 x2 a2v', real=True)
def ddt_frozen(e):
    out = 0
    for f, v in zip(flds, vels): out += sp.diff(e, f)*v
    for v, aa in zip(vels, acc): out += sp.diff(e, v)*aa
    return out
EL = [sp.expand(ddt_frozen(sp.diff(Lred_num, vels[i])) - sp.diff(Lred_num, flds[i])) for i in range(3)]
hat = sp.symbols('hS hX hA', real=True)
subw = (list(zip(acc, [-w**2*h for h in hat])) + list(zip(vels, [sp.I*w*h for h in hat]))
        + list(zip(flds, hat)))
Msys = sp.Matrix(3,3, lambda i,j: sp.diff(sp.expand(EL[i].subs(subw, simultaneous=True)), hat[j]))
D = sp.expand(Msys.det())
Dp = sp.Poly(D, w)
d0 = sp.expand(Dp.coeff_monomial(1)); d2 = sp.expand(Dp.coeff_monomial(w**2)); d4 = sp.expand(Dp.coeff_monomial(w**4))
print("det M rebuilt (%.1f s)" % (time.time()-t0))

softH0 = sp.cancel(-sp.factor(sp.expand(d0.subs(Hh,0)))/sp.factor(sp.expand(d2.subs(Hh,0))))
softA0 = sp.cancel(softH0.subs(Ab, 0))

def klead(e):
    e = sp.cancel(sp.together(e)); num, den = sp.fraction(e)
    pn, pd = sp.Poly(num, k), sp.Poly(den, k)
    return sp.cancel(pn.coeff_monomial(k**pn.degree())/pd.coeff_monomial(k**pd.degree())*k**(pn.degree()-pd.degree()))

print("\n(1) SYMBOLIC LIMITS OF THE SOFT (khronon/dust) BRANCH, H->0, Ab=0:")
lead = klead(softA0)
target = K1*(2-KB)*k**2/(av**2*(3*K1*KB + K2*Qbs*(KB+2)))
check(sp.simplify(sp.cancel(lead - target)) == 0,
      "c_s^2 k^2 (k->inf) = K1 (2-K_B) k^2 / (a^2 [3 K1 K_B + K2 Qb (K_B+2)])"
      "  -- POSITIVE iff 0 < K_B < 2 (charge-suppressed sound speed; the AeST window)")
ser = sp.series(softA0, k, 0, 5).removeO()
c2 = sp.simplify(ser.coeff(k, 2)); c4 = sp.simplify(ser.coeff(k, 4))
print("   k->0:  omega^2 =", sp.factor(c2), "* k^2  +", sp.factor(c4), "* k^4 + ...")
check(sp.simplify(c2 + 1/(3*av**2)) == 0, "k^2 coefficient (sub-Jeans, WKB-formal) = -1/(3 a^2)")
check(sp.simplify(c4 - KB/(72*sp.pi*G*K1*Qbs*av**4)) == 0,
      "k^4 coefficient = K_B/(72 pi G K1 Qb a^4): a k^4 term GENERATED by the constraint eliminations, "
      "coefficient ~ 1/(G rho_dust): enormous for trace charge => k^4-dominated Jeans cutoff")
kJ2 = sp.solve(sp.Eq(c2 + c4*k**2, 0), k**2)
print("   Jeans crossing k_J^2 =", [sp.factor(s) for s in kJ2], " (= 24 pi G (K1 Qb) a^2/K_B; K1 Qb = rho_dust+p ~ rho_dust)")

print("\n(2) NUMERIC BRANCHES AT PHYSICAL HIERARCHY (Omega_dust ~ 1e-6, trace):")
import numpy.polynomial.polynomial as npoly
pars = dict(G=1.0, av=1.0, H=0.05, Qb=1.0, K0=-2.984e-4, K2=0.40, A0cp=1.0)
# K0 = -M^4 ~ -rho_Lambda ~ -rho_cr today: rho_cr = 3H^2/(8 pi G) = 2.984e-4. K1 = n = rho_d/Qb.
rho_cr = 3*pars['H']**2/(8*np.pi*pars['G'])
for label, K1v, Abv, ubv in [
    ("Omega_d=1e-6, Ab=0",            1e-6*rho_cr, 0.0,   0.0),
    ("Omega_d=1e-6, Ab ub^2 = 1e-10", 1e-6*rho_cr, 1e-4,  1e-3),
]:
    print("  --- %s  (K1 = %.3g) ---" % (label, K1v))
    subs_num = [(G,1.0), (av,1.0), (Hh,0.05), (Qbs,1.0), (K0,pars['K0']), (K1,K1v),
                (K2,0.4), (Ab,Abv), (ub,ubv), (A0cp,1.0)]
    d0n = sp.lambdify(([KB, k]), d0.subs(subs_num), 'numpy')
    d2n = sp.lambdify(([KB, k]), d2.subs(subs_num), 'numpy')
    d4n = sp.lambdify(([KB, k]), d4.subs(subs_num), 'numpy')
    print("   %6s %10s | %14s %14s" % ("K_B", "k/aH", "w2_soft", "w2_hard"))
    for KBv in [0.5, 1.9, 2.1]:
        for kv in [1.0, 10.0, 1e3, 1e5]:
            kk = kv*pars['H']  # k in units of aH
            a_, b_, c_ = d4n(KBv, kk), d2n(KBv, kk), d0n(KBv, kk)
            disc = b_*b_ - 4*a_*c_
            r1 = (-b_ + np.sqrt(complex(disc)))/(2*a_)
            r2 = (-b_ - np.sqrt(complex(disc)))/(2*a_)
            soft, hard = sorted([r1, r2], key=abs)
            def fmt(x):
                return "%.4g%+.1gi" % (x.real, x.imag) if abs(x.imag) > 1e-12*abs(x.real)+1e-30 else "%.4g" % x.real
            print("   %6s %10g | %14s %14s" % (KBv, kv, fmt(soft), fmt(hard)))
    print("   (w2 in units where a=1; positive = stable oscillation, negative = growth ~ sqrt|w2|)")

print("\n(3) VERDICT LOGIC:")
print("   0 < K_B < 2, K''> 0, K1 > 0: soft branch w2 >= 0 at every sub-horizon k (k^4-cured Jeans, then")
print("   charge-suppressed c_s^2 > 0); K_B > 2: c_s^2 < 0 -> slow gradient instability (rate ~ sqrt(K1));")
print("   K2 < 0: khronon ghost (kinetic entry K2*K_B*k^2 < 0). The AeST window is REPRODUCED.")
print("\nDONE (%.1f s)" % (time.time()-t0))
