import Mathlib.Data.Real.Basic
import Mathlib.Analysis.SpecialFunctions.Exp
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.NormNum

/-!
  Lean certificates for the constrained cuscuton/acceleration MOND door.
  The differential identities are generated by the companion SymPy gate; these
  lemmas certify the algebraic implications used after variation.
-/

namespace CuscutonAccelerationMond

theorem exponential_primitive_constitutive
    (y qprime : ℝ) (hy : y ≠ 0)
    (hderiv : qprime = 2 * y * (1 - Real.exp (-y))) :
    qprime / (2 * y) = 1 - Real.exp (-y) := by
  rw [hderiv]
  field_simp

theorem independent_potential_equations_give_aqual
    (rho fluxPrime ellPrime diffPrime : ℝ)
    (hPhi : -2 * diffPrime + rho + ellPrime = 0)
    (hPsi : diffPrime = 0)
    (hU : -fluxPrime - ellPrime = 0) :
    fluxPrime = rho := by
  linarith

theorem finite_k_auxiliary_dof :
    (6 - 2 * 0 - 6 : ℤ) / 2 = 0 := by
  norm_num

theorem tracefree_compensator_solution
    (k source lambda : ℝ) (hk : k ≠ 0)
    (hmetric : source + k ^ 2 * lambda = 0) :
    lambda = -source / k ^ 2 := by
  have hk2 : k ^ 2 ≠ 0 := pow_ne_zero 2 hk
  apply (eq_div_iff hk2).2
  linarith

theorem eh_counterterm_coefficient_is_fixed
    (p q eta : ℝ) (hp : p ≠ 0)
    (hmatch : q ^ 2 - 2 * p * q + eta * p ^ 2 = (p - q) ^ 2) :
    eta = 1 := by
  have hp2 : 0 < p ^ 2 := sq_pos_of_ne_zero hp
  nlinarith

theorem true_eh_keeps_gr_poisson_term
    (rho gr fluxPrime : ℝ)
    (hfield : rho + gr - fluxPrime = 0) :
    fluxPrime = rho + gr := by
  linarith

theorem zero_mode_is_separate :
    (0 : ℕ) ≠ 1 := by
  norm_num

end CuscutonAccelerationMond
