import Mathlib.Data.Real.Basic
import Mathlib.Analysis.SpecialFunctions.Exp
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.NormNum

/-!
  Lean certificates for the constrained cuscuton/acceleration MOND door.
  The differential identities are generated by the companion SymPy gate; these
  lemmas certify the algebraic implications used after variation.
-/

namespace CuscutonAccelerationMond

theorem exponential_primitive_constitutive
    (y qprime : ℝ) (hy : y ≠ 0)
    (hderiv : qprime = 2 * y * (1 - Real.exp (-y))) :
    qprime / (2 * y) = 1 - Real.exp (-y) := by
  rw [hderiv]
  field_simp

theorem independent_potential_equations_give_aqual
    (rho fluxPrime ellPrime diffPrime : ℝ)
    (hPhi : -2 * diffPrime + rho + ellPrime = 0)
    (hPsi : diffPrime = 0)
    (hU : -fluxPrime - ellPrime = 0) :
    fluxPrime = rho := by
  linarith

theorem finite_k_auxiliary_dof :
    (6 - 2 * 0 - 6 : ℤ) / 2 = 0 := by
  norm_num

theorem zero_mode_is_separate :
    (0 : ℕ) ≠ 1 := by
  norm_num

end CuscutonAccelerationMond
